### PR TITLE
LPS-153747 Search Result message is in plural when only one result returns

### PR DESCRIPTION
**Pull request by daiazius**
In this PR I made changes in the search results templates. I put a condition to show the `x-result-for-x` message when there is only one result and `x-results-for-x` when there is more. In [brianchandotcom#120548](https://github.com/brianchandotcom/liferay-portal/pull/120548) I sent this with a ternary operator inside the function, now i used an if/else like the ones used in most other templates. I just didn't understand how to use the `emptyResultsMessage` as it is reserved for empty search results, which is not the case with this ticket.

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:search

**Review by oliv-yu — APPROVED** [review]
Looks good! I think it would help to write some details the description, give some context about the previous PR https://github.com/brianchandotcom/liferay-portal/pull/120548. Explain a bit about `emptyResultsMessage` being reserved for empty search results. The if/else statement maintains readability and used throughout most templates.

**Comment by oliv-yu** [comment]
Unique failure looks related to a known bug https://issues.liferay.com/browse/LPS-158939

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/121183

**Pull request closed without merging**
