### PR TITLE
LPS-162591 Fix nested sort translation in a Blueprint

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-162591

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @peerkar, it looks like this change caused a few ApplyBlueprint tests to fail related the testing result ordering. I would guess https://github.com/liferay-search/liferay-portal/pull/551/commits/543d8766f17ecd688f3997585f180db95fc0d094 caused it.

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
