### PR TITLE
LPS-169866 portal-search-web: Deprecate site, folder, custom, category and tag methods that were not present in BucketDisplayContext

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-170138

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1257401_5609

**Comment by joshchong** [comment]
ci:test:relevant

**Pull request closed without merging**
