### PR TITLE
LPD-33329: "Portlet is temporarily unavailable" error appears if you try to filter by a non-existent categoryId via the URL

### PR DESCRIPTION
**Pull request by gustavolimav**
Ticket: https://liferay.atlassian.net/browse/LPD-33329

- Sub-task: https://liferay.atlassian.net/browse/LPD-34712

Follow-up test for this changes https://github.com/brianchandotcom/liferay-portal/pull/153612

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Looks good to me :+1:

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
