### PR TITLE
LPS-159240

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-159240
Follow up: https://github.com/liferay-search/liferay-portal/pull/517

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@felipelorenz can you [remove the line here](https://github.com/liferay/liferay-portal/blob/6615c02e2d9fe38b4f297f221656c7433a3ea4f4/test.properties#L1007), push the change to this PR and rerun the relevant test? You can commit to the ticket LPS-159240 for that change as well.

**Comment by felipelorenz** [comment]
> @felipelorenz can you [remove the line here](https://github.com/liferay/liferay-portal/blob/6615c02e2d9fe38b4f297f221656c7433a3ea4f4/test.properties#L1007), push the change to this PR and rerun the relevant test? You can commit to the ticket LPS-159240 for that change as well.

sure, I will do that

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@felipelorenz @gustavolimav The test results look good. I've confirmed the test SearchBarPortletDisplayContextFactoryTest is running and is no longer timing out. See https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/64836/testReport/com.liferay.portal.search.web.internal.search.bar.portlet.display.context.factory/SearchBarPortletDisplayContextFactoryTest/

**Comment by gustavolimav** [comment]
LGTM

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
