### PR TITLE
LPS-200654 Handle gracefully when the associated Site or Blueprint is deleted in Result Rankings & LPS-201969 [BE] Add filtering + search capabilities based on URL

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
Hey @AlmirFe , plese fix the tests and the SF faillure

**Comment by AlmirFe** [comment]
@BryanEngler I just sent this PR https://github.com/BryanEngler/liferay-portal/pull/748 to your branch containing the fix for these broken tests.

\cc @gustavolimav

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@oliv-yu or @thektan can you guys help out with this <clay:icon> SF error? not sure if we need to fix the code or if source formatter is maybe broken?

**Comment by oliv-yu** [comment]
@BryanEngler That SF rule was introduced in https://liferay.atlassian.net/browse/LPS-179523 where it discourages new usages of the older `liferay-ui` taglibs. Could you add the latest commit from [here](https://github.com/oliv-yu/liferay-portal/commits/2023_12_21_pr1196_liferay_search_LPS_200654_ranking_site_blueprint_deleted/) to the branch? It just uses markup instead of the taglib, I think it'll pass SF that way 🤞

It looks like eventually we'd need to adopt `clay:dropdown-actions` instead of `liferay-ui:icon-menu`, which would need to define the appropriate action dropdown items inside the `RankingEntryDisplayContext` 😅

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
@oliv-yu sounds good, thank you!

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
