### PR TITLE
LPD-24555 Replace deprecated CreateIndexRequest

### PR DESCRIPTION
**Pull request by gustavolimav**
use import org.elasticsearch.client.indices.CreateIndexRequest; instead of import org.elasticsearch.action.admin.indices.create.CreateIndexRequest

reason:

[types removal] Using include_type_name in get mapping requests is deprecated. The parameter will be removed in the next major version of elasticsearch

https://liferay.atlassian.net/browse/LPD-24555

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-remote

**Comment by gustavolimav** [comment]
ci:test:relevat

**Comment by gustavolimav** [comment]
ci:report:2568328154

**Comment by gustavolimav** [comment]
Pushed one change on `ElasticsearchSearchEngineAdapterDocumentRequestTest.java`  that was missing `createIndexRequest.mapping(_MAPPING_SOURCE, XContentType.JSON);`

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-remote

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
LGTM

**Review by joshuacords — APPROVED** [review]

**Comment by gustavolimav** [comment]
ci:report:2568656552

**Comment by gustavolimav** [comment]
ci:report:2568642154

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:2569046051

**Comment by gustavolimav** [comment]
ci:report:2569023103

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
Still need to split Breaking changes in each commit and send SF commit, lets wait to see CI Results

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:report:2569226122

**Comment by gustavolimav** [comment]
ci:report:2569236098

**Comment by peerkar** [comment]
@gustavolimav generally looks good to me. However `type` should not be removed from the APIs just like that, without any deprecation period, because it can cause issues on the customer side. Can you please deprecate only the relevant methods in search engine adapter, in portal search API and in kernel. Those can be removed then after a good grace period.

**Pull request closed without merging**
