### PR TITLE
LPD-7731: Prepare CI for OpenSearch2 tests

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-7731

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:opensearch

**Comment by peerkar** [comment]
ci:test:opensearch2

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:reevaluate:1407401_8693

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:report:2541870543

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:test:workflow-opensearch2

**Comment by peerkar** [comment]
ci:test:commerce-opensearch2-remote

**Comment by peerkar** [comment]
ci:test:commerce-opensearch2

**Comment by peerkar** [comment]
ci:test:workflow-opensearch2

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:report:2543405869

**Comment by peerkar** [comment]
ci:test:workflow-opensearch2

**Pull request closed without merging**
