### PR TITLE
LPS-189240 Enable execution modes by default and include BETA

### PR DESCRIPTION
**Pull request by BryanEngler**
https://issues.liferay.com/browse/LPS-189240 - Reindex execution modes and the updated Index Actions page layout are becoming enabled by default with indication of the feature status of Concurrent and Sync modes (BETA)
https://liferay.atlassian.net/browse/LPS-197359 (Subtask)

Edit: I named the branch under the FF to be removed, but it's supposed to be named under `LPS-189240` and `LPS-197359`, sorry for the confusion!

UI updates:
- Beta badge added to "Concurrent" and "Sync" options of dropdown
- Action buttons renamed to "Reindex"
- Extra "Reindex Mode" label removed
- "Configuration" title added on left side panel to match with the right side "Action" title

Other changes:
- Option "Regular" is now "Full" in codebase
- Remove `feature.flag.LPS-183661` in favor of the beta tags

Screenshot:
Screenshot 2023-09-26 at 10 31 16 AM

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by oliv-yu** [comment]
@BryanEngler Oh it looks like there's an SF issue with the `main.js` file... I think it's just this change, if you wanted to add it in: https://github.com/oliv-yu/liferay-portal/commit/92828cff8663f53906734b7c1c0d1e161379e489

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
