### PR TITLE
LPS-185640 Search After Null Pointer with 1000s

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-185640

Continued from: https://github.com/liferay-search/liferay-portal/pull/931

The problem was that the Elasticsearch API was rounding 1000s to 16.6m and the PIT does not accept fractional numbers.

The solution was to change the default value of the PIT keep alive time to 60 and make the PIT only accept numbers from 1 to 60 seconds.

**Author:** @gustavolimav 
**Reviewer:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:forward:force

Re-running `stable` since the `portal-license-smoke-mysql57-jdk8` batch failed

**Comment by joshuacords** [comment]
Hi @xbrianlee, does this look good to go?

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
