### PR TITLE
LPS-180102: Use AnalyticsManager to check whether AC is enabled

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-180102

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:reevaluate:1317401_7581

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
