### PR TITLE
LPS-188222: Update index aliases gracefully

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-188222

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:stop

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:forward:force

**Pull request closed without merging**
