### PR TITLE
[TS] LPS-131302 Add showExtraInfo parameter for searched documents

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-131302

The issue here is that the info button does not appear for searched documents that have a preview. This was occurring because all documents with a preview were being viewed by view_file_entry_simple_view.jsp because showExtraInfo is always equal to false.

I resolved this issue by adding a showExtraInfo parameter to the generated URL. I also needed to update showExtraInfo in AssetDisplayTag because it was overriding the one I added to the URL.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:search

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:search

**Comment by noornajj** [comment]
Hi, is there an ETA for this PR?
Thank you.

**Comment by lipusz** [comment]
ci:reevaluate:1067401_8503

**Comment by lipusz** [comment]
:white_check_mark: `IndexerScoreDistortionTest` is a known flaky failure, handled on #122

**Comment by lipusz** [comment]
Hello @noornajj 

One question: if I read your steps - without screenshots - I assume the info button works for .docx files, but not for .pdf files. However, if I look at your changes, nothing indicates that it's working for any type of documents.

Asking, because if the behavior is the same for all doc types, this might be am improvement, but not a bug.

Thanks for clarifying!

**Comment by noornajj** [comment]
Hello @lipusz,

Yes, the info button does appear for .docx files but does not appear for any document that has a preview. It is not just limited to .pdf files. I don't know what the full list of document types that have a preview so I had all documents being searched to have the showExtraInfo parameter set to true. 
The true value is still accurate for .docx files and it makes sense that this parameter reflect the correct value; even if it is not needed for .docx files.

Let me know if you have any other questions.

**Comment by BryanEngler** [comment]
running tests again here https://github.com/liferay-search/liferay-portal/pull/125, @noornajj maybe you can verify my changes cover all the cases you have tested. thanks!

**Pull request closed without merging**
