### PR TITLE
LPS-131812 Search configuration: No more Lucene

### PR DESCRIPTION
**Pull request by olafk**
https://issues.liferay.com/browse/LPS-131812

As discussed here: https://liferay.slack.com/archives/C04D8F2LM/p1620309559100400?thread_ts=1620309041.098800&cid=C04D8F2LM
With "Lucene" in the headline it looks like this section is outdated for 5 years now, but apparently it isn't (you might want to validate if it indeed isn't outdated, now that quite some search-related configuration is in OSGi)

### CODE REVIEW

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
TODO: Also remove 

```properties
#
    # Set the maximum number of clauses to allow in a boolean query. The default
    # is 1024.
    #
    # Env: LIFERAY_LUCENE_PERIOD_BOOLEAN_PERIOD_QUERY_PERIOD_CLAUSE_PERIOD_MAX_PERIOD_SIZE
    #
    #lucene.boolean.query.clause.max.size=1024
```

**Comment by lipusz** [comment]
Thanks @olafk for catching this. :+1:

**Comment by joshuacords** [comment]
New PR here: https://github.com/liferay-search/liferay-portal/pull/145

**Pull request closed without merging**
