### PR TITLE
LPD-22037 Add missing mappings for fields

### PR DESCRIPTION
**Pull request by jkappler**
Story ticket: https://liferay.atlassian.net/browse/LPD-18421
Subtask: https://liferay.atlassian.net/browse/LPD-22037

Dear team, @lipusz noticed that some mappings from vocabularies/categories were missing, so I add them. Please let me know what you think.

Thanks in advance!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:report:2558186785

**Comment by joshuacords** [comment]
Hello @jkappler, this looks good to me. Feel free to forward this.

**Comment by jkappler** [comment]
Thanks @joshuacords!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
