### PR TITLE
LPS-155716 SXPElement field localization breaks with nested fields

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-155716

Also fixed the overlapping text in the autocomplete dropdown:

Before:
Screen Shot 2022-09-14 at 4 09 03 PM

After:
Screen Shot 2022-09-14 at 5 25 16 PM

Truncated text will show full text on hover.

### CODE REVIEW

**Comment by thektan** [comment]
Unrelated failures since none of them are on happening on the blueprint edit page.

**Review by oliv-yu — APPROVED** [review]
Looks good! Thanks for making the dropdown look better too!

**Comment by oliv-yu** [comment]
ci:forward

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
