### PR TITLE
LPD-22160 Investigate the failures of the SearchResultResourceTest

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-22160

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
hey i just noticed the _postSearchPage has an entryClassNames param, so maybe we can just use that and not have to make any of the changes in 685037f. 
see https://github.com/BryanEngler/liferay-portal/commits/2024_04_12_LPS_22160_headless_type_facet_test_2/

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by gustavolimav** [comment]
ci:test:search-opensearch

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Review by gustavolimav — APPROVED** [review]
Code LGTM! 🚀 

Lets wait Solr and Opensearch suits to pass so we can forward.

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
