### PR TITLE
LPS-165921 portal-search-web Limit drag area to drag button so not to interfere with copy/paste

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-165921 - Unable to select and copy-paste from the input fields of the Search Bar Suggestions configurations

Not sure about how to fix the slow UX (I haven't been able to reproduce), but this fix addresses the drag functionality. Starting the drag is now scoped to the drag handle, instead of the whole box, to allow actions like copy/paste.

A quick demo:

https://user-images.githubusercontent.com/14063502/200433627-d45e3712-a134-422b-8f90-94b984f3d7fc.mp4

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Looks good! Thanks for making these updates and confirming that the drag preview still appears even though the recording didn't capture that. 👍

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/126292

**Pull request closed without merging**
