### PR TITLE
LPS-153747 Search Result message is in plural when only one result returns

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-153747

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:search

**Comment by daiazius** [comment]
I made the requested changes, can you take a look? Thanks @oliv-yu

**Review by oliv-yu — APPROVED** [review]
Looks great! Was able to try it out and see the changes 💯  I'll try forwarding

**Comment by oliv-yu** [comment]
@daiazius It looks like Brian Chan hasn't responded to https://github.com/brianchandotcom/liferay-portal/pull/120548 for over a week 😓 . I asked @thektan about the fix, he also wasn't sure if `emptyResultsMessage` would work for this x-of-x-result message. 

Maybe the if/else you had before would work? Does it work to have the if/else inside the `search-total-label` div? If you can discuss other examples of it being used, with some reasoning why we aren't using `emptyResultsMessage`, Brian may be more inclined to merge it. Do you mind sending a new PR with those changes? Feel free to clean up the commits. Thank you!

**Pull request closed without merging**
