### PR TITLE
LPD-15752 Upgrade process is not being executed

### PR DESCRIPTION
**Pull request by AlmirFe**
- https://liferay.atlassian.net/browse/LPD-15752

The changes were tested and approved in https://github.com/liferay-search/liferay-portal/pull/1261

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:forward

**Comment by AlmirFe** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:report: 2537111632

**Comment by xbrianlee** [comment]
ci:report:2537111632

**Comment by xbrianlee** [comment]
ci:report:2537759806

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
