### PR TITLE
LPS-156169 portal-search-web: Rename suggestion parameter for including asset summary

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-156169

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
Attempting to forward on https://github.com/liferay-search/liferay-portal/pull/470 🤞

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:forward

**Pull request closed without merging**
