### PR TITLE
LPS-151266 Add version and key fields to SXPElement and SXPBlueprint sb

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-151266

Based on: 
https://github.com/brianchandotcom/liferay-portal/pull/116110#issuecomment-1099038719

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:test

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hey Gustavo,

Can you ask our QA friends if there's a way to trigger the upgrade step on CI?

Otherwise, what you should try manually is to start U19 or U20 on a DB, stop, then build your branch, point your bundle to the same DB and run the Upgrade Tool manually locally.

Ignore my comment if such testing has already been done. :-)

Thanks!

**Comment by gustavolimav** [comment]
ci:help

**Comment by gustavolimav** [comment]
ci:test:help

**Comment by gustavolimav** [comment]
@lipusz unfortunately we don't have an upgrade test, so I will test it manually :muscle:

**Pull request closed without merging**
