### PR TITLE
[TS] LPS-119230 hotfix

### PR DESCRIPTION
**Pull request by joshuacords**
Author: @joshuacords 

https://issues.liferay.com/browse/LPS-119230

Hello @arboliveira,

Could you look through this to double check if this is code we can have the customer use while the ultimate fix is in development?

Notes: 
- Full Reindex will NOT recursively reindex child documents.
- I've added logic to use partialPermissioning when there is only additive permissions
- Only fixes DLFolders and DLFileEntries
- Threaded so indexing delays are not experienced by users

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @arboliveira,

I've fixed the problem which the DDMTemplateSearchTest.testSearchWithRegularRoleIndividualPermission test found. 

We don't need to worry about the semantic versioning as this will be rebased onto a 7.2 fixpack.

**Comment by joshuacords** [comment]
Search failures are on our known failures sheet.

Double checking the failures from Relevant

**Comment by joshuacords** [comment]
I tested the PDFProcessorTests locally and did not experience any failures.
The SearchRequestBuilderTest is listed in our known failures.

**Comment by lipusz** [comment]
Hello @joshuacords I think we should close this one and send a new PR unless André is actively reviewing/working on this. Currently it is affecting the team's review times unnecessarily.

**Pull request closed without merging**
