### PR TITLE
LPS-159773 portal-search-elasticsearch7-impl: downgrade ES client to …

### PR DESCRIPTION
**Pull request by joshuacords**
…widen range of compatible ES versions

https://issues.liferay.com/browse/LPS-159773

**Author:** @joshuacords 

Running tests to see if anything broke, everything seemed fine on my machine.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search-remote

**Comment by lipusz** [comment]
Hey Josh,

Please ask QA to also run it through the other suites for Commerce, Workflow etc.

**Comment by xbrianlee** [comment]
ci:test:search-environments

**Comment by xbrianlee** [comment]
ci:test:commerce

**Comment by xbrianlee** [comment]
ci:test:workflow

**Comment by xbrianlee** [comment]
ci:test:commerce-es7-remote

**Comment by xbrianlee** [comment]
ci:test:workflow-es7-remote

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
