### PR TITLE
LPS-151265

### PR DESCRIPTION
**Pull request by wcao20170619**
continued from https://github.com/wcao20170619/liferay-portal/pull/133
(https://github.com/brianchandotcom/liferay-portal/pull/118816)

added the ticket https://issues.liferay.com/browse/LPS-148563 for fixing the upgrade process.
thanks for fixing the useless codes and optimizing the codes. (also UpgradeExternalReferenceCode.java)

### CODE REVIEW

**Comment by joshchong** [comment]
Hey @wcao20170619, can you take a look at these two unique integration test failures that seem to be caused by this PR?

[com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest.testBoostContentsInACategoryForAUserSegment](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/67787/testReport/com.liferay.search.experiences.internal.blueprint.test/SXPBlueprintSearchResultTest/testBoostContentsInACategoryForAUserSegment/)
and
[com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest.testSearch](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/67787/testReport/com.liferay.search.experiences.internal.blueprint.test/SXPBlueprintSearchResultTest/testSearch/)

There is also a unique functional test failure caused by this PR, but it just needs a test fix which you can cherry pick here: https://github.com/joshchong/liferay-portal/commit/471482aef4c01fd62a2968278ba5dcaca65adda9

**Comment by wcao20170619** [comment]
ci:test:search

Hi, @joshchong I have made changes for the test failures and cherry-picked your fix.
Thanks!

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@wcao20170619 @joshchong i think a service-builder test failing on the relevant suite?

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@wcao20170619 it looks like the service-builder failure is caused by this PR so I aborted the latest relevant run. Can you take a look? 

[Full console log](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/73564/consoleText)
Failure snippet:
```
     [echo] diff --git a/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPBlueprintPersistenceImpl.java b/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPBlueprintPersistenceImpl.java
     [echo] index c5fd9d080402..ee7cc8e8586b 100644
     [echo] --- a/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPBlueprintPersistenceImpl.java
     [echo] +++ b/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPBlueprintPersistenceImpl.java
     [echo] @@ -3456,17 +3456,16 @@ public class SXPBlueprintPersistenceImpl
     [echo]  		SXPBlueprintModelImpl sxpBlueprintModelImpl =
     [echo]  			(SXPBlueprintModelImpl)sxpBlueprint;
     [echo]  
     [echo] -		if (Validator.isNull(sxpBlueprint.getExternalReferenceCode())) {
     [echo] -			sxpBlueprint.setExternalReferenceCode(
     [echo] -				String.valueOf(sxpBlueprint.getPrimaryKey()));
     [echo] -		}
     [echo] -
     [echo]  		if (Validator.isNull(sxpBlueprint.getUuid())) {
     [echo]  			String uuid = _portalUUID.generate();
     [echo]  
     [echo]  			sxpBlueprint.setUuid(uuid);
     [echo]  		}
     [echo]  
     [echo] +		if (Validator.isNull(sxpBlueprint.getExternalReferenceCode())) {
     [echo] +			sxpBlueprint.setExternalReferenceCode(sxpBlueprint.getUuid());
     [echo] +		}
     [echo] +
     [echo]  		ServiceContext serviceContext =
     [echo]  			ServiceContextThreadLocal.getServiceContext();
     [echo]  
     [echo] diff --git a/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPElementPersistenceImpl.java b/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPElementPersistenceImpl.java
     [echo] index c5fee1d1a1d1..58cf8d2cdfed 100644
     [echo] --- a/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPElementPersistenceImpl.java
     [echo] +++ b/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/service/persistence/impl/SXPElementPersistenceImpl.java
     [echo] @@ -6275,17 +6275,16 @@ public class SXPElementPersistenceImpl
     [echo]  		SXPElementModelImpl sxpElementModelImpl =
     [echo]  			(SXPElementModelImpl)sxpElement;
     [echo]  
     [echo] -		if (Validator.isNull(sxpElement.getExternalReferenceCode())) {
     [echo] -			sxpElement.setExternalReferenceCode(
     [echo] -				String.valueOf(sxpElement.getPrimaryKey()));
     [echo] -		}
     [echo] -
     [echo]  		if (Validator.isNull(sxpElement.getUuid())) {
     [echo]  			String uuid = _portalUUID.generate();
     [echo]  
     [echo]  			sxpElement.setUuid(uuid);
     [echo]  		}
     [echo]  
     [echo] +		if (Validator.isNull(sxpElement.getExternalReferenceCode())) {
     [echo] +			sxpElement.setExternalReferenceCode(sxpElement.getUuid());
     [echo] +		}
     [echo] +
     [echo]  		ServiceContext serviceContext =
     [echo]  			ServiceContextThreadLocal.getServiceContext();
     [echo]  
[stopwatch] [run.batch.test.action: 41:21.879 sec]
     [echo] .
     [echo] 
     [echo] Detected build services changes. See above build services log for more
     [echo] information. Make sure to commit in all build services results.
```

**Comment by wcao20170619** [comment]
ci:test:sf

@BryanEngler, I am done with my updating.

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@wcao20170619 @BryanEngler, the tests look good. However there's a merge conflict.

**Comment by wcao20170619** [comment]
@joshchong thanks! I have lowered the number in bnd.bnd file.

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
Hey @wcao20170619 @BryanEngler unfortunately with the latest changes, semantic versioning is failing with:
```
     [exec] [Baseline Warning] Bundle Version Change Recommended: 7.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.search.experiences.api-6.1.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.search.experiences.api/6.1.0/1a9d7cd5470b162eaaee37ed1d8140afda2cd90a/com.liferay.search.experiences.api-6.1.0.jar
```

**Comment by wcao20170619** [comment]
@joshchong that should work.

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
@joshchong @BryanEngler rebased

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@wcao20170619 @BryanEngler the test results look good to me!

**Comment by BryanEngler** [comment]
running tests one more time here - https://github.com/BryanEngler/liferay-portal/pull/652

**Pull request closed without merging**
