### PR TITLE
LPS-173765 Adds default mapping for viewCount as long, also add it to Solr to keep consistency

### PR DESCRIPTION
**Pull request by ealonso**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-173765)

The goal of these changes is to add the correct mapping for viewCount field into default mappings, also add it to Solr to keep it consistency.

## Change summary:

* Add field to **liferay-type-mappings.json** and **portal-search-solr8-impl/schema.xml**

## Test Scenario

1. Start Liferay
2. Go to Control Panel - Configuration - Search > Field Mappings
3. Copy the field mappings and inspect it, look for "viewCount" and "viewCount_sortable"

 Expected: "viewCount" is indexed as "keyword", "viewCount_sortable" is indexed as "long"
 Actual: "viewCount" is indexed as "text"

### CODE REVIEW

**Comment by peerkar** [comment]
ci:reevaluate:1277401_6735

**Comment by peerkar** [comment]
@ealonso could you please update the ElasticsearchIndexInformationTest-testGetFieldMappings.json accordingly?

I'm not sure what's the purpose of viewCount (nowadays) and how much scalability to expect of if it only updates on updating AssetEntry but choosing integer (max value 2^31-1) over long would perform slightly better if this field was used in search filters. Long is naturally better for scalability.

**Review by peerkar — CHANGES_REQUESTED** [review]
Already reviewed. Please see comment above.

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Review by peerkar — APPROVED** [review]

**Comment by ealonso** [comment]
Hey @peerkar,

I've already updated ElasticsearchIndexInformationTest-testGetFieldMappings.json. 

Regarding the viewCount usage, it is used on Most Viewed Assets widget to order the assets depending on it. I think it is the only use case that we have at this moment.

Widget_Page_-_Liferay_DXP

**Comment by peerkar** [comment]
ci:forward

**Pull request closed without merging**
