### PR TITLE
[TS] LPS-152937 Elasticsearch sort doesn't work with accented words

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
**Issue:** https://issues.liferay.com/browse/LPS-152937 - Elasticsearch sort doesn't work with accented words
See also https://issues.liferay.com/browse/PTR-3054

This issue was previously reported in https://issues.liferay.com/browse/LPS-93341 and some work was done in spike https://issues.liferay.com/browse/LPS-94561

The idea of that spike was to use the **icu_collation_keyword** from Elasticsearch ICU Plugin, see: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-collation-keyword-field.html 

In this PR I have used the code from that spike as the starting point (see https://github.com/brandizzi/liferay-portal/pull/813 PR and this branch https://github.com/brandizzi/liferay-portal/tree/LPS-94561 from @brandizzi repository)

**Original commits from LPS-94561 spike:** https://github.com/liferay-search/liferay-portal/commit/ceeefbecd5d2b3ecfc23e60d3cd9d693f22dd50c , https://github.com/liferay-search/liferay-portal/commit/35df586e3bf87e7fc65f124e0ead186d16123845, and https://github.com/liferay-search/liferay-portal/commit/fc9c4b462c027b22ae4df996398f3b57205c2932

I have done the following changes to this code:

**Changes 1: Tests added in BaseMultiLanguageSortTestCase** (from previous PR https://github.com/brandizzi/liferay-portal/pull/813)
   - https://github.com/liferay-search/liferay-portal/commit/640c3189a5b617a4898080c6e33d80d44e646dc3 fixes test name to testJapanKatakana
   - https://github.com/liferay-search/liferay-portal/commit/8509d70dc6ab212173a106ff83cd9bde74bef4a3 removes the Kanji sort test because it is not correct:
        - ICU library used by Elasticsearch doesn't support Kanji sorting, see: http://unicode.org/faq/collation.html#7
        - If you use this [ICU Collation Demo](https://icu4c-demos.unicode.org/icu-bin/collation.html), it returns different results than the expected in the removed test
        - In general, Japanese Kanji sorting seems to be a non-trivial task, read: http://www.localizingjapan.com/blog/2011/02/13/sorting-in-japanese-%E2%80%94-an-unsolved-problem/ or https://stackoverflow.com/questions/4895527/can-sorting-japanese-kanji-words-be-done-programmatically
        - It seems the author of that test (_Vagner Castro_) no longer works for Liferay, so I couldn't reach him to have more information about that test.
   - https://github.com/liferay-search/liferay-portal/commit/fa518c23f02e8f9c688360643be234a97fb68442 improves the Spanish test. As a native Spanish speaker, I detected that the original test had some missing checks related to the "ñ", "ch", and vowels with accents "á", "é"... 

**Changes 2: Elasticsearch mapping changes**
     - https://github.com/liferay-search/liferay-portal/commit/1ea1225a2fb52a04da24e8b499d5e0c6749048a5 => We must cover both regular `*_en_US_sortable` and nested `ddmFieldArray.ddmFieldValueText_en_US_String_sortable` fields
   - https://github.com/liferay-search/liferay-portal/commit/2ff477e2b1de9f8747be877b59ff2b6d5f17d19d => Replicate new mappings to all the existing locales. It is not necessary to specify the country because it is optional (see elasticsearch ICU plugin code: https://github.com/elastic/elasticsearch/blob/5aa174e6d3d280438822fc03c580bd9eac9faccf/plugins/analysis-icu/src/main/java/org/elasticsearch/plugin/analysis/icu/ICUCollationKeywordFieldMapper.java#L377-L391 )
   - https://github.com/liferay-search/liferay-portal/commit/e95c250a389e77b658996fa0b638a032b0a6f876 => Add de_AT (_Austrian German_) and fr_CA (_Canadian French_) country configurations as they have an specific collation configuration according to https://github.com/unicode-org/cldr/tree/main/common/collation

**Changes 3: Broken tests**
   - The Elasticsearch mapping changes break some existing tests because they compare the `_sortable `fields returned by Elasticsearch but now they are encoded in a strange way because we are using the **icu_collation_keyword** type:
```
expected:<...itle_de_DE_sortable=[entity title, localized_title_en_US=entity title, localized_title_en_US_sortable=entity title, localized_title_es_ES=entity title, localized_title_es_ES_sortable=entity title, localized_title_fi_FI=entity title, localized_title_fi_FI_sortable=entity title, localized_title_fr_FR=entity title, localized_title_fr_FR_sortable=entity title, localized_title_hu_HU=entitas neve, localized_title_hu_HU_sortable=entitas neve, localized_title_ja_JP=entity title, localized_title_ja_JP_sortable=entity title, localized_title_nl_NL=entity title, localized_title_nl_NL_sortable=entity title, localized_title_pt_BR=entity title, localized_title_pt_BR_sortable=entity title], localized_title_sv...> but was:<...itle_de_DE_sortable=[MkRQOlBaBFA6UEAyARABEAA=, localized_title_en_US=entity title, localized_title_en_US_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_es_ES=entity title, localized_title_es_ES_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_fi_FI=entity title, localized_title_fi_FI_sortable=entity title, localized_title_fr_FR=entity title, localized_title_fr_FR_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_hu_HU=entitas neve, localized_title_hu_HU_sortable=entitas neve, localized_title_ja_JP=entity title, localized_title_ja_JP_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_nl_NL=entity title, localized_title_nl_NL_sortable=entity title, localized_title_pt_BR=entity title, localized_title_pt_BR_sortable=MkRQOlBaBFA6UEAyARABEAA=]
```
   - In this example, the `entity title` text is encoded in the Elasticsearch side as `MkRQOlBaBFA6UEAyARABEAA=`
   - To solve this I am adding a new nested "raw" field in commit https://github.com/liferay-search/liferay-portal/commit/735cd5a27a305dd9607b39ff62f045a82e1c265f that stores the original _sortable value
   - https://github.com/liferay-search/liferay-portal/commit/ffea5d0c5dd508d61735a8d4e39b6151f1acb395 => I am modifying the **FieldValuesAssert** class where the returned and expected values are compared. I have added the _filterSortableFields method where the `_sortable.raw` fields are used to overwrite the `_sortable` ones that contain the encoded value. [After overwriting them](https://github.com/liferay-search/liferay-portal/commit/ffea5d0c5dd508d61735a8d4e39b6151f1acb395#diff-0209c19ec423285593c766e8cf8f37a02228eb4dc22bc2b86a13062a1f8d5c9aR190-R195), the comparison works correctly.

**Additional notes:**
   - In the end, we are only changing the mapping configurations, so this fix won't be applied to our existing customers until they execute a full reindex
   - On the other hand, If the customer updates to a version that contains this code, they won't detect any issue if they don't want to execute the full reindex, because their installation will continue to use the old mappings
   - **Warning:** :warning: If the customer has a custom development that uses the information stored in the _sortable fields, they will have problems, as now the information will be encoded. As a workaround, they can use the new `_sortable.raw` field.
   -  **We should add this information to the breaking changes documentation because the customer must be aware that they have to execute a full reindex to fix this issue and they have to review their custom developments just in case they query the `_sortable fields`**

**About the tests added in this PR:**
   - The tests are a bit incomplete. The major problem here is we need native speakers to add more tests in every supported language.
   - I have improved the Spanish test in this commit https://github.com/liferay-search/liferay-portal/commit/fa518c23f02e8f9c688360643be234a97fb68442 but I don't have the knowledge to improve any other language
   - Perhaps we can use the ICU Collation Demo (https://icu4c-demos.unicode.org/icu-bin/collation.html) or check the ICU information from https://github.com/unicode-org/cldr/tree/main/common/collation where there is information of every supported language, for example in the [pl.xml polish definition](https://github.com/unicode-org/cldr/blob/main/common/collation/pl.xml) you can see the precedence between every letter so, for example, `Z<ź<<<Ź<ż<<<Ż` means that `Ża, Ze, Źu` is sorted to `Ze, Źu, Ża`
   - Nevertheless, the best option is to double-check with native speakers (perhaps we can reach the people from this volunteer list https://liferay.slack.com/archives/CJ1ERLHUZ/p1650977876964469 )

Let me know if you have any questions about this PR

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Thanks @jorgediaz-lr for the thorough analysis and work on this.

Can you push a change to update the Breaking Changes markdown? We can also add that information to the ticket once it will be merged.

Thanks!

**Comment by jorgediaz-lr** [comment]
Hi @lipusz @BryanEngler 

I have added a new commit with the Breaking changes information, see https://github.com/liferay-search/liferay-portal/pull/434/commits/e02f8cef19103b430150cbf7bc15e273bafa4fe3

**Comment by BryanEngler** [comment]
im not necessarily a fan of storing the data twice with the raw field. kind of seems unlikely that anyone would be pulling values from the sortable field vs the value from the non-sortable field. also, the field is only encoded when retrieved as a stored_field. if its custom code they might be able to just retrieve from _source of fields instead. maybe we could document how to use override type mappings if someone needs the original keyword mapping. but to store everything twice for the majority of environments that would never use the raw field doesnt sound like the most efficient thing to do... theres a tradeoff both ways.

@lipusz @jorgediaz-lr thoughts?

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

The main reason to store the raw data is to just be able to restore here https://github.com/liferay-search/liferay-portal/pull/434/commits/ffea5d0c5dd508d61735a8d4e39b6151f1acb395#diff-0209c19ec423285593c766e8cf8f37a02228eb4dc22bc2b86a13062a1f8d5c9aR174-R199 the original `xxxxx_sortable` value from the stored `xxxxx_sortable.raw` and avoid having problems with the integration tests.

Getting the information from the **_source** field is more complex and I would need some help to change the tests as it seems the query is done in several places but the comparation is only done in the FieldValuesAssert class, can you give me more information about the necessary changes to apply this idea?

Thank you

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler @lipusz 

I have been working today on some changes in the tests that will avoid storing the raw field.

The drawback is we need to fix the failing tests individually.

I will keep you updated

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler @lipusz 

I have sent a new PR here: https://github.com/liferay-search/liferay-portal/pull/444

The new PR is similar to this, but instead of adding the "raw" mapping, I am updating the test code to use the "_source" information. For more information read the "Changes 3" section of the new pull request.

**Pull request closed without merging**
