### PR TITLE
LPS-195967 Fix integration tests in search suite that run into Company deletion issue

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-195967

approach suggested here:
https://github.com/liferay-core-infra/liferay-portal/pull/3935#issuecomment-1482047017

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@gustavolimav did you consider using `@DeleteAfterTestRun`?

**Comment by gustavolimav** [comment]
@BryanEngler Actually I didn't I will make the changes here and test

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
@BryanEngler resent [here](https://github.com/liferay-search/liferay-portal/pull/1104) using @DeleteAfterTestRun

**Pull request closed without merging**
