### PR TITLE
LPS-144398: Switch to Contributor Model

### PR DESCRIPTION
**Pull request by peerkar**
Switches SXP from indexers to contributor model resolving indexer registration issue and makes SXPElements visible without reindexing if deployed on existing installation. 

https://issues.liferay.com/browse/LPS-147776

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@gustavolimav @peerkar just FYI, this will conflict with https://github.com/liferay-search/liferay-portal/pull/340 since we are making changes to / deleting SXPBlueprintIndexer.java

**Comment by peerkar** [comment]
@BryanEngler just noticed I created this under the spike ticket number so re-sending this anyways. 

I can merge this https://github.com/liferay-search/liferay-portal/pull/340/commits/919ec42f155a629d0edfdc17be24cacba9977cca to the contributor (if description is really needed to be sortable?)

**Comment by BryanEngler** [comment]
https://github.com/liferay-search/liferay-portal/commit/919ec42f155a629d0edfdc17be24cacba9977cca can be kept under LPS-149053. Lets give priority to your changes here and get them committed, then either @gustavolimav or I will rebase and make the LPS-149053 changes to the contributor instead of the indexer

**Comment by peerkar** [comment]
Re-sent as https://github.com/liferay-search/liferay-portal/pull/343 under correct ticket number

**Pull request closed without merging**
