### PR TITLE
LPD-6591 Isolate Clause Contributors

### PR DESCRIPTION
**Pull request by joshuacords**
Story:
https://liferay.atlassian.net/browse/LPD-6591

Sub-tasks:
https://liferay.atlassian.net/browse/LPD-18244
https://liferay.atlassian.net/browse/LPD-18296

In https://liferay.atlassian.net/browse/LPD-18244 it was discovered that certain Administrator searches rely on query clause pollution to return related assets. They do this for comments when searchContext.isIncludeDiscussions is set, and for attachments when searchContext.isIncludeAttachments is set. I'll be [creating a ticket](https://liferay.atlassian.net/browse/LPD-19865) to improve this behavior in the future. For now, when these relatedAssets are needed, we will use the old behavior of non-isolated query clauses.

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search-solr

**Comment by joshuacords** [comment]
ci:test:opensearch2

**Comment by joshuacords** [comment]
ci:test:search-opensearch

**Comment by joshuacords** [comment]
ci:report:2547378144

**Comment by joshuacords** [comment]
ci:test:search-opensearch2

**Comment by joshuacords** [comment]
ci:report:2547393045

**Comment by joshuacords** [comment]
ci:report:2547411813

**Comment by joshuacords** [comment]
All tests look good!

**Comment by gustavolimav** [comment]
ci:help

**Comment by gustavolimav** [comment]
ci:test:search-es8-remote

**Comment by gustavolimav** [comment]
ci:report:2548780950

**Comment by gustavolimav** [comment]
Code and Tests looks good, I will test manually to make sure it is working as expected.

**Comment by BryanEngler** [comment]
@joshuacords @gustavolimav 
i think this should all be under a feature flag?

**Comment by BryanEngler** [comment]
@joshuacords @gustavolimav
nevermind, @lipusz said no FF for this one

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
