### PR TITLE
LPS-158848

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-158848

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@gustavolimav, the relevant run is going to keep failing due to the aborting unit test in https://issues.liferay.com/browse/LPS-159240. I've terminated your relevant run and will forward this PR along with the ignore of that test in https://github.com/liferay-search/liferay-portal/pull/513 
cc @brookedalton

**Pull request closed without merging**
