### PR TITLE
LPS-162054 Custom Facet Ordering

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-163277

Term Frequency Ascending
Screenshot from 2022-09-16 13-56-00

Term Frequency Descending
Screenshot from 2022-09-16 13-56-25

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by thektan — APPROVED** [review]
Frontend JSP changes look good 👍

**Comment by gustavolimav** [comment]
ci:reevaluate:1347401_2824

**Comment by BryanEngler** [comment]
i made a few commits and sent back to you @gustavolimav 
we can talk on about it on monday. thanks!

**Pull request closed without merging**
