### PR TITLE
LPS-149128 search-experiences-test: Add test coverage boost longer co…

### PR DESCRIPTION
**Pull request by gustavolimav**
…ntents element

https://issues.liferay.com/browse/LPS-149128

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
Looks good.

**Pull request closed without merging**
