### PR TITLE
LPD-32725 Homogenize button copy in Blueprints empty state & modal

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-32725 - Homogenize button copy in Blueprints empty state & modal

For consistency, this just updates the naming when making new blueprint/element/synonym sets.

Chaning to "Add" for SXP entities:
Screenshot 2024-07-30 at 12 28 33 PM
Screenshot 2024-07-30 at 12 26 16 PM
Screenshot 2024-07-30 at 12 26 29 PM

Changing to "New" for Synonym Sets:
Screenshot 2024-07-30 at 12 27 59 PM
Screenshot 2024-07-30 at 12 26 52 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Review by thektan — CHANGES_REQUESTED** [review]
If I'm not mistaken from the ticket, I think the correct change here would be to rename the _buttons_ to "New Search Blueprint" and "New Search Element". 

Also with other management bars adapting this "New" labeled button it seems like "New" is the preferred name over "Add".

Screenshot 2024-08-02 at 11 36 16 AM

**Comment by oliv-yu** [comment]
Oops, thanks for catching that @thektan! My bad, I'll update it the other way around 😅

**Comment by oliv-yu** [comment]
Updated! Screenshots for reference:

Screenshot 2024-08-02 at 3 03 35 PM
Screenshot 2024-08-02 at 3 03 45 PM

It looked like the language keys for "add-blueprint" and "add-element" were no longer being used anywhere, so I ended up taking them out as well.

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
