### PR TITLE
LPS-193391: Remove document type

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-193391

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@peerkar i thought "compatibility mode" supposed to handle these issues? when i looked into doc type removal a few years ago i think i tried removing most of the .type() methods... but it seemed like we didnt have to do that this time because of compatibility mode. i guess my point it, if we have to do it here, we might have to do it in a few more places...

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:reevaluate:1377401_13862

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by danielCamara02** [comment]
ci:forward:force

**Pull request closed without merging**
