### PR TITLE
LPS-203184 FTL Error in Category Facet with Vocabulary Layout Display Template

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPS-203184

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
@AlmirFe So it looks like as @felipelorenz had mentioned, the template error does not show thanks to this commit, however, now it uncovers the issue that the vocabulary names `assetCategoriesSearchFacetDisplayContext.getVocabularyNames()` are an empty array when there are no search hits, so the categories that are selected won't show. In the Vocab Layout ADT, the vocabulary names are important to grab categories for each vocabulary. Maybe someone who has worked on the `AssetCategoriesSearchFacetDisplayContextBuilder` would have a good idea how to render those vocabulary names? 😅 

It looks like with facets, it does display the selected even if there are no results, so the expectation is that they should still show up.
Screenshot 2023-12-04 at 12 38 22 PM

Otherwise, the fallback would be to insert an else starting around [here](https://github.com/liferay-search/liferay-portal/blob/0008df790d0a1ad81127a61e1459d8f4a83f8a16/modules/apps/portal-search/portal-search-web/src/main/resources/com/liferay/portal/search/web/internal/category/facet/portlet/display/template/dependencies/portlet_display_template_vocabulary.ftl#L155-L156) to not use the tree-view and just have a flat checkbox list.

**Comment by AlmirFe** [comment]
@gustavolimav ,  could you take a look at the back-end changes?

**Comment by oliv-yu** [comment]
Continued on: https://github.com/liferay-search/liferay-portal/pull/1181

**Pull request closed without merging**
