### PR TITLE
LPS-154676 Ensure unique FDS IDs in search-experiences modules

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-154676 Ensure unique FDS IDs in search-experiences modules](https://issues.liferay.com/browse/LPS-154676)

### What is the goal of this PR?

1. To ensure uniqueness of FDS ID, we are adding the portlet key prefix.
2. We are removing unnecessary FDS tag attributes, that are now set by default.

Pinging @oliv-yu , resident FDS expert :slightly_smiling_face:  

### What does it look like?

No changes in UI.

### CODE REVIEW

**Review by oliv-yu — APPROVED** [review]
Changes look good! Tried it out as well and works as expected 💯

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
❌ [ci:test:search - 123 out of 127 jobs passed in 2 hours 48 minutes](https://github.com/liferay-search/liferay-portal/pull/448#issuecomment-1137861195)

- Blueprints#ViewBlueprintsPreviewValidationForInvalidJSONProperty 
   - Known issue: [LPS-154217](https://issues.liferay.com/browse/LPS-154217)
- DataLayoutResourceTest
   - Known issue: [LPS-154679](https://issues.liferay.com/browse/LPS-154679)
- SXPBlueprintSearchResultTest
   - Known issue: [LPS-153543](https://issues.liferay.com/browse/LPS-153543)

✔️  Search test results look good!

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
