### PR TITLE
LPS-151040 search-experiences-test: Unflaky testBoostContentswithMore…

### PR DESCRIPTION
**Pull request by gustavolimav**
…Versions

https://issues.liferay.com/browse/LPS-151040

my theory is that this element is fine and without any bug, this flaky is caused by some cases where the boost is not sufficient to make the article with more versions be returned as the first. My change only adds an expressive boost to avoid that.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by joshuacords** [comment]
I think this boost is several magnitudes too high. But perhaps we could get QA to run this change 100 times on a test CI server to confirm your hypothesis.

@xbrianlee do we have resources set up to do this?

**Comment by xbrianlee** [comment]
I was able to run it about 70 times today and this failure didn't happen again.

**Comment by gustavolimav** [comment]
@xbrianlee thx!! @joshuacords so probably my hypothesis is correct, what numbers do you think it's nice to use here?

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
These numbers look reasonable - forwarding.

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
