### PR TITLE
LPS-184524 GET and PUT by ERC SXPElements

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-184524

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@felipelorenz can you resolve the conflicts?

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by gustavolimav — CHANGES_REQUESTED** [review]
@felipelorenz Can you make those changes before sending it?

**Comment by gustavolimav** [comment]
@felipelorenz can you reproduce those changes in SXPBlueprints PR?

**Pull request closed without merging**
