### PR TITLE
LPD-15752 Upgrade process is not being executed

### PR DESCRIPTION
**Pull request by AlmirFe**
- https://liferay.atlassian.net/browse/LPD-15752

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by gustavolimav** [comment]
ci:report:2536082319

**Review by gustavolimav — APPROVED** [review]

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
the tests results look good

**Comment by AlmirFe** [comment]
ci:forward

**Comment by AlmirFe** [comment]
ci:stop

**Comment by AlmirFe** [comment]
ci:test:stop

**Comment by AlmirFe** [comment]
New PR sent #1262

**Pull request closed without merging**
