### PR TITLE
Remove unused @Reference variables - Search components - second scan

### PR DESCRIPTION
**Pull request by AlmirFe**
- https://liferay.atlassian.net/browse/LPD-16539
     - https://liferay.atlassian.net/browse/LPD-16547

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Review by gustavolimav — APPROVED** [review]
LGTM 🚀

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
test results look good!

**Comment by AlmirFe** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
