### PR TITLE
LPS-202710 portal-search-web: Check if user has administrator rule instead of if it is omni admin

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-202710

Tested with test test user:
image

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by lipusz** [comment]
@AlmirFe @gustavolimav 

This is intentionally limited to Omni Admins. Not a bug.

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:stop

**Pull request closed without merging**
