### PR TITLE
LPS-130001 Change the default value of ProxyModeThreadLocal#forceSync to TRUE

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130001](https://issues.liferay.com/browse/LPS-130001).<br/><br/>This relates to an on-going issue across portal where the UI does not show up-to-date indexer results after an action that triggers a reindex on a number of documents. This occurs because reindexing is asynchronous by default, with the option to force synchronous reindexing using ProxyModeThreadLocal used often to work around this issue (see the changes in accounts-admin-web for examples). After discussing this issue with Shuyang, we would like to make reindexing synchronous by default, with the option to force asynchronous indexing still present by the same means. This should make it easy to resolve instances where performance is a concern.<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @shuyangzhou

### CODE REVIEW

**Comment by drewbrokke** [comment]
Related story: https://issues.liferay.com/browse/LPS-125833

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@Sharryxue @patriciajeanperez is this a real failure? https://github.com/liferay-search/liferay-portal/pull/111#issuecomment-829439733

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
