### PR TITLE
LPS-194710 portal-search-elasticsearch-impl: Add unit test to when Elasticsearch Deep Pagination keep alive time is  > 60 and <= 0

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-194710

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
LGTM!

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
ci:force:forward

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
