### PR TITLE
LPD-8052 Review and bump third-party other dependencies in the Elasticsearch 7 connector on all versions to the latest available compatible version

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-8052

The bump of `jackson-dataformat-cbor` was made on modules `portal-search-elasticsearch7-impl` and `multi-factor-authentication-fido2-web` the other module that has CBOR dependencie (`portal-store-s3`) when I made the bump appeared some failures related to this bump, so I kept it the way it was.

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:2544285746

**Comment by felipelorenz** [comment]
ci:report:2544303730

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by joshuacords — CHANGES_REQUESTED** [review]
Hello @felipelorenz,

I was looking at the jackson versions available in maven for [cbor](https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor) and others, and it seems like they can be upgraded to 2.16.1 just fine (I compiled and built it.) Lucene dependencies like [lucene-core](https://mvnrepository.com/artifact/org.apache.lucene/lucene-core) also might be upgradeable (perhaps with some code changes).

Could you outline each of the libraries you looked into bumping and the problems you encountered?

**Comment by lipusz** [comment]
@joshuacords The Lucene libraries must match the version used by Elasticsearch 7.17.18.

**Comment by lipusz** [comment]
You can find all dependencies and their versions used by 7.17.18 in this file: https://github.com/elastic/elasticsearch/blob/v7.17.18/gradle/verification-metadata.xml#L2937

**Comment by felipelorenz** [comment]
Thanks @lipusz! @joshuacords I bumped to the most up-to-date version used by elasticsearch 7.17.18

**Comment by joshuacords** [comment]
I've looked through the elasticsearch metadata, it looks like we should be able to use a newer version of snake-yaml:
`<component group="org.yaml" name="snakeyaml" version="2.2">`

I'm also wondering if `compileInclude group: "org.ow2.asm", name: "asm-debug-all", version: "5.1"` can be bumped.

**Comment by joshuacords** [comment]
I still don't see why we can't bump the com.fasterxml.jackson.dataformat libraries to 2.16.1.

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by joshuacords** [comment]
@felipelorenz, these version look good to me

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:2548111233

**Comment by felipelorenz** [comment]
ci:report:2548074527

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:2548262562

**Comment by felipelorenz** [comment]
Failures also occur without those changes, so they are not related.

**Pull request closed without merging**
