### PR TITLE
LPS-165923 Add support for View Raw Request to the Blueprints Preview

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-165923

**Background**

I recorded this as a todo item based on the lessons learned of the Gartner demo and today I got some time to play with it. If it gets merged soon, I could leverage this during the /dev/24 sessions on Nov 29-30 right away.

**Solution**

As the `requestString` is already available in the response, I just followed the pattern to display it.

image
image

Thanks guys for taking care of the rest!
,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
Hi @thektan or @oliv-yu 

This was not in the scope of the Sprint so it's absolutely not a priority to review. It's just something I recorded as a todo item based on the lessons learned of the Gartner demo and today I got some time to play with it.

It appears to be working, though it may need extra massaging from you.

It was really easy to apply these changes thanks to the well-organized components. :wink: 

If one of you could allocate some time to review this later during the Sprint that would be great. I could leverage this during he /dev/24 session too on Nov 29-30.

Thanks!

**Comment by lipusz** [comment]
ci:test:relevant

**Review by oliv-yu — APPROVED** [review]
Thanks for adding this! I don't have any changes to suggest, but I'll wait for @thektan in case he has feedback about the appearance/performance.

**Comment by thektan** [comment]
Looks straight-forward to me! I'll go ahead and forward this. None of the failures seem unique to this PR.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
