### PR TITLE
LPS-192650 HTML seen in search suggestions widget

### PR DESCRIPTION
**Pull request by AlmirFe**
### **LPS link:** [LPS-192650](https://liferay.atlassian.net/browse/LPS-192650)

# Context

After changes made by https://github.com/liferay-search/liferay-portal/pull/911/commits/effab8390638b7767e395ebfc4eee3eaf69d4901 the [view.jsp](https://github.com/liferay/liferay-portal/blob/7.4.3.89-ga89/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/suggestions/view.jsp) file is using "clay:link" instead of "aui:a" as you can see bellow:

## Before changes

```
<aui:a href="<%= suggestionDisplayContext.getURL() %>">
	<%= suggestionDisplayContext.getSuggestedKeywordsFormatted() %>
</aui:a>
```

## After changes

```
<clay:link
	href="<%= suggestionDisplayContext.getURL() %>"
	label="<%= suggestionDisplayContext.getSuggestedKeywordsFormatted() %>"
/>
```

The getSuggestedKeywordsFormatted function of the SuggestionDisplayContext class returns the suggested keywords with HTML formatting. However, the label field of "clay:link" does not need HTML formatting. Because of this, HTML elements are shown in the UI.

# Proposed solution

The [stripHtml](https://github.com/liferay/liferay-portal/blob/e7b4deb6b873d5f964882141e352d0b9601138eb/portal-kernel/src/com/liferay/portal/kernel/util/HtmlUtil.java#L163C1-L165C3) function of the [HtmlUtil](https://github.com/liferay/liferay-portal/blob/7.4.3.89-ga89/portal-kernel/src/com/liferay/portal/kernel/util/HtmlUtil.java) class is used to strip HTML from clay:link label, as you can see bellow:

```
<clay:link
	href="<%= suggestionDisplayContext.getURL() %>"
	label="<%= HtmlUtil.stripHtml(suggestionDisplayContext.getSuggestedKeywordsFormatted()) %>"
/>
```

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:stop

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
@AlmirFe Thanks for working on this! Hadn't realized using `clay:link` would cause this bug, I was looking back at other replacements to `clay:link` on that commit, and it seems like those labels are translated language keys so hopefully this bug has only been happening within suggestions portlet.

Suggestion: I think when you apply `stripHtml`, the link would actually lose the bold formatting and the class name of `changed-keyword` that the suggestions builder had applied. In that case, I would suggest just using the `a` tag, as it's still common in JSPs:

```
<a href="<%= suggestionDisplayContext.getURL() %>">
	<%= suggestionDisplayContext.getSuggestedKeywordsFormatted() %>
</a>
```

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Hey @AlmirFe, it looks like using `aui:a` taglib causes the SF to fail, maybe just using the `a` tags might pass?

**Comment by AlmirFe** [comment]
> Hey @AlmirFe, it looks like using `aui:a` taglib causes the SF to fail, maybe just using the `a` tags might pass?

This error didn't happen when I ran `gw formatSource`. I'm going to change it. Thanks @oliv-yu

**Comment by AlmirFe** [comment]
ci:test:sf

**Review by oliv-yu — APPROVED** [review]

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/139499

**Pull request closed without merging**
