### PR TITLE
LPS-174196 | LPS-174547, LPS-179092, LPS-179089 Scroll API

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
@gustavolimav once CI is good to go, i think you will probably have to resolve some merge conflicts with the code from https://github.com/liferay-search/liferay-portal/pull/874, so you should probably get that one merged first before you try to forward this one... thanks!

**Comment by gustavolimav** [comment]
Resent here: https://github.com/liferay-search/liferay-portal/pull/880

**Pull request closed without merging**
