### PR TITLE
Failed upgrade process com.liferay.search.experiences.internal.upgrade.v3_0_0.SXPBlueprintUpgradeProcess

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPS-203687

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
LGTM!

**Review by felipelorenz — APPROVED** [review]

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
