### PR TITLE
LPS-184523 Search with a Blueprint by its External Reference Code (ERC)

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Manually forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/138348

**Pull request closed without merging**
