### PR TITLE
LPS-183440 portal-search-solr8-impl: Fix NullPointerException in SearchResponseResourceTest.testPostSearch with Solr

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-183440

### CODE REVIEW

**Comment by gustavolimav** [comment]
It fixes the NullPointerException but we need to fix another bug:
image

Assert Error Point -> https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-rest-test/src/testIntegration/java/com/liferay/portal/search/rest/resource/v1_0/test/SearchResponseResourceTest.java#L391

Where it is set -> https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-rest-impl/src/main/java/com/liferay/portal/search/rest/internal/resource/v1_0/SearchResponseResourceImpl.java#L330


@peerkar seems to me that Solr documents never return an `Id`, can you confirm that?

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by joshuacords** [comment]
Keep working on the fix until the test runs successfully.

**Comment by gustavolimav** [comment]
ci:test:search-sorl

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Continued here: https://github.com/liferay-search/liferay-portal/pull/924

**Pull request closed without merging**
