### PR TITLE
LPS-140998 Blueprints & Elements: Bulk Actions + Order

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-140998 - Blueprints & Elements: Bulk Actions, Filter and Order, Blueprint Actions (Kebab menu)

Some notes:
- The current FDS display doesn't look like it can dynamically vary the dropdown actions based on properties of the items, so this was a bit tricky for bulk delete with read only elements. So for that case, if any of the selected elements is a read-only, there will just be an error message informing that delete action was unsuccessful.
- Small edit to FDS was made on https://issues.liferay.com/browse/LPS-149052 for the look of 'Items Selected'
- Being able to order on FDS display is provided on the heading row of the table, so you'll see double arrows near Title and Modified/Created Date, which will allow sorting that way.

Thanks for taking a look!

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Thanks @oliv-yu! Showing an error message seems appropriate to me. Hiding the delete icon might be more frustrating not knowing why the delete icon doesn't appear. 

Thanks for also sending frontend infra that label change!

**Comment by joshchong** [comment]
continued in:
https://github.com/liferay-search/liferay-portal/pull/338

**Pull request closed without merging**
