### PR TITLE
[TS] LPS-161064 The 'Card Layout' in the search result portlet is not working correctly if there is a data inconsistency between Elasticsearch and Database entries

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
See https://issues.liferay.com/browse/LPS-161064

Instead of fixing the "Card Layout" freemarker template, I think it is better to fix this in the SearchResultsPortlet code, skipping the temporarily unavailable results in the same way it is done in the SimilarResultsPortlet (see https://github.com/liferay-search/liferay-portal/blob/4f0444b593b5845b2b0cdef1a1cea0c433dadb53/modules/dxp/apps/portal-search-similar-results/portal-search-similar-results-web/src/main/java/com/liferay/portal/search/similar/results/web/internal/portlet/SimilarResultsPortlet.java#L173-L178)

The main advantage of this is we will also solve the problem in the customer freemarker templates that don't check the isTemporarilyUnavailable value for every result.

After adding this validation, I have also added an additional commit that removes the now redundant isTemporarilyUnavailable checks in our freemarker templates.

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Rebased to latest master

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Rebased again, now using upstream/master

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
