### PR TITLE
LPS-122062 Update "org-elasticsearch7-painless" to 7.9.0.LIFERAY-PATCHED-1

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-122062

Hello Brian,

We need to bump this to 7.9.0 to be able to bump the client libs on 7.2.x to 7.9.0 to fix https://issues.liferay.com/browse/LPS-120240.

Thanks,
Tibor

/cc @BryanEngler fyi

### CODE REVIEW

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
Thanks @timpak for keeping your eyes om this. 😉

**Comment by timpak** [comment]
ci:forward

**Comment by lipusz** [comment]
ci:forward

**Pull request closed without merging**
