### PR TITLE
LPS-168167 LPS-168292 LPS-168293 LPS-168463 LPS-168935 Semantic Search Configuration Typo + Renaming + Bug

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-168292 - [FE] Fix: help text in Semantic Search configuration has a typo. "embedded" is spelled as "embbedded"
https://issues.liferay.com/browse/LPS-168293 - [FE] Semantic Search configuration section renaming
https://issues.liferay.com/browse/LPS-168463 - [FE] Rename Hugging Face Sentence Transformer to "Hugging Face - Inference API"
https://issues.liferay.com/browse/LPS-168935 - Test Configuration button is not disabled while there are missing required fields

It's long, but straightforward...sending all these together to avoid rebase conflicts! Items mentioned:

- Fix typo with 'embbedding' inside language key
- Rename TRANSFORM PROVIDER SETTINGS section to SENTENCE TRANSFORMER SETTINGS
- Rename the "Sentence Transform Provider" dropdown to "Sentence Transformer" (rename all variables)
- Rename Indexing Settings section > INDEX SETTINGS
- Move "Cache Timeout" from Index Settings to a new section called "SEARCH SETTINGS"
- Add help text is shown when this provider is selected under the "Sentence Transformer" option (include support for learn message links)
- Remove enableGPU configuration option
- Fix small bug with test configuration button (just had to update the hugging face variable)

Let me know if there's anything else, thanks!

### CODE REVIEW

**Comment by oliv-yu** [comment]
Had to rebase for the language key merge conflicts, and it looks like this might need some test updates? Otherwise, let me know what you think, thanks!

**Comment by joshchong** [comment]
@oliv-yu @thektan hey, I noticed this branch requires a test fix which I've committed here: https://github.com/joshchong/liferay-portal/commit/fb95c7416c0b175bd1ff4eefd9972b9226c9f558

Feel free to cherry pick the commit into this branch and rerun the tests

**Comment by thektan** [comment]
@joshchong Thanks!

@oliv-yu Can you cherry pick and rerun the tests? I'm just doing some final testing, but the code looks good. 👌

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Review by thektan — APPROVED** [review]
Thanks for especially making all those consistent renames! I'll forward after `relevant` finishes.

**Comment by thektan** [comment]
@oliv-yu Looks like you'll need to run gradle baseline in `search-experiences-api`

**Comment by thektan** [comment]
You can run ci forward after you make that commit.

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
