### PR TITLE
LPD-15115 portal-impl: Ajust type of the FF to system level

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-15115

https://liferay.atlassian.net/browse/LPD-15115?focusedCommentId=2562392

Tested manually the ERROR is not appearing anymore.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by AlmirFe — APPROVED** [review]
LGTM!

**Comment by AlmirFe** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
