### PR TITLE
LPS-199490 Duplicated values in search bar

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPS-199490

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
LGTM :rocket:

**Pull request closed without merging**
