### PR TITLE
LPD-28673 Update Categories related OOTB Blueprints elements and UI configuration components to use and query by ERC

### PR DESCRIPTION
**Pull request by joshuacords**
**Story:** [LPD-28673](https://liferay.atlassian.net/browse/LPD-28673)
**Subtasks:** [LPD-37239](https://liferay.atlassian.net/browse/LPD-37239), [LPD-37240](https://liferay.atlassian.net/browse/LPD-37240), [LPD-37248](https://liferay.atlassian.net/browse/LPD-37248)

FE already Reviewed [here](https://github.com/liferay-search/liferay-portal/pull/1494).

**Authors:** @joshuacords @oliv-yu

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
