### PR TITLE
LPD-27212 Restriction account  not working properly in custom Facets

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-27212

The solution it self its already approved by @BryanEngler, its necessary just review the tests.

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:34398601

**Comment by felipelorenz** [comment]
Tests are good, the failures are not related.

**Review by joshuacords — APPROVED** [review]
Tests LGTM :rocket:

**Comment by felipelorenz** [comment]
ci:forward

**Pull request closed without merging**
