### PR TITLE
De-couple search engine connection help texts from Elasticsearch; supports LPS-200781

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-200781

Request originated here: https://liferay.atlassian.net/wiki/spaces/ENGSEARCH/pages/2572093101/OpenSearch+Testing?focusedCommentId=2581791251

cc @peerkar @bryanengler @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
@rbohl Thanks for taking care of it. Could you guys create a Task ticket or something to commit the changes under?

Epics normally do not have commits associated.

**Comment by peerkar** [comment]
@rbohl looks good to me :+1:

**Comment by rbohl** [comment]
https://liferay.atlassian.net/browse/LPS-203570

Does that mean I can send to Brian (after amending my commit message to use this task?)

**Comment by rbohl** [comment]
ci:test:sf

**Comment by rbohl** [comment]
ci:forward

**Comment by rbohl** [comment]
ci:stop

**Comment by rbohl** [comment]
Sent manually to avoid superfluous CI tests: https://github.com/brianchandotcom/liferay-portal/pull/145042

**Pull request closed without merging**
