### PR TITLE
LPS-156770 sxp blueprint suggestions contributor test

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-156770

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1297401_4112

**Comment by BryanEngler** [comment]
@gustavolimav 
looks like SXPBlueprintSuggestionsContributorTest.testSuggestionsContributorConfigurationWithAssetRendererNull is failing on this branch?

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
@BryanEngler I pushed the right version

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
lgtm, i just added a small sf commit so i will forward from https://github.com/BryanEngler/liferay-portal/pull/662
thanks!

**Pull request closed without merging**
