### PR TITLE
LPS-157872 Add new variables to the search results widget template context

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-157872

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:reevaluate:1267401_5040

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:reevaluate:1307401_4641

**Comment by gustavolimav** [comment]
ci:forward

**Comment by brookedalton** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/123360

**Pull request closed without merging**
