### PR TITLE
LPD-5581 Refactor search widgets AUI JS - modified/date facet configuration

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-5581 - Refactor search widgets AUI JS to plain JavaScript or React for portal-search-web - modified_facet_configuration.js

Dev notes:
- Creates a plain JS component to handle what AUI used to, in this case it'd be arranging the date ranges input for submission
- Since the new file for the modified and date facet configuration are the same, it seemed reasonable to share the component and put it in /shared. Let me know what you think about that choice! 🤔

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Looks good! Cleaner than the original 👌

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:report:2531074772

**Comment by oliv-yu** [comment]
ci:forward:force

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
