### PR TITLE
LPS-155726 LPS-171212 Help texts and links to documentation for searchbar

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-155726 - Help Texts and Links to Documentation for the Search Bar Suggestions

This adds some helptexts and descriptions for the searchbar within configuration + system/instance settings, also adding a learn more link. To avoid some confusion with existing language keys, I added an extra descriptor to some of them, such as `size-suggestion-help` or `fields-suggestion-help` or `suggestions-contributor-configuration-system-settings-help` ... feel free to adjust, thanks!

Screen Shot 2022-12-16 at 4 53 18 PM
Screen Shot 2022-12-16 at 4 52 52 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
The test failures don't seem to look related, but let me know what you think, thanks!

**Review by thektan — APPROVED** [review]
Changes look good and the adding the `-suggestion` in the key sounds good with me. 👍

**Comment by thektan** [comment]
I don't see any related failures as well, so I'll attempt to forward this.

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
Manually forwarded to bchan
https://github.com/brianchandotcom/liferay-portal/pull/128069

**Pull request closed without merging**
