### PR TITLE
LPS-166987 LPS-167286 portal-search-solr8-impl: Fix SolrDocumentMappingTest

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-167290
https://issues.liferay.com/browse/LPS-167286

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1267401_5927

**Comment by BryanEngler** [comment]
@gustavolimav thanks for the pr, see https://github.com/BryanEngler/liferay-portal/pull/712

i ended up fixing the tests in a different way, so when you get a chance take a look and see what i did instead. thanks!

**Pull request closed without merging**
