### PR TITLE
LPD-17372 Fix incorrect number of pages in the paginated results in the SearchResultsPortlet

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-17372 - Incorrect number of pages in the paginated results in the SearchResultsPortlet

Based on the conversation in https://liferay.atlassian.net/browse/LPP-52649, in order for the pagination to keep proper track for the items in its dropdown, `useNamespace` should be set to `true`. This means the parameters for `delta` and `start` would then be namespaced.

Demo of bug fix and what the URL looks like now:

https://github.com/liferay-search/liferay-portal/assets/14063502/b77e2d2c-74e3-462e-a5c1-e2565b5cf552

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Needs more discussion.

**Pull request closed without merging**
