### PR TITLE
LPD-26148   POST /search FF status becomes RELEASE, GET /search becomes DEV in U131/2024.Q3

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-26148

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:report:38774752

**Comment by joshuacords** [comment]
ci:report:38774752

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:help

**Comment by joshuacords** [comment]
ci:test:bundle

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Review by gustavolimav — CHANGES_REQUESTED** [review]
Hey @joshuacords, you forgot to run `gw buildLang`

**Comment by gustavolimav** [comment]
Other than that code looks good.

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:report:40269457

**Comment by joshuacords** [comment]
ci:report:40301683

**Pull request closed without merging**
