### PR TITLE
LPS-151930 portal-kernel: Update class name for highlighted text

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-151930 Search results portlet highlighted results should be styled by Clay and the theme.

Updating the class to 'mark' instead of 'highlight' actually changes the highlighting slightly, so I included a side by side comparison. Also removed the styling involved with the 'highlight' class name since it would no longer be used! Let me know if there's anything else to change, thanks!

Before:
Screen Shot 2022-12-12 at 3 18 04 PM
Screen Shot 2022-12-12 at 3 19 50 PM

After:
Screen Shot 2022-12-12 at 3 18 31 PM
Screen Shot 2022-12-12 at 3 19 13 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Thanks for making the adjustments we discussed! 👍

**Comment by thektan** [comment]
Tests need to be updated to match the background color defined in clay css: `#fcf8e3`

https://github.com/liferay/clay/blob/f942a819c744d74ac65f4d39167217efe16454d7/packages/clay-css/src/scss/variables/_globals.scss#L699

**Comment by xbrianlee** [comment]
Tested with functional test fix in https://github.com/xbrianlee/liferay-portal/pull/1061.

Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/127730.

**Pull request closed without merging**
