### PR TITLE
LPS-196807 Older versions of Web Content are indexed with the newest version's values

### PR DESCRIPTION
**Pull request by lfbesada**
Previous PR: https://github.com/liferay-search/liferay-portal/pull/1114

This PR fixes three bugs:
https://liferay.atlassian.net/browse/LPS-196807
https://liferay.atlassian.net/browse/LPS-198486
https://liferay.atlassian.net/browse/LPS-199784
On already existing content, a reindex is needed to fix these issues.

**Motivation**

When content that has asset entries is reindexed, the different AssetEntry contributors add fields to the content based on information related to its assetEntry.
Journal articles have versions and not all of them have asset entries.
Currently, the no-latest article published versions are processed assuming that their assetEntry was the latest published one, and that is not correct.
This PR adds a new method in AssetRendererFactory to get the AssetEntry from the base model and delegates the calculation of the entryClassPK field to that method. It is taking into account that the base model could have no asset entry, so its entryClassPK is going to be 0. So, from now on, for those articles that do not have any asset entry, its entryClassPK is going to be 0.
Consequently, the AssetEntryDocumentContributor does not add fields for versions that do not have an entry, which fixes the original bug.
The same logic manages to fix LPS-198486 because AssetTagDocumentContributor and AssetCategoryDocumentContributor receive 0 as entryClassPK so they do not use the categories and tags published for the other versions.

Hi @joshuacords 

Thank you very much for the review of the previous pull request and more additional thanks for finding those problems in the previous pull request :raised_hands: 

This pull request is the same as the previous one but I added three more commits.

The first two commits solve [the first problem you detected](https://github.com/liferay-search/liferay-portal/pull/1114#issuecomment-1778069220)

* [LPS-196807 Use TYPE_LATEST instead of TYPE_LATEST_APPROVED](https://github.com/liferay-search/liferay-portal/pull/1125/commits/b28f9b1139ef766b1104b4d04140fca65a40d345)
* [LPS-196807 Catch NoSuchArticleException and then return null](https://github.com/liferay-search/liferay-portal/pull/1125/commits/7adaedd26a3b048fa7b7205a7aa967d507b35641)

The last one commit fixes [the second problem](https://github.com/liferay-search/liferay-portal/pull/1114#issuecomment-1778088095)

* [LPS-196807 Populates localization to index the proper translation …](https://github.com/liferay-search/liferay-portal/pull/1125/commits/5caea49b93553fcce491fca3f1b39b63df5d285a)

Thanks in advance :heart: 

Regards

PD: This PR fixes [this issue]( https://liferay.atlassian.net/browse/LPS-199784) too thanks to @joshuacords that detected this scenario [here](https://github.com/liferay-search/liferay-portal/pull/1114#issuecomment-1778088095)

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

Re-running since CI Infrastructure was restarted

**Comment by xbrianlee** [comment]
ci:test:relevant

Re-running since CI Infrastructure was restarted

**Comment by xbrianlee** [comment]
ci:test:search

Re-running since CI Infrastructure was restarted again

**Comment by xbrianlee** [comment]
ci:test:relevant

Re-running since CI Infrastructure was restarted again

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @lfbesada, letting you know that we want our lead engineer to take a look at this as well, he's expecting that he won't be able to until Wed.

**Comment by lfbesada** [comment]
Hi @joshuacords 
Thanks for your kind update!
Regards

**Comment by brunofernandezg** [comment]
Hi @joshuacords,
This PR fixes a customer bug and is an escalation, we would need to prioritize it.
Thanks

**Comment by BryanEngler** [comment]
So I basically just looked at BaseIndexer and BaseModelDocumentFactoryImpl (identical logic added for both), and the changes seem fine to me... the relationship between JournalArticle's id_ / resourcePrimKey / classPK / articleId is a little blurry to me, and I didn't manually test at all, but this pr has 3 integration tests so I'll trust that the necessary behavior has been implemented. Thanks @lfbesada

**Comment by xbrianlee** [comment]
ci:test:search

Re-running this test suite to confirm if there were unique failures

**Comment by lfbesada** [comment]
Hi @BryanEngler @joshuacords 
Thank you very much for the review! :heart: 
Please, could you inform me of the next step? Should I do the forward myself or it will be handled by the Search Team?
Thank you! 
Regards

**Comment by xbrianlee** [comment]
Hey @lfbesada, there are some [unique test failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2449530177&testrayRunIdA=2449073006&statusB=3) on this PR. Could you look into them?

[Search#SearchWebContent](https://testray.liferay.com/home/-/testray/case_results/2449530656) is failing due to search results returning "WC" when searching for "WC1". In upstream, "WC" doesn't get returned.

**Comment by lfbesada** [comment]
Hi @xbrianlee 
Thanks for the analysis! :heart: 
I ran all those search and journal integration tests locally before pushing this PR and they worked correctly I just manually tested the poshi test with the same result.
Please, could we rerun the tests to see if those failures are consistent?
Tomorrow is a bank holiday in Spain, I will be back on Thursday
Thanks in advance!

**Comment by xbrianlee** [comment]
@lfbesada These tests failed in all 3 test suite runs in this PR and they aren't flaky based on recent results. I would recommend investigating them with the [bundle generated by CI](https://files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/8114/liferay-portal-bundle-tomcat.tar.gz) (in case there are differences with the bundle you tested with) before re-running the tests again. I was able to manually reproduce the functional test failure on this bundle.

**Pull request closed without merging**
