### PR TITLE
[TS] LPS-157511 Date field added from widget template does not allow manual enter of data in Modified Facet

### PR DESCRIPTION
**Pull request by antonio-ortega**
https://issues.liferay.com/browse/LPS-157511

Hi guys,

This restriction was added [here](https://github.com/liferay/liferay-portal-ee/commit/e102f9dfb700df1260b2a3f53095b34f97279102), I guess to help validating dates, however preventing keyboard input makes really hard for end users to select dates far from today. 

I've checked introducing data manually after this change and I can see how data is still being validated.

Let me know if you have further questions.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Thanks for this change @antonio-ortega! This change makes sense to me too.

**Comment by thektan** [comment]
Failures don't seem related but I'll run it again and forward it once I double-check the test results.

**Comment by thektan** [comment]
ci:reevaluate:1387401_1995

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
