### PR TITLE
LPD-31227 Low Level Search Options configuring Contributors can lead to UnsupportedOperationException with Collections

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-31227

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:report:35287607

**Review by gustavolimav — APPROVED** [review]
✅  Passed manual test

Code looks good too 🚀

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
