### PR TITLE
Search Experiences Canary Tests

### PR DESCRIPTION
**Pull request by joshchong**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by xbrianlee** [comment]
ci:test:search-experiences:norebase

**Comment by xbrianlee** [comment]
ci:test:search-experiences:norebase

**Comment by xbrianlee** [comment]
ci:test:search-experiences:norebase

**Comment by xbrianlee** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search-experiences

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Comment by joshchong** [comment]
ci:test:search-experiences:norebase

**Pull request closed without merging**
