### PR TITLE
LPS-140641 Asset Category Selector inside Blueprint Editor

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-140641 - When building Blueprint, I can select an Asset Category for my element through the UI without collecting its ID manually

This new component allows the selection of categories by directly typing in the name or looking it up in the tree. It uses several APIs to access sites, vocabularies, categories, and subcategories. This new input type is called `categorySelector` and it defaults to selecting only a single asset category, but with the typeOption `format` set to `array` it can accept and output the IDs as an array. 

Edit: All OOTB elements related to selecting categories have been updated with the category selector, so they are available to try out! Boost Contents in a Category is the only multiselect.

Edit: Updated to use descriptiveName of site, from ticket https://issues.liferay.com/browse/LPS-157176.

Screenshots:

Single Selection

Screen Shot 2022-07-20 at 4 24 51 PM

Screen Shot 2022-07-20 at 4 24 59 PM

Screen Shot 2022-07-20 at 4 32 14 PM

Screen Shot 2022-07-20 at 4 24 05 PM

Multi Selection

Screen Shot 2022-07-20 at 4 27 17 PM

Screen Shot 2022-07-20 at 4 54 45 PM

Screen Shot 2022-07-20 at 4 51 26 PM

Screen Shot 2022-07-20 at 4 25 57 PM

Screen Shot 2022-07-20 at 4 26 19 PM

Demo with Search Preview:

Single Selection
https://user-images.githubusercontent.com/14063502/180098759-f824581f-d2b7-474c-898e-704e69bb68d8.mp4

Multi Selection
https://user-images.githubusercontent.com/14063502/179274276-a44ae7ac-091a-49e2-8025-34c49d540e92.mp4

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by joshchong** [comment]
@oliv-yu @lipusz given that the category IDs are no longer valid inputs for these fields, do you think we should rename the field from `Asset Category IDs` to `Asset Categories`?

**Comment by lipusz** [comment]
I'm actually surprised, as it was never planned to stop accepting IDs. The selector is just meant to help the user to find the Category by its name, rather spending time to dig into the AC admin to find the ID.

The elements must still need to store and use IDs.

**Comment by lipusz** [comment]
IDs and category names are not interchangeable in a search query.

**Comment by lipusz** [comment]
I've double checked and it's also indicated this way in the AC list.

**Comment by oliv-yu** [comment]
@lipusz We can update it to accept manually input IDs, but I think an issue we ran into was not being able to load every single category all at once (since categories get loaded with various APIs after knowing the individual parent category/vocabulary ID), making it difficult to actually match manually inputted IDs to a valid category. That's why we went with a dropdown selection in the input text (which is what the web content form does for categorization), but unfortunately the search query it uses is limited to names and not IDs.

Then again, it seems like that only matters more when defining the tree. A user can type in category with ID '121212' with no associated name and the UI would not think it's part of the tree until you expand the tree til you see a category ID '121212'. So as long as the category tree modal design doesn't keep track of selection count and checking for what is a real category, we can definitely do something more flexible where you just type in the ID? I guess in that case you can type in anything really, terms or IDs, and it would show up in the JSON as that. Would that be okay? Would we still want validated categories listed under its name, or would we want them all listed as IDs for consistency?

**Comment by lipusz** [comment]
Hi @oliv-yu 

Let's continue discussing this here: https://liferay.slack.com/archives/C0154CEGR3Q/p1659355414860279

**Comment by oliv-yu** [comment]
Updated screenshots to allow manually input values / lookup by category ID:

(Single)
Screen Shot 2022-08-04 at 5 04 28 PM
Screen Shot 2022-08-04 at 5 04 54 PM
Screen Shot 2022-08-04 at 5 05 55 PM
Screen Shot 2022-08-04 at 5 06 11 PM

(Multi)
Screen Shot 2022-08-04 at 5 06 58 PM
Screen Shot 2022-08-04 at 5 07 11 PM

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
Oh sorry, there is a small bug I asked @thektan if he could take a look at (regarding the input on the multiselect option), so this isn't ready to push up @joshchong

**Comment by joshchong** [comment]
@oliv-yu oh okay got it. i'll abort the tests.

**Review by thektan — APPROVED** [review]

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
Hey @oliv-yu @thektan I'm seeing the following issue when using a virtual instance. See steps below:

1. Create a virtual instance and sign in
2. Create a blueprint
3. Add any element to the query builder that has the `Asset Category Name (ID)` field

:warning: Result: **`Error:An unexpected error occurred`** alert pops up and the following is thrown in the browser console:
```GET http://192.168.42.138:8080/o/headless-admin-taxonomy/v1.0/sites/46708/taxonomy-vocabularies 500```

The following is also thrown in the server console:
```
2022-08-10 19:39:10.646 WARN  [http-nio-8080-exec-7][BaseExceptionMapper:70] Problem {detail=null, status=Internal Server Error, title=null, type=null}
java.lang.NullPointerException: null
	at com.liferay.headless.admin.taxonomy.internal.resource.v1_0.TaxonomyVocabularyResourceImpl._getModelResource(TaxonomyVocabularyResourceImpl.java:579) ~[?:?]
```

**Comment by thektan** [comment]
@joshchong

@oliv-yu is fixing this so that the alert won't appear due to a failed request when adding the element.

I've reported the root cause of the error and will be sending the Frontend Infra Team a PR soon. https://issues.liferay.com/browse/LPS-160310

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/121594

**Pull request closed without merging**
