### PR TITLE
LPS-162049 LPS-164425 portal-search-web: Type - Add tests

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-164416
https://issues.liferay.com/browse/LPS-164425
https://issues.liferay.com/browse/LPS-168938

Not possible to test types with the same name because [AssetEntriesSearchFacetDisplayContextBuilder](https://github.com/liferay/liferay-portal/blob/20a47f5d8c59595151888943736367d05dc30449/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/facet/display/context/builder/AssetEntriesSearchFacetDisplayContextBuilder.java#L143) uses:

`facetCollector.getTermCollector(
				assetType);`
				
instead of

`facetCollector.getTermCollectors();`

And because AssetEntriesSearchFacetDisplayContextBuilder uses the assetTypeName to define the bucketText

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1367401_2614

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
Looks great!

**Pull request closed without merging**
