### PR TITLE
LPS-198941 search-experiences: Update validation when creating SXPElement

### PR DESCRIPTION
**Pull request by gustavolimav**
For the task [LPS-198941](https://liferay.atlassian.net/browse/LPS-198941), the key information is detailed in the commit message.

Move this logic to Resource is necessary because of OOTB Elements, which are read-only and thus not subject to editing. This approach is essential to address a specific scenario: if there's a change in the defaultLocale and concurrently the originalDefaultLocale from the Element is removed, it could result in significant issues, such as be not possible to copy an Element.

https://liferay.atlassian.net/browse/LPS-202540

sending tests together

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
@joshuacords if the code looks good can you run ci for me?

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
