### PR TITLE
LPS-187225 search-experiences-web: Translate blueprint title inside options widget

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-187225 - On Blueprint Options widget, title is not translated on initial load

Just need to add a translate step when passing in the `initialSXPBlueprintTitle` 👍

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
LGTM! 👍

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:stable

**Comment by joshchong** [comment]
@oliv-yu just FYI, the stable suite is already run when relevant is run so no need to call stable separately :slightly_smiling_face:

**Pull request closed without merging**
