### PR TITLE
[TS] LPS-123103 - The Sort Widget's Top Option Isn't Applied on Page Load

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-123103

Hi @samanzanedo!

I made 2 additional changes:

1. Moved the additional "Relevance" default option as the first option since it's more standard for default options to be the first option in the list, allowing the additional options to list below the field.
2. If a blank field already exists, that one is selected instead of creating another "Relevance" option. Since the default sort widget would already have "Relevance" as an option, it seemed strange having it listed twice.
Screen Shot 2020-12-01 at 3 20 27 PM

Let me know if these changes are still acceptable.

Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:test:search

**Comment by samanzanedo** [comment]
Hi @thektan,

Your additional changes are very good to me.

Best regards.

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
