### PR TITLE
LPD-15752 Upgrade process is not being executed due to schema version value null: Result Ranking entries are not shown on the UI

### PR DESCRIPTION
**Pull request by AlmirFe**
- https://liferay.atlassian.net/browse/LPD-15752

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by lipusz** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:report:2533384968

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
A lot of failures in upgrade suit with the same message
```
LIFERAY_ERROR: Failed upgrade process for module com.liferay.portal.search.tuning.rankings.web LIFERAY_ERROR: Pending Upgrade System Checker check result: Required upgrades in modules are pending.
```

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@AlmirFe it seems upgrade test suit is not finishing, can you open a new PR and run this suit again?

**Comment by AlmirFe** [comment]
@gustavolimav I sent a new PR #1256

**Pull request closed without merging**
