### PR TITLE
LPD-5523 javadocs

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-5523
https://liferay.atlassian.net/browse/LPD-5525
https://liferay.atlassian.net/browse/LPD-5526

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
small updates here https://github.com/BryanEngler/liferay-portal/pull/772

**Pull request closed without merging**
