### PR TITLE
LPS-153543 & LPS-152183

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-153543
https://issues.liferay.com/browse/LPS-152183

I did a overdue refactoring to clarify how journal articles are being set up.

**Authors:** @gustavolimav @joshuacords 

**Reviewers:** @joshuacords 

@gustavolimav, could you read through my changes as a peer review?

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@joshuacords for sure I could take a look at that failures

**Comment by gustavolimav** [comment]
ci:forward

**Comment by joshuacords** [comment]
Ran tests successfully on my machine, looking to forward without CI based on B Chan: https://github.com/brianchandotcom/liferay-portal/pull/120326#issuecomment-1183532212

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
