### PR TITLE
[TS] LPS-134832 SearchPhaseExecutionException when using special char in keyword for AP filter

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-134832

/cc @HuongNguyen-gs @huynguyen-codeengine 

Based on research from the TSE, there doesn't seem to be a situation where we would want to call `queryStringQueryBuilder.escape` with a false value, so in my head, it would make more sense to simplify always call the method with true and not update the API. However, in case there is such a situation, I've forwarded the pull as-is to let the search team evaluate which solution makes sense.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
In my opinion, the Echo Team should move the `AssetSearcher` into an asset module so they could leverage the StringQuery from the portal-search-api that already supports `escape`, instead of modifying a legacy API in kernel.

A minor bump in that kernel search package will probably force us release a new version of non-bundled search engine connectors in all versions. (Don't forget that on 7.3.x you'll also need to handle it in the Solr8 module, and the same on es6, es7, solr7 and solr8 modules in 7.2.x and 7.1.x).

>Based on research from the TSE, there doesn't seem to be a situation where we would want to call queryStringQueryBuilder.escape with a false value,

Yeah, this would be better, though from API/behavior perspective it would not be dev friendly.

/cc @arboliveira or @BryanEngler whoever will have a time to look into this earlier.

**Comment by BryanEngler** [comment]
>Based on research from the TSE, there doesn't seem to be a situation where we would want to call queryStringQueryBuilder.escape with a false value

what about a filter where you wanted to use a wildcard? currently you would be able to do that. after this fix, pretty sure you wont... 
usually in a case like this i would say its super helpful to add some tests because it would be pretty easy to cause regressions. (unless we actually want to prevent wildcard search etc and just take everything literally, but thats a PM decision because behavior will change...)

just some thoughts... using a Query String Query allows for all kinds of "lucene syntax" operators/expressions/etc https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters
maybe a different type of query (ie Match) would work better for the AP? (see the "warning", quoted below https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-dsl-query-string-query) again, adding tests and getting PM involved would help make a decision like this. 

>Because it returns an error for any invalid syntax, we don’t recommend using the query_string query for search boxes.

>If you don’t need to support a query syntax, consider using the match query. If you need the features of a query syntax, use the simple_query_string query, which is less strict.

or maybe just adding documentation/logging/error reporting that these keywords follow the string query syntax and that special characters would need escaping... gives more power to the user and we dont have to figure out every single edge case in regards to special chars etc... this way the steps to reproduce just change the keywords from 2021/4 to 2021\/4 and the "bug" is gone

finally, like tibor said, we try to avoid portal-kernel bumps, so any solution that can avoid that would be great.

ill close this pr while you guys look into some of these other possible solutions ive mentioned

**Pull request closed without merging**
