### PR TITLE
[TS] LPS-140070 Listed elements should be in div tag instead of heading tag in search result widget

### PR DESCRIPTION
**Pull request by orsolyaDekany**
https://issues.liferay.com/browse/LPS-140070

Hi @thektan @lipusz,
PR related to https://github.com/liferay/liferay-portal-ee/pull/25588

I changed heading tags to div. It was necessary to add "h6" as a class to the div, so the style remained unchanged.

tag and details **before** (font-size is 0.8125rem)
before tag
**after**
after tag

Besides these changes, I can see one more file using heading tags in a search container, but could not find where they are on the Portal: https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/main_search_result_form.jspf#L42-L78
I could check them, too, and make a change if needed. Please let me know.

cc.  @georgel-pop-lr 

Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
Thanks @orsolyaDekany! The changes look good. Thanks for the screenshots too!

Can you make the same changes in `main_search_result_form.jspf` too? You'll have to add the older "Search" widget to a page. It can be found under the "tools" category. 

Screen Shot 2021-10-04 at 9 33 19 AM

**Comment by orsolyaDekany** [comment]
Hi @thektan ,
I upsted the commit with the rest of the changes.
**main_search_result_form.jspf** --> added div and span, and the style remained unchanged (font-size is 0.875rem)
**portlet_display_template_list.ftl** --> added div with h6 class, and the style remained unchanged (font-size is 0.8125rem)

Please review. Thank you.

cc. @georgel-pop-lr

**Comment by orsolyaDekany** [comment]
c:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
Hi @thektan , can you please review this PR? Thank you.

**Comment by lipusz** [comment]
Hi Orsi,

We are quite busy with the release so this may take some time.

**Comment by brookedalton** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Tested in https://github.com/xbrianlee/liferay-portal/pull/645 and forwarded to https://github.com/brianchandotcom/liferay-portal/pull/108349.

**Pull request closed without merging**
