### PR TITLE
LPD-30441 Blueprint upgrade process is not completed if a portlet retains an Id of a deleted blueprint

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-30441

### Tests for this use case will be added through [LPD-27032](https://liferay.atlassian.net/browse/LPD-27032)

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by AlmirFe** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
LGTM! 🚀

**Comment by AlmirFe** [comment]
ci:forward:force

**Pull request closed without merging**
