### PR TITLE
LPS-186789 Search Tuning reindex errors

### PR DESCRIPTION
**Pull request by BryanEngler**
https://issues.liferay.com/browse/LPS-186789

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/135959

**Pull request closed without merging**
