### PR TITLE
LPD-26165 Add tests to ensure that search widgets have ExportImportPortletPreferencesProcessor classes

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-26165

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:report:26680600

**Comment by gustavolimav** [comment]
All tests passed.

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by AlmirFe — APPROVED** [review]
@gustavolimav the tests themselves look good. I just have some proposals for improvements to the code. Therefore I submitted a new PR with some changes in https://github.com/liferay-search/liferay-portal/pull/1387 as we had discussed.

**Comment by AlmirFe** [comment]
I'm going to close this PR since I've opened another. https://github.com/liferay-search/liferay-portal/pull/1387

**Pull request closed without merging**
