### PR TITLE
[TS] LPS-148164 - Fix validation errors of the code in searchbarportlet

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Please check https://issues.liferay.com/browse/LPS-148164 for steps and details

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:search

**Comment by georgel-pop-lr** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hi @georgel-pop-lr 

This appears to be breaking the Modified Facet. Can you look into it? Thanks!

**Comment by georgel-pop-lr** [comment]
> 1. [earchWithModifiedFacet](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/36028//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchWithModifiedFacet_) -

Hi @lipusz,

I see is expecting name attribute on the li element and I just removed, as name it should be used only for inputs.

`com.liferay.poshi.runner.PoshiRunner > test[LocalFile.Search#SearchWithModifiedFacet] STANDARD_ERROR
     [exec]     com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//li[contains(@name,'ModifiedFacet')]//span[contains(.,'Past 23 Hours')]"
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.getWebElement(BaseWebDriverImpl.java:4259)
     [exec]     	at com.liferay.poshi.runner.selenium.ChromeWebDriverImpl.getWebElement(ChromeWebDriverImpl.java:131)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.getText(BaseWebDriverImpl.java:1400)
     [exec]     	at com.liferay.poshi.runner.selenium.ChromeWebDriverImpl.getText(ChromeWebDriverImpl.java:100)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.getText(BaseWebDriverImpl.java:1392)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$17.evaluate(BaseWebDriverImpl.java:4001)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$17.assertTrue(BaseWebDriverImpl.java:3989)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4521)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4500)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForPartialTextCaseInsensitive(BaseWebDriverImpl.java:3334)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1179)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)`
     
    How this name is being used?
    
    Regards.

**Comment by oliv-yu** [comment]
@georgel-pop-lr It looks like `name` was important for the QA test to locate a certain modified facet selection. 

@joshchong Since adding `name` to an `li` element is triggering some validation errors on the HTML checker, can the locator maybe be updated to look for `class` instead? Or let us know what works best for ya.

**Comment by georgel-pop-lr** [comment]
ci:test:search

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr It looks like `name` was important for the QA test to locate a certain modified facet selection.
> 
> @joshchong Since adding `name` to an `li` element is triggering some validation errors on the HTML checker, can the locator maybe be updated to look for `class` instead? Or let us know what works best for ya.

Hi @oliv-yu,

Thanks for reviewing.

I updated with class instead: https://github.com/liferay-search/liferay-portal/pull/307/commits/5adcc91764f7d6990792a157ce17246dc1267270 

I rerun tests. 

Regards.

**Review by oliv-yu — APPROVED** [review]
The changes look all right, it looks like search-web still looks and works as expected. Talked with @thektan about adding in the action as `#` but seeing as it doesn't affect functionality and helps with the HTML validation errors, that seems like the most straightforward solution.

I'll check with QA about the latest test failure, but otherwise, it seems fine to approve!

**Comment by brookedalton** [comment]
Test results look good to me, the failures are unrelated.

**Comment by brookedalton** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
Continued in https://github.com/liferay-search/liferay-portal/pull/309 with different xpath test fix to be more specific.

**Pull request closed without merging**
