### PR TITLE
LPS-192640 LPS-193200 Add editable ERC field to the SXPElement and SXPBlueprint editing views

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://liferay.atlassian.net/browse/LPS-192640
**Sbutask:** https://liferay.atlassian.net/browse/LPS-193200

Follow-up to https://github.com/brianchandotcom/liferay-portal/pull/141030#issuecomment-1728563456

- Moved `externalReferenceCode` to first param

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:sf

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/141275

**Pull request closed without merging**
