### PR TITLE
LPS-149306: Configurable Similar Results Link Behavior

### PR DESCRIPTION
**Pull request by peerkar**

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:stable

**Comment by BryanEngler** [comment]
looks good to me. none of the unit tests ran in the search suite so im gonna run it again... ill keep an eye on the results and then forward it once its done

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
