### PR TITLE
LPS-196807 Older versions of Web Content are indexed with the newest version's values

### PR DESCRIPTION
**Pull request by lfbesada**
Previous PR: https://github.com/liferay-search/liferay-portal/pull/1125

This PR fixes two bugs:
https://liferay.atlassian.net/browse/LPS-196807
https://liferay.atlassian.net/browse/LPS-198486
On already existing content, a reindex is needed to fix these issues.

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Hi @lfbesada,

> I have verified that without the changes in this PR and following the steps of Poshi's test, if I translate the title with the same value in JA or ZH, the content is also found when we search for the term "WC1". Is that expected?

> I don't understand why it is searched in those localized fields when it is searched with a different locale and why it is found in those localized fields but not in the others.

I think that does sound like a problem, if you're not searching with the JA or ZH locale, we wouldn't want those localized fields to be searched against.

Could you provide reproduction steps for this scenario so we could look into what's causing this behavior?

**Comment by xbrianlee** [comment]
@joshuacords Here are the steps:
1. Create a Web Content Article - WC
2. Enable "Display Results in Document Form" for Search Results portlet
3. Search for "WC1"
4. WC is returned in the search results❌ 

I've confirmed that this issue does not happen upstream ([cc05f4db10c47570735bca628f992ddf6058433b](https://github.com/liferay/liferay-portal/commit/cc05f4db10c47570735bca628f992ddf6058433b)).

**Comment by lfbesada** [comment]
Hi @joshuacords @xbrianlee 

Thank you very much for looking at this :raised_hands: 

> I think that does sound like a problem, if you're not searching with the JA or ZH locale, we wouldn't want those localized fields to be searched against.
> 
> Could you provide reproduction steps for this scenario so we could look into what's causing this behavior?

Steps to reproduce that behavior at master [4886b65c92118d4cdf11bc24969da2c1804a68d0](https://github.com/liferay/liferay-portal/commit/4886b65c92118d4cdf11bc24969da2c1804a68d0)

1. Create a Web Content Article - WC
2. Enable "Display Results in Document Form" for Search Results portlet
3. Search for "WC1"
4. **Checkpoint**: WC isn't returned in the search results
5. Edit the created web content 
6. Use the title language selector to switch to Japanese
7. Add "Web Content Article - WC" as a title in Japanese and publish the web content
8. Search "WC1" again

**Expected result**: WC isn't returned in the search results
**Current result**: WC is returned in the search results and in the details you can see that it has been found for the term "WC" in the fields "title_ja_JP" and "snippet_title_ja_JP", see highlighted in the screenshot

Screenshot from 2023-11-03 07-39-41

**The same behavior can be seen using Chinese as the language instead of Japanese.**

Thanks in advance!

**Comment by lipusz** [comment]
Isn't the behavior since https://liferay.atlassian.net/browse/LPSA-67307?

**Comment by joshuacords** [comment]
Hi @lfbesada,

I've been meaning to look into this, I've just had other customer issues that I've been juggling as well. I'll try to do something today but we'll just have to see.

**Comment by lfbesada** [comment]
Hi @joshuacords 

Thanks for the update!

I've updated this PR to decouple the solution from the escalated ticket solution so I can ship it separately, please see: https://github.com/liferay-echo/liferay-portal/pull/14212

In this PR I have only modified the[ last commit](https://github.com/liferay-search/liferay-portal/pull/1134/commits/e7440f19b9309bdf6c56f0a0fd9b0b8033245a11) to remove the changes in the urlTitle field and [the Auto commit](https://github.com/liferay-search/liferay-portal/pull/1134/commits/5d193a212f2d113e2a74c37ef96d20679e7f8cb9) that I have regenerated.

So I am updating this PR description to reflect it.

Thanks!

**Comment by lfbesada** [comment]
Hi @joshuacords 
I have forced push only to resolve the conflicts.
Would it be possible to receive an update about this PR?
Thanks in advance!
Regards

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Hi @lfbesada, sorry for the delay! Josh is out sick. One of our other engineers will rotate onto this ticket when they have availability.

**Comment by joshuacords** [comment]
Hi @lfbesada, 

I'm sorry for all the back and forth on this. I'm just returning to work today but I'm in cat ch-up mode with customer tickets. Please check back with me in a couple days.

**Comment by lfbesada** [comment]
Hi @joshuacords 

I hope you're fine :smiling_face_with_three_hearts: 

I posted [this comment](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1794794544) last week with a proposal to unblock this pull request, have you had a chance to look at it?

Thanks in advance!

Regards

**Comment by joshuacords** [comment]
Hello @lfbesada,

I've just spent some time on this, thank you for your patience.

I agree with [Tibor](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1792198890) that the behavior you're [seeing here](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1790886351) is correct. 

Unfortunately, your [comment here](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1794794544) is a little confusing since the rebase broke the links. But it doesn't seem necessary to change direction to me. 

What I'm going to do next is look into the test failures to see what behavior changes they caught and if they should change or the code.

**Comment by lfbesada** [comment]
Hi @joshuacords 

Thanks for looking at this. :heart: 

I am sorry, I didn't realize that when I updated the PR the links would not work.

What I was trying to explain in this comment is that if we are deliberately adding the other localizations of the fields Title, Content, and Description fields than the locale used in the search, as @lipusz mentions [here](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1792198890), then we shouldn't populate those translations when indexing the web content's version.

I understood you were suggesting this [here](https://github.com/liferay-search/liferay-portal/pull/1114#issuecomment-1778088095), so I was populating all those field translations, and that is the cause of all the failures here.

To solve this I have changed my last commit [preventing the involuntary population](https://github.com/liferay-search/liferay-portal/pull/1134/commits/201c705fcd308c5196a1bff9ee82294bd5260126) that I was doing before when the web content's version was not the latest. That was what I proposed in my previous comment.

I am going to re-launch CI, I think that now the tests should not fail since those translations are no longer added.

Thank you very much!

Regards

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
The integration test I added failed [here](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833580/testReport/com.liferay.journal.search.test/JournalArticleAssetEntryTest), I'm working on it.

**Comment by lfbesada** [comment]
I have added a commit to solving the integration test failures. So I am re-launching CI

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Looks like a related PMD violation failure under relevant: 
> PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/journal/journal-test/src/testIntegration/java/com/liferay/journal/search/test/JournalArticleAssetEntryTest.java:221 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)

**Comment by joshuacords** [comment]
Hello @lfbesada,

I'm talking with Tibor about what you [wrote here](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1815909028). I'm second guessing populating all the locales even though other assets such as Pages, Documents, and Blogs do this.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
Hi @joshuacords ,

I forced push to fix the integration tests source formatting to solve [this](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1817194479).

Thanks for the heads up!

Regards

**Comment by joshuacords** [comment]
I'm now thinking that we don't want to populate all the locales that aren't specifically defined, I'm waiting for another senior member to agree with this direction as it's different from what other assets are doing.

**Comment by lfbesada** [comment]
> I'm now thinking that we don't want to populate all the locales that aren't specifically defined, I'm waiting for another senior member to agree with this direction as it's different from what other assets are doing.

Hi @joshuacords 

IMHO we should not add translations to the index of these fields while adding to the search those localized fields with other languages. I think we can do one thing or the other, but we should never do both at the same time.

This PR no longer completes any localization, it is limited to fixing the two linked bugs without adding anything else. The translations that were added before were removed [here](https://github.com/liferay-search/liferay-portal/pull/1134#issuecomment-1815909028).

Thank you very much!

Regards

**Comment by lfbesada** [comment]
Hi @joshuacords

I am closing this pull because I have found some errors in the dashboard UI and web content in this one that made me add three more commits that must be reviewed by Echo. Please see: https://github.com/liferay-echo/liferay-portal/pull/14433

I think that the commit of this PR that affects your components may be already been reviewed here, but please, do not hesitate to comment on what you consider appropriate in the Echo repo PR.

Thank you!

Regards

**Comment by joshuacords** [comment]
Sorry for the delays, everything has been approved from the search side.

**Comment by lipusz** [comment]
Happy to help. :-)

**Pull request closed without merging**
