### PR TITLE
LPD-22974 LPD-265507 Updates to saving ClauseContributorsIncludes/Excludes on editor

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-22974 - Clause Contributors configurations are stored in Blueprints in a less verbose way and with improved consistency when it comes to the handle of new contributors introduced to the system
https://liferay.atlassian.net/browse/LPD-26507 (subtask) - [FE] Enable All saves ClauseContributorsIncludes dynamically

### Updates to Blueprint Editor and Saving Query Contributor Section

In order to make the blueprint JSON less wordy, the options for query contributors would now be saved as:
Option | Stored as
-- | --
Enable All | clauseContributorsIncludes=["*"], clauseContributorsExcludes=[]
Disable All | clauseContributorsIncludes=[], clauseContributorsExcludes=["*"]
Customize | clauseContributorsIncludes=["class3","class5",...], clauseContributorsExcludes=[]

- If all contributors are selected within Customize, it will remain as customized, not 'enable all'. To avoid confusion, an upgrade will be performed for existing blueprints to turn its "selected all" contributors list into the new notation with the wildcard.
- New blueprints would be saved with "Enable All" as the default
- "Disable All" option added
- Tooltip that opens the sidebar was included for Query Contributors (similar to how it works for Indexer Clauses section)
- Language keys updates

Screenshot 2024-05-30 at 11 32 57 AM
Screenshot 2024-05-30 at 11 33 19 AM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Changes make the logic a lot cleaner 💯 ✨ 

Outside of this PR, I'd suggest creating another subtask to add some playwright tests. 

Some tests I could see:
- Clicking on the help icon displays the help text
- "Customize" "Disable All" and "Enable All" are listed as options
- Options are persisted (clicking "Disable All" -> Save -> Revisit page to check if still selected)

I'd also suggest creating an [ApiHelper](https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/helpers/ApiHelpers.ts) to add a blueprint. You can reference how [Data Set Manager adds their own ApiHelper](https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/tests/frontend-data-set-views-web/helpers/DataSetManagerApiHelpers.ts), but I would strongly encourage to start your test from scratch and add in parts that make sense rather than copy-pasting files which could end up in over-complicated file structure and unnecessary parameters. This can also help understand all the parts of a test more easily as well to see what parts are actually needed.

**Comment by oliv-yu** [comment]
Thank you, @thektan! I should look into APIHelper sometime, anything to make blueprint tests go more smoothly heheh

Closing this PR as it is included in https://github.com/liferay-search/liferay-portal/pull/1371 👍

**Pull request closed without merging**
