### PR TITLE
LPS-174196 Add tests to Scrolls and Search Afteer

### PR DESCRIPTION
**Pull request by gustavolimav**
On hold, while Scrolls API is not merged.

**Scrolls:**

https://issues.liferay.com/browse/LPS-179382

What the test does:

1. Index 3 documents
2. Create SearchSearchRequest and set fields (need to set scroll to keep alive minutes to use scroll)
3. Execute the first search without scroll
4. Execute 3 more searches using scroll
5. The last search will return anything proving that the pagination is working

**SearchAfter:**

https://issues.liferay.com/browse/LPS-174551

What the test does:

1. Index 3 documents
2. Create SearchSearchRequest and set fields (need to set point in time and Sorts to use Search After)
3. Execute the first search without search after
4. Execute 3 more searches using search after
5. The last search will return anything, proving that the pagination is working.
6. (1 document per page until the last one without anything)

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:forward:force

**Pull request closed without merging**
