### PR TITLE
LPS-201176 Add more validation for CCR configs

### PR DESCRIPTION
**Pull request by BryanEngler**
https://liferay.atlassian.net/browse/LPS-201176

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
Hey @BryanEngler, the test results look good!

**Comment by BryanEngler** [comment]
ci:forward:force

**Pull request closed without merging**
