### PR TITLE
LPS-201176 Add validation for CCR config input

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Testing in https://github.com/xbrianlee/liferay-portal/pull/1388. The past 3 runs have had CI issues.

**Comment by BryanEngler** [comment]
ci:forward:force

**Pull request closed without merging**
