### PR TITLE
[TS] LPS-164442 track_total_hits

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-164442

May have no functional impact on 7.4.x-7.2.x, but is necessary for 7.1.x and should stay standardized.

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Josh,

Can you fix it on 7.2.x first? It's only in the search calls there too.

https://github.com/liferay/liferay-portal-ee/blob/7.2.x/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/ElasticsearchIndexSearcher.java#L329-L330

Thanks!

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
