### PR TITLE
LPD-37535 Ids of all inactive groups are added to search query in manual collection searches

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-37535

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @AlmirFe,

I don't understand how this change is related to what's described on the bug ticket. I'll be awaiting more clarification before approving this.

**Comment by AlmirFe** [comment]
Hey @joshuacords, I've sent an explanation on the ticket https://liferay.atlassian.net/browse/LPD-37535?focusedCommentId=2752555

**Review by joshuacords — APPROVED** [review]
Hi @AlmirFe,

This code looks good. We'll just be expecting a test to be created for this later down the line.

**Pull request closed without merging**
