### PR TITLE
LPS-174746: Create text embedding only for the last approved version of JournalArticle

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-174746

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:forward

**Comment by lipusz** [comment]
Hi @peerkar 

Sorry if I did not express myself clear enough at the beginning: the intention was not to 'blame' or anything like that: I was trying to act like a peer-reviewer and wanted to _challenge_ the code, to see if it is following the same logic as much as possible that the Echo Team does, because I noticed we were introducing a logic code to our contributor that is otherwise encapsulated inside that private util for JA. And the goal of this challenge was to avoid any diverge between our and their contributors.

It's absolutely fine if you say we are good here.

**Comment by lipusz** [comment]
Ah, commented to the wrong PR...

**Pull request closed without merging**
