### PR TITLE
LPS-187194:  Sync SearchHits with the permission filtered kernel search Hits

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-187194

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
will forward from https://github.com/BryanEngler/liferay-portal/pull/732, thanks!

**Pull request closed without merging**
