### PR TITLE
LPD-26165 Add tests to ensure that search widgets have ExportImportPortletPreferencesProcessor classes

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-26165

### Changes in this PR have been reviewed in https://github.com/liferay-search/liferay-portal/pull/1386

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:report: 27760815

**Comment by gustavolimav** [comment]
ci:report:27760815

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:report:28038233

**Comment by gustavolimav** [comment]
ci:report:28038233

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by AlmirFe** [comment]
ci:forward:force

**Comment by AlmirFe** [comment]
PR sent manually https://github.com/brianchandotcom/liferay-portal/pull/151877

**Pull request closed without merging**
