### PR TITLE
[TS] LPS-176493 Facets show results with Empty Searches with a Blueprint on Page

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-176493

**Author:** @joshuacords 

Fixed is based on [these observations](https://liferay.slack.com/archives/C0154CEGR3Q/p1675761250861929).

In summary, FacetedSearcherImpl skips searching when keywords are empty and the Allow Empty Search flag is set. This is correct behavior, as we are just visiting a search page and not actually searching (to my knowledge a search page is the only place where faceted search happens). The BaseIndexer does not make this check, but this is also correct behavior because many admin portlets rely on empty searches to display their assets. The problem is when a Blueprint narrows the scope of assets to a single asset type, then the BaseIndexer is used instead of FacetedSearchImpl and a empty search happens, returning results that the Facets display.

This solution stops the search from the SearchDisplayContext used on search pages before it enters the full search framework.

Because SearchResponseImpl and FacetContextImpl are internal to portal-search, I had to re-implement them here for the purposes of returning empty results.

### CODE REVIEW

**Review by gustavolimav — APPROVED** [review]
LGTM!:rocket:

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
I've been asked to look into some alternatives - don't forward.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Review by gustavolimav — APPROVED** [review]

**Comment by gustavolimav** [comment]
The code looks good and test failures are not related, I will forward it.

**Comment by BryanEngler** [comment]
@joshuacords @gustavolimav 

i took one more quick look at this and came up with some alternate options for a solution...
https://github.com/BryanEngler/liferay-portal/tree/2023_03_03_LPS_176493_emtpy_search_blueprint

i only spent like 30 min on so this maybe you guys can take a closer look, fine tune it according to this "strategy" and see if it passes CI etc. it might not work out, but its an option to look in to

**Comment by joshuacords** [comment]
Hi @BryanEngler,
I don't think we can the check where you shared because most admin portlets use empty searches to populate their assets.

**Comment by BryanEngler** [comment]
@joshuacords not sure if i understand. i dont think empty searches would be changed with my fix. if the ATTRIBUTE_KEY_EMPTY_SEARCH value is true, the search will still execute. the problem is when empty search is false, we are returning results when we shouldnt. if admin portlets are using an empty search to populate results (which i actually couldn't find one that was, maybe you have an example?), they should set that attribute to true

**Comment by joshuacords** [comment]
> https://issues.liferay.com/browse/LPS-176493
> 
> **Author:** @joshuacords

I found @BryanEngler was correct (thanks for stopping the PR), changes to the SearchRequestImpl don't affect admin portlets. Made the recommended change and testing now.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Found the test failures were because we should be discounting the Federated searches as well, Federated searches will also call doSearch and will be checked then.

**Pull request closed without merging**
