### PR TITLE
LPD-27031 LPD-27032 Convert SearchContinuousUpgrade#ViewSXPBlueprintsAndElements on Integration Tests

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-27032

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
@AlmirFe do you get an java.lang.ArrayIndexOutOfBoundsException when running the test?

**Comment by BryanEngler** [comment]
forwarding from here https://github.com/BryanEngler/liferay-portal/pull/773

**Pull request closed without merging**
