### PR TITLE
[TS] LPS-171713 Configuration is sent twice when Search preferences are saved for the second time

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

The following solution fixes the bug reported in [LPS-171713](https://issues.liferay.com/browse/LPS-171713), which is only reproducible when SPA is enabled.

The root cause is that the event registered is not properly unregistered when the portlet is destroyed.

The approach followed in the proposed solution is to use the attribute onSubmit of the taglib liferay-frontend:edit-form.

Could you please review it?

Please, also let me know if further clarifications are needed.

Thanks in advance!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:search

**Comment by dacousalr** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Thanks for this fix! Looks good!

**Comment by thektan** [comment]
Running tests again and I'll forward if they pass

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:forward

**Comment by joshchong** [comment]
Failures are unrelated. Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/128383

**Pull request closed without merging**
