### PR TITLE
LPS-116907 - Search bar with federated search key returns no results

### PR DESCRIPTION
**Pull request by arboliveira**
(was: https://github.com/liferay-search/liferay-portal/pull/4)

http://issues.liferay.com/browse/LPS-116907

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:test:relevant

**Comment by arboliveira** [comment]
@thektan https://github.com/arboliveira/liferay-portal/compare/LPS-116907-federated-search-key---liferay-search_pull_4..LPS-116907-federated-search-key

**Comment by thektan** [comment]
Resent to fix freemarker template breaking on a null string: https://github.com/liferay-search/liferay-portal/pull/6

**Pull request closed without merging**
