### PR TITLE
LPD-24555 Replace deprecated CreateIndexRequest

### PR DESCRIPTION
**Pull request by gustavolimav**
use import org.elasticsearch.client.indices.CreateIndexRequest; instead of import org.elasticsearch.action.admin.indices.create.CreateIndexRequest

reason:

[types removal] Using include_type_name in get mapping requests is deprecated. The parameter will be removed in the next major version of elasticsearch

https://liferay.atlassian.net/browse/LPD-24555

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html

Resend: https://github.com/liferay-search/liferay-portal/pull/1341

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:report:2570142073

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:2570260183

**Comment by gustavolimav** [comment]
ci:report:2570260183

**Comment by joshuacords** [comment]
Hi @gustavolimav,

This looks good to me for forwarding.

I see though we still have a number of references left in the portal to "_doc" and the doc type. Some of this is the now deprecated methods, some are other places:
_doc

Do we still need (most of) these "_doc" usages? If not, could you create a Task ticket to remove the deprecated methods and the unnecessary "_doc" usages in the portal to be worked on by the team another time?

Thanks

**Review by joshuacords — APPROVED** [review]

**Comment by gustavolimav** [comment]
Thx @joshuacords, I saw most of those usages but couldn't remove because we need first deprecate as Petteri mentioned here https://github.com/liferay-search/liferay-portal/pull/1341#issuecomment-2117521525. I will create the ticket. Thanks ❤️

**Comment by gustavolimav** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/150493

**Comment by gustavolimav** [comment]
@joshuacords https://liferay.atlassian.net/browse/LPD-26361

**Pull request closed without merging**
