### PR TITLE
[TS] LPS-123817 Allow proxy configuration.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey @marianoalvarosaiz! I made yet some other changes on top of yours. I also changed the default value of the proxy port to zero and took out your last commit addressing that. I am not totally sure it was the right approach, and we should have probably discussed it more, but so far I guess it should solve the customer's issue and get merged. I also added a test called `ProxyConfigTest` so we can now have explicit tests for various corner cases. If you find another necessary change on building proxy configs, we can add tests there. The final result is in https://github.com/liferay-search/liferay-portal/pull/67/ waiting for the results of `ci:forward`.

**Comment by marianoalvarosaiz** [comment]
Hi @brandizzi, thanks a lot. Sounds good. Could you, please, provide the link to the final result. Guess the one you added points to the current one.
Kind regards.

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/97410

**Pull request closed without merging**
