### PR TITLE
LPD-35048: Fix stable

### PR DESCRIPTION
**Pull request by gustavolimav**
Ticket: https://liferay.atlassian.net/browse/LPD-35048

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:forward

**Comment by AlmirFe** [comment]
ci:forward

**Comment by AlmirFe** [comment]
commit merged https://github.com/brianchandotcom/liferay-portal/pull/154322

**Pull request closed without merging**
