### PR TITLE
LPS-182927 Fix bugs from suggestions

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-182927
https://liferay.atlassian.net/browse/LPS-194298

Hi @peerkar, I did some changes in suggestions and I want to know your opinion about it, my changes fix the bug but I am not sure if I can do it. 

Can you explain to me why we need to use a search layout? The results after my changes look pretty equal as it was using the search layout.

I added setRedirect to the current page but I believe it should back to the search page right?

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:stop

**Comment by peerkar** [comment]
@gustavolimav layout was there to be able to follow the search bar destination page ("search.suggestions.destination.friendly.url") setting, but I can see that it's not needed any more. Layout looks good to me to be removed, if:

1.  suggestions links work correctly
2. "Show more" work correctly and follows the search bar destination page

I think they will, but please double check.

**Comment by gustavolimav** [comment]
@peerkar Yes, both topics are working well. I double check it now.

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Manually forwarded to BChan due to an additional functional fix: https://github.com/brianchandotcom/liferay-portal/pull/139709

**Pull request closed without merging**
