### PR TITLE
[TS] LPS-179778 Missing highlighting

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-179778

Made the requested changes from https://github.com/liferay-search/liferay-portal/pull/859, resending.

**Author:** @joshuacords 
**Reviewer:** @BryanEngler

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:stop

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
It looks like the ci:test:sf failure was a fluke. :frowning_face:

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@joshuacords looks good to me

**Comment by joshchong** [comment]
ci:forward:force

**Comment by joshchong** [comment]
ci:forward:force

**Comment by joshchong** [comment]
ci:forward:force

**Pull request closed without merging**
