### PR TITLE
Multiple com.liferay.search.experiences.rest.resource.v1_0.test integration test failures

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-143238

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@gustavolimav thanks for this pr, i made some changes to the fix to resolve the issue on the indexing side instead of the query side
see https://github.com/BryanEngler/liferay-portal/pull/631

**Pull request closed without merging**
