### PR TITLE
LPS-151265 update key version on elements blueprints [backend]

### PR DESCRIPTION
**Pull request by wcao20170619**
https://issues.liferay.com/browse/LPS-151265

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test:sf

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
@wcao20170619 not sure if we can change public service method signatures (@BryanEngler ?) but should make an overload but other than that looks good to me.

**Comment by wcao20170619** [comment]
merged to https://github.com/liferay-search/liferay-portal/pull/429

**Pull request closed without merging**
