### PR TITLE
LPS-173591 Changing pagination shows wrong search count results.

### PR DESCRIPTION
**Pull request by felipelorenz**
Ticket: https://issues.liferay.com/browse/LPS-173591

PR with Tests: https://github.com/liferay-search/liferay-portal/pull/787

Send to BChan here, and he asked some changes https://github.com/brianchandotcom/liferay-portal/pull/130180

### CODE REVIEW

**Comment by joshuacords** [comment]
Changes are good

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/130400

**Pull request closed without merging**
