### PR TITLE
LPS-184524 GET and PUT by ERC SXPElement

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-184524
Continued from here: https://github.com/liferay-search/liferay-portal/pull/957

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
Sent to BChan.
master: https://github.com/brianchandotcom/liferay-portal/pull/136729

**Pull request closed without merging**
