### PR TITLE
LPS-204959 Similar Results are not showing up regression

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-204959

Regression caused by https://github.com/liferay/liferay-portal/commit/89ee5a75a51e4ec59696a1a460f54aec95682b6c from [LPS-202054](https://liferay.atlassian.net/browse/LPS-202054) which made assetEntryId a public render parameter.

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
LGTM!

**Comment by felipelorenz** [comment]
https://docs.google.com/spreadsheets/d/1twzU-nNB9sATwmVLVaNJJd9Ub-rVhWqJF7j6ii5WAZA/edit?usp=sharing I double check the tests using the RCA enviroment and looks good also

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:forward:force

**Comment by joshuacords** [comment]
ci:forward:force

**Pull request closed without merging**
