### PR TITLE
LPS-201728 [Components with more than 1 service] LPS-201728 Remove ReindexSingleIndexerBackgroundTaskExecutor from BackgroundTaskConfigurator initialization #6263

### PR DESCRIPTION
**Pull request by rcsdnj**
**Issue**: https://liferay.atlassian.net/browse/LPS-201728
**Previous PR**: https://github.com/liferay-core-infra/liferay-portal/pull/6263
**Original comment**:
ReindexSingleIndexerBackgroundTaskExecutor had two services (ReindexSingleIndexerBackgroundTaskExecutor itself), and the only reason for this is because BackgroundTaskConfigurator was registering it manually. We removed this manual registration and consequently the need for being registered as more than 1 service.

The change in this PR was suggested by @dantewang, in https://github.com/liferay-core-infra/liferay-portal/pull/6185 refering to this task.

We're sending it to liferay-search because @Kvale1733 pointed a problem that we were not able to relate to ReindexSingleIndexerBackgroundTaskExecutor class, so a deeper analysis may be necessary.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
Hey @rcsdnj,

Reviewed the code and did a manual test – looks good. Let's run the search suite to double-check before approve it.

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
hi @rcsdnj, this looks good to me, but i dont understand what the issue was that @Kvale1733 found?

**Comment by BryanEngler** [comment]
ok, i think i found it - https://github.com/liferay-core-infra/liferay-portal/pull/6263#issuecomment-1843469119

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@rcsdnj @Kvale1733
indexNameNext is supposed to be null after a concurrent reindex executes. its only populated while the reindex is happening. so step 5 (After the reindex is done, execute MySQL query "SELECT indexNameNext FROM lportal.Company;") was wrong on https://github.com/liferay-core-infra/liferay-portal/pull/6263#issuecomment-1843469119. the indexNameCurrent column is the one that should have a value after the reindex.

i manually tested this and everything looked fine. im running the search suite again, but my guess is that a failure on that test would be caused by reasons other than the changes in this pr. ill forward once ive got the new CI results verified

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@xbrianlee if these concurrent reindex tests fail again im curious if you have any thoughts about it? i know the "next index name" doesnt get created instantly, so im not sure how the timing of the database query is done accurately?

**Comment by BryanEngler** [comment]
trying a couple of tests, here https://github.com/BryanEngler/liferay-portal/pull/751 and here https://github.com/BryanEngler/liferay-portal/pull/752

**Pull request closed without merging**
