### PR TITLE
LPD-25260 LRCI-4242 Fix OpenSearch test runs in CI

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-25260

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
Hey @peerkar the CI is not working. https://liferay.slack.com/archives/C19PWQ74J/p1716180801484269

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by kenjiheigel** [comment]
Sent with additional CI changes here: 
https://github.com/liferay-search/liferay-portal/pull/1357

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
Errors in relevant not related but caused by the ignored tests. Sending directly in https://github.com/brianchandotcom/liferay-portal/pull/150780

**Pull request closed without merging**
