### PR TITLE
LPS-185839: Fix CTEntrySearcherTest

### PR DESCRIPTION
**Pull request by peerkar**
Covers:

- https://issues.liferay.com/browse/LPS-185839
  - https://issues.liferay.com/browse/LPS-187614

Fixes the following issues in CTEntrySearcherTest:
- companyId not indexed for CT entities (causes SOLR tests to failI)
- sort tests failing, because of:
  -  ignoring the order
  - getting a blank field to sort on
  - no sortable fields available

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:forward:force

**Review by pei-jung — APPROVED** [review]
Changes look good to me. Thanks for fixing this @peerkar!

**Comment by peerkar** [comment]
Sending directly here: https://github.com/brianchandotcom/liferay-portal/pull/136670

**Pull request closed without merging**
