### PR TITLE
LPS-148749 When editing my Element or using the Custom JSON Element, I want to be aided by schema-driven JSON auto-completion

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-148749

This adds autocompletion to the element editor on the Blueprint Edit Page "Custom JSON Element" and Element Edit Page.

Enable feature flag in `portal-ext.properties`:
`feature.flag.LPS-148749=true`

To follow the logic, you can start with reading `CodeMirrorEditor.js` > `getCodeMirrorHints` which is the function that gets called when you type in the code mirror editor.

Here's a demo of it in action 📹 : 
Kapture 2022-04-11 at 17 45 21

### CODE REVIEW

**Comment by thektan** [comment]
@peerkar Could take a look at this schema I created for the SXPElement autocomplete? https://github.com/liferay-search/liferay-portal/blob/5d369d5f750657f34442bb1e436a09b9c9359cb1/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/schema/sxpelement.schema.json

I based this off of the `openapi.json` (http://localhost:8080/o/search-experiences-rest/v1.0/openapi.json). Here's a gist of the `openapi.json`: https://gist.github.com/thektan/9c97e8cfb614acb48ecf4eaa4703781e

These are some of the notable properties I removed, but let me know if anything should be changed:
- configuration
  - advancedConfiguration ❌ 
  - aggregationConfiguration ❌ 
  - generalConfiguration ❌ 
  - highlightConfiguration ❌ 
  - parameterConfiguration ❌ 
  - searchContextAttributes ❌ 
  - sortConfiguration ❌ 
- queryConfiguration
  - applyIndexerClauses ❌

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:sf

**Review by oliv-yu — APPROVED** [review]
🔥 🔥 🔥 This looks great!! I don't have any suggestions!

**Comment by thektan** [comment]
Thanks @oliv-yu! Looks like I'll need to fix some tests so I'll go ahead and do that before forwarding.

**Comment by peerkar** [comment]
@thektan looks pretty good to me. Just few notes:

- Is the plan to add all the other schemas (aggregations, highlight etc.) to this same file? If not, then I'd suggest renaming it to sxp_query_element.json or alike.
- Can you please check the "format" in numbe/integer. I don't think there's such a property in JSON schema
- Maybe we could consider setting additionalProperties to false for entities that have a fixed set of properties. I think that would make sense because elements having extra properties would then anyways fail in REST API validation.

"type" property: this is a bigger question than just the schema so maybe something to discuss separately: element "type" property in not in schema but it seems we are not even using it to anything at the moment. The element types are defined in SXPElementConstants but then: we are always setting it to "0". Suggestion: 
- Let's start using the constants consistently
- Modify the constants file so that the query element is 0 (maybe others 1,2) so that no upgrade is necessary in the future.

cc @lipusz

**Comment by thektan** [comment]
Thanks for the feedback @peerkar!

- Renamed the file to `sxp-query-element.json` (I found other json files using the `-` format naming)
- `format` is a valid property, but looks like `format` is only used for `string` types so I'll remove them for `number` and `integer`. https://json-schema.org/understanding-json-schema/reference/string.html#format
- Since setting `"additionalProperties": false` wouldn't affect the autocomplete (or anything) at the moment, I'll leave it out for now. We can add it in when it's applicable.

I left `type` out of this schema since it shouldn't be suggested while using the Custom JSON Element in the Blueprint Edit Page's Query Builder (it should always be a query type here).

I created a separate task ticket for updating SXPElementConstants:  https://issues.liferay.com/browse/LPS-151609

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
