### PR TITLE
LPS-146033 Handle requests unable or very slow to resolve

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-146033 Handle requests unable or very slow to resolve (preview search, searchable types, and query contributors)

Some notes:
- Added a hook `useFetchData` that would offer the chance to refetch.
- There was a small bug if you do a search on the preview sidebar when not logged in (403 error). It wouldn't say there was an error, so I just added that in the last commit.
- To test the slow loading on preview sidebar, I went to the Network tab and made a custom throttling of 1 kbit/s 🐢 
- To test the clause contributors/searchable types messages, I used Storybook and just remained logged out of portal. 

Some screenshots of the new features:
clause contributors

searchable types

Cancel button will occur after 10 seconds of loading.
preview sidebar

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Looks good! Thanks for adding the helpful documentation and the new hook looks nice too. Since we have a handful of hooks now, maybe we can move these hooks into a `hooks` folder sibling to the `utils` folder.

Folders could be like:
- hooks <-- new
- utils
- shared

**Comment by thektan** [comment]
@oliv-yu Assigning back to you if you decide to create the new folder but you can `ci:forward` when you're ready.

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
Just rebased

ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
