### PR TITLE
LPS-126745 Allow to scope Result Rankings to a specific site so that it will be applied on matching Search Bar searches with "This Site" as scope

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-196342

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@gustavolimav lgtm

**Comment by gustavolimav** [comment]
pushed the code again fixing the semantic error and rebased with master

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/141510

**Pull request closed without merging**
