### PR TITLE
LPS-172811 asset-test: Add test to getAssetRendererFactories by companyId for objectDefinition

### PR DESCRIPTION
**Pull request by gustavolimav**
Issue: https://issues.liferay.com/browse/LPS-172811

Tests requested by bchan: https://github.com/brianchandotcom/liferay-portal/pull/129012#issuecomment-1399754577

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1387401_6047

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Continued here: https://github.com/liferay-search/liferay-portal/pull/759

**Pull request closed without merging**
