### PR TITLE
LPD-33411 Replace ModifyBlueprintsAdminTableFields with playwright 

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-33411 - Blueprints#ModifyBlueprintsAdminTableFields [functional]

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
LGTM! 👍

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
