### PR TITLE
LPD-39064: Adjust supported vector fields' dimensionality based on the search engine capabilities

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-39064

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
will forward from https://github.com/liferay-search/liferay-portal/pull/1530

**Pull request closed without merging**
