### PR TITLE
[TS] LPS-151854 Improve sort input accessibility when using keyboard, allo…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
https://issues.liferay.com/browse/LPS-151854

LPS-151854 Improve sort input accessibility when using keyboard, allow arrows keys to navigate the values and sort by pressing enter key, otherwise just use click, enter or space to select a value and sort by confirming (enter or closing the item menu).

### CODE REVIEW

**Comment by lipusz** [comment]
Hi, @georgel-pop-lr 

Back in April, the direction was to use lexicon drop-down in the future, see https://issues.liferay.com/browse/LPS-151854?focusedCommentId=2669696&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2669696

Nothing has changed with this plan, so I was wondering what's the motivation behind this new PR.

**Comment by lipusz** [comment]
Now I see that I actually closed it as Won't Fix. But got reopened without discussing it.

**Comment by lipusz** [comment]
Unless our frontend folks tell me it's okay to merge, so Olivia's concerns are also addressed, we'll close this one as well as Won't Fix.

**Comment by oliv-yu** [comment]
@georgel-pop-lr Was talking this over with @thektan, and from a closer read of the w3 documentation, scrolling through options with Left/Right Arrow keys will "select the previous/next top-level menu item." It seems like normal behavior to have the page refresh automatically upon selection. It avoids the situation when a user navigates away without entering, and the results do not reflect the selection. When a checkbox is selected on the Type search widget via accessibility, the page automatically refreshes as well and does not require an enter. It seems all right to not alter this, and we do have https://issues.liferay.com/browse/LPS-152365 to rework the select with the lexicon dropdown.

**Pull request closed without merging**
