### PR TITLE
LPS-200686 Prevent JS rounding off companyId numbers when search reindexing

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-200686 - Prevent JS rounding off companyId numbers when search reindexing

Realized after search indexing failures from [LPS-196393](https://liferay.atlassian.net/browse/LPS-196393) when large companyIds were being generated.

In the submission of the prop `virtualInstances` to the JS component, long companyIds like `5529287947776598415` get rounded off to `5529287947776598000` ([more context](https://stackoverflow.com/questions/1379934/large-numbers-erroneously-rounded-in-javascript)). Sending this data as a String would help prevent this from occurring.

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
@thektan hi! Let me know what you think about this change? The CI build keeps aborting, kicked off a rerun but hopefully it's unrelated.

**Review by thektan — APPROVED** [review]
LGTM! 🚀

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
