### PR TITLE
LPS-135245 | master

### PR DESCRIPTION
**Pull request by davidtellolr**
Hi Team,

Make sync-asynchronous mode in index write operations configurable.
After analyzing the changes made in the index operations from an asynchronous to the synchronous mode in PTR-2496, it was decided to make this behavior configurable by a portal property.
The changes in the index write operations were made in:

- LPS-127843 (Flip IndexableAdvice to do sync indexing by default, and add a manual switch to allow override. ) already released in 7.3 FP1
- LPS-130001 (Change the default value of ProxyModeThreadLocal#forceSync to TRUE) committed to 7.3.x but not released yet in an FP1

In master, by default, we selected the synchronous mode, but, as Tibor Lipusz told in the PTR, this selection could be changed during the PR review.

After the core team rejects committing the first PR with a general solution, I asked the search team if a more granular solution could be attractive and I made a proposition. andre.oliveira said the modification could be a good option and suggest some adjustments to the original idea. In this PR I develop all his suggestions and this solution applies only to the search module.

Please, let me know if you have any doubts.

### CODE REVIEW

**Comment by davidtellolr** [comment]
ci:test:sf:norebase

**Comment by davidtellolr** [comment]
ci:test:relevant:norebase

**Comment by davidtellolr** [comment]
ci:test:stable:norebase

**Comment by jorgediaz-lr** [comment]
Fixed typo in https://github.com/liferay-search/liferay-portal/pull/181

**Comment by jorgediaz-lr** [comment]
ci:close

**Pull request closed without merging**
