### PR TITLE
LPS-182779 LPS-183982 portal-search-web: Update taglibs in search web portlet

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-182779 - Update taglibs that are listed in new source formatting rule

This updates several of the outdated taglibs mentioned in LPS-179523 (SF rule). Some taglibs were left unchanged either because they were in legacy code or the recommended clay taglib does not work the same way as the "older" one (for example, `liferay-ui:icon` has a lot more attributes than `clay:icon` to introduce tooltips, links, etc). Since it looks like portal has many usages of the older taglibs and the source formatter is supposed to target new usages, it seems fine to leave some existing taglibs as is. 

Also I'm not sure if the icon for locale flags was working, but updated that too.

Thanks for taking a look!

### CODE REVIEW

**Review by thektan — APPROVED** [review]
LGTM!

**Comment by xbrianlee** [comment]
ci:test:search-as

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
