### PR TITLE
LPS-188842 LPS-206367 Validate companyAdmin in EditMVCActionCommand for reindexed companies

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-206367

Hi @lipusz,

Here is the complement of https://github.com/liferay-search/liferay-portal/pull/1223, we can send it in different PRs.

### CODE REVIEW

**Comment by lipusz** [comment]
@gustavolimav As far as I can see, the logic is still missing to consider all aspects.

So there are multiple layers of safeguard:
1. The user is Omni Admin, OR
2. FF enabled + User is Company Admin + ReindexConfiguration allows the given company + the User is the Company Admin of the given Company 

In case of #1, no no need to further validate the submitted company IDs or FF or anything else.

**Comment by lipusz** [comment]
Also, can you please include the commits from https://github.com/liferay-search/liferay-portal/pull/1223?

**Review by lipusz — CHANGES_REQUESTED** [review]
See my comments.

**Comment by gustavolimav** [comment]
> @gustavolimav As far as I can see, the logic is still missing to consider all aspects.
> 
> So there are multiple layers of safeguard:
> 
> 1. The user is Omni Admin, OR
> 2. FF enabled + User is Company Admin + ReindexConfiguration allows the given company + the User is the Company Admin of the given Company
> 
> In case of #1, no need to further validate the submitted company IDs or FF or anything else.

No need to add this logic in EditMVCActionCommand.java because it is already validate in SearchAdminControlPanelEntry, I tested this.

**Comment by gustavolimav** [comment]
https://github.com/liferay-search/liferay-portal/pull/1225

**Pull request closed without merging**
