### PR TITLE
LPS-141138 LPS-174959 object-web: Add unit test coverage to getURLViewInContext()

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-174959

### CODE REVIEW

**Comment by gustavolimav** [comment]
@joshuacords while my first PR is in stuck by ci failures, could you review my tests?

**Comment by joshuacords** [comment]
The tests looks good to me!

**Review by carolmariaabb — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:objects

**Comment by gustavolimav** [comment]
ci:test:object

**Pull request closed without merging**
