### PR TITLE
LPD-2835 Display more than index.max_terms_count value to inactive users

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-2835

Sending https://github.com/liferay-search/liferay-portal/pull/1306 again after discussions

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by gustavolimav** [comment]
ci:test:opensearch2

**Comment by gustavolimav** [comment]
ci:report:2561855270

**Comment by gustavolimav** [comment]
ci:report:2561863476

**Comment by gustavolimav** [comment]
@AlmirFe I pushed the change to include opensearch, can you add the tests to this PR?

**Comment by AlmirFe** [comment]
@gustavolimav I just sent another PR containing commits of both tickets https://github.com/liferay-search/liferay-portal/pull/1311

**Pull request closed without merging**
