### PR TITLE
LPS-166761: Add Elasticsearch Collapse support to the search API

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:stop

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:forward:force

**Comment by joshuacords** [comment]
ci:forward:force

**Pull request closed without merging**
