### PR TITLE
LPS-149968 Adapt API search to be able to implement JournalArticleIndexer as Contributors

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-149968

Hi Team 👋 

From the Echo Team,  we are trying to migrate the indexing of JournalArticles to the new paradigm. Due to the characteristics of JournalArticles, we have found a series of limitations in the API that prevent us from completing this migration.

The main problem is that all the versions of a JournalArticle are in the same table and, furthermore, the version indexing is configurable by the user.
There are two possible ways to configure version indexing:
1. All versions are indexed.
2. Only the latest published version is indexed.

The fact that everything is modeled by JournalArticle complicates indexing because indexing an article, depending on its status and the configuration, can trigger different actions.

When configured to index all versions, indexing of an article should trigger indexing of all its versions. This with the current API cannot be done without falling into an infinite loop. This is because we are not able to tell when one version is being indexed because another has been indexed.

In the case that it is configured to index only the last published version, we also find that sometimes it must trigger the indexing of other versions because the update implies that the last published version has changed.

After analyzing all this we concluded that we need to add mechanisms to the API that allow us to:

1. From ModelIndexerWriterContributor.modelIndexed to be able to launch the indexing of other objects of that same model without that method being called again to avoid the infinite loop
2. To receive a notification when an object has been deleted as a result of the @Indexable(type = IndexableType.DELETE) annotation.

This PR is my proposal to solve these points, with these changes JournalArticle can be migrated to the new paradigm.

Could you please review this proposal?

Thanks in advance ❤️

### CODE REVIEW

**Comment by lfbesada** [comment]
Hi @BryanEngler 
Thanks in advance for the review ❤️ 
In case it helps to understand the need for API changes, [this is the PR](https://github.com/liferay-echo/liferay-portal/pull/11250) I have prepared based on them.
Thank you so much!
Regards

**Comment by lipusz** [comment]
Hi @lfbesada 

Bryan is out this week, hopefully he can get back to you next week. Sorry about the delay.

**Comment by lfbesada** [comment]
Hi @lipusz Thanks a lot for the update ❤️ Regards

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_7512

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_8821

**Comment by lfbesada** [comment]
Hi @BryanEngler 
Thanks for the review!
I have updated this PR rebasing and regenerating the baselines.
The failed test seems not to be related.
Thanks!
Regards

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
