### PR TITLE
LPS-181827: Headless search integration tests

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-181827

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:reevaluate:1357401_4092

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:reevaluate:1407401_1879

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:search

**Comment by suilin** [comment]
ci:forward

**Comment by suilin** [comment]
Failures unique of relevant suite are not related to the current change, so I will force forward it.

**Comment by suilin** [comment]
ci:forward:force

**Pull request closed without merging**
