### PR TITLE
[TECHNICAL SUPPORT] LPS-118907 align search icon with wrapper

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-118907](https://issues.liferay.com/browse/LPS-118907),

Please review my changes

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Hi @NemethNorbert! Thanks for these changes!

This is how the button looked on my local machine with your changes:
Screen Shot 2020-08-12 at 6 07 33 PM

Let me know if that's not the same as what you see, but the active state on the button still looked too big so I added additional css to decrease the size.
Screen Shot 2020-08-12 at 6 01 08 PM

I created a new PR here: https://github.com/liferay-search/liferay-portal/pull/19

**Pull request closed without merging**
