### PR TITLE
LPS-153813 [FE] As an Instance Admin, I can search in a different index of my Virtual Instance other than the main index using a Blueprint

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-153813 - As an Instance Admin, I can search in a different index of my Virtual Instance other than the main index using a Blueprint

Subtasks covered:
https://issues.liferay.com/browse/LPS-163676 - Add select for search index inside blueprint editor
https://issues.liferay.com/browse/LPS-163751 - Restrict select option to only Instance Administrators
https://issues.liferay.com/browse/LPS-163752 - Selecting a different index should inactivate certain elements in query builder and sidebar

In order to view this, `feature.flag.LPS-153813=true` needs to be added to `portal-ext.properties` of the bundle.  Once the API is functional to grab search indexes (https://issues.liferay.com/browse/LPS-163750), some code-block can be un-commented out. 

Selection (when some indexes are hardcoded in):
Screen Shot 2022-10-06 at 4 50 14 PM
Screen Shot 2022-10-06 at 4 40 19 PM

When a different index is selected, tooltips will remind the user what is going on:
Screen Shot 2022-10-06 at 5 32 30 PM
Screen Shot 2022-10-06 at 5 32 21 PM

Index Configuration is added as `indexConfiguration` alongside the other configurations for submission:
Screen Shot 2022-10-06 at 4 45 13 PM

Let me know if there's anything I should add, thank you!

### CODE REVIEW

**Comment by oliv-yu** [comment]
Seems like the test failures are known issues 😺

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Resent here: https://github.com/liferay-search/liferay-portal/pull/589

**Pull request closed without merging**
