### PR TITLE
LPS-123413 NullPointerException is thrown when deleting user

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-123413](https://issues.liferay.com/browse/LPS-123413)
Dear Search Team,

**Issue:**
When administering users on "Users and Organizations" page the following issues may occur:

- When deleting user(s), NPE may be thrown and no users are displayed.
- When activating/inactivating users, the activated/inactivated users doesn't disappear from the list.

The above issues occur because the re-rendering of the page happens earlier than the update of the affected search index documents. The delayed search index update probably comes from the performance penalty observed after switching from Elasticsearch REST Client to Transport Client.

**Note:** Reproduction is easier with remote ES and HSQL, but I was able to reproduce with embedded ES and MySQL as well.

**Solution:**
In case of stale index state the search is repeated with 500 ms delay, maximum 3 times to avoid too long page render times.

Thanks for reviewing my changes. Please let me know if you have any questions or concerns.

Regards,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hey Pisti,

Please send this to the User & System Mgmt team for review.

Regarding:
>The delayed search index update probably comes from the performance penalty observed after switching from Elasticsearch REST Client to Transport Client.

> Note: Reproduction is easier with remote ES and HSQL, but I was able to reproduce with embedded ES and MySQL as well.

I'm bit confused as we are not using Transport Client on 7.3.x and master. :thinking:

**Pull request closed without merging**
