### PR TITLE
LPD-27031 LPD-27032 Convert SearchContinuousUpgrade#ViewSXPBlueprintsAndElements on Integration Tests

### PR DESCRIPTION
**Pull request by AlmirFe**
Previous PR: https://github.com/liferay-search/liferay-portal/pull/1414
https://liferay.atlassian.net/browse/LPD-27032

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:report:55826296

**Comment by AlmirFe** [comment]
ci:report:55831024

**Comment by AlmirFe** [comment]
ci:test:search

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:test:upgrade

**Comment by AlmirFe** [comment]
ci:forward

**Pull request closed without merging**
