### PR TITLE
LPD-34222 portal-search-web: Change initial layout look and feel of search portlets for greater visibility

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-34222 - Increase visibility of search portlets on widget page

Given that search portlets are configured as "barebone" on the default search page, users would not be able to see what portlets are actually available. Setting it to "borderless" allows some clarity by introducing the header. This change would apply to future search pages.

Search portlets would now look like this after startup:
Screenshot 2024-08-27 at 10 08 03 AM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:report:72663755

**Comment by oliv-yu** [comment]
It looks like the test failures look unrelated (some upgrade failures happening due to a different change), @BryanEngler did you want to review this change?

**Comment by BryanEngler** [comment]
ya from my side it looks good to forward, thanks!

**Comment by oliv-yu** [comment]
ci:forward:force

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
