### PR TITLE
LPS-179624, LPS-172131 LPS-178538 Sort widget configuration styling bug and index field update

### PR DESCRIPTION
**Pull request by thektan**
**Bug:** https://issues.liferay.com/browse/LPS-179624

**Story**: https://issues.liferay.com/browse/LPS-172131
**Subtask:** https://issues.liferay.com/browse/LPS-178538

---

- Previous PR: https://github.com/liferay-search/liferay-portal/pull/860
- Sending with https://issues.liferay.com/browse/LPS-179624 to avoid conflicts.

### Screenshots

Screenshot 2023-03-30 at 4 36 25 PM
Screenshot 2023-03-30 at 4 36 33 PM

cc @oliv-yu

### CODE REVIEW

**Comment by thektan** [comment]
@oliv-yu Search ci tests are still running, but to be able to get this forwarded by tomorrow, I was hoping you could review this today.

**Review by oliv-yu — APPROVED** [review]
Looks good! Thank you for fixing the focus too 🥇

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
Failures don't seem related.

**Comment by thektan** [comment]
ci:forward:force

**Comment by thektan** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/132729

**Pull request closed without merging**
