### PR TITLE
LPS-185742 Deep pagination errors

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-185742

Fixes LPS-185742 and other small errors.

Author: @joshuacords
Reviewer: @gustavolimav

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@joshuacords Hey Joshua! I found a bug in your changes and fixed it!

The code looks good! Just the small change that I added!

**Comment by gustavolimav** [comment]
@joshuacords Other than that you must assign your commits with Onepassword, otherwise it will not be merged in the master. Can you do that and resend it?

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
Fixed here: https://github.com/liferay-search/liferay-portal/pull/956

**Pull request closed without merging**
