### PR TITLE
LPS-182596 Fix back-end tests

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-182596

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by felipelorenz — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Pull request closed without merging**
