### PR TITLE
[TS] LPS-194520 Frequency Threshold= 0 does not apply in custom facets

### PR DESCRIPTION
**Pull request by AlmirFe**
### **LPP link:** [LPP-50593](https://liferay.atlassian.net/browse/LPP-50593)

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@AlmirFe looks good

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search-solr

**Comment by joshuacords** [comment]
This looks good, but we should run the solr tests as there's changes to solr.

**Comment by xbrianlee** [comment]
Manually forwarded since `stable` failed due to unrelated reasons
https://github.com/brianchandotcom/liferay-portal/pull/140359

**Comment by BryanEngler** [comment]
@AlmirFe @joshuacords 
you can pass in -1 as a default value to dataJSONObject.getInt. its cleaner than having to do the null check yourself

**Pull request closed without merging**
