### PR TITLE
[TS] LPS-123508 Field value factor score not translated

### PR DESCRIPTION
**Pull request by joshuacords**
Authors: @joshuacords @arboliveira

[Bug] Field value factor score not translated
https://issues.liferay.com/browse/LPS-123508

Already delivered to customer.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@joshuacords Please tell Brian not to backport this to 7.3.x as we'd like to test the multi-backport support in LBM on this fix if possible.

/cc @CsabaTurcsan fyi

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
