### PR TITLE
LPS-181903 Fix bugs Blueprint Collection Provider

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPS-189065
https://liferay.atlassian.net/browse/LPS-189067
https://liferay.atlassian.net/browse/LPS-189107

Continued from here: https://github.com/liferay-search/liferay-portal/pull/979

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:reevaluate:1287401_6907

**Comment by felipelorenz** [comment]
ci:reevaluate:1287401_6907

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
ci:reevaluate:1397401_5762

**Comment by brookedalton** [comment]
ci:forward:force

**Pull request closed without merging**
