### PR TITLE
LPS-149393: Switch to contributor model

### PR DESCRIPTION
**Pull request by peerkar**
This PR covers both:

- https://issues.liferay.com/browse/LPS-144398: SXPElements not getting indexed when SXP deployed on existing installation (see [comments](https://issues.liferay.com/browse/LPS-144398?focusedCommentId=2639976&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2639976)  
- https://issues.liferay.com/browse/LPS-149393: Switch to contributor model

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:forward

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
