### PR TITLE
LPD-17800 LPS-22190 Integrate the Date + Range Facet into the Custom Facet as new aggregation types

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-17800 - Integrate the Date Facet into the Custom Facet as new aggregation type (Date Range) - Dev FF
https://liferay.atlassian.net/browse/LPD-22190 - Add support for Range aggregation to the Custom Facet - Dev FF

Changes are behind FF 
`feature.flag.LPS-153839=true`

@peerkar

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:stop

**Comment by peerkar** [comment]
@oliv-yu please see the updated PR [here](https://github.com/liferay-search/liferay-portal/pull/1503)

**Pull request closed without merging**
