### PR TITLE
LPS-164852 portal-search-web: Format destination URL for suggestions call

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-164852 - Suggestion results should be clickable even when Destination Page doesn't start with "/"

To fix this, there's just a new function that formats the destinationFriendlyURL to trim and append a `/` in the front of the string (if no slash is provided), which was what the suggestions call needed. If left blank, the destination URL defaults to `/search` as before. Let me know if I should make other changes, thanks!

### CODE REVIEW

**Review by thektan — CHANGES_REQUESTED** [review]
Taking a further look at this issue, a fix on the backend should be more appropriate. Otherwise, all templates would always have to implement this slash formatting.

I haven't tried this out myself, but you could try implementing the same `_slashify` method like we have in [SearchBarPortletDisplayContextFactory.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/search/bar/portlet/display/context/factory/SearchBarPortletDisplayContextFactory.java#L475-L481) into [SuggestionResourceImpl.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-rest-impl/src/main/java/com/liferay/portal/search/rest/internal/resource/v1_0/SuggestionResourceImpl.java#L178-L180).

So this line would be
```java
		searchContext.setAttribute(
			"search.suggestions.destination.friendly.url",
			_slashify(destinationFriendlyURL));
```

**Comment by thektan** [comment]
@oliv-yu Adding the slashify here actually might be better as it'd be the same usage in [SearchBarPortletDisplayContextFactory.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/search/bar/portlet/display/context/factory/SearchBarPortletDisplayContextFactory.java#L475-L481) 

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/suggestions/spi/BasicSuggestionsContributor.java#L341-L345

**Comment by oliv-yu** [comment]
@thektan Also noticed https://github.com/liferay/liferay-portal/blob/46f344f9cd11e66f2c8b188e83e011712bab4d2c/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/internal/suggestions/spi/SXPBlueprintSuggestionsContributor.java#L411, same approach?

**Comment by thektan** [comment]
@oliv-yu Good catch...since it seems like something we'd want for all contributors, putting the `slashify` at the very beginning might be better. So back to the first file I mentioned except even earlier: https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-rest-impl/src/main/java/com/liferay/portal/search/rest/internal/resource/v1_0/SuggestionResourceImpl.java#L94

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by thektan** [comment]
@oliv-yu To double-check, could you try `gradlew baseline` in `portal-search-rest-impl` to see if there are any version bumps?

**Comment by thektan** [comment]
I forget if that fails for sf or in the search ci

**Comment by oliv-yu** [comment]
@thektan Ran baseline, no version bumps! 🤞

**Review by thektan — APPROVED** [review]
Thanks for making those backend changes! 🔥

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
Forwarded https://github.com/brianchandotcom/liferay-portal/pull/127396

**Pull request closed without merging**
