### PR TITLE
LPS-192640 LPS-196113 Allow duplicate ERC error to display

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://liferay.atlassian.net/browse/LPS-192640
**Subtask:** https://liferay.atlassian.net/browse/LPS-196113

The early `!response.ok` check was preventing the error message from returning.

This also follows the same pattern found in https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/view_sxp_blueprints/ImportSXPBlueprintModal.js#L78-L129

## Screenshot with fix

Screenshot 2023-09-26 at 4 07 36 PM

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Review by oliv-yu — APPROVED** [review]
It's beautiful 🥲 thank you for figuring this out! lgtm

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
