### PR TITLE
LPS-155753 Search Bar Suggestions doesn't work with "Everything" scope

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-155753

**Additional Notes**
- Only checking `isSelectedEverythingSearchScope` since the only 2 scope choices are "everything" and "this site".
- Added an additional change to only add the `scope` URL parameter if the "Let The User Choose" scope selector is present. The original search bar JS function also does this by checking if the select element is present. https://github.com/liferay/liferay-portal/blob/13b0e2b835e528ca701c5d6bc22c8fcc7b98aa12/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/js/search_bar.js#L108-L113

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Pushed up additional commits so that suggestions in search bar widgets on the search page would use the header's search bar configured scope. Otherwise, the search bar widget suggestions would always be set to "this site" since the configurations are disabled.

Screen Shot 2022-06-16 at 8 26 17 PM

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
running tests here https://github.com/BryanEngler/liferay-portal/pull/651

**Pull request closed without merging**
