### PR TITLE
LPS-151209

### PR DESCRIPTION
**Pull request by AlmirFe**
https://issues.liferay.com/browse/LPS-151209

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Review by oliv-yu — CHANGES_REQUESTED** [review]
I think you need to cherry-pick in the other two commits, and I would update the commit message to say `LPS-151209` instead of the original LPS.

https://github.com/liferay-search/liferay-portal/pull/272/commits/41ce88281433772a452bc063cebd8e2e612b7438 (this removes the older way warnings were processed)
https://github.com/liferay-search/liferay-portal/pull/272/commits/c2b8af1ba2fd75464732354abae6f4c852d87ec9 (this fixes the styling, to include warning styles)

I had to fix some merge conflicts with cherry-picking, but I made a branch here https://github.com/oliv-yu/liferay-portal/commits/LPS-151209-display-errors to refer to. Feel free to add those into this branch and rerun ci!

**Comment by AlmirFe** [comment]
Ok Olivia, thanks for the review. We will work on it now

**Comment by AlmirFe** [comment]
> I think you need to cherry-pick in the other two commits, and I would update the commit message to say `LPS-151209` instead of the original LPS.
> 
> [41ce882](https://github.com/liferay-search/liferay-portal/commit/41ce88281433772a452bc063cebd8e2e612b7438) (this removes the older way warnings were processed) [c2b8af1](https://github.com/liferay-search/liferay-portal/commit/c2b8af1ba2fd75464732354abae6f4c852d87ec9) (this fixes the styling, to include warning styles)
> 
> I had to fix some merge conflicts with cherry-picking, but I made a branch here https://github.com/oliv-yu/liferay-portal/commits/LPS-151209-display-errors to refer to. Feel free to add those into this branch and rerun ci!

Ok Olivia, thanks for the review. We will work on it now

**Comment by AlmirFe** [comment]
Open a new pull request #524

**Pull request closed without merging**
