### PR TITLE
LPS-198679 - Apply --control-menu-container-height css variable to search-experiences.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-198679

This PR is consistently applying the use of the --control-menu-container-height css variable to handle the offset for elements that have a fixed position.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by lipusz** [comment]
@oliv-yu Could you help with this? Thanks!

/cc @brunofalc

**Review by oliv-yu — APPROVED** [review]
Looks good! Thanks for updating this and letting us know about the `--control-menu-container-height`!

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
Manually forwarded to Bchan: https://github.com/brianchandotcom/liferay-portal/pull/142536

**Pull request closed without merging**
