### PR TITLE
 LPS-199645 Integration test SXPBlueprintSearchResultTest.testBoostContentsForTheCurrentLanguage is intermittently failing

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPS-199645

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
Good to go! Forwarding.

**Pull request closed without merging**
