### PR TITLE
LPS-189221 Update Elasticsearch Sidecar version to latest 7.17.x (7.17.12)

### PR DESCRIPTION
**Pull request by AlmirFe**
### Links
- Story: [LPS-189221](https://liferay.atlassian.net/browse/LPS-189221)
-  Subtask: [LPS-191969](https://liferay.atlassian.net/browse/LPS-191969)

## PR goal
Update Elasticsearch Sidecar version to latest 
Screenshot from 2023-07-27 14-28-03

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshchong** [comment]
Sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/138531

**Pull request closed without merging**
