### PR TITLE
LPD-30304 and LPD-30309

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-30304
https://liferay.atlassian.net/browse/LPD-30309

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:29933307

**Comment by gustavolimav** [comment]
ci:report:29916975

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
