### PR TITLE
LPS-182432 Field "userGroupRoleIds" should have an explicit "string" mapping in the Solr schema.xml

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-182432

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
:+1: LGTM @felipelorenz

**Review by lipusz — APPROVED** [review]

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by felipelorenz** [comment]
ci:forward:force

**Comment by felipelorenz** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
