### PR TITLE
LPD-26932: Move semantic search to portal-search. Add embedding support for DLFileEntry

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-26932

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
resend [here](https://github.com/liferay-search/liferay-portal/pull/1391)

**Pull request closed without merging**
