### PR TITLE
LPS-172811 add tests

### PR DESCRIPTION
**Pull request by joshuacords**
Continued from: https://github.com/liferay-search/liferay-portal/pull/758

Tests requested by bchan: https://github.com/brianchandotcom/liferay-portal/pull/129012#issuecomment-1399754577

**Author:** @gustavolimav 
**Reviewer:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:reevaluate:1267401_7336

**Comment by joshchong** [comment]
Failures are unrelated.
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/129485

**Pull request closed without merging**
