### PR TITLE
LPD-28431 Bump third-party libraries in the Elasticsearch connector to their latest, if needed

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-28431

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:report:21892461

**Comment by felipelorenz** [comment]
Tests looks good, failures are not related.

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
