### PR TITLE
LPD-31094

### PR DESCRIPTION
**Pull request by gustavolimav**
[LPD-31094](https://liferay.atlassian.net/browse/LPD-25633)

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
https://github.com/liferay-content-management/liferay-portal/pull/5715

**Pull request closed without merging**
