### PR TITLE
LPS-165216 search-experiences-service: Gracefully ignore custom web content structures. Title only will be used

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-165216

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@peerkar, fyi running the relevant suite will also run the stable suite so you don't have to trigger that separately. I'll abort the duplicate stable run in this PR.

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:stop

**Comment by peerkar** [comment]
Closing this and creating a new PR because of CI not responding

**Pull request closed without merging**
