### PR TITLE
[TS] LPS-115203 Do not index Company content into System index

### PR DESCRIPTION
**Pull request by istvansajtos**
https://issues.liferay.com/browse/LPS-115203

Dear Search Team,

Please review my changes.

**Issue:** Single entity reindex duplicates Company content into System index.

**Solution:** I used the the same approach that [LPS-105532](https://issues.liferay.com/browse/LPS-105532) used to fix the same issue for "Reindex all search indexes".

Thank you in advance,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
ci:test:search:norebase

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by istvansajtos** [comment]
Hi @BryanEngler ,

Could you please take a look at my changes and [these failures](https://github.com/liferay-search/liferay-portal/pull/38#issuecomment-696248250) ? 

I would like to give out an SDH fix if you think it is safe.

Thank you.

**Comment by BryanEngler** [comment]
hey @istvansajtos
i dont see any unique failures and the fix looks good, you can go ahead and send an SDH

**Comment by BryanEngler** [comment]
i will forward from https://github.com/BryanEngler/liferay-portal/pull/535 after tests pass

**Pull request closed without merging**
