### PR TITLE
LPD-38774: Account restriction in object not filtering properly using Custom Facets

### PR DESCRIPTION
**Pull request by gustavolimav**
Ticket: https://liferay.atlassian.net/browse/LPD-38774

I need just a review of search code to approve hotfix creation. Tests will be created yet.

GeneralSXPSearchRequestBodyContributorTest

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
https://github.com/liferay-objects/liferay-portal/pull/3714 pr to objects team

**Comment by gustavolimav** [comment]
ci:report:35623561

**Comment by gustavolimav** [comment]
no unique failures

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
@marcelabc, here is the PR

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
LGTM!

**Comment by marcelabc** [comment]
@gustavolimav thank you! LGTM :tada:

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:43911903

**Pull request closed without merging**
