### PR TITLE
LPS-203828 portal-search-web: Escape attribute inside user jsp

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-203828 - XSS with "_com_liferay_portal_search_web_portlet_SearchPortlet_userId=" on search widget

Small update, just need to escape the attribute :)

### CODE REVIEW

**Review by thektan — APPROVED** [review]

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
