### PR TITLE
LPD-28416 Index Status by User's ERC

### PR DESCRIPTION
**Pull request by joshuacords**
**Story:** [LPD-28416](https://liferay.atlassian.net/browse/LPD-28416)
**Subtasks:**
- [LPD-31278](https://liferay.atlassian.net/browse/LPD-31278)
- [LPD-32921](https://liferay.atlassian.net/browse/LPD-32921) Tests

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:stop

**Review by gustavolimav — CHANGES_REQUESTED** [review]
Just a few changes following the last changes Bchan did. Other than that code LGTM. You can forward after those two requested changes are done.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:search-solr

**Comment by joshuacords** [comment]
ci:test:search-opensearch2

**Comment by joshuacords** [comment]
ci:forward-force

**Pull request closed without merging**
