### PR TITLE
LPS-204773 Result rankings web module is not being initialized when LES is not available

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPS-204773

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
this is going to conflict with dd0d51cbc591b5179fa18fc709d92ca6a8461d33, so its fine to hotfix, but now, instead of committing this to master, we should probably just work on the extraction of sxp imports

**Pull request closed without merging**
