### PR TITLE
[TS] LPS-118811 Set track_total_hits to true, to maintain the old behavior of Elasticsearch 6

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by lipusz** [comment]
@jorgediaz-lr https://grow.liferay.com/share/How+to+send+Pull+Request+to+the+Search+Team+liferay-search#trigger-ci--review-results

**Comment by jorgediaz-lr** [comment]
Hi @lipusz 

Could be possible to launch ci:test:sf and ci:test:relevant automatically? 

Thank you

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@jorgediaz-lr thanks for the fix, see https://github.com/BryanEngler/liferay-portal/pull/518 with the added config

**Pull request closed without merging**
