### PR TITLE
LPS-167348 [FE] Semantic Search System Settings UI Updates 

### PR DESCRIPTION
**Pull request by thektan**
FE Subtasks for the story https://issues.liferay.com/browse/LPS-166657
 (As an Administrator, I can test the configuration with the selected Transform Provider when configuring Semantic Search)
- https://issues.liferay.com/browse/LPS-167505
- https://issues.liferay.com/browse/LPS-167346
- https://issues.liferay.com/browse/LPS-167471
- https://issues.liferay.com/browse/LPS-167347
- https://issues.liferay.com/browse/LPS-167506
- https://issues.liferay.com/browse/LPS-167507

Grouped all these subtasks in the same PR since they all are editing the same file.

### Summary of changes
- Renamed Test Connection button to Test Configuration
- Made Hugging Face Access Token and Model fields required
- Improved test configuration error messaging and handled more returned error formats

**Example screenshot of error (using mocked data)**
Screenshot 2022-11-07 at 9 54 34 PM

Screenshot 2022-11-07 at 10 22 37 PM

### CODE REVIEW

**Comment by thektan** [comment]
@oliv-yu I don't think any failures are related, but I'll check with QA after you finish your review and it's ready to forward. In the meantime I'll also run ci:test:relevant to see if any failures would block this PR.

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Review by oliv-yu — APPROVED** [review]
Lgtm! 💯

**Comment by thektan** [comment]
Force pushed to fix LPS ticket number. `ci:test:search` results don't seem related, so I'm going to forward this.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
