### PR TITLE
[TS] LPS-167763 Search Bar Scope Everything doesn't return Site members documents results for Guest role if View Document scope isn't also All Sites And Asset Library

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
From: https://github.com/liferay-search/liferay-portal/pull/724
Ticket: [LPS-167763](https://issues.liferay.com/browse/LPS-167763)
Author: @georgel-pop-lr Reviewer: @joshuacords

### CODE REVIEW

**Comment by kungfumanda** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@joshuacords @kungfumanda the failing search tests are unrelated

**Comment by joshuacords** [comment]
Looks good to me!

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
