### PR TITLE
LPS-193198 Add destination unreachable check

### PR DESCRIPTION
**Pull request by victorg1991**
https://liferay.atlassian.net/browse/LPS-193198

I have added an additional check that it is used here: https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/search/bar/view.jsp#L44

Since the message is that the portlet is not viewable yet, we should include the PORTLET_CONFIGURATOR_VISIBILITY to allow hiding it with the toggle controls

### CODE REVIEW

**Review by gustavolimav — APPROVED** [review]
LGTM! :rocket:

Thanks for fixing it @victorg1991!

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
Hey @victorg1991, analyzing tests I can see that this [LocalFile.Search#SearchBarPresentWithNoDestinationPage](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605479//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchBarPresentWithNoDestinationPage_) is falling and it is not normal. Can you verify it? I test it manually and it seems to be ok but for some reason the test failled.

**Review by gustavolimav — CHANGES_REQUESTED** [review]
Hey @victorg1991, analyzing tests I can see that this [LocalFile.Search#SearchBarPresentWithNoDestinationPage](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/605479//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchBarPresentWithNoDestinationPage_) is falling and it is not normal. Can you verify it?

**Comment by gustavolimav** [comment]
Hey @victorg1991 can you verify that [ticket](https://liferay.atlassian.net/browse/LPS-163126)

if you set that property that bug will start to happen again, can you find some workaround?

**Comment by victorg1991** [comment]
Hey @gustavolimav that issue doesn't seem to be an issue. Without my fix you can see that message even when the user is not logged in, which doesn't make any sense

Also in content pages, when you visualize the view mode of the page, those alert shouldn't be showing. For instance if you add an asset publisher to a content page, the message is displayed in edit mode, but no on view mode. Could you verify that?

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
Tests are ignored now, after ci we can forward it

**Comment by joshchong** [comment]
hey @gustavolimav, I aborted the tests since those test suites already ran in this PR. we don't need to confirm that the test is ignored in a test run to forward this PR.

**Comment by joshchong** [comment]
ci:forward:force

**Comment by joshchong** [comment]
Forwarded to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/139575

**Pull request closed without merging**
