### PR TITLE
LPS-183214: Allow excluding document fields from headless search API response

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-183214

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:reevaluate:1407401_1947

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
Discarded

**Comment by lipusz** [comment]
@peerkar Should I discard the complete task?

**Comment by peerkar** [comment]
Personally I regard it a to-have feature

**Pull request closed without merging**
