### PR TITLE
LPS-158694 portal-kernel: there are ES fields we want to be able to r…

### PR DESCRIPTION
**Pull request by joshuacords**
…eference starting with underscore

https://issues.liferay.com/browse/LPS-158694

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Waiting for CI issues to subside before re-running tests. See [latest Slack update about CI](https://liferay.slack.com/archives/C19PWQ74J/p1658417487999909).

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Results for the search suite test run look good ✅

**Comment by joshuacords** [comment]
Updated code based on Bryan's suggestions, new PR here: https://github.com/liferay-search/liferay-portal/pull/504

**Pull request closed without merging**
