### PR TITLE
LPS-158850

### PR DESCRIPTION
**Pull request by AlmirFe**
https://issues.liferay.com/browse/LPS-158850
Follow up: https://github.com/brianchandotcom/liferay-portal/pull/123275

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@AlmirFe https://liferay.slack.com/archives/G982WB4TH/p1663784762354389

**Comment by brookedalton** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:stop

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:reevaluate:1267401_5113

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
