### PR TITLE
LPD-31098 SXPBlueprintSearchResultTest.testBoostAssetType test fix

### PR DESCRIPTION
**Pull request by gustavolimav**
[LPD-31098](https://liferay.atlassian.net/browse/LPD-31098)

The test is just failing in the first time you run it  in a clean bundle, if you want to test the fix just startup a clean bundle and run the test.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by AlmirFe — APPROVED** [review]
@gustavolimav LGTM! :rocket:

**Comment by AlmirFe** [comment]
ci:forward

**Pull request closed without merging**
