### PR TITLE
LPD-25837 Create test to ensure End and Start fields for federated search requests are populated correctly

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-25837

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Review by gustavolimav — CHANGES_REQUESTED** [review]
Hey @AlmirFe, in general it looks good, can you just rename the test?

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:forward

**Pull request closed without merging**
