### PR TITLE
LPD-39546 portal-search-web/search*.spec.ts [Playwright]

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPD-39546 - portal-search-web/search*.spec.ts [Playwright]

Several updates:
- Use `isolatedLayoutTest` in order to keep processes clean (no need to teardown)
- Use `test.step` instead of comments
- I think maybe the playwright issue was that the searchPage.goto was giving a restricted page error on cloud runs, so the path was updated. But having paths to separate pages should also work, and is a good practice in general.

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:test:playwright

**Review by thektan — APPROVED** [review]
LGTM! 👍

**Comment by oliv-yu** [comment]
@thektan Thank you!! 🙏

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
