### PR TITLE
LPS-167992 [FE] Update Hugging Face providers' help texts

### PR DESCRIPTION
**Pull request by thektan**
Story: https://issues.liferay.com/browse/LPS-167992
Subtask: https://issues.liferay.com/browse/LPS-175813

- Updated the help text to use completed sentences

### CODE REVIEW

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:forward:force

**Pull request closed without merging**
