### PR TITLE
LPS-147329 [BE] Upgrade Step: Upgrade SXPElement entries and element instances to add language key

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-175579 - [BE] Upgrade Step: Upgrade SXPElement entries and element instances to add language key

Cherry-picked from @peerkar's branch https://github.com/peerkar/liferay-portal/commits/LPS-147329-language-key-localizable-titles

I was able to test out using a few blueprints with several elements, a custom element, and OOTB elements pre-LPS-147329. After performing the upgrade, it looks good! 
- OOTB elements have proper title/description set in the appropriate language keys
- Existing blueprints that had several element instances with OOTB elements have their titles and descriptions in language keys. Even if the title/description object was empty before (in case of https://issues.liferay.com/browse/LPS-172278), they update. It looks like it uses the externalReference code to get those language keys.
- Custom element is unchanged (makes sense, as it has a non-OOTB externalReference code)

@thektan

### CODE REVIEW

**Comment by joshchong** [comment]
@lipusz regarding:

> Custom element is unchanged (makes sense, as it has a non-OOTB externalReference code)

I noticed that in the validation steps in https://issues.liferay.com/browse/LPS-175579, that we are to add a custom element, but wasn't sure what the purpose was. Is it expected that the custom element was to remain unchanged after the upgrade?

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@joshchong I don't see that on the ticket you mentioned. Where did this quote come from? :thinking: 

> Custom element is unchanged (makes sense, as it has a non-OOTB externalReference code)

**Comment by lipusz** [comment]
@joshchong I believe @oliv-yu refers to custom element instances created using the "Custom JSON Element" on the Query Builder, not actual custom elements created through the Edit Element screen: those must have an ERC as it's automatically generated by the service layer. So if that's the case, Olivia's assessment is valid. :white_check_mark:

**Comment by oliv-yu** [comment]
@lipusz Oh when I said "Custom element is unchanged (makes sense, as it has a non-OOTB externalReference code)", I actually was referring to an element created via View Elements page. They do have an externalReference code, just it's something like `2790ac61-df2e-4a44-a61d-d21ea76a6d7d`, while OOTB elements have something like `BOOST_ALL_KEYWORDS_MATCH`. 😅 For these custom elements, I just assumed they don't have their titles/descriptions automatically translated into language keys in the upgrade. I guess @joshchong  was curious whether we expect any of them to have changes? There's a step in the ticket description to create a custom element.

**Comment by lipusz** [comment]
@oliv-yu So, if I enter lang keys as the title and the description for my Custom Element, will it work after these changes?

**Comment by oliv-yu** [comment]
@lipusz Yup! That should still work. If you previously added language keys to title/description for a custom element, it isn't affected by this upgrade process. So there should be translations, because of the changes that were merged from https://github.com/brianchandotcom/liferay-portal/pull/130740

Thanks for asking, I actually was testing out custom elements with Chinese locales and ran into a bug, so I pushed up a short commit.

**Comment by lipusz** [comment]
Thanks @oliv-yu ! :+1:

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@oliv-yu, the tests look good. you can run `ci:forward:force` to forward to bchan if you're ready.

**Comment by oliv-yu** [comment]
@joshchong Thanks for looking it over!!

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
