### PR TITLE
LPS-145820 Adapt layout search creation and removes no needed methods

### PR DESCRIPTION
**Pull request by ealonso**
https://issues.liferay.com/browse/LPS-145820

Motivation
=======
Liferay provides some page templates out of the box with the goal of showcasing the page template functionality. The original goal was for this page templates to also provide a good starting point to cover real world use cases. However, because they haven't been adapted with the years to these real world needs they currently add very little value.

Considering this it's been decided that it is better to remove the out of the box page templates so that they are not created in new installations. Existing installations will not be affected by this change, since the page templates will already have been created and thus will not be impacted.

[Link to the issue](https://issues.liferay.com/browse/LPS-110243) 

Proposed Solution
========
It removes the creation of layout page template from **AddLayoutPrototypePortalInstanceLifecycleListener** class, also update the way we are creating the Search layout since we were using the page template to create it.

### CODE REVIEW

**Comment by lipusz** [comment]
Hi @ealonso 

I see it has been added as a tech-debt. Give me some time to think it through from our perspective. :timer_clock:

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Just a quick update: we are going to discuss this with André and Petteri tomorrow to see what additional long-term implications this change has for us.

I'll keep you posted.

**Comment by ealonso** [comment]
Hey @lipusz @gustavolimav,

Are you discarding the pr? Are you planing to include it on any other ticket?

Some feedback will be really appreciated, since I spend my time fixing a problem of your team and you close my pr without any comment.

Regards,
Eudaldo

**Comment by lipusz** [comment]
Hi @ealonso 

There is a Story being worked on where your changes will be re-used, its the parent of your original ticket.

We've had several discussions with Julia and Jurgen since this PR was closed. I'm sorry I thought you were kept updated.

**Comment by lipusz** [comment]
I've just DMed you the related.google doc.
Ticket: https://issues.liferay.com/browse/LPS-146646

**Pull request closed without merging**
