### PR TITLE
LPD-36512 Search pagination delta is shared when using multiple search results widgets

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-36512

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by joshuacords** [comment]
The code looks good but we need a test.

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @AlmirFe - it seems like I missed checking for all the places that ```searchContext.setEnd(searchContainer.getEnd());``` is used, this probably should get re-reviewed.

**Comment by AlmirFe** [comment]
new PR sent https://github.com/liferay-search/liferay-portal/pull/1533

**Pull request closed without merging**
