### PR TITLE
LPS-128302 & LPS-128307 Bumping ES to 7.10

### PR DESCRIPTION
**Pull request by joshuacords**
Original Sidecar bump here: #90
Older PR here: #91

My commit bumps the client for https://issues.liferay.com/browse/LPS-128307

Authors: @joshchong @joshuacords
Reviewer: @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:search-jdk11

**Comment by joshuacords** [comment]
ci:test:workflow

**Comment by joshuacords** [comment]
ci:test:commerce

**Comment by lipusz** [comment]
Why aren't we bumping to 7.11?

**Comment by lipusz** [comment]
Hey @liferay/qa-search

Regarding `ci:test:search-jdk11`: 

I was wondering if it has any value still testing ES7 with different JDKs since we don't have anymore the matching JDK requirement in 7.3 and master thanks to the REST client that does not rely on Java serialization.

**Comment by joshuacords** [comment]
Hi @lipusz,

I'm going to work on a spike for how to upgrade to 7.11, in particular how do we need to get the distribution to complying with the new ES licensing terms. Once that's figured out we'll go to 7.11. (7.10 won't be committed).

**Comment by xbrianlee** [comment]
Hey @lipusz, we mainly ran the JDK11 suites on master and 7.3 to be absolutely sure we covered all our bases. If switching to REST means there isn't a risk of incompatibility with JDK11, we can turn off these suites. What do you think?

**Comment by lipusz** [comment]
As we discussed, we should only bump the sidecar version, but keep the client on 7.9.0.

**Pull request closed without merging**
