### PR TITLE
LPD-27992 Fix flakiness for reindex/localized search admin tests

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-27992 - Search#IsLocalizedInSearchAdmin
https://liferay.atlassian.net/browse/LPD-27123 - Elasticsearch7#ReindexWithSyncExecutionMode

These flakey test fails are related to not being able to see the Test Test user sometimes on startup, so the workarounds have been to:
- Add a site to be able to access user admin menu
- Assert a visible document (tree.png) or the default-service-account user

And also:
- Add a little step before grabbing reindex timestamp

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
@xbrianlee Hi! Not sure why sf is still stuck in pending, but do you mind taking a look at these changes in poshi?
Thanks!!

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
Thanks, @xbrianlee! Forwarding now 👍

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
