### PR TITLE
[TS] LPS-148130 Index all available locales for AssetTags

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-148130

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
is this not a case to use the raw assetTagNames field?

**Comment by joshuacords** [comment]
@BryanEngler, I was thinking about it, but using the raw does 2 things
1. We wouldn't be using a proper language analyzer when we could
2. We would be breaking out multi-language pattern more instead of fixing it

**Comment by BryanEngler** [comment]
im just thinking that if we could fix on the query side instead of index side, then a reindex wouldnt be necessary... 

if we are indexing "assetTagNames_ja_JP" : "english", (along with all of the other locales as well) i dont think thats using the proper analyzer either, because "english" is not a japanese word... if youre going to mismatch content with analyzer, then you might as well just use the standard analyzer with the plain "assetTagNames" text field (not the "raw" field, i shouldnt have used that term), which is already available. if the goal is just to use the same analyzer for index and query time, and be searching a field that exists/has content, it should work the same. 

The other option (which i think is the correct one after looking at this more), if we want to use the same analyzer for both indexing and query, is to use the site default locale field. so even though display language is japanese, we would still query "assetTagNames_en_US" because thats how the tag is indexed/localized. Tags can really only be localized/analyzed with 1 language, the default language of the site. There is some gray area here (ie it depends on what choices users make), but in general, i think the way it was designed is that if the site is english by default, the tags would be english. If it was a japanese site by default, the tags would probably be japanese. So i think it makes sense to always query on the field where the data is indexed (the default locale field), regardless of display language.

take a look at this and let me know what you think https://github.com/BryanEngler/liferay-portal/commits/pr_2022_03_02_liferay_search_pr305_JCords_LPS_148130

fyi i wasnt able to run the integration test yet, ant alling...

**Comment by lipusz** [comment]
+1 to what Bryan wrote

**Comment by BryanEngler** [comment]
testing here https://github.com/BryanEngler/liferay-portal/pull/633

**Pull request closed without merging**
