### PR TITLE
[TS] LPS-167763 Search Bar Scope Everything doesn't return Site members documents results for Guest role if View Document scope isn't also All Sites And Asset Library

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
https://issues.liferay.com/browse/LPS-167763

Comes from https://github.com/liferay-search/liferay-portal/pull/684

@joshuacords I tried to add tests, but for SuggestionResourceImpl.java I wasn't able to check searchContext for groupsIds and I made resultsSuggestions, but for some reason is returning a max of 5, not sure why.

Because of that testWithScopeEverythingViewCompanyPermission and testWithScopeEverythingViewGroupPermission are failing as I expect all the 6 files to be returned.

Could you please check and let me know if the tests are okay, and why SuggestionResourceImpl.java is returning a max of 5 results?

Thanks in advance!

Regards.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:search

**Comment by georgel-pop-lr** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Thanks for getting the tests this far @georgel-pop-lr, the final tests are running in https://github.com/liferay-search/liferay-portal/pull/716

**Pull request closed without merging**
