### PR TITLE
LPS-178150 Data in the Searchbar should not persist when navigating away

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

Previous PR: https://github.com/liferay-search/liferay-portal/pull/834
PR is updated with the same change in additional locations.
LPS: https://issues.liferay.com/browse/LPS-178150

Could you please review it?

Cc. @oliv-yu
Thank you

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:search

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
Could you also add autocomplete=off to this line? https://github.com/liferay-search/liferay-portal/blob/44c0c14d824520927dba19ee06c37ce9bda4baca/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/search/bar/view.jsp#L130

Thanks! Let me know if there's any issues.

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:search

**Comment by orsolyaDekany** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:stop

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Waiting for tests to finish, but changes look good! Thank you for working on this @orsolyaDekany 💯

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
