### PR TITLE
Lps 157872 modified date modified user name modified user portrait and creator user portrait are available in the search results widget template context

### PR DESCRIPTION
**Pull request by gustavolimav**
@BryanEngler 
https://issues.liferay.com/browse/LPS-157872

Fixed the test as discussed [here](https://github.com/BryanEngler/liferay-portal/pull/667#issuecomment-1247357534)

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@gustavolimav looks good, you can push the additional commits for publish date to this pr, just let me know when you do. thanks!

**Comment by gustavolimav** [comment]
@BryanEngler Pushed the additional commits

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:help

**Comment by gustavolimav** [comment]
That PR is not running the tests I closed and resend here: https://github.com/liferay-search/liferay-portal/pull/563

**Pull request closed without merging**
