### PR TITLE
LPS-172073 search-experiences-web: Cleanup CSS files

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-172073 - Clean up CSS files + associated JS files

Basically more refactoring, for sass files:
- Organize sass files in the same way the js folder is organized
- Name sass files more closely to the component + follow a `sxp-` and `-root` naming convention 
- Existing modals were converted into their own component, for naming consistency
- Shared `builder` sass file was renamed to the more general `_edit_sxp_blueprint.scss` and updated `builder` classname (since `builder` is not accurate)
- Remove some repeated sass variables (mostly colors) and renamed to reflect Lexicon
- Remove styling for `sxp-blueprints-search-container` which doesn't look like it's being used anywhere
- Remove usage of `utils.scss` since it is not associated with `utils.js` and isn't heavily used

Making changes on top of https://github.com/brianchandotcom/liferay-portal/pull/128245 to avoid merge conflicts.

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:sf

**Review by thektan — APPROVED** [review]
Thanks for these changes! Cleans up a lot! 🔥

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by joshchong** [comment]
Continued in https://github.com/liferay-search/liferay-portal/pull/742 with test fixes

**Pull request closed without merging**
