### PR TITLE
[TS] LPS-152937 Elasticsearch sort doesn't work with accented words (2nd pull request)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This PR is similar to https://github.com/liferay-search/liferay-portal/pull/434 but instead of adding a new nested "raw" mapping, I have fixed every failing test, using the "_source" field, see **Changes 3** section.

----

**Issue:** https://issues.liferay.com/browse/LPS-152937 - Elasticsearch sort doesn't work with accented words
See also https://issues.liferay.com/browse/PTR-3054

This issue was previously reported in https://issues.liferay.com/browse/LPS-93341 and some work was done in spike https://issues.liferay.com/browse/LPS-94561

The idea of that spike was to use the **icu_collation_keyword** from Elasticsearch ICU Plugin, see: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-collation-keyword-field.html 

In this PR I have used the code from that spike as the starting point (see https://github.com/brandizzi/liferay-portal/pull/813 PR and this branch https://github.com/brandizzi/liferay-portal/tree/LPS-94561 from @brandizzi repository)

**Original commits from LPS-94561 spike:** https://github.com/liferay-search/liferay-portal/commit/77ed5fcf9e9a269801049390661ff7898656240c , https://github.com/liferay-search/liferay-portal/commit/352d72a2fa70a3729b7e118165eb77e0e8a051d6, and https://github.com/liferay-search/liferay-portal/commit/fbdfd8ccd12a491bcbe698d82bcb3faaa0fe32e4

I have done the following changes to this code:

**Changes 1: Tests added in BaseMultiLanguageSortTestCase** (from previous PR https://github.com/brandizzi/liferay-portal/pull/813)
   - https://github.com/liferay-search/liferay-portal/commit/9da34ea57b398aad665ea5a5276790554a354385 fixes test name to testJapanKatakana
   - https://github.com/liferay-search/liferay-portal/commit/ca619b0db81b0c3948c1b1016bba4fbb44b7c79f removes the Kanji sort test because it is not correct:
        - ICU library used by Elasticsearch doesn't support Kanji sorting, see: http://unicode.org/faq/collation.html#7
        - If you use this [ICU Collation Demo](https://icu4c-demos.unicode.org/icu-bin/collation.html), it returns different results than the expected in the removed test
        - In general, Japanese Kanji sorting seems to be a non-trivial task, read: http://www.localizingjapan.com/blog/2011/02/13/sorting-in-japanese-%E2%80%94-an-unsolved-problem/ or https://stackoverflow.com/questions/4895527/can-sorting-japanese-kanji-words-be-done-programmatically
        - It seems the author of that test (_Vagner Castro_) no longer works for Liferay, so I couldn't reach him to have more information about that test.
   - https://github.com/liferay-search/liferay-portal/commit/b0eab6b0edcc0f18de7671bc37837accc19344a5 improves the Spanish test. As a native Spanish speaker, I detected that the original test had some missing checks related to the "ñ", "ch", and vowels with accents "á", "é"... 

**Changes 2: Elasticsearch mapping changes**
     - https://github.com/liferay-search/liferay-portal/commit/ca3d0fa71e85a3d56798a37974c187172e276fd0 => We must cover both regular `*_en_US_sortable` and nested `ddmFieldArray.ddmFieldValueText_en_US_String_sortable` fields
   - https://github.com/liferay-search/liferay-portal/commit/31bce6bcd6629df3e78099e258be843f4d51b2f5 => Replicate new mappings to all the existing locales. It is not necessary to specify the country because it is optional (see elasticsearch ICU plugin code: https://github.com/elastic/elasticsearch/blob/5aa174e6d3d280438822fc03c580bd9eac9faccf/plugins/analysis-icu/src/main/java/org/elasticsearch/plugin/analysis/icu/ICUCollationKeywordFieldMapper.java#L377-L391 )
   - https://github.com/liferay-search/liferay-portal/commit/b8db5a4053e94f867b48c5970a849ed9357ce806 => Add de_AT (_Austrian German_) and fr_CA (_Canadian French_) country configurations as they have an specific collation configuration according to https://github.com/unicode-org/cldr/tree/main/common/collation

**Changes 3: Broken tests**
The Elasticsearch mapping changes break some existing tests because they compare the `_sortable `fields returned by Elasticsearch but now they are encoded in a strange way because we are using the **icu_collation_keyword** type:
```
expected:<...itle_de_DE_sortable=[entity title, localized_title_en_US=entity title, localized_title_en_US_sortable=entity title, localized_title_es_ES=entity title, localized_title_es_ES_sortable=entity title, localized_title_fi_FI=entity title, localized_title_fi_FI_sortable=entity title, localized_title_fr_FR=entity title, localized_title_fr_FR_sortable=entity title, localized_title_hu_HU=entitas neve, localized_title_hu_HU_sortable=entitas neve, localized_title_ja_JP=entity title, localized_title_ja_JP_sortable=entity title, localized_title_nl_NL=entity title, localized_title_nl_NL_sortable=entity title, localized_title_pt_BR=entity title, localized_title_pt_BR_sortable=entity title], localized_title_sv...> but was:<...itle_de_DE_sortable=[MkRQOlBaBFA6UEAyARABEAA=, localized_title_en_US=entity title, localized_title_en_US_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_es_ES=entity title, localized_title_es_ES_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_fi_FI=entity title, localized_title_fi_FI_sortable=entity title, localized_title_fr_FR=entity title, localized_title_fr_FR_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_hu_HU=entitas neve, localized_title_hu_HU_sortable=entitas neve, localized_title_ja_JP=entity title, localized_title_ja_JP_sortable=MkRQOlBaBFA6UEAyARABEAA=, localized_title_nl_NL=entity title, localized_title_nl_NL_sortable=entity title, localized_title_pt_BR=entity title, localized_title_pt_BR_sortable=MkRQOlBaBFA6UEAyARABEAA=]
```
In this example, the `entity title` text is encoded in the Elasticsearch side as `MkRQOlBaBFA6UEAyARABEAA=`
To solve this:
   - https://github.com/liferay-search/liferay-portal/commit/fd6cfe28904e208fc61418aa105a54730a187e9f commit: I am getting the information from the sources map of `searchResponse` and overwrite the value in `filteredFieldValuesMap` with the value from `sourcesMap` if it exists. **Note:** the `sourcesMap` can be empty if you don't set the fetchSource flag in the request.
   - In order to get the source we need the `searchResponse` so in https://github.com/liferay-search/liferay-portal/commit/0031230294f1f0ff967c0d9984e8df539a1584dd and https://github.com/liferay-search/liferay-portal/commit/0acf6e42a48aa50b0ebd340da276b4bb5f00a0ea I have created a new **searchOnlyOneSearchResponse** method that is similar to the existing **searchOnlyOne** but it returns a SearchResponse object instead of the Document and we use the `_searchRequestBuilderFactory` to set the fetchSource to true.
   - https://github.com/liferay-search/liferay-portal/commit/d3b0c616e1fcedbf75343a187d9ab464598ee39f commit: we have to add the SearchRequestBuilderFactory parameter to the **new IndexerFixture<>(...)** call in every test. This is necessary inside the IndexerFixture class to be able to set the fetchSource to true.
   - https://github.com/liferay-search/liferay-portal/commit/cba33e2d74526aee0d091bc09e62d243a0e7aa97 commit: Replace the usages of searchOnlyOne with searchOnlyOneSearchResponse in every test that fails after the mapping changes.
   - https://github.com/liferay-search/liferay-portal/commit/65c2c94fe29ac324c4def8345e7fe87ca4d5c827 commit: Set the fetchSource to true in every failing test that is already using the `searchResponse` object when it calls the assertFieldValues method.
   - https://github.com/liferay-search/liferay-portal/commit/90cde330a35a74791505958b08762a458a8965dc commit: The new code always expect having the priority_sortable set, so I am changing it to true by default.

**Additional notes:**
   - In the end, we are only changing the mapping configurations, so this fix won't be applied to our existing customers until they execute a full reindex
   - On the other hand, If the customer updates to a version that contains this code, they won't detect any issue if they don't want to execute the full reindex, because their installation will continue to use the old mappings
   - **Warning:** :warning: If the customer has a custom development that uses the information stored in the _sortable fields, they will have problems, as now the information will be encoded. As a workaround, they can use the information stored in the _source internal field or they can change the mappings.
   -  I have updated the breaking changes document, see https://github.com/liferay-search/liferay-portal/commit/2c6126cb7e407864208d84b2f2d61868afcfaeb3 we must include it in the release notes of the update that will include this LPS.

**About the tests added in this PR:**
   - The tests are a bit incomplete. The major problem here is we need native speakers to add more tests in every supported language.
   - I have improved the Spanish test in this commit https://github.com/liferay-search/liferay-portal/commit/fa518c23f02e8f9c688360643be234a97fb68442 but I don't have the knowledge to improve any other language
   - Perhaps we can use the ICU Collation Demo (https://icu4c-demos.unicode.org/icu-bin/collation.html) or check the ICU information from https://github.com/unicode-org/cldr/tree/main/common/collation where there is information of every supported language, for example in the [pl.xml polish definition](https://github.com/unicode-org/cldr/blob/main/common/collation/pl.xml) you can see the precedence between every letter so, for example, `Z<ź<<<Ź<ż<<<Ż` means that `Ża, Ze, Źu` is sorted to `Ze, Źu, Ża`
   - Nevertheless, the best option is to double-check with native speakers (perhaps we can reach the people from this volunteer list https://liferay.slack.com/archives/CJ1ERLHUZ/p1650977876964469 )

Let me know if you have any questions about this PR

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

Do you have any update about this pull request?

Thank you

**Comment by BryanEngler** [comment]
@jorgediaz-lr im still reviewing it, trying to understand why all of the other tests need to use the new IndexerFixture constructor

**Comment by jorgediaz-lr** [comment]
Ok no problem, let me know if you need more information or any code change.

**Comment by BryanEngler** [comment]
ive added a few commits, running tests here and will forward if results look good - https://github.com/BryanEngler/liferay-portal/pull/649

@jorgediaz-lr if you see any concerns with my commits let me know. but great job on this, thanks!

**Pull request closed without merging**
