### PR TITLE
LPS-174196 Scroll

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-174547
https://issues.liferay.com/browse/LPS-174546
https://issues.liferay.com/browse/LPS-174548

### CODE REVIEW

**Comment by gustavolimav** [comment]
Refactored based on @BryanEngler requests here: https://github.com/liferay-search/liferay-portal/pull/795

**Comment by gustavolimav** [comment]
That [branch](https://github.com/gustavolimav/liferay-portal/tree/LPS-174547_scroll_api_final_version) has a commit to test the scroll API.

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
I started looking at this, it's going to take me more time though.

**Pull request closed without merging**
