### PR TITLE
LPS-187224 portal-search-web: Update styles on configuration pages of certain search widgets

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-187224 - Update styling on configuration pages of certain Search widgets

It looks like the `cadmin` class adds admin styling with higher specificity by using these selectors `html:not(#_):not(#__)`, so our stylesheets for search widgets' configuration pages were not being applied. In order to update this, I just applied clay utilities directly on the JS component and made more use of some clay components. Also thinned out the CSS files affected.

Adding some screenshots (not too dramatic, tried to keep the appearance as before), let me know if I should make other adjustments, thanks!

Screenshots:
Screenshot 2023-06-15 at 4 51 52 PM
Screenshot 2023-06-15 at 4 52 15 PM
Screenshot 2023-06-15 at 4 59 06 PM
Screenshot 2023-06-15 at 5 07 25 PM

### CODE REVIEW

**Comment by thektan** [comment]
@oliv-yu As a heads up, I'll finish reviewing this tomorrow. I ran into portal build issues, but I wanted to see how existing styling in portal handled these add/remove buttons. 

My current thinking is that these shouldn't be primary buttons since it clashes with the "save" button and the spacing is too close.

246278971-df1415f7-035f-4445-bc40-510ab3818035

**Comment by oliv-yu** [comment]
@thektan They do look a little wonky, though I think those are handled by `Liferay.AutoFields` and is used several places? I could look into how they change up their styling, hm not sure yet.

**Review by thektan — CHANGES_REQUESTED** [review]
Thanks for cleaning up a lot of the css! Definitely will help things be more maintainable.

I would like to see styling applied to the low level search configuration add/remove buttons though. We can target those specific buttons for our configuration since we know our use case.

**Comment by oliv-yu** [comment]
Ah ha so it looks like if I try targeting those add/remove buttons with CSS, it ends up not applying because of that `.cadmin` rule for elements on the `configuration.jsp` 🤔 I suppose there's a way to change it on the JS, but it looks like auto fields is something from frontend-js-aui-web? Should I maybe file a separate ticket for that?

**Comment by thektan** [comment]
@oliv-yu You can override by adding `:not(#__):not(#___)`, but I was searching for better practices, and looks like this was a suggestion I found in [slack](https://liferay.slack.com/archives/C03CAD9EF/p1650986009227879) you could try. So something like (but adjust the actual classes your use case):

```scss
@import 'cadmin-variables';

html#{$cadmin-selector} .cadmin {
   .your-component-selector {}
}
```

**Comment by oliv-yu** [comment]
@thektan Rebased and added an extra commit to change up the styling using `html#{$cadmin-selector} .cadmin`, it's kept in `search_auto_fields.scss` since it's shared among several widgets. Let me know if that works, thanks for the helpful advice!

Preview:
Screenshot 2023-06-20 at 5 44 39 PM

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Looks great! Thanks for making the adjustments!

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Sent to BChan.
master: https://github.com/brianchandotcom/liferay-portal/pull/136838

**Pull request closed without merging**
