### PR TITLE
LPS-178539 LPS-179990: Add support for sorting on nested Object fields, don't break if sort options removed

### PR DESCRIPTION
**Pull request by peerkar**
Covers:
- https://issues.liferay.com/browse/LPS-178539
- https://issues.liferay.com/browse/LPS-179990

Functional tests covered in https://issues.liferay.com/browse/LPS-179480

### CODE REVIEW

**Comment by xbrianlee** [comment]
Manually tested following the steps in [LPS-172131](https://issues.liferay.com/browse/LPS-172131). I was able to sort they the date field of keyword object entries without issues. Tested with the bundle from https://github.com/liferay-search/liferay-portal/pull/853#issuecomment-1481671190.

**Comment by xbrianlee** [comment]
Automated test results above also look good 👍

**Comment by peerkar** [comment]
@BryanEngler coming

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
