### PR TITLE
LPD-39110 

### PR DESCRIPTION
**Pull request by oliv-yu**

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
There looks to be some error affecting several search tests on upstream, so the playwright results aren't accurate :\

**Review by thektan — APPROVED** [review]
💯

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
There is still a 404 screen on CI results, but when running the playwright tests locally, they look ok. Since this addresses an LPP with some urgency and it has already passed review, I just manually forward to BChan and we can maybe look into what's going on with CI later.

Manually forwarded to BChan: https://liferay.atlassian.net/browse/LPD-39110

**Pull request closed without merging**
