### PR TITLE
LPS-186952 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-186952

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search-solr

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by joshuacords** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
Manually forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/139370

**Pull request closed without merging**
