### PR TITLE
LPS-160556 Result ranking help text not visible

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-160556

**Screenshot With Fix**
Screen Shot 2022-09-09 at 11 26 07 AM

### CODE REVIEW

**Comment by thektan** [comment]
Test failures don't seem related.

**Review by oliv-yu — APPROVED** [review]
Looks good!! 💯

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
