### PR TITLE
[TS] LPS-191765 Missing <prefix>-<companyId>-search-tuning-rankings index after switching embedded/remote ES

### PR DESCRIPTION
**Pull request by AlmirFe**
### **LPP link:** [LPP-50233](https://liferay.atlassian.net/browse/LPP-50233)

# Context
 
After switching embedded/remote ES, the Ranking index is no longer accessible (because the index is stored inside the Elasticsearch server). Therefore, it is necessary to create a new Ranking index. This new Ranking index should be created through a background task added in the [RankingIndexCreationBundleActivator](https://github.com/liferay/liferay-portal/blob/7.4.3.89-ga89/modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/java/com/liferay/portal/search/tuning/rankings/web/internal/index/creation/activator/RankingIndexCreationBundleActivator.java) class, as you can see bellow:

```
...

		if (_singleIndexToMultipleIndexImporter.needImport()) {
			_addBackgroundTask();
		}
	}

	private void _addBackgroundTask() {
		try {
			_backgroundTaskManager.addBackgroundTask(
				UserConstants.USER_ID_DEFAULT, CompanyConstants.SYSTEM,
				"createRankingIndex-" + _portalUUID.generate(),
				RankingIndexCreationBackgroundTaskExecutor.class.getName(),
				new HashMap<>(), new ServiceContext());
		}
		catch (PortalException portalException) {
			_log.error(
				"Unable to schedule the job for RankingIndexRename",
				portalException);
		}
	}
...
```
 
However this background task is never executed because the "liferay/background_task" destination is not configured yet when the [sendMessage](https://github.com/liferay/liferay-portal/blob/e7b4deb6b873d5f964882141e352d0b9601138eb/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/DefaultMessageBus.java#L66C1-L116C3) function is called, as you can see below:

```
...

Destination destination = _destinations.get(destinationName);

		if (destination == null) {
			if (_log.isWarnEnabled()) {
				_log.warn(
					"Destination " + destinationName + " is not configured");
			}

			return;
		}
...
```

After that the liferay-20096-search-tuning-rankings index is not created and the Result Rankings application is not available on the portal.

# Proposed solution

The proposed solution consists of changing the [RankingIndexCreationBundleActivator](https://github.com/liferay/liferay-portal/blob/7.4.3.89-ga89/modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/java/com/liferay/portal/search/tuning/rankings/web/internal/index/creation/activator/RankingIndexCreationBundleActivator.java) class so that a new ranking index is created directly without the need to add a background task, as you can see bellow:

```
if (_singleIndexToMultipleIndexImporter.needImport()) {
			List<Company> companies = _companyLocalService.getCompanies();

			for (Company company : companies) {
				RankingIndexName rankingIndexName =
					_rankingIndexNameBuilder.getRankingIndexName(
						company.getCompanyId());

				if (_rankingIndexReader.isExists(rankingIndexName)) {
					continue;
				}

				_rankingIndexCreator.create(rankingIndexName);
			}
		}
```

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
