### PR TITLE
LPS-174768: Do not run text embedding model document contributors with SOLR

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-174768

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:reevaluate:1277401_6799

**Comment by peerkar** [comment]
ci:reevaluate:1287401_5701

**Comment by lipusz** [comment]
@BryanEngler added an API for this: `com.liferay.portal.search.capabilities.SearchCapabilities.isSearchExperiencesSupported()`

**Comment by lipusz** [comment]
Maybe we should use that

**Comment by peerkar** [comment]
@lipusz not sure. SXP is not strictly required to take advantage of embeddings. But, providers are in SXP so com.liferay.portal.search.capabilities.SearchCapabilities.isSearchExperiencesSupported() is kind of tautology, because those contributors only exists in SXP.

I would stick with this approach.

**Comment by lipusz** [comment]
👍 Makes sense.

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
Forwarding here https://github.com/brianchandotcom/liferay-portal/pull/130001

**Pull request closed without merging**
