### PR TITLE
LPS-126703: Put filter clauses in root 

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-126703

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:stable

**Comment by suilin** [comment]
Hi @peerkar, I found there are two issues related to the changes, could you look at it? Thanks!

1. Fail to search Blueprints Preview after upgrading, here is the detailed console log https://gist.github.com/suilin/dcb30cef57842029c58e4946e1946443

2. Integration test: SXPBlueprintSearchRequestContributorFederatedTest 
```
com.liferay.search.experiences.internal.blueprint.search.spi.searcher.test.SXPBlueprintSearchRequestContributorFederatedTest > test FAILED
     [exec]     java.lang.RuntimeException: com.liferay.portal.kernel.search.SearchException: java.lang.NullPointerException
     [exec]     	at com.liferay.portal.search.internal.permission.SearchResultPermissionFilterFactoryImpl._search(SearchResultPermissionFilterFactoryImpl.java:92)
     [exec]     	at com.liferay.portal.search.internal.permission.SearchResultPermissionFilterFactoryImpl.lambda$create$0(SearchResultPermissionFilterFactoryImpl.java:57)
     [exec]     	at com.liferay.portal.search.internal.permission.DefaultSearchResultPermissionFilter._getHits(DefaultSearchResultPermissionFilter.java:193)
     [exec]     	at com.liferay.portal.search.internal.permission.DefaultSearchResultPermissionFilter.search(DefaultSearchResultPermissionFilter.java:104)
     [exec]     	at com.liferay.portal.kernel.search.BaseIndexer._search(BaseIndexer.java:1587)
     [exec]     	at com.liferay.portal.kernel.search.BaseIndexer.search(BaseIndexer.java:563)
     [exec]     	at com.liferay.portal.search.internal.searcher.SearcherImpl.search(SearcherImpl.java:86)
     [exec]     	at com.liferay.portal.search.internal.searcher.SearcherImpl._multiIndexerSearch(SearcherImpl.java:206)
     [exec]     	at com.liferay.portal.search.internal.searcher.SearcherImpl._indexerSearch(SearcherImpl.java:168)
     [exec]     	at com.liferay.portal.search.internal.searcher.SearcherImpl._smartSearch(SearcherImpl.java:253)
     [exec]     	at com.liferay.portal.search.internal.searcher.SearcherImpl.doSearch(SearcherImpl.java:62)
     [exec]     	at com.liferay.portal.search.internal.searcher.SearcherImpl.search(SearcherImpl.java:48)
```
cc @xbrianlee @joshchong

**Comment by peerkar** [comment]
@suilin I'll take a look. Thanks!

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:stable

**Comment by peerkar** [comment]
ci:reevaluate:1347401_2765

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
