### PR TITLE
LPS-200436 portal-search: add debugging timers and counts to SlidingW…

### PR DESCRIPTION
**Pull request by joshuacords**
…indowSearcher

https://liferay.atlassian.net/browse/LPS-200436

**Author:** @joshuacords 

Output when enabled looks like this:

> 2023-10-30 23:04:27.137 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:370] Starting sliding window searches
2023-10-30 23:04:27.145 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:399] Count: 20 AmplificationFactor: 1.0 AmplifiedCount: 20
2023-10-30 23:04:27.156 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:399] Count: 20 AmplificationFactor: 1.5 AmplifiedCount: 30
2023-10-30 23:04:27.163 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:399] Count: 20 AmplificationFactor: 1.5 AmplifiedCount: 30
2023-10-30 23:04:27.173 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:399] Count: 20 AmplificationFactor: 1.5 AmplifiedCount: 30
2023-10-30 23:04:27.179 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:399] Count: 11 AmplificationFactor: 1.5 AmplifiedCount: 17
2023-10-30 23:04:27.186 DEBUG [http-nio-8080-exec-4][DefaultSearchResultPermissionFilter:458] 5 sliding window searches took 50 ms, Hit filtering took 4 ms

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Review by AlmirFe — APPROVED** [review]
Looks good to me!

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:reevaluate:1327401_2640

**Comment by joshuacords** [comment]
ci:forward:force

**Comment by joshuacords** [comment]
ci:forward:force

**Pull request closed without merging**
