### PR TITLE
LPS-128302 Bump Sidecar's Elasticsearch version from 7.9.0 to 7.10.0 | master

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-128302
https://issues.liferay.com/browse/LRQA-64727

@arboliveira @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi @joshchong, have you run our test suite on these changes yet? If not, go ahead an trigger them.

**Comment by joshuacords** [comment]
Hi @joshchong, almost everything looks good. The one thing that seems to be missing is an update to build.gradle (see https://github.com/brianchandotcom/liferay-portal/pull/93026/commits/674b6ea3364cf2684759d6519f7a8be7a45f05b1#diff-a1ca047b18d3947d687f58032786e6ffb6ac0d15e6608bf26e91075a5159fc31R9)

I tried this and we do get compile errors. It'll probably be up to me to update the code so that it does compile.

**Comment by joshchong** [comment]
@joshuacords oh do we still need to make updates to build.gradle if we keep the client version on 7.9? I was assuming we were going to bump only the sidecar version to 7.10.

**Comment by joshchong** [comment]
@joshuacords oh sorry, just saw your first message. Yeah I ran the search suites against the changes and everything looked good. I linked the analysis tickets to this ticket.

**Comment by joshuacords** [comment]
@joshchong, don't know if we want to do it now but the changes are ready to go here: https://github.com/liferay-search/liferay-portal/pull/91

@arboliveira thoughts?

**Pull request closed without merging**
