### PR TITLE
LPS-153813 LPS-16638 [FE] Replace "suffix" with "name" property in frontend

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-166388

### CODE REVIEW

**Review by oliv-yu — APPROVED** [review]
Looks good! I don't think there's anything I'd change

**Comment by oliv-yu** [comment]
ci:stop

**Comment by thektan** [comment]
ci:forward

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/125238

**Pull request closed without merging**
