### PR TITLE
LPD-20841 portal-search-web: For a11y, remove autocomplete value for hidden inputs

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-20841 - Remove autocomplete attribute from hidden fields for accessibility

Simple change to remove `autocomplete=off` for hidden inputs in search widgets. A customer had recently pointed out that it goes against a11y practices.

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:report:2557491431

**Review by thektan — APPROVED** [review]
This looks good. 👍

I only want to leave a note about how this originally might have been a fix for an old bug that doesn't seem present anymore. I couldn't find the origin of it besides a related online post:
> Looking back at the git history, autocomplete=off was added back in 2018 by [#2596597: [regression] Soft reload does not clean up user inputs like in D7 (Firefox only)](https://www.drupal.org/project/drupal/issues/2596597) to fix a bug with Firefox browsers.

https://www.drupal.org/project/drupal/issues/3320467

Regardless, it seems like `"on"` and `"off"` values for the `autocomplete` attribute aren't allowed anymore so these should be removed. 

MDN states:
> If including the autocomplete attribute on [hidden](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/hidden) input elements (<input type="hidden">), its value must be an ordered list of space-separated tokens; the on and off keywords are not allowed.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by oliv-yu** [comment]
@thektan Thanks for the info, I added it to the ticket as well! The tests look good so I'll forward this for now, and will keep this in mind if there's any issues that come up. 👍

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
