### PR TITLE
LPD-17984 portal-search-web: Update id for search results paginator

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-17372 - Incorrect number of pages in the paginated results in the SearchResultsPortlet
https://liferay.atlassian.net/browse/LPD-17984 (subtask) - Update id in search result's search-paginator

Simple update to remove the appended suffix on the `id` within search result's paginator. This doesn't fix the bug, but this will be helpful for later changes to the `DynamicInlineScroll` component.

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:report:2539488358

**Comment by oliv-yu** [comment]
ci:report:2539478752

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:report:2539808335

**Comment by oliv-yu** [comment]
@thektan hi, this is a small change after @antonio-ortega's [comment](https://liferay.atlassian.net/browse/LPP-52649?focusedCommentId=2579388). Let me know if this sounds good? If so, I think it'd be ok to forward!

**Comment by thektan** [comment]
@oliv-yu Since this doesn't completely fix the bug and changes are needed for `DynamicInlineScroll` still, could you commit this under a subtask in the ticket and create a separate subtask for the `DynamicInlineScroll` updates? 

This can be forwarded otherwise.

**Comment by oliv-yu** [comment]
@thektan Ok! Subtask for the DynamicScroll is under https://liferay.atlassian.net/browse/LPD-17985, and updated the details on this one under https://liferay.atlassian.net/browse/LPD-17984.

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
