### PR TITLE
[TS] LPS-191765 Missing <prefix>-<companyId>-search-tuning-rankings index after switching embedded/remote ES

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/141421

**Pull request closed without merging**
