### PR TITLE
LPD-41532 Change SXPBlueprintUpgradeProcess class to use AutoBatchPreparedStatementUtil

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-41532

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
LGTM!

**Pull request closed without merging**
