### PR TITLE
LPS-189337 Add /search endpoint description to indicate feature status. (Dev)

### PR DESCRIPTION
**Pull request by lipusz**
https://liferay.atlassian.net/browse/LPS-189337

Add description (we had before the recent changes) back.

.
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
ci:reevaluate:1277401_8977

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:forward:force

**Comment by danielCamara02** [comment]
ci:forward:force

**Pull request closed without merging**
