### PR TITLE
LPS-197195 [FE] Connect sites MVCResourceCommand with UI

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-126745 - Allow to scope Result Rankings to a specific site so that it will be applied on matching Search Bar searches with "This Site" as scope
https://liferay.atlassian.net/browse/LPS-197195 - (Subtask) Connect sites MVCResourceCommand with UI

Rebased on master and includes changes from https://github.com/liferay-search/liferay-portal/pull/1084

These are the frontend changes to supplement https://liferay.atlassian.net/browse/LPS-196342, where fetchSitesUrl was created. Now the sites are available for selection on the dropdown menu when creating a result ranking, and the name of the site should be available next to the scope (if selected).

Screenshots:
Screenshot 2023-09-28 at 1 05 38 PM
Screenshot 2023-09-28 at 1 05 53 PM
Screenshot 2023-09-28 at 1 07 53 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
resend [here](https://github.com/liferay-search/liferay-portal/pull/1092) with bchan [follow up request](https://github.com/brianchandotcom/liferay-portal/pull/141510#issuecomment-1740179309)

**Pull request closed without merging**
