### PR TITLE
LPS-184523 Search with a Blueprint by its External Reference Code (ERC)

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPS-184523
See here: https://github.com/brianchandotcom/liferay-portal/pull/137188#issuecomment-1615925468

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
continuing here https://github.com/liferay-search/liferay-portal/pull/1003

**Pull request closed without merging**
