### PR TITLE
LPS-153251 search-experiences-web: Remove feature flag of json autocompletion (blueprints configuration)

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-153251 - Remove Feature Flag and enable JSON auto-completion (Blueprints Configuration)

Removing `featureFlagLps143720` so that [LPS-143720](https://issues.liferay.com/browse/LPS-143720) is no longer behind a feature flag. Looked for all instances of it, but me know if there's anything else to take out!

### CODE REVIEW

**Review by thektan — APPROVED** [review]
LGTM! 💯

**Comment by thektan** [comment]
Unique search failure is already reported https://issues.liferay.com/browse/LPS-154217, so I'll be forwarding this.

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
