### PR TITLE
[ee-ts] LPS-135028 Add and implement missing setter for statingAware in ModelSearchDefinition

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-135028

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
:white_check_mark: Failures are known and not caused by these changes.

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hello @arboliveira, 

Let me know if you think it's ready to be forwarded.

Thanks,
Tibor

**Review by arboliveira — APPROVED** [review]

**Comment by arboliveira** [comment]
ci:forward

**Pull request closed without merging**
