### PR TITLE
[TS] LPS-124244

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-124244

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello @jcampoy 

Can you please fixup your SF commit into your original commit? Usually we don't send changes with self-SF commits. Thanks!

**Comment by lipusz** [comment]
You could have just force-pushed your changes, but it's also okay if you send a new PR. :wink:

**Comment by jcampoy** [comment]
https://github.com/liferay-search/liferay-portal/pull/134

**Pull request closed without merging**
