### PR TITLE
LPS-128302 & LPS-128307 Bumping ES to 7.10

### PR DESCRIPTION
**Pull request by joshuacords**
Sidecar bump here: https://github.com/liferay-search/liferay-portal/pull/90

My commit bumps the client for https://issues.liferay.com/browse/LPS-128307

Authors: @joshchong @joshuacords 
Reviewer: @joshuacords

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:search-jdk11

**Comment by joshchong** [comment]
ci:test:workflow

**Comment by joshchong** [comment]
ci:test:commerce

**Comment by joshuacords** [comment]
ci:test:search

**Comment by suilin** [comment]
ci:test:bundle

**Comment by joshuacords** [comment]
Continued on #95

**Pull request closed without merging**
