### PR TITLE
LPS-174196 SearchAfter

### PR DESCRIPTION
**Pull request by gustavolimav**
Forwarded from: https://github.com/liferay-search/liferay-portal/pull/909

https://issues.liferay.com/browse/LPS-181755
https://issues.liferay.com/browse/LPS-181947
https://issues.liferay.com/browse/LPS-183090
https://issues.liferay.com/browse/LPS-183159

Author: @gustavolimav

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
test

**Comment by gustavolimav** [comment]
test

**Comment by gustavolimav** [comment]
${i}

**Comment by gustavolimav** [comment]
${i}

**Comment by gustavolimav** [comment]
a

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Review by peerkar — APPROVED** [review]

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
