### PR TITLE
LPS-177112 Remove unused feature added by task LPS-94161

### PR DESCRIPTION
**Pull request by W2jx**
https://issues.liferay.com/browse/LPS-180707

Hi @lipusz , following our discussion https://liferay.slack.com/archives/CKY6GP7BL/p1679506932536969, I reomved some classes, could you please help me to check that it is correct? About adding it to the Breaking Changes markdown, I'm currently just setting this [ticket](https://issues.liferay.com/browse/LPS-177112) as a Breaking Change, is there anything else I need to do? Thanks in advance.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hello @W2jx ,

It also looks safe to remove [ASMUtil.java](https://github.com/brianchandotcom/liferay-portal/pull/71861/files#diff-75fe2e0a4fc70a153de60196190e6d37ddea3d83d35618be427c01ae3670ba06), [Activator.java](https://github.com/brianchandotcom/liferay-portal/pull/71861/files#diff-0e6cadcb20147be55d2bfbd3fb6f8fcf92116392cb6274b726da4af7f0be0637), [ComponentPropertyMapUtil.java](https://github.com/brianchandotcom/liferay-portal/pull/71861/files#diff-df200d0207d1cb1af74d20eaa0e43393ab84cadb409dfc3dec7b4147ce8ef608), [Microcontainer.java](https://github.com/brianchandotcom/liferay-portal/pull/71861/files#diff-d09a2c68e196e06cf957532092636889445e8f502993b4b4fe715f31e2309b5d), [MicrocontainerImpl.java](https://github.com/brianchandotcom/liferay-portal/pull/71861/files#diff-5fd1afb0a52f96b832c74d148f3ca87d1833ee82c58528952f2870bcd3828e24)

**Comment by W2jx** [comment]
Thank you @joshuacords , I will resend it.

**Comment by W2jx** [comment]
ci:test:search

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Hi @joshuacords , I have resent it.

**Comment by joshuacords** [comment]
Hi @W2jx,
In the future it's much easier to review changes when a separate commit is used instead of editing the original commit. Were there any changes besides the removal of those 5 classes?

**Comment by joshuacords** [comment]
Hi @W2jx,

There's semantic versioning errors that need correcting:
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-search/portal-search-spi] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 8.0.0
```
and
```
com.liferay.portal.search.elasticsearch7.spi.index MAJOR      1.0.0      1.0.0      2.0.0      
VERSION INCREASE REQUIRED  -   interface  com.liferay.portal.search.elasticsearch7.spi.index.IndexRegistrar   -   access     abstract   -   method     register(com.liferay.portal.search.elasticsearch7.spi.index.helper.IndexRegistrarHelper)    -   access     abstract    -   return     void [Baseline Warning] Bundle Version Change Recommended: 7.0.0

**Comment by lipusz** [comment]
Please, resend. thanks!

**Pull request closed without merging**
