### PR TITLE
LPD-25633 Performance issue with batch import

### PR DESCRIPTION
**Pull request by gustavolimav**
[LPD-25633](https://liferay.atlassian.net/browse/LPD-25633)

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:54373087

**Pull request closed without merging**
