### PR TITLE
LPS-144066 Add aria-label to search bar

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-144066

The search bar does not contain any aria-label, aria-labelledby, or hidden attributes that will help for accessibility. I added `aria-label` with the word Search.
Let me know if there is any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Looks good, thanks @fortunatomaldonado!

**Comment by thektan** [comment]
ci:forward

**Comment by lipusz** [comment]
ci:forward

**Pull request closed without merging**
