### PR TITLE
LPD-32565

### PR DESCRIPTION
**Pull request by gustavolimav**
[LPD-32565](https://liferay.atlassian.net/browse/LPD-32565)

same solution as https://liferay.atlassian.net/browse/LPD-2141

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search-es8-remote

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @gustavolimav,

The code is good, but I think you have the wrong LPD linked in the commit message :sweat_smile: - so update that and then forward. (Run only the necessary tests for forwarding after the force-push)

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
