### PR TITLE
LPS-200851 Avoid NullPointerException during upgrade process

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-200851](https://liferay.atlassian.net/browse/LPS-200851)

Although we're not sure exactly how to reproduce the `null` largeValue in the PortletPreferenceValue table, it seems to be possible on a clean instance because we had multiple customers encounter this same `NullPointerException` when they tried to upgrade. I think it's something in low-level Hibernate code that causes the `null` largeValue (rather than a blank one) to be set.

### CODE REVIEW

**Review by gustavolimav — APPROVED** [review]
Hey @mbowerman, I’ve looked over the code and it looks good 👍 Thanks for the fix!

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward-force

**Comment by felipelorenz** [comment]
ci:forward:force

**Pull request closed without merging**
