### PR TITLE
[TS] LPS-123817 Allow proxy configuration in ES client

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
https://issues.liferay.com/browse/LPS-123817

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hello, @marianoalvarosaiz! It took some time but we are working on it. Here are [some comments on the state of this pull request](https://issues.liferay.com/browse/LPS-123817?focusedCommentId=2336761&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2336761). Also, we have this new version with so far some minor source formatting: #62  I believe we will get it fixed soon.

**Comment by brandizzi** [comment]
I am closing this pull request since we are working on these changes in https://github.com/liferay-search/liferay-portal/pull/62 now.

**Pull request closed without merging**
