### PR TITLE
LPS-195458: A generic date facet

### PR DESCRIPTION
**Pull request by peerkar**
- Story: https://liferay.atlassian.net/browse/LPS-195458
- Covered subtasks:
  - https://liferay.atlassian.net/browse/LPS-195459
  - https://liferay.atlassian.net/browse/LPS-195460
  - https://liferay.atlassian.net/browse/LPS-195895

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
@BryanEngler  There is a regression with Modified facet date picker. Asked @oliv-yu to take a look at that

**Comment by oliv-yu** [comment]
Hi @peerkar, I was trying to deploy this to see what may be causing the regression, however after adding the feature flag (`feature.flag.LPS-153839=true`) and restarting portal, I'm not seeing the Date Facet in the list of widgets. Was wondering if I was missing a particular step? 😅 

I also encountered this error, not sure if related:

> 2023-09-22 23:25:48.234 ERROR [http-nio-8080-exec-10][AdvancedPermissionChecker:1276] null
com.liferay.portal.kernel.exception.NoSuchResourceActionException: com_liferay_portal_search_web_date_facet_portlet_DateFacetPortlet#ADD_PORTLET_DISPLAY_TEMPLATE
	at com.liferay.portal.service.impl.ResourceActionLocalServiceImpl.getResourceAction(ResourceActionLocalServiceImpl.java:324) ~[portal-impl.jar:?]
	at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
@oliv-yu can you please now try again

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
@peerkar It looks like I'm able to see the Date Facet now (I'm using createDate)! Did you still encounter issues with using it alongside modified date? I wasn't sure if I saw that happen.

Screenshots:
 
(Filtering in the past as of 9/29)
Screenshot 2023-09-29 at 4 10 50 PM

(Filtering in current week)
Screenshot 2023-09-29 at 4 12 00 PM

**Comment by BryanEngler** [comment]
ci:test:search:norebase

**Comment by BryanEngler** [comment]
continuing with testing here https://github.com/liferay-search/liferay-portal/pull/1138

**Pull request closed without merging**
