### PR TITLE
LPS-135858 Do not close company index when synonyms are empty

### PR DESCRIPTION
**Pull request by yuhai**
https://issues.liferay.com/browse/LPS-135858

Thanks, @lipusz

cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
thanks guys, forwarding from here https://github.com/BryanEngler/liferay-portal/pull/599

**Pull request closed without merging**
