### PR TITLE
LPS-188150 portal-search-web: Unescape search result content

### PR DESCRIPTION
**Pull request by oliv-yu**
Continued from https://github.com/liferay-search/liferay-portal/pull/999

https://liferay.atlassian.net/browse/LPS-188150

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@oliv-yu @ZakiMiklos @lipusz The changes in this PR introduces a major XSS regression.

Steps to reproduce:
1. Create any asset with content `<script>alert(123);</script>`
2. Search for the asset

:x: The alert `123` appears when the search is executed and user is taken to the search page. I tried this with message boards threads, web content articles, and blogs and it happened for all of them. Didn't try any other assets tho.

**Comment by oliv-yu** [comment]
@ZakiMiklos To avoid XSS regression, it seems like we shouldn't be trying to unescape all content and would want to look into how the content for this particular case is being generated, it might even be outside search 🤔

**Comment by ZakiMiklos** [comment]
Hello @oliv-yu, @joshchong.

I couldn't replacate it in the current current patch.  With same and  some new asset too. Some like the blog arcicles not even  shown in the search preview. Can you show me  more detailed reproduction   steps?

**Comment by oliv-yu** [comment]
@ZakiMiklos Attached a GIF to show the steps, I just created a web content article with that content `<script>alert(123);</script>` and searched for it. The GIF doesn't capture the alert so enclosing a screenshot.

https://github.com/liferay-search/liferay-portal/assets/14063502/0ad14234-a65b-44c4-9bde-67132d92e5a0

Screenshot 2023-07-24 at 9 56 26 AM

**Pull request closed without merging**
