### PR TITLE
LPS-166197: Backend support for sentence transformer health check / configuration validation

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-166190

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:stop

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
looks good to me, just 2 notes:
1- not critical, but the commit messages dont follow the template we are trying to standardize
2- potential conflict with this line on another pr that i was going to try to forward to bchan today if possible:  https://github.com/BryanEngler/liferay-portal/pull/705/commits/b622ba879fc08fb144cd7978b7f53d8f591d6114#diff-27b0b8a2e181a4f449a608953f4a5385153cc22b98e77d560950bbf2db983472R541

**Comment by xbrianlee** [comment]
The only test failure from relevant is from [modules-integration-mysql57-jdk8/0/2](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/289845//consoleText)
{code}     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-rest-test/src/testIntegration/java/com/liferay/search/experiences/rest/resource/v1_0/test/SentenceTransformerResourceTest.java:28: error: cannot find symbol
     [exec] 	extends BaseSentenceTransformerResourceTestCase {
     [exec] 	        ^
     [exec]   symbol: class BaseSentenceTransformerResourceTestCase{code}

`ci:test:search` is still finishing up. It was sitting in queue most of today due to the CI backlog. I can analyze the results tomorrow morning.

**Comment by peerkar** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
looks good to me, can be forwarded once tests pass

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
ci:forward

**Pull request closed without merging**
