### PR TITLE
LPS-146997 LPS-197203 Update Duplicate detection

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-197203

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
if CI is good here, forward the branch at https://github.com/liferay-search/liferay-portal/pull/1091

**Pull request closed without merging**
