### PR TITLE
LPS-161461 Associate the log entries of reindex spell-check actions with the Virtual Instance (aka. Company) they belong to/LPS-163666

### PR DESCRIPTION
**Pull request by wcao20170619**
https://issues.liferay.com/browse/LPS-161461

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:forward

**Pull request closed without merging**
