### PR TITLE
LPS-170715 Remove the class SettingsContributor and its only impl UnicastSettingsContributor

### PR DESCRIPTION
**Pull request by W2jx**
https://issues.liferay.com/browse/LPS-170715

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:search

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Review by peerkar — APPROVED** [review]

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:forward - Tests look good to me :+1:

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Pull request closed without merging**
