### PR TITLE
LPS-161668 + LPS- 174975 Removal of Document Types (Road to ES 8.x Compatibility)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-174975

**Testing only, do not merge.**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search-remote

**Comment by lipusz** [comment]
ci:help

**Comment by lipusz** [comment]
ci:test:commerce

**Comment by lipusz** [comment]
ci:test:commerce-es7-remote

**Comment by lipusz** [comment]
ci:test:commerce-functional

**Comment by lipusz** [comment]
ci:test:workflow-metrics

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:commerce

**Comment by xbrianlee** [comment]
ci:test:commerce-es7-remote

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search-remote

**Comment by xbrianlee** [comment]
ci:test:workflow-es7-remote

**Comment by xbrianlee** [comment]
ci:test:workflow-metrics

**Comment by xbrianlee** [comment]
ci:test:workflow

**Comment by xbrianlee** [comment]
ci:test:search-environments

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Test results noted [here](https://issues.liferay.com/browse/LPS-175894?focusedCommentId=2858477&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2858477)

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
Test analysis finished. Results recorded [here](https://github.com/liferay-search/liferay-portal/pull/791).

**Pull request closed without merging**
