### PR TITLE
LPD-2835 ElasticsearchStatusException occurs when there are more than 65536 inactive groups & LPD-23550 Create test to ensure that an ElasticsearchStatusException will not be thrown even if the number of terms exceeded the allowed maximum

### PR DESCRIPTION
**Pull request by AlmirFe**
### This PR contains the changes asked here: https://github.com/brianchandotcom/liferay-portal/pull/149498#issuecomment-2069431558

https://liferay.atlassian.net/browse/LPD-2835

https://liferay.atlassian.net/browse/LPD-23550

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
Hey @AlmirFe, can you rename [e093978](https://github.com/liferay-search/liferay-portal/pull/1315/commits/e093978a37c1ba2702fd8429c8b2a889e23a452c) with a descriptive name?

**Review by gustavolimav — CHANGES_REQUESTED** [review]

**Comment by gustavolimav** [comment]
Other than that changes looks good, lets run CI so we can make sure everything is working as expected.

**Comment by gustavolimav** [comment]
ci:stop

**Pull request closed without merging**
