### PR TITLE
LPS-185640 Search After Null Pointer with 1000s

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-185640

The problem was that the Elasticsearch API was rounding 1000s to 16.6m and the PIT does not accept fractional numbers.

The solution was to change the default value of the PIT keep alive time to 60 and make the PIT only accept numbers from 1 to 60 seconds.

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi @gustavolimav,

I noticed we can set the config min and max, see [AntivirusAsyncConfiguration](https://github.com/liferay/liferay-portal/blob/7d9e8ffbfa799c954d47b691891e5cafe73ac325/modules/dxp/apps/antivirus/antivirus-async-store/src/main/java/com/liferay/antivirus/async/store/configuration/AntivirusAsyncConfiguration.java#L44-L48). This should remove the need of the validation code, but test the behavior of setting out of bound numbers and of creating a config with out of bounds numbers. (For the config, you can export the configuration from the top right, edit the values, and place in the osgi/configs folder during a portal restart.)

Also notice their [Language key that uses the verbiage (between 1 and _60_)](https://github.com/liferay/liferay-portal/blob/12f0fdbbf5914a49e24ee63d87a222416ab32978/modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties#L14130) which is shorter.

**Comment by gustavolimav** [comment]
Hi, @joshuacords tested it, and it doesn't work as expected.

image

**Comment by gustavolimav** [comment]
@Meta.AD(
		deflt = "60", description = "point-in-time-keep-alive-seconds-help",
		max = "60", min = "1", name = "point-in-time-keep-alive-seconds",
		required = false
	)
	public int pointInTimeKeepAliveSeconds();

**Comment by joshuacords** [comment]
What does the max/min actually do then?

**Comment by gustavolimav** [comment]
I don't know but for sure it is not working as we expected

**Pull request closed without merging**
