### PR TITLE
 [TS] LPS-131302 Add showExtraInfo parameter for searched documents (reviewed)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-131302

Removed the original and the revert commits from https://github.com/liferay-search/liferay-portal/pull/125, keeping the final commit only.

/cc @noornajj @BryanEngler

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@noornajj Can I ask you to test the changes? If it works on your side as well, just type `ci:forward` on this pull request. Thank you!

**Comment by noornajj** [comment]
I have tested the changes and everything is working as expected.

**Comment by noornajj** [comment]
ci:forward

**Pull request closed without merging**
