### PR TITLE
SXP | LPS-142956 search-experiences: Include Search Experiences in DXP 7.4 U5

### PR DESCRIPTION
**Pull request by lipusz**
Depends on https://github.com/brianchandotcom/liferay-portal/pull/112308 (should be merged earlier or at least make sure it gets merged in time to be included in the release cut).

https://issues.liferay.com/browse/LPS-142956

https://issues.liferay.com/browse/LRQA-72510 should be applied on top of it before forwarding to Brian. @liferay/qa-search

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by joshchong** [comment]
@lipusz from the SF result it looks like search-experiences needs to be added to build.properties as well.

**Comment by lipusz** [comment]
Thanks @joshchong , will do! :+1:

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@lipusz merged.

**Pull request closed without merging**
