### PR TITLE
LPS-195831 Update Elasticsearch 7 to 7.17.14 (Client & Sidecar)

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
@BryanEngler The issue I encountered with the incorrect client and sidecar versions was fixed by the extra commits in this PR
image

cc/ @AlmirFe

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Test results above look good 👍

**Comment by xbrianlee** [comment]
Manually forwarded
https://github.com/brianchandotcom/liferay-portal/pull/142832

**Pull request closed without merging**
