### PR TITLE
LPD-15197 revert code

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-15197

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
@felipelorenz hi! just letting you know I added your commits to https://github.com/liferay-search/liferay-portal/pull/1239 since they're related, and I let eudaldo know about it haha

**Comment by felipelorenz** [comment]
> @felipelorenz hi! just letting you know I added your commits to #1239 since they're related, and I let eudaldo know about it haha

Perfect! Thanks @oliv-yu
I will closed this PR.

**Pull request closed without merging**
