### PR TITLE
LPS-181295: Remove the Category Facet Field Configuration

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-181295

### CODE REVIEW

**Comment by peerkar** [comment]
ci:stop:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@peerkar it looks good to me.

did we run ci:test:search?

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
Sending directly here https://github.com/brianchandotcom/liferay-portal/pull/145303

**Pull request closed without merging**
