### PR TITLE
LPD-1961 portal-search-opensearch2-impl: Fix Incorrect usage of NooHostnameVerifier.INSTANCE for SSL-Enabled Connections

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-1961

DefaultHostnameVerifier performs a strict check according to RFC 2818. The hostname must match any of the alternative names specified by the certificate, or in case no alternative names are given, the most specific Common Name (CN) of the certificate subject. A wildcard can occur in the CN, and in any of the subject-alts

On the other hand, NoopHostnameVerifier essentially turns hostname verification off. It accepts any SSL session as valid and matching the target host, regardless of the hostname in the certificate

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search-opensearch

**Comment by lipusz** [comment]
@gustavolimav Could you check if the same problem also occurs in the Elasticsearch connector?

**Comment by gustavolimav** [comment]
> @gustavolimav Could you check if the same problem also occurs in the Elasticsearch connector?

After the lunch I can take a look

**Comment by gustavolimav** [comment]
@lipusz We don't set this property in Elasticsearch connector, it makes me think that maybe we must not set this value in Opensearch too. If we don't set it, it will be by default: `new DefaultHostnameVerifier(PublicSuffixMatcherLoader.getDefault());`

**Comment by gustavolimav** [comment]
Hey @peerkar, do you remeber why did you set this value to hostnameVerifier?

**Comment by gustavolimav** [comment]
ci:report:2530102845

**Comment by peerkar** [comment]
> Hey @peerkar, do you remember why did you set this value to hostnameVerifier?

Yeah, the reason was what you found out already:

> @lipusz We don't set this property in Elasticsearch connector

Maybe the reason with ES was being able to use self-signed certs, don't know, but if the verification is changed, maybe good to check whether it could cause any issue in LXC, if people can/want to use SSL there.

**Comment by gustavolimav** [comment]
@peerkar how can I test whether it could cause any issue in LXC or who can I ask about it?

**Comment by peerkar** [comment]
I think @lipusz said yesterday that LXC doesn't let to use SSL connections for search engine at all, so this shouldn't be a problem.

**Comment by gustavolimav** [comment]
ci:test:search-opensearch

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/146773

**Pull request closed without merging**
