### PR TITLE
LPS-174888 ComparisonFailure in AddressLocalServiceTest

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-174888](https://issues.liferay.com/browse/LPS-174888).

@BryanEngler this applies your suggestion from our Slack conversation.

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:search

**Comment by drewbrokke** [comment]
@BryanEngler any update on this one?

**Comment by brunofalc** [comment]
Hey @drewbrokke we'll close this PR, since it doesn't fix the issue.

**Comment by brunofalc** [comment]
ci:close

**Pull request closed without merging**
