### PR TITLE
LPS-159041

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-159041

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:stable

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hopefully the test will work today

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
