### PR TITLE
LPS-149126 search-experiences-test: Add test converage to Boost Conte…

### PR DESCRIPTION
**Pull request by gustavolimav**
…nts in a category element

https://issues.liferay.com/browse/LPS-149126

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Passed Review

**Comment by joshuacords** [comment]
Combine with other Blueprints Element tests before forwarding.

**Pull request closed without merging**
