### PR TITLE
LPS-172278 search-experiences-web: Show titles and descriptions if en-us locale is not enabled in the instance

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-172278 SXPElement titles and descriptions not visible in Blueprint editing view if en-us locale not enabled in the instance

Some dev notes:
- To address the lack of titles/descriptions in the sxp element without en-US, the localized `title` and `description` will be utilized for the sxpElement, in addition to `title_i18n` and `description_i18n` that's already being saved. Function `getLocalizedText` has been updated to `getSXPElementTitleAndDescription` to take them into account and return the desired title and description.
- Elements and blueprints's titles and descriptions rely on object form (there is even a language selector provided for them), and it's a bad idea to remove all available languages in the instance settings that would have translations. That's why it's possible for the title to show blank on the header. Hopefully with https://issues.liferay.com/browse/LPS-147329 we can work localizing titles with a language key instead.
- Added the default header to fetch calls, since this exception occurs when en-us locale is not enabled: `NotAcceptableException: No locales match the accepted languages: en-US,en;`
- Used the default locale for the custom JSON element since it's currently hard-coded to `en_US`

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Seems like the unique test failures are unrelated, but let me know what you think, thanks!

**Review by thektan — APPROVED** [review]
Looks good! Thanks for documenting the breakdown of `getSXPElementTitleAndDescription` and naming the function specifically as well! 👍

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/129149

**Pull request closed without merging**
