### PR TITLE
LPS-193346: Fix DTO conversion for Objects

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-193346

Related: https://liferay.atlassian.net/browse/LPS-193764

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
Manually forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/139365

**Pull request closed without merging**
