### PR TITLE
LPS-101775 portal-search-elasticsearch7-impl:fix failed test case in the base test case.

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test:sf

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
**ci:test:search Analysis**
- Elasticsearch7#AssertSidecarDoesNotCluster: [LRQA-56373](https://issues.liferay.com/browse/LRQA-56373)
- Elasticsearch7#AssertIndexOnStartup: Fluke,  test failed to open the URL within 180 seconds so it timed out
- Search#ViewCreatedSearchPagePermissions, Search#ViewDefaultSearchPagePermissions: [POSHI-118](https://issues.liferay.com/browse/POSHI-118)
- CommercePriceListIndexerTest.testSearch: [COMMERCE-4776](https://issues.liferay.com/browse/COMMERCE-4776)
- and I think the Java heap space issue is related to [LPS-110716](https://issues.liferay.com/browse/LPS-110716)

**ci:test:relevant Analysis**
- semantic-versioning-jdk8: Caused by publishing issues, unrelated to these changes

**Pull request closed without merging**
