### PR TITLE
[TS] LPS-191765 Missing <prefix>-<companyId>-search-tuning-rankings index after switching embedded/remote ES

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
also sent to shuyang https://github.com/shuyangzhou/liferay-portal/pull/11230

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-search/liferay-portal/pull/1083

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
