### PR TITLE
LPS-203184 FTL Error in Category Facet with Vocabulary Layout Display Template

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-203184

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
Hi @AlmirFe, I've added a commit to reduce code complexity and to ensure no unnecessary code duplication. Your previous changes were great; just want to double-check this aspect. Thanks! can you review it back?

**Comment by gustavolimav** [comment]
@oliv-yu Thanks for catch this I already know what I missed, I will fix and create a test for that.

**Comment by gustavolimav** [comment]
Hey @oliv-yu, I pushed the fix, I will continue creating the test

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
Prior issue is fixed and the tests pass, thanks! I think someone should still review the changes from the refactor, @AlmirFe did you want to take a look again?

**Review by AlmirFe — APPROVED** [review]
LGTM! :100: @gustavolimav

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
