### PR TITLE
RELEASE-5743 Quarantine failing solr tests from release tester

### PR DESCRIPTION
**Pull request by john-co**
Description
Quarantine failing release tests to reduce impact on release testing analysis. Please unquarantine the tests as each fix is implemented in their respective follow up tickets.

JIRA Ticket
https://liferay.atlassian.net/browse/RELEASE-5743

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:stable

**Comment by xbrianlee** [comment]
@john-co We finished the Solr release last week so this should no longer be necessary. Can you let us know if the Solr test failures persist in the next release run?

**Comment by john-co** [comment]
Thanks @xbrianlee, closing PR for now.

**Pull request closed without merging**
