### PR TITLE
LPD-36512 Search pagination delta is shared when using multiple search results widgets

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-36512

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Review by oliv-yu — CHANGES_REQUESTED** [review]
Thanks for working on this! I left several comments about the playwright test, and tried it out locally and it passed for me. 

Let me know if you have any questions!

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by oliv-yu** [comment]
Looks good to me too! 🔥

**Review by oliv-yu — APPROVED** [review]

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:forward

**Pull request closed without merging**
