### PR TITLE
LPS-176393 LPS-176395 Remove document type from Liferay mappings and introduce ES compatibility headers

### PR DESCRIPTION
**Pull request by joshuacords**
**Stories:**
[LPS-176393](https://issues.liferay.com/browse/LPS-176393) Remove Document Types
[LPS-176395](https://issues.liferay.com/browse/LPS-176395) Add compatibility headers
[LPS-176398](https://issues.liferay.com/browse/LPS-176398) Gracefully handle Additional Types and Overriding

Subtasks:
[LPS-183776](https://issues.liferay.com/browse/LPS-183776) Remove Document Types
[LPS-184194](https://issues.liferay.com/browse/LPS-184194) Add compatibility headers
[LPS-184327](https://issues.liferay.com/browse/LPS-184327) Gracefully handle Additional Types and Overriding

**Authors:** @joshuacords, @peerkar, @lipusz

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:commerce

**Comment by xbrianlee** [comment]
ci:test:workflow

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:search-remote

**Comment by xbrianlee** [comment]
ci:test:search-remote-minimum

**Comment by joshuacords** [comment]
Hi @xbrianlee,

I'm seeing a lot of failures here, would you be able to clarify which tests appear related?

**Comment by xbrianlee** [comment]
ci:test:commerce

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search-remote

**Comment by xbrianlee** [comment]
ci:test:search-remote-minimum

**Comment by xbrianlee** [comment]
ci:test:search-solr

**Comment by xbrianlee** [comment]
ci:test:workflow

**Comment by xbrianlee** [comment]
ci:test:search-lxc

**Comment by xbrianlee** [comment]
ci:test:commerce-es7-remote

**Comment by xbrianlee** [comment]
ci:test:workflow-es7-remote

**Comment by BryanEngler** [comment]
continued in https://github.com/BryanEngler/liferay-portal/pull/723

**Pull request closed without merging**
