### PR TITLE
LPD-25847 Add Test to assert that Search Result redirect to the right page after configuration is updated

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-25847

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Review by felipelorenz — APPROVED** [review]
LGTM!

**Comment by felipelorenz** [comment]
ci:forward

**Comment by AlmirFe** [comment]
ci:forward

**Pull request closed without merging**
