### PR TITLE
LPS-191707 Allow SearchRegistrars to configure/override permissionAware

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-191707

This addition allows for backwards compatibility for omitting permission clauses in the search query. This provides a solution to https://liferay.atlassian.net/browse/PTR-4138 

**Authors:** @joshuacords @BryanEngler 

cc: @brianikim

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@joshuacords two small things

1) your baseline commit message says portal-search-api instead of -spi

2) maybe add more details to the javadoc. 
```
	 * Allows backwards compatibility to disable permission filtering in search
	 * queries. By default, permission awareness is controlled by the presence of a 
	 * ModelResourcePermission implementation for the class. It is generally not 
	 * suggested to set this value to false.
	 *
	 * @param permissionAware false if the indexer should not add permission clauses 
	 *        to the pre-filter of the search query 
	 * 
```
@rbohl, any other suggestions on the javadoc? / also, not sure if this should be added to the official docs... its a behavior we dont really suggest to implement

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @BryanEngler, I like your wording and I made those changes. I don't think we need to run the search suite since no code was changed since the force push.

**Comment by BryanEngler** [comment]
ci:forward

**Comment by rbohl** [comment]
Wording looks fine to me. I'd probably have used

> For backwards compatibility, disables permission filtering in search queries when set to false. By default, permission awareness is controlled by the presence of a ModelResourcePermission implementation for the class. This method is not recommended for external use.

But your version is fine, @BryanEngler

**Pull request closed without merging**
