### PR TITLE
LPS-142523 Error uploading files if the Index Registry buffer is disabled

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-142523

I have opened https://issues.liferay.com/browse/PTR-3111 but I have finally decided to send a PR with my solution.

**Root cause of the issue:**

The error is produced in this line [com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl](https://github.com/liferay/liferay-portal/blob/4416c97701203c4ca4ec1933224213c9c770d45a/modules/apps/asset/asset-entry-rel-service/src/main/java/com/liferay/asset/entry/rel/service/impl/AssetEntryAssetCategoryRelLocalServiceImpl.java#L243) with document and media files because they implement the com.liferay.portal.repository.liferayrepository.model.LiferayFileEntry class.

This **com.liferay.portal.repository.liferayrepository.model.LiferayFileEntry** class doesn't implement the `com.liferay.portal.kernel.model.BaseModel` model but it implements the {{com.liferay.portal.kernel.model.ClassedModel}}

When the buffer is enabled, the BufferedIndexerInvocationHandler intercepts the calls and if the object is a instance of ClassedModel, it converts the reindex request to a safe `indexer.reindex(className, primaryKey)` call, see: [com.liferay.portal.search.internal.buffer.BufferedIndexerInvocationHandler](https://github.com/liferay/liferay-portal/blob/4416c97701203c4ca4ec1933224213c9c770d45a/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/buffer/BufferedIndexerInvocationHandler.java#L96-L109)

When the buffer is disabled, the BufferedIndexerInvocationHandler logic is not executed and the `indexer.reindex(object)` fails because the DefaultIndexer expects a BaseModel model.

**Solution:**

Commit https://github.com/liferay/liferay-portal/commit/539b76be3adb0b504f0ce60e95ab41d5ba8fb4ab I am avoiding the ClassCastException checking that the assetObject is a instance of BaseModel and as fallback in case it is a ClassedModel, I am doing a similar logic than the BufferedIndexerInvocationHandler.

Commit https://github.com/liferay/liferay-portal/commit/a6afc3056a9cfab62b1b9d51054b0e83fafb149c I am removing the option of disabling the index buffered because disabling it is always a bad idea:
  - The search tests are not executed with the index buffer disabled, so any customer that changes this option can detect unexpected errors because this option is not tested.
  - The customers that disables it they will also detect the problems that the index buffer solved when it was created, for example [LPS-56593](https://issues.liferay.com/browse/LPS-56593) or [LPS-69361](https://issues.liferay.com/browse/LPS-69361)

If somebody wants to disable the buffer by its own, out of the Liferay support, they can always blacklist the **com.liferay.portal.search.internal.buffer.IndexerRequestBufferTransactionLifecycleListener** component, this will have the same effect than current option. 
The customer can also leave the buffer enabled but changing its size to zero.

Let me know if you have any question

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
The same exception:
```
javax.portlet.PortletException: java.lang.ClassCastException: class com.liferay.portal.repository.liferayrepository.model.LiferayFileEntry cannot be cast to class com.liferay.portal.kernel.model.BaseModel (com.liferay.portal.repository.liferayrepository.model.LiferayFileEntry and com.liferay.portal.kernel.model.BaseModel are in unnamed module of loader com.liferay.shielded.container.internal.ShieldedContainerClassLoader @178213b)
 ```
was temporary reproduced by three customers, see Helpcenter tickets in https://issues.liferay.com/browse/LPS-142523?focusedCommentId=2694064&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2694064
But the issue was solved with workarounds.

**Comment by jorgediaz-lr** [comment]
Hi @liferay-search 

Do you have any update about this pull request?

Thank you

**Comment by lipusz** [comment]
Hi Jorge,

We handle it as a low priority due to other more urgent tasks we have to work on.
It should be picked up later this week or early next.

**Comment by jorgediaz-lr** [comment]
Thanks for the update @lipusz

**Comment by BryanEngler** [comment]
@jorgediaz-lr thanks for the pr. i was talking to tibor and wanted to see what your thoughts are on this approach -> https://github.com/BryanEngler/liferay-portal/commits/pr_2022_06_15_liferay_search_pr451_LPS_142523_file_upload

basically we would just hide the entire config UI instead of only removing the buffered setting. this way the semver bump isnt as aggressive. let me know if you think there are any issues with this approach. thanks

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

I think just hiding all the index registry buffer setting is a good approach, because customers shouldn't touch anything here and in case there is any justified case they can always change it using a config file.

BTW, I didn't know you can just add `generateUI = false` to hide some settings, this is good to now!

**Comment by BryanEngler** [comment]
sounds good, i will forward from https://github.com/BryanEngler/liferay-portal/pull/650

**Pull request closed without merging**
