### PR TITLE
LPD-2835 ElasticsearchStatusException occurs when there are more than 65536 inactive groups & LPD-23550 Create test to ensure that an ElasticsearchStatusException will not be thrown even if the number of terms exceeded the allowed maximum

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-2835

https://liferay.atlassian.net/browse/LPD-23550

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
LGTM!

**Review by felipelorenz — APPROVED** [review]

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:report:2562223287

**Comment by gustavolimav** [comment]
ci:report:

**Comment by gustavolimav** [comment]
ci:report:2562223268

**Comment by gustavolimav** [comment]
ci:report:2562225681

**Comment by gustavolimav** [comment]
ci:report:2562221373

**Comment by gustavolimav** [comment]
No unique failures

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
