### PR TITLE
LPS-120958 Elasticsearch scripted_upsert

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @rafaprax
Reviewer: @arboliveira 

https://issues.liferay.com/browse/LPS-120958

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Pull request closed without merging**
