### PR TITLE
LPD-28428 Bump third-party libraries in the Elasticsearch connector to their latest

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-28428

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:21608763

**Review by gustavolimav — APPROVED** [review]
LGTM! 🚀

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
