### PR TITLE
LPS-188150 unescape search result content

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPS-188150

### CODE REVIEW

**Comment by oliv-yu** [comment]
Hi @ZakiMiklos thank you for working on this! I took a look at this PR and while it works, I wanted to ask about it. 

It looks like this fix will unescape all content that will come in, but this bug only applies to highlighted content of specifically a page. Is there a way to address what's happening for that? In the example shown, I'm seeing `summary.getContent()` look like `Trial &amp;amp; error ...` where I see that extra `amp;` so perhaps there's something happening there? Please let me know what you think.

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
@ZakiMiklos Ah, I see what you mean then, it sounds simpler to do this than try changing deeper into the code for getting search summaries.

The sf test seems to fail, would you mind updating the formatting of the line and rerunning `ci:test:search` and `ci:test:relevant`?

Afterwards, I'll ask QA to check on the search tests. As long as those look good, we can forward 💯 

Thanks again!

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by lipusz** [comment]
@ZakiMiklos Your Liferay organization membership must be public on your GitHub profile in order to trigger CI commands on liferay-portal repos. Can you do that?

**Comment by lipusz** [comment]
Like this: 
image

vs.

image

**Comment by lipusz** [comment]
Go to https://github.com/orgs/liferay/people and find your profile in the list and make sure it's saying "Public":

image

**Comment by lipusz** [comment]
Then trigger SF again. :crossed_fingers:

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
Thank you @lipusz for the help it is working now!

**Comment by lipusz** [comment]
@ZakiMiklos Can you fixup your second commit into the first one? Usually, self-SF commits are fixed-up into the related "original" commit.

**Comment by oliv-yu** [comment]
Hi @ZakiMiklos, just resending here with the fixup https://github.com/liferay-search/liferay-portal/pull/1001 since ci tests would take a while to run, hope that's okay. Thanks @lipusz for the instruction!

**Pull request closed without merging**
