### PR TITLE
LPS-197717 Fix validation to Everything Scope and Fix bug applying RR to search bar

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-197717

The query needs to have group and blueprints ERC even if it is blank because it needs to filter by scopes

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
:construction: Related thread: https://liferay.slack.com/archives/CLY5F4YN5/p1696007677542789?thread_ts=1695993845.594579&cid=CLY5F4YN5

**Comment by lipusz** [comment]
Just for the reference

**Comment by BryanEngler** [comment]
testing here  https://github.com/liferay-search/liferay-portal/pull/1095

**Pull request closed without merging**
