### PR TITLE
LPS-162052 Modified Facet Refactoring

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-162052

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1377401_7752

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
