### PR TITLE
LPS-140641 When building Blueprint, I can select an Asset Category for my element through the UI without collecting its ID manually

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-140641 When building Blueprint, I can select an Asset Category for my element through the UI without collecting its ID manually

Relies on the existing OOTB element by checking for the input type of "number"/"multiselect" and the presence of `asset_category_id(s)` as the field name, instead of specifying its own category selector input type (as mentioned in https://github.com/BryanEngler/liferay-portal/pull/665). For single selectors, this should be able to start saving the label and value of a category based on information from the autocomplete or the modal. 

Labels have also been updated to look like `Name (ID: 1234)`.

Screen Shot 2022-09-01 at 3 17 25 PM
Screen Shot 2022-09-01 at 3 22 27 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
Resolved merge conflict and added commit from https://github.com/liferay-frontend/liferay-portal/pull/2628 (for error when upgrading from an older db)

**Comment by thektan** [comment]
Running tests with the new bug fix at https://github.com/thektan/liferay-portal/pull/256

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
Relevant failures are not relevant.

Manually forwarded to BChan:
https://github.com/joshchong/liferay-portal/pull/606

**Comment by thektan** [comment]
Thanks @joshchong!

**Pull request closed without merging**
