### PR TITLE
[TS] LPS-135288 Escape tag parameter

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://issues.liferay.com/browse/LPS-135288

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:relevant

**Review by lipusz — CHANGES_REQUESTED** [review]
@jonathanmccann Please use `HtmlUtil.escapeAttribute` instead (see `portal-search-web/src/main/resources/META-INF/resources/user/facet/view.jsp`) and force push then hit `ci:forward`. Thanks!

**Comment by jonathanmccann** [comment]
@lipusz Thanks for the quick review.

**Comment by jonathanmccann** [comment]
ci:forward

**Review by lipusz — APPROVED** [review]
👍

**Comment by arboliveira** [comment]
https://issues.liferay.com/browse/LPS-135288?focusedCommentId=2480921&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2480921

**Comment by arboliveira** [comment]
ci:forward

**Pull request closed without merging**
