### PR TITLE
LPS-149091 Add test Coverage to SXPElements

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-149130
https://issues.liferay.com/browse/LPS-149132
https://issues.liferay.com/browse/LPS-149139

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by joshuacords** [comment]
Hello @gustavolimav,

This is very close, I need to ask for 2 changes. First, I believe the testBoostContentsForTheCurrentLanguage is very likely to be flaky as all the titles and contents are identical besides the locale in the title and could be returned in any order by the search engine. The articles titles and/or contents in the different locale should be slightly different. Perhaps just adding "Extra irrelevant text" to each of the en_US contents would prove the point while insuring they are returned after their es_ES counterparts in the regular search.

Second, in testBoostContentsInACategoryForTheTimeOfDay we need to show that the element only boosts articles during that time frame, and not articles outside of the time frame. For this a third check needs to happen. I would think it would follow closely with what testBoostContentsInACategoryForAPeriodOfTime is doing. 

PS: I like the Refactor _updateConfigurationJSON commit.

**Comment by gustavolimav** [comment]
https://github.com/liferay-search/liferay-portal/pull/391

**Pull request closed without merging**
