### PR TITLE
LPS-182595 NullPointerException for Some Facets Tests

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-182595

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
LGTM! 🚀

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @felipelorenz, instead of creating a User variable, can you just stick `TestPropsValues.getUser();` inside the Overridden getUser() method?

**Comment by gustavolimav** [comment]
> Hi @felipelorenz, instead of creating a User variable, can you just stick `TestPropsValues.getUser();` inside the Overridden getUser() method?

Hi @joshuacords, actually he can't because if he does that, it would need to add an exception to overridden 'getUser()' and to method signatures in the whole method hierarchy.

**Comment by joshuacords** [comment]
LGTM then

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
