### PR TITLE
LPS-171290 configuring the Category Facet with the vocabulary layout the ordering options don't take effect

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-171290

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/128421

**Pull request closed without merging**
