### PR TITLE
LPS-134505 portal-search-elasticsearch7-impl: bump httpClient version

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-134505

**Author**: @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @lipusz, the tests look good. Would you mind reviewing and forwarding?

**Comment by lipusz** [comment]
ci:forward

**Review by lipusz — APPROVED** [review]
:+1:

**Pull request closed without merging**
