### PR TITLE
LPS-173591 portal-search-web: Merge _getHits logics to be more consistent

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-173591

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
@joshchong can I foward?

**Comment by joshuacords** [comment]
These test failures are documented on the test sheet, so I'll forward it.

**Comment by joshuacords** [comment]
ci:forward:force

**Pull request closed without merging**
