### PR TITLE
LPS-178528: Custom facet support for Objects

### PR DESCRIPTION
**Pull request by peerkar**
- https://issues.liferay.com/browse/LPS-178528
- Functional tests: https://issues.liferay.com/browse/LPS-179295
- Original PR with QA manual testing comments: https://github.com/liferay-search/liferay-portal/pull/852

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward:force

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
