### PR TITLE
[TS] LPS-135245 - Make sync-asynchronous mode in index write operations configurable

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-135245

This is the same pull request than https://github.com/liferay-search/liferay-portal/pull/180 but I have fixed a minor typo.

Original comment from @davidtellolr

> Hi Team,
> 
> Make sync-asynchronous mode in index write operations configurable.
> After analyzing the changes made in the index operations from an asynchronous to the synchronous mode in PTR-2496, it was decided to make this behavior configurable by a portal property.
> The changes in the index write operations were made in:
> 
>     * [LPS-127843](https://issues.liferay.com/browse/LPS-127843) (Flip IndexableAdvice to do sync indexing by default, and add a manual switch to allow override. ) already released in 7.3 FP1
> 
>     * [LPS-130001](https://issues.liferay.com/browse/LPS-130001) (Change the default value of ProxyModeThreadLocal#forceSync to TRUE) committed to 7.3.x but not released yet in an FP1
> 
> 
> In master, by default, we selected the synchronous mode, but, as Tibor Lipusz told in the PTR, this selection could be changed during the PR review.
> 
> After the core team rejects committing the first PR with a general solution, I asked the search team if a more granular solution could be attractive and I made a proposition. andre.oliveira said the modification could be a good option and suggest some adjustments to the original idea. In this PR I develop all his suggestions and this solution applies only to the search module.
> 
> Please, let me know if you have any doubts.

@davidtellolr will be on PTO next weeks, so I will take care of this LPS, let me know in case you have any question.

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Pushed additional commit to fix the SF error after fixing the typo, it seems SF forces a different order if the parameter variable name matches with the internal class variable name.

**Comment by jorgediaz-lr** [comment]
Hi @liferay-search 

Do you have any update about this pull request?

Thank you

**Comment by BryanEngler** [comment]
i think BufferedIndexerInvocationHandlerInternalConfiguration needs to be moved to the same package as IndexStatusManagerInternalConfiguration.

also, i think a mistake was made in IndexStatusManagerImpl and "com.liferay.portal.search.internal.index.IndexStatusManagerInternalConfiguration" was added as a configurationPid?

please resend, thanks

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

Thanks for your comment, I will review the code and I will resend it.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler I have sent a new PR with the requested changes: https://github.com/liferay-search/liferay-portal/pull/185

**Pull request closed without merging**
