### PR TITLE
LPD-39064: Adjust supported vector fields' dimensionality based on the search engine capabilities 

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-39064

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:search-opensearch2

**Comment by peerkar** [comment]
ci:reevaluate:1397401_11493

**Comment by peerkar** [comment]
ci:reevaluate:1307401_10250

**Comment by peerkar** [comment]
ci:reevaluate:1337401_6817

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
see my last commit on https://github.com/peerkar/liferay-portal/pull/29

thanks!

**Pull request closed without merging**
