### PR TITLE
LPS-201968 [FE] Update management toolbar with filter + search controls

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-201968 -  [FE] Update management toolbar with filter + search controls

Only the FE changes to set up the management toolbar with the filtering / search capabilities. When clicked on a filter, the URL will look like:

- Status by inactive + scope by blueprint
```
http://localhost:8080/group/guest/~/control_panel/manage?
p_p_id=com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_mvcRenderCommandName=%2F&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_displayStyle=list&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_orderByCol=queryStrings.keyword&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_orderByType=desc&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_scope=blueprint&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_status=inactive
```

- Search for 'test'
```
http://localhost:8080/group/guest/~/control_panel/manage?
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_keywords=test
&p_p_mode=view&p_p_state=maximized&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_orderByCol=queryStrings.keyword&
p_p_id=com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet&p_p_lifecycle=0&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_displayStyle=list&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_orderByType=desc&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_status=all&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_mvcRenderCommandName=%2F&
_com_liferay_portal_search_tuning_rankings_web_internal_portlet_ResultRankingsPortlet_scope=all
```

Expectation from backend would be to set up the rankings with these filters, please let me know if there's any adjustments to be made.

Note: The 'not applicable' filter option can be added after the changes from https://liferay.atlassian.net/browse/LPS-200654 get merged!

Screenshots:
Screenshot 2023-12-01 at 3 46 13 PM
Screenshot 2023-12-01 at 3 03 13 PM
Screenshot 2023-12-01 at 3 06 52 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
LGTM! ✨

**Comment by oliv-yu** [comment]
Will resend after changes from https://github.com/liferay-search/liferay-portal/pull/1196 get merged!

**Comment by oliv-yu** [comment]
Resent with https://github.com/liferay-search/liferay-portal/pull/1201

**Pull request closed without merging**
