### PR TITLE
LPS-198787 Fix result rankings hidding

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-198787

This bug was created by [this commit](https://github.com/brianchandotcom/liferay-portal/commit/130c97887316224e930248854d265bac6c418b11) where the names were changed but the js was not updated.

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
@oliv-yu - would you be up for reviewing this?

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@joshuacords @oliv-yu, the tests look good. feel free to ci:forward:force when done with your review.

**Comment by joshchong** [comment]
@BryanEngler, was able to peer review this and said it's good to forward.

Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/142113

**Pull request closed without merging**
