### PR TITLE
LPS-185631 Configure the pagination style and empty result message in search results widget

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-185631 - Allow user to configure the pagination style and empty result message in the Search Results widget so that it can be customized via display templates

Configurations for `showPagination` and `showEmptyResultMessage` were created (set to true by default) to give users the option of customization and not introduce regression bugs like https://issues.liferay.com/browse/LPS-185620 🐛 

Let me know if there's anything else to update, thanks!

### CODE REVIEW

**Review by thektan — APPROVED** [review]
Looks good! We can forward this if the test results are good!

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:stable

**Comment by brookedalton** [comment]
Sent to BChan.
master: https://github.com/brianchandotcom/liferay-portal/pull/136112

**Pull request closed without merging**
