### PR TITLE
LPS-178733: upgrade process loses element instance description localizations

### PR DESCRIPTION
**Pull request by felipelorenz**
In the upgrade process [v1_3_2 SXPBlueprintUpgradeProcess](https://github.com/liferay/liferay-portal/blob/7.4.3.68-ga68/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/internal/upgrade/v1_3_2/SXPBlueprintUpgradeProcess.java#L110) it loses element instance description localizations but there is no need for a new upgrade step, because it only affects element instances inside blueprints with no actual functional impact: when a blueprint with element instances is opened for editing, the elements are always rendered with the correct title and description as they are always obtained from the corresponding SXPElement entry. And when the blueprint gets saved the next time, the values inside the element instances will be updated to be the correct ones.

So we are just fixing the logic inside v1_3_2 SXPBlueprintUpgradeProcess.

https://issues.liferay.com/browse/LPS-178733

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:forward:force

**Pull request closed without merging**
