### PR TITLE
Lps 137597 comparison failure in blogs entry asset search test.test order by create date asc

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-137597

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
