### PR TITLE
LPS-171139: Future proof semantic search API

### PR DESCRIPTION
**Pull request by peerkar**
**Covers:**

- https://issues.liferay.com/browse/LPS-171139
- https://issues.liferay.com/browse/LPS-171140
- https://issues.liferay.com/browse/LPS-173208

**Unblocks:**

- https://issues.liferay.com/browse/LPS-166568

**Purpose in a nutshell:**

- Add a portal-search-web accessible API for showing statuses of embedding providers on the index actions page (LPS-166568)
- Get rid of provider specific configuration properties and namings because more providers will come
- Prepare APIs to support multiple active embedding providers.
- Modularize the retriever API to support retrievers for other kinds of embeddings (images)

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:reevaluate:1277401_6628

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
ci:reevaluate:1397401_2492

**Comment by peerkar** [comment]
ci:reevaluate:1397401_2492

**Comment by peerkar** [comment]
ci:forward

**Comment by thektan** [comment]
@peerkar @joshchong The Blueprints/Elements admin page appearing blank was fixed in this commit https://github.com/liferay/liferay-portal/commit/24b5991d481158eb8c6365940cb61eaffaf31512. I rebased and re-ran `gradle buildLang` to fix the merge conflicts here: https://github.com/liferay-search/liferay-portal/pull/755

**Pull request closed without merging**
