### PR TITLE
LPS-191544 Search Admin > Index Actions page featuring reindex execution modes and improved type selection

### PR DESCRIPTION
**Pull request by joshchong**
From @oliv-yu:

https://liferay.atlassian.net/browse/LPS-187171 - Search Admin > Index Actions page featuring reindex execution modes and improved type selection

https://liferay.atlassian.net/browse/LPS-191544 - [FE] Rework Execution Mode/Scope selector and Reindex Actions list (minimal change design)
https://liferay.atlassian.net/browse/LPS-191549 - [FE] Create warning confirmation dialog when running out of disk space on concurrent

 Enable with feature flag:
`feature.flag.LPS-183661=true`

### Screenshots

Here's a short demo of the new design working:
https://github.com/liferay-search/liferay-portal/assets/14063502/2ca49609-052d-42bf-ab9c-c15b38db0f09

Screenshot 2023-08-11 at 3 54 17 PM
Screenshot 2023-08-11 at 4 03 59 PM
Screenshot 2023-08-11 at 3 55 18 PM
Screenshot 2023-08-11 at 3 56 02 PM
Screenshot 2023-08-11 at 4 08 24 PM

### Updates

- Execution mode react component was updated to the new selector with dropdown
- Categories were added to each indexer type, and language keys were added in order to provide more friendly-to-read display names
- Execute buttons will disable depending on what is getting reindexed:
-- If reindexing all search indexes, the rest are disabled.
-- If reindexing one type of index, the "all search indexes" is disabled. 
-- If reindexing spell check dictionaries or rankings/synonyms, all the execute buttons are disabled as the page loads (due to lack of background task manager)
- Informational or warning modals will show depending on whether mode is concurrent, disk space is low, or if user has checkboxed "do not see again". The low disk space threshold is calculated inside the `main.js`, when the availableDiskSpace is less than 1.5 times the currentDiskSpaceUsed.

### Disk Space Warning

Currently the disk space warning looks like this because there are no elastic search metrics passed in:

Screenshot 2023-08-11 at 2 45 27 PM

Once the disk space is determined on backend https://liferay.atlassian.net/browse/LPS-187293, it can be added into `index_actions.jsp` into the `Liferay.Portlet.Admin`, something like this (hopefully this makes sense, if not we can update it once backend has these values):

```
<aui:script use="liferay-admin">
	new Liferay.Portlet.Admin({
		controlMenuCategoryKey:
			'<%= ProductNavigationControlMenuCategoryKeys.TOOLS %>',
		elasticSearchDiskSpace: {
			availableDiskSpace: <%= availableDiskSpaceInGB %>,
			currentDiskSpaceUsed: <%= currentDiskSpaceUsedInGB %>
		},
		form: document.<portlet:namespace />fm,
		indexActionWrapperSelector: '.index-action-wrapper',
		indexActionsPanel:
			'<%= '#' + liferayPortletResponse.getNamespace() + "adminSearchAdminIndexActionsPanel" %>',
		namespace: '<portlet:namespace />',
		redirectUrl: '<%= redirectURL %>',
		submitButton: '.save-server-button',
		url:
			'<portlet:actionURL name="/portal_search_admin/edit"><portlet:param name="redirect" value="<%= redirectURL %>" /></portlet:actionURL>',
	});
</aui:script>
```

### Note about Language Keys

Some of the previous keys for phrases like "Reindex search indexes." or "Reindex spell-check dictionaries." had periods at the end, but in the new design their usage doesn't have periods, so the language key has been updated.

I think the wording of some of the descriptions is still being decided, so I'll run buildLang after it's finalized!

### CODE REVIEW

**Comment by oliv-yu** [comment]
Hi @BryanEngler! It looks like there are several `NullPointerExceptions` in the test runs inside `SearchAdminDisplayContextTest`

I was thinking it has to do with the changes in https://github.com/liferay-search/liferay-portal/pull/1041/commits/1611091a3cfefa209d5f576c56b97f88fb688777 where it's grabbing `IndexerRegistryUtil.getIndexers()`. They're being used to sort into categories for viewing on the page, but it looks like there's a problem trying to sort something that hasn't been mocked, is that what's happening? Do you have any suggestion for how to resolve that with minimal changes? It seems like these tests were created by Adam 4 years ago 😅

**Comment by joshchong** [comment]
@BryanEngler @oliv-yu, my test changes in this branch are needed so please fetch them if continuing work on this ticket. thanks!

**Comment by joshchong** [comment]
Also I just noticed when you reindex in any of the 3 reindex modes (full, concurrent, or sync mode), the server logs refers to them as `null`. for example: `Finished reindexing company 20096 with execution mode null`

**Comment by oliv-yu** [comment]
@joshchong If the server logs are referring to them as `null`, maybe there's some issues rendering the execution mode react component. It's still able to select the different options?

Could you share the link to the logs? 🪵

**Comment by joshchong** [comment]
@oliv-yu hey yeah it's still able to select the different options. there's not much in the logs, no errors or anything, it just shows things like this when I reindex:
```
21-Aug-2023 22:33:07.933 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [39186] milliseconds
2023-08-21 22:33:46.717 INFO  [liferay/background_task-2][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 0 with execution mode null
2023-08-21 22:34:06.614 INFO  [liferay/background_task-2][ReindexPortalBackgroundTaskExecutor:81] Finished reindexing company 0 with execution mode null
2023-08-21 22:34:06.615 INFO  [liferay/background_task-2][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 20096 with execution mode null
2023-08-21 22:34:12.357 INFO  [liferay/background_task-2][ReindexPortalBackgroundTaskExecutor:81] Finished reindexing company 20096 with execution mode null
2023-08-21 22:34:50.674 INFO  [liferay/background_task-4][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 0 with execution mode null
2023-08-21 22:35:05.836 INFO  [liferay/background_task-4][ReindexPortalBackgroundTaskExecutor:81] Finished reindexing company 0 with execution mode null
2023-08-21 22:35:05.837 INFO  [liferay/background_task-4][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 20096 with execution mode null
2023-08-21 22:35:07.938 INFO  [liferay/background_task-4][ReindexPortalBackgroundTaskExecutor:81] Finished reindexing company 20096 with execution mode null
2023-08-21 22:35:29.819 INFO  [liferay/background_task-5][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 0 with execution mode null
2023-08-21 22:35:44.436 INFO  [liferay/background_task-5][ReindexPortalBackgroundTaskExecutor:81] Finished reindexing company 0 with execution mode null
2023-08-21 22:35:44.436 INFO  [liferay/background_task-5][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 20096 with execution mode null
2023-08-21 22:35:47.340 INFO  [liferay/background_task-5][ReindexPortalBackgroundTaskExecutor:81] Finished reindexing company 20096 with execution mode null
```

**Comment by thektan** [comment]
@oliv-yu For the failing backend tests, you might have to mock `IndexerRegistryUtil.getIndexers()`.

For example: https://github.com/liferay-search/liferay-portal/blob/master/modules/apps/portal-search/portal-search-admin-web/src/test/java/com/liferay/portal/search/admin/web/internal/display/context/FieldMappingsDisplayContextTest.java#L207-L213

**Comment by joshchong** [comment]
continued in https://github.com/liferay-search/liferay-portal/pull/1045

**Pull request closed without merging**
