### PR TITLE
LPS-177665 LPS-180980 [FE] Add "Execution Mode" option in Index Actions page

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-177665
**Subtask:** https://issues.liferay.com/browse/LPS-180980

---

- Behind feature flag (Set `feature.flag.LPS-177664=true`)
- Execute buttons are disabled by adding `data-blue-green-disabled=""` to the buttons. 

### Screenshots

Screenshot 2023-04-06 at 7 08 35 PM

### CODE REVIEW

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
@oliv-yu Also as a note, destructuring `useRef` with `const {current: executeButtonElements} = useRef(...);` doesn't currently work since `yarn format` will fail with an error. It's most likely a bug, but I also realized a benefit to not destructuring is so you can re-assign the value with `someRef.current = "new value";`.

```
TypeError: Cannot read properties of undefined (reading 'match')
Occurred while linting /Users/ktan/Developer/liferay-portal-master/portal/modules/apps/portal-search/portal-search-admin-web/src/main/resources/META-INF/resources/js/execution_options/index.js:56
    at VariableDeclarator (/Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/@liferay/eslint-plugin/rules/general/lib/rules/ref-name-suffix.js:26:21)
    at /Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/ktan/Developer/liferay-portal-master/portal/modules/node_modules/eslint/lib/linter/linter.js:954:32
    at Array.forEach (<anonymous>) {
  currentNode: <ref *1> Node {
    type: 'VariableDeclarator',
    start: 1707,
    end: 1811,
    loc: SourceLocation { start: [Position], end: [Position] },
    range: [ 1707, 1811 ],
    id: Node {
      type: 'ObjectPattern',
      start: 1707,
      end: 1739,
      loc: [SourceLocation],
      range: [Array],
      properties: [Array],
      _babelType: 'ObjectPattern',
      parent: [Circular *1]
    },
    init: Node {
      type: 'CallExpression',
      start: 1742,
      end: 1811,
      loc: [SourceLocation],
      range: [Array],
      callee: [Node],
      arguments: [Array],
      optional: false,
      _babelType: 'CallExpression',
      parent: [Circular *1]
    },
    _babelType: 'VariableDeclarator',
    parent: Node {
      type: 'VariableDeclaration',
      start: 1701,
      end: 1812,
      loc: [SourceLocation],
      range: [Array],
      declarations: [Array],
      kind: 'const',
      trailingComments: [Array],
      _babelType: 'VariableDeclaration',
      parent: [Node]
    }
  }
}
```

**Review by oliv-yu — APPROVED** [review]
I deployed it and tried it out behind the FF, looks good! Thanks for the heads-up about destructuring a useRef too 💯

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
