### PR TITLE
LPS-151999 Post 7.3 -> 7.4 Upgrade, custom Search Bar widget templates are no longer visible in the UI

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-151999

### Fix Notes

Followed pattern from https://github.com/brianchandotcom/liferay-portal/pull/127638 without the removal part, as there are no template we should delete at this point imo.

:heavy_check_mark: The facet widgets have been addressed in [LPS-170694](https://issues.liferay.com/browse/LPS-170694)

### Analysis 

Caused by , [LPS-147369](https://issues.liferay.com/browse/LPS-147369): https://github.com/liferay/liferay-portal/commit/2efe7c97b8cd716ce597c1feb7f460b59d942fd4#diff-e08850f3cf8da693387e962e3906b41c92c86d93a6f8beb5b791e083fc60f719
* 7.4 U9+/GA13+: `com.liferay.portal.search.web.internal.search.bar.portlet.display.context`
* 7.3.x, 7.4 U8/GA12 and prior: `com.liferay.portal.search.web.internal.search.bar.portlet`

More about the root cause [here](https://issues.liferay.com/browse/LPS-170694?focusedCommentId=2816937&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2816937).

### QA Results

Search QA has tested the upgrade scenarios from the ticket already. :white_check_mark:

### CODE REVIEW

**Comment by lipusz** [comment]
ci:help

**Comment by xbrianlee** [comment]
ci:test:data-engine

Since `dynamic-data-mapping` was modified

**Comment by xbrianlee** [comment]
`search` suite failures above are unrelated to the changes in this PR

**Comment by xbrianlee** [comment]
Manual testing passed following the steps in [LPS-151999](https://issues.liferay.com/browse/LPS-151999)

**Comment by xbrianlee** [comment]
ci:test:data-engine:norebase

**Comment by xbrianlee** [comment]
ci:test:data-engine:norebase

Past runs failed due to authentication failures on CI

**Comment by xbrianlee** [comment]
ci:test:data-engine:norebase

**Comment by xbrianlee** [comment]
ci:test:data-engine

**Comment by xbrianlee** [comment]
ci:test:data-engine

**Comment by xbrianlee** [comment]
`data-engine` test results look good too

**Review by peerkar — APPROVED** [review]
Code looks ok to me. I didn't test it manually as @xbrianlee appeared to have done that already.

**Comment by lipusz** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward:force

The functional test failure above appears to be a fluke. The widget sidebar failed to expand.

**Pull request closed without merging**
