### PR TITLE
LPS-183726 Remove unused "like" parameter from search API

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-183726

[FieldQueryFactoryImpl.createQuery](https://github.com/liferay/liferay-portal/blob/a646f22e82da6d49ebc0b46fa9a20cb89d438cf0/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/query/FieldQueryFactoryImpl.java#L38) method is ignoring the "boolean like" parameter.

The usage of this parameter was removed in DXP 7.0 in LPS-66593, see https://github.com/brianchandotcom/liferay-portal/pull/41254/files#diff-98a58270441a57ab1c5d0685d62f478cc6715e909a74219a025e4b85b42b8c20

This method is used by several search API classes, so neither of them are using this method.
This causes some misunderstandings to our customers as they think our API is not working correctly

To avoid these problems, my proposal is to remove the parameter, as current behavior hasn't change since DXP 7.0, so it seems the parameter is not necessary

Let me know if you have any question

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Jorge,

We can look into this later, though I'd not handle it as a bug, so I have converted it to be a Task for now until refinement.

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi all,

I have updated to latest master, solving some conflicts.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by lipusz** [comment]
This PR can be reused later, but closing so it's not impacting internal reports, unnecessarily.

**Pull request closed without merging**
