### PR TITLE
[Test] LPS-129828 SynonymSearchTest integration test fails when run with a remote Elasticsearch server

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-129828

We need to account that the Elasticsearch config may have already been altered by the test env (e.g. in `ci:test:search-remote`) so we have to keep the current properties to prevent "resetting" the config unintentionally. Plus some minor cosmetics.

@ Brian: this should be clean cherry-pick, so I'd appreciate if you could backport this to 7.3.x. For 72x, I'll send a PR as it requires slight changes due to the differences between 7.3 and 7.2. Thanks!

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search-remote

**Comment by lipusz** [comment]
Passed local manual testing with both sidecar and remote ES. :white_check_mark:

**Comment by joshchong** [comment]
hey @lipusz, the test failures are unrelated so this PR should be good to go.

**Comment by lipusz** [comment]
ci:forward

**Comment by joshchong** [comment]
Resent here to address unrelated ci:forward failure: https://github.com/liferay-search/liferay-portal/pull/107

**Pull request closed without merging**
