### PR TITLE
LPS-149278 portal-search-elasticsearch-impl:add a checkpoint for ZipSlipVulnerability

### PR DESCRIPTION
**Pull request by wcao20170619**
https://issues.liferay.com/browse/LPS-149278

### CODE REVIEW

**Comment by joshuacords** [comment]
Hello @wcao20170619,

I tried testing this test and the results indicate the test isn't properly testing the functionality. What I did was edit the `_isZipSlipVulnerable()` to always return false, making it so we would expect the some of tests to fail. The first time you run the testUnzipZipSlipVulnerable test, it will succeed. But afterwards it fails with a file already exists error.
This happens because the evil.txt file is not placed within the tempDir but instead directly into the tmp directory, and of course the whole point is to make sure it cannot be placed into a different directory.

2 changes should be made, first the tearDown method should consider that the evil.txt file could be located outside of the tempDir, and should remove that file if present. (You can do this manually by `cd /tmp` and remove evil.txt from there.) Perhaps the file directory the evil.txt file gets placed in should be another tempDir the test makes.

Second, the _assertDoesNotExist needs to check at /tmp/evil.txt, not /tmp/temp_dir4776123001495912176/tmp/evil.txt for the file. 

Let me know if anything was unclear.

**Comment by wcao20170619** [comment]
@joshuacords you may need to look into testZipSlip.zip. Second, the _assertDoesNotExist should 
 not check at /tmp/evil.txt. it checks the full path of "tmp/evil.txt" from the tempDir.resolve(name). Looking into testZipSlip.zip file you may get a clear picture of that. Thanks for the detailed review. Nice!

**Comment by joshuacords** [comment]
I did look into testZipSlip.zip and spent a lot of time understanding what was happening. We could meet when your back if need be.

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:forward

**Comment by wcao20170619** [comment]
@joshuacords I thought I had explained your concern by looking into the testZipSlip.zip. Since @BryanEngler mentioned it in PR again, I am trying to explain it a little further here. 
What you were trying to do is to reproduce the bug via using the unit test and testZipSlip.zip(make _isZipSlipVulnerable always return False). There is no such unit test to reproduce the bug that has been fixed already. The unit test we need is the test to verify the bug that has been fixed. If you follow the TDD programming approach, First we make the test fail and then we make it work(NOT make it work by fixing in the test. It is to make it work by fixing the implementation code). After this fix, any entries in the zip files that try to install them outside of the destination directory would never happen.

**Comment by wcao20170619** [comment]
@joshuacords, @BryanEngler Please let me know if the meeting is still needed. Is Josh Cord's concern related to Technical or Business logic?

**Comment by joshuacords** [comment]
Hi @wcao20170619, my concern is that the test does not protect against changes to the UncompressUtil and will not preserve behavior as it does not truly test the _isZipSlipVulnerable() method. For example, if someone changes the _isZipSlipVulnerable() method incorrectly, such that the method returns false (it's safe) instead of true (it's vulnerable), the test wouldn't catch this. I'm demonstrating this purposefully modifying the Uncompress._isZipSlipVulnerable() to always return false. In doing this I expect that a test would fail, but instead it will pass. And after you run the test, navigate to /tmp and you will see evil.txt is in this directory. IF evil.txt can end up directly in /tmp THEN the test should fail, but instead it passes.

Please try modifying UncompressUtil._isZipSlipVulnerable() to always return false and check the result of the test. It should fail to indicate behavior has changed and the Vulnerability is present again.

**Comment by wcao20170619** [comment]
@joshuacords, I think you are in a dead corner.  I would suggest that you add a commit on the top of the fix to demo your idea to me. When I started to fix it, I had _isZipSlipVulnerable with empty code in it and it always returned false and It would fail after first running successful(just like you had). And then I fill in the codes into _isZipSlipVulnerable to make the test work. That is standard TDD procedure. The problems with your idea are 1. different OS has different tmp directory 2. the tmp directory is the place for all the processes. (always use the dynamical directory under the tmp directory) 3. the slip path in the testZipSlip.zip is a relative path. The final directory to install that evil.txt is based on where you run the test.

The unit test is a test to assert(verify) the function works as supposed to be and not protect against changes to the function. If you change the function, of cause, you have to change the test to match what you want.

**Pull request closed without merging**
