### PR TITLE
LPD-36424 search-experiences-web: Prevent errors/warnings with storybook

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-36424 - Update search-experiences-web for Storybook 8 compatibility

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]

**Comment by thektan** [comment]
I'll be keeping an eye on this and forward if the tests pass 👀

**Comment by thektan** [comment]
Unrelated failures on the search tests.

**Comment by thektan** [comment]
ci:forward

**Comment by thektan** [comment]
Looks like some tests are untested so I'll run this again.

**Pull request closed without merging**
