### PR TITLE
LPD-28436 Include Sidecar Elasticsearch version in the log

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-28879

image

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@lipusz just wanted to confirm the log message here is correct since the AC changed from the last time i saw it, just wanted to make sure the change was intentional (the "...node named..." part of the message was removed):
`Sidecar Elasticsearch 7.17.21 liferay_sidecar started at 127.0.0.1:9201`

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:23749344

**Comment by felipelorenz** [comment]
ci:report:23731998

**Pull request closed without merging**
