### PR TITLE
LPD-28414 AssetCategory and Vocab ERC

### PR DESCRIPTION
**Pull request by joshuacords**
**Story:** [LPD-28414](https://liferay.atlassian.net/browse/LPD-28414)
**Subtasks:**
- [LPD-31073](https://liferay.atlassian.net/browse/LPD-31073)
- [LPD-33425](https://liferay.atlassian.net/browse/LPD-33425) Tests

Resent to address https://github.com/brianchandotcom/liferay-portal/pull/153289#issuecomment-2288607845

**Author:** @joshuacords 
**Reviewer:** @gustavolimav

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:report:61305219

**Comment by joshuacords** [comment]
ci:report:61305219

**Comment by joshuacords** [comment]
ci:report:61318563

**Comment by joshuacords** [comment]
ci:forward-force

**Comment by joshuacords** [comment]
ci:forward-force

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
hey @joshuacords, you can forward this manually. It already passed on CI.

**Pull request closed without merging**
