### PR TITLE
LPS-190910 Description localization incorrect with search suggestions

### PR DESCRIPTION
**Pull request by AlmirFe**
### **LPS link:** [LPS-190910](https://liferay.atlassian.net/browse/LPS-190910)

# Context

The error occurs after performing a search for a web content (with translation) using a different locale than the default one. The suggestion is displayed correctly (with the translation compatible with the locale) but the SearchSummary is displayed without the translation (following the default locale). This happens because the [_getSuggestion](https://github.com/liferay/liferay-portal/blob/0f20ab121443b8c1e70c58285586d82ce48e7a8d/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/suggestions/spi/BasicSuggestionsContributor.java#L246C1-L306C3) function is filling the assetSearchSummary attribute through the [getSearchSummary](https://github.com/liferay/liferay-portal/blob/0f20ab121443b8c1e70c58285586d82ce48e7a8d/portal-kernel/src/com/liferay/asset/kernel/model/BaseAssetRenderer.java#L104C2-L107C3) function, as shown below. 

```
suggestionBuilder.attribute(
                   "assetSearchSummary",
		   assetRenderer.getSearchSummary(locale));
```

This function calls the [getSummary](https://github.com/liferay/liferay-portal/blob/0f20ab121443b8c1e70c58285586d82ce48e7a8d/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java#L204C2-L214C3) function passing null values in the portletRequest and portletResponse parameters as shown below. 

```
public String getSearchSummary() {
		return getSummary(null, null);
	}
```

These null values cause the default locale to be used.

# Proposed solution 

The [_getSuggestion](https://github.com/liferay/liferay-portal/blob/0f20ab121443b8c1e70c58285586d82ce48e7a8d/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/suggestions/spi/BasicSuggestionsContributor.java#L246C1-L306C3) function was changed to fill the assetSearchSummary attribute directly by [getSummary](https://github.com/liferay/liferay-portal/blob/0f20ab121443b8c1e70c58285586d82ce48e7a8d/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java#L204C2-L214C3)  function passing the correct parameters as shown below.

```
suggestionBuilder.attribute(
		"assetSearchSummary",
		assetRenderer.getSummary(
			liferayPortletRequest, liferayPortletResponse));
```

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
Hey @AlmirFe, assigning back the ticket for you because `BasicSuggestionsContributorTest.testGetSuggestionWithAssetRenderer` is failing due to `suggestion.getAttribute("assetSearchSummary")` is returning null.
|
Probably because the test class is not mocking `assetRenderer.getSumary(liferayPortletRequest, liferayPortletResponse)`.

Remove it and add your mock: https://github.com/gustavolimav/liferay-portal/blob/3138189013c9b3a83a7d7c42a7c96fc6b9c62340/modules/apps/portal-search/portal-search/src/test/java/com/liferay/portal/search/internal/suggestions/spi/BasicSuggestionsContributorTest.java#L222-L228

Please fix and resend!

**Review by gustavolimav — CHANGES_REQUESTED** [review]
Hey @AlmirFe, assigning back the ticket for you because BasicSuggestionsContributorTest.testGetSuggestionWithAssetRenderer is failing due to suggestion.getAttribute("assetSearchSummary") is returning null.
|
Probably because the test class is not mocking assetRenderer.getSumary(liferayPortletRequest, liferayPortletResponse).

Remove it and add your mock: https://github.com/gustavolimav/liferay-portal/blob/3138189013c9b3a83a7d7c42a7c96fc6b9c62340/modules/apps/portal-search/portal-search/src/test/java/com/liferay/portal/search/internal/suggestions/spi/BasicSuggestionsContributorTest.java#L222-L228

Please fix and resend!

**Comment by AlmirFe** [comment]
Hey @gustavolimav , thank you for your review. I've already sent a commit fixing this test. Could you check it please?

**Review by gustavolimav — APPROVED** [review]

**Comment by gustavolimav** [comment]
LGTM :) I will just run the tests again

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
