### PR TITLE
LPS-165920 portal-search-web: Fix bug with arrow key in searchbar suggestions skipping over entries

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-165920 - Navigating with arrow keys in the search bar suggestions jumps over entries

The simple solution was to remove the FocusScope component, maybe since Autocomplete has its own FocusScope which may have conflicted. Let me know if there should be other changes to be made, thanks!

### CODE REVIEW

**Review by thektan — APPROVED** [review]
Looks good! 👍

**Comment by thektan** [comment]
Failures don't seem related so I'm going to attempt to forward.

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
