### PR TITLE
LPD-31129 bug sxpelement creation en us not enabled

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-31129

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @gustavolimav,

First of all, good work figuring out what the heck was going wrong on the LPP. :clap: 

I would like to see the changes be more streamlined, we shouldn't have to handle finding the backup locales in the Service, it would be better for the LocalizedMapUtil to handle them.

My first preference is to add a method to LocalizedMapUtil like [getLocalizedMap](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal-vulcan/portal-vulcan-api/src/main/java/com/liferay/portal/vulcan/util/LocalizedMapUtil.java#L108-L127), but with the signature `getLocalizedMap(Map<String, String> i18nMap, boolean default)` that would do all the same logic except it would call a version of [_getLocale()](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal-vulcan/portal-vulcan-api/src/main/java/com/liferay/portal/vulcan/util/LocalizedMapUtil.java#L257-L259) that would pass that useDefault to `LocaleUtil.fromLanguageId(languageId, true, useDefault);`

If that path doesn't work, then at least use the [LocalizedMapUtil.getLocalizedMap(Locale defaultLocale, String defaultValue, Map<String, String> i18nMap)](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal-vulcan/portal-vulcan-api/src/main/java/com/liferay/portal/vulcan/util/LocalizedMapUtil.java#L72-L83), pass in the backup locale using `LocaleUtil.fromLanguageId(languageId, true, true)` along with the value.

**Review by joshuacords — CHANGES_REQUESTED** [review]
See my comment above.

The test looks good :+1:

**Comment by gustavolimav** [comment]
Hi @joshuacords, nice tips in the review! I'll pay attention to this next time, let me know if the changes are in line with what you wanted. The test passed and I tested manually again to make sure it is still working. If the changes are good please trigger the suits.

**Review by joshuacords — APPROVED** [review]
Changes look good to me, you should also ask the team in charge of LocalizedMapUtil if they're good with the changes there.

(probably easiest is to ping them here noting the specific commit for them to check)

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:36792972

**Comment by gustavolimav** [comment]
ci:report:36795828

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
