### PR TITLE
LPS-169040 Set txtai Host Address field as required 

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-169040

Sets txtai Host Address field as required.

Screenshot 2022-11-30 at 5 19 41 PM

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
None of the failures seem related, but I went ahead and ran ci test relevant in the meantime while this gets reviewed.

**Review by oliv-yu — APPROVED** [review]
Looks good! ⭐ Thanks for adding this in!

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Forwarded here https://github.com/brianchandotcom/liferay-portal/pull/127152

**Pull request closed without merging**
