### PR TITLE
[TS] LPS-130126 portal-kernel: all Inherited methods are now null safe

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-130126

In working on providing a fix for the customer I discovered 7.2 and before needs to fix other methods as well. This additional commit is necessary. Now all public methods are checked for nulls.

Original PR now merged: https://github.com/liferay-search/liferay-portal/pull/110 

Author: @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
cc: @BryanEngler - if you can, could you review this followup PR.

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
fix looks good to me, just gotta get the tests to pass

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
You could ask again Brian to backport to the x branches too (if there will be no conflicts) as the previous PR was backported all the way to 7.0.x.

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@joshuacords if/when the search job passes can you run forward? ill be on PTO until next thurs

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
