### PR TITLE
LPD-28090 Remove hardcoded string values ​​from prepareStatement calls in blueprint upgrade classes

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-28090

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Review by gustavolimav — APPROVED** [review]
LGTM 🚀

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by AlmirFe** [comment]
ci:forward

**Comment by AlmirFe** [comment]
ci:forward:force

**Pull request closed without merging**
