### PR TITLE
LPD-12594 Add integration tests for /portal-search-rest/search 

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-12594

The changes have been approved in https://github.com/liferay-search/liferay-portal/pull/1280

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:2548783705

**Comment by gustavolimav** [comment]
ci:report:2548796228

**Comment by gustavolimav** [comment]
testPostSearchPageWithTypeFacetConfiguration failing https://testray.liferay.com/home/-/testray/case_results/2548796744

**Comment by gustavolimav** [comment]
resent here https://github.com/liferay-search/liferay-portal/pull/1289

**Pull request closed without merging**
