### PR TITLE
LPS-170694 Facet Templates

### PR DESCRIPTION
**Pull request by joshuacords**
Previous PR: https://github.com/BryanEngler/liferay-portal/pull/716

**Author:** @BryanEngler 
**Reviewer:** @joshuacords 

cc: @joshchong @lipusz

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
@joshchong see c53a3df31ea1d67c9d0616b05ba040ab2f8acd6a

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/127638

**Pull request closed without merging**
