### PR TITLE
[TS] LPS-187515 Authenticated requests fail with [HTTP/1.1 403 Forbidden]

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-187515](https://issues.liferay.com/browse/LPS-187515)
Hi Search Team,

Please review my change that removes a call which breaks authenticated requests. I haven't found much information about _disableAuthCaching()_, but as written [here](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/7.17/_basic_authentication.html), it disables adding authentication headers to the request.

Please let me know if you have any questions or concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:reevaluate:1287401_6773

**Comment by istvansajtos** [comment]
ci:reevaluate:1287401_6773

**Comment by joshuacords** [comment]
LGTM :rocket:

**Comment by joshuacords** [comment]
ci:forward

**Comment by xbrianlee** [comment]
ci:forward:force

Test failures above are unrelated. The modules-compile stable failure is resolved in BChan's origin now.

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
