### PR TITLE
[TS] LPS-166969 When creating or updating a Webcontent or any other ResourcedModel, the IndexerRequestBuffer stores and executes two index requests

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-166969

When creating or updating a Webcontent or any other ResourcedModel, the IndexerRequestBuffer stores and executes two index requests, so two index operations are executed.

This is a regression caused by LPS-105011:

 - It was detected after updating from 7.1 to 7.4, but it is also reproduced in 7.3
 - The bug was originally fixed by LPS-67703
 - But its code changes were reverted in this commit https://github.com/brianchandotcom/liferay-portal/pull/83458/commits/c8cff1f258f90931e25360ae324d7ac2782194fa

This is problematic for customers who bulk import web content objects, as the indexing operation is duplicated, it takes twice the time to index them.

We have done some tests with a script that creates 1000 Webcontents and we had these times:

 - Before LPS-166969: 228 seconds
 - After LPS-166969: 168 seconds

To solve the issue, I am just doing a partial revert of the LPS-105011 commit that caused the problem.

I think we can implement a test to check that only one webcontent is sent to Elasticsearch.

   - My idea is to do a test that creates a database transaction, inside this transaction, create a webcontent and check the content of the Index Buffer.
   - I will be on PTO next week, I can implement the test when I am back.

Let me know if you need any information.

/cc @jcampoy

----

**Update:**

The old code generates a SF error.

I have fixed it here: https://github.com/liferay-search/liferay-portal/pull/626/commits/09089e263e8515faedce1b9cbcf1341426d326c0

- obj variable must be called "object"
- We must use the "exception" object in the try...catch but everytime a reindex is done using resourcePrimKey, we will get an exception that can be ignored. 
- To avoid having lots of exceptions that are safe to ignore in the DEBUG log level, I have changed it to TRACE level.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
@jorgediaz-lr re-opening this to get the tests within

**Comment by jorgediaz-lr** [comment]
Hi @peerkar 

I was on PTO

Yes, no problem, I will implement a test.

**Comment by jorgediaz-lr** [comment]
Hi @peerkar 

I have added a test, see new commit https://github.com/liferay-search/liferay-portal/commit/5ad297c9d345700c22e40adfe5e22ba9baf1d863

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
Hi @joshuacords @peerkar 

Do you have any updates about this PR?

Thank you

**Comment by joshuacords** [comment]
I'm testing it today

**Comment by jorgediaz-lr** [comment]
Thank you!

**Comment by joshuacords** [comment]
Hi @jorgediaz-lr, I was testing this out and it seems like creating JournalArticles triggers the bufferedIndexer 5 times and updating a JournalArticle triggers it 7 times. I see the fix changes what classPK is used, but I want to better understand why we're triggering it so many times. I'm continuing work tomorrow but if you have an explanation that would be helpful.

**Comment by jorgediaz-lr** [comment]
Hi @joshuacords 

Yes, when you create/update an object, several index operations are sent and the IndexerRequestBuffer intercept them, executing only one time the indexer, when all the data is already stored in the database.

So IndexerRequestBuffer  has two goals:

- Avoid executing repeated index operations
- Avoid executing the index operation before the commit is executed in the database, and ignore the changes if the transaction is rollback 

The root reason why an object triggers several index operations is because the LocalServiceImpl logic calls external services (ResourcePermission, AssetEntry, Workflow...) that also trigger a reindex because they don't know if its caller will execute the reindex (for example, a permission update will only call the ResourcePermissionLocalService logic)

For example, for a JournalArticle creation, you have 5 calls, see attached threaddumps:

- **First:** `JournalArticleLocalServiceImpl.addArticleResources` method calls `_resourceLocalService.addModelResources` that internally triggers a reindex operation using the resourcePrimKey. For more information, see:
    - threaddump 1: [dump_01.txt](https://github.com/liferay-search/liferay-portal/files/10015081/dump_01.txt)
    - code: https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L926
- **Second and Third:** `JournalArticleLocalServiceImpl.updateAsset` method calls `_assetEntryLocalService.updateEntry` that internally triggers two reindex operations, using both resourcePrimKey and primaryKey. For more information, see:
    - threaddump 2: [dump_02.txt](https://github.com/liferay-search/liferay-portal/files/10015082/dump_02.txt)
    - threaddump 3: [dump_03.txt](https://github.com/liferay-search/liferay-portal/files/10015077/dump_03.txt)
    - code: https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L6635
- **Fourth:** `JournalArticleLocalServiceImpl.startWorkflowInstance` method calls  `WorkflowHandlerRegistryUtil.startWorkflowInstance` that internally triggers a reindex operation using the primaryKey. For more information, see:
    - threaddump 4: [dump_04.txt](https://github.com/liferay-search/liferay-portal/files/10015079/dump_04.txt)
    - code: https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L8440
- **Fifth:** the IndexableAdvice of `JournalArticleServiceImpl.addArticle` internally triggers a reindex operation using the primaryKey. For more information, see:
    - threaddump 5: [dump_05.txt](https://github.com/liferay-search/liferay-portal/files/10015080/dump_05.txt)
    - code: https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleServiceImpl.java#L323


The major problem with JournalArticle indexation and any other ResourcedModel is some index operations triggered by AssetEntry or ResourcePermission logic are done using the resourcePrimKey and some index operation triggered by IndexableAdvice or workflow logic are done using the primaryKey, so in the end, the buffer is storing two index operations one for the resourcePrimKey and another for the primaryKey

The code of [LPS-67703](https://issues.liferay.com/browse/LPS-67703) that I am restoring this commit https://github.com/liferay-search/liferay-portal/pull/626/commits/af921a3758b036ea5624218811aa5224a97bf1f8 is just converting all primaryKey requests into resourcePrimKey , that avoids the issue of having duplicated index operations.

Let me know if you need more information.

Regards,
Jorge

**Comment by joshuacords** [comment]
Thank you for the detailed explanation!

**Comment by joshuacords** [comment]
Now that I can track all that's happening the code looks good to me

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
