### PR TITLE
LPS-145631 Sidecar bump + frontend test fix

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-145631

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:environment

**Comment by xbrianlee** [comment]
ci:test:environments

**Comment by xbrianlee** [comment]
ci:test:environments

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@xbrianlee should we bump this version too or not? https://github.com/liferay-search/liferay-portal/pull/280/commits/dc0e5ba800eaf769a93d2e5a5da4d6667e2919a8#diff-8ac3706389f58626da5f004132dedccae8432bb91f2aba8ba3d22755b59877b3R21

**Comment by BryanEngler** [comment]
`<property name="elasticsearch.version" value="7.16.3" />` in build-test-elasticsearch7.xml

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:environments

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:license

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:environments

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:environments

**Comment by BryanEngler** [comment]
Thanks Brian, im running a final set of tests here https://github.com/BryanEngler/liferay-portal/pull/630

**Pull request closed without merging**
