### PR TITLE
LPD-15803 Result Rankings are not applied to searches originating from Basic and Blueprints Suggestions Contributors

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-15803

Video testing:
[RR_apply_suggestions.zip](https://github.com/liferay-search/liferay-portal/files/14099174/RR_apply_suggestions.zip)

### CODE REVIEW

**Review by felipelorenz — APPROVED** [review]
LGTM!

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:2533106637

**Comment by gustavolimav** [comment]
search suit looks good

**Comment by gustavolimav** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
