### PR TITLE
LPS-151266 add version and key fields to sxp element and sxp blueprint sb

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-151266

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test;search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:forward

**Pull request closed without merging**
