### PR TITLE
LPD-2249 Search Bar Scope Everything doesn't return Site members documents results for Guest role if View Document scope isn't also All Sites And Asset Library

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-2249

### CODE REVIEW

**Comment by gustavolimav** [comment]
I identified code duplication between `SearchPermissionCheckerImpl` and `SearchPermissionDocumentContributorImpl`. These classes seem to have a high degree of similarity (around 80% similar code).

To improve code maintainability and reduce redundancy, I propose investigating this duplication and potentially open a new ticket to:

Refactoring: We can potentially refactor the common code into a reusable component that both classes can utilize.
Merging Classes: If the functionality is identical, we might even consider merging the classes entirely.

Other than that you must verify if the solution should be applied in `SearchPermissionDocumentContributorImpl` too.

**Review by gustavolimav — APPROVED** [review]
Hey @AlmirFe, the code LGTM! I think we should add test for this bug, you can use SearchPermissionCheckerImplTest to create a new test. 

@BryanEngler do you think we can forward it and create the test in a new ticket or are we expecting sending PR with the test already done?

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:search-opensearch2

**Comment by AlmirFe** [comment]
@gustavolimav there is already a task to implement tests for this ticket: https://liferay.atlassian.net/browse/LPD-6008

**Comment by AlmirFe** [comment]
@gustavolimav I created a new ticket to eliminate code duplication: https://liferay.atlassian.net/browse/LPD-25719

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:forward:force

**Pull request closed without merging**
