### PR TITLE
LPS-153813  Create API to get search indexes/LPS-163750

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Review by thektan — APPROVED** [review]
As far as the REST response data needed on the frontend, this is good to forward. Thanks @wcao20170619!

**Comment by BryanEngler** [comment]
@wcao20170619 thanks for the pr, a few things to address:

1) @wcao20170619 can you use LPS-163750 as the ticket number for the commits
2) @wcao20170619 separate the `rest-openapi.yaml` changes from the autogenerated `gw buildREST` changes into different commits. any auto-generated code should always be in its own, separate commit
3) @wcao20170619 in `rest-openapi.yaml`, can we change `fullName` -> `name` and `name` -> `suffix`? @thektan not sure if this would cause any updates to be needed in the front end?
4) @thektan i know you already confirmed, just wanted to double confirm that the front end expects the company index ("liferay-12345") to NOT be included in the response
5) @wcao20170619 its a minor thing, but i think `Objects.equals(indexName, indexNamePrefix + "0")` can be removed because the next condition `!indexName.startsWith(companyIndexName)` covers the "liferay-0" case?

**Comment by BryanEngler** [comment]
@wcao20170619 you could also call `ArrayUtil.remove(indexNames, companyIndexName);` before the loop and then the entire condition just becomes `!indexName.startsWith(companyIndexName)`

**Comment by thektan** [comment]
@BryanEngler @wcao20170619 

> 3. @wcao20170619 in rest-openapi.yaml, can we change `fullName` -> `name` and `name` -> `suffix`? @thektan not sure if this would cause any updates to be needed in the front end?

Yes, I'll update my frontend PR https://github.com/liferay-search/liferay-portal/pull/600 to reflect these changes.

> 4. @thektan i know you already confirmed, just wanted to double confirm that the front end expects the company index ("liferay-12345") to NOT be included in the response

Yup, the company index should not be included since the radio selection for "Default Company Index" would be saved as a blank string `{indexName: ""}` and "Configure a Different Index" would list everything excluding the default.

Screen Shot 2022-10-19 at 12 04 13 PM

**Comment by wcao20170619** [comment]
@BryanEngler for #1, do you want LPS-163750 or LPS-153813 LPS-163750 for the commits? For the URL of the ticket, do you want LPS-153813, LPS-163750, or both? thx

**Comment by thektan** [comment]
@BryanEngler Also I'm curious if the "Default" in "Default Company Index" makes sense from your point of view. I noticed Tibor had only "Company Index" as the selection but May had suggested "Default Company Index". I'm not sure if it's redundant or confusing.

**Comment by BryanEngler** [comment]
@wcao20170619 follow the format thats in the google doc i posted yesterday
```
LPS-153813 LPS-163750 message

https://issues.liferay.com/browse/LPS-163750
```

**Comment by BryanEngler** [comment]
@thektan in my opinion "Company Index" is probably better than "Default Company Index"

there is only 1 company index, so if theres no such thing as other "non-default" company indexes, i dont think we need to say "default" company index because then it might make people think there are other "company" indexes (which technically there are, for the other virtual instances, if more than one virtual instance exists). i guess people might not understand that the company index would be the default index we search, so "Default Index" (which is the company index) could be another option...

**Comment by thektan** [comment]
@BryanEngler Thanks! I'll adjust the naming to "Company Index" in my existing PR as well. That's what's written in the ticket as well. I wasn't sure if "Default Company Index" was technically correct so thanks for the explanation!

**Comment by lipusz** [comment]
Yeah, Company Index is better with the "Default" qualifier.

**Pull request closed without merging**
