### PR TITLE
Lps 153450 basic suggestions contributor test

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-153450

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:reevaluate:1367401_1774

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:reevaluate:1317401_4556

**Comment by BryanEngler** [comment]
i did some refactoring, running tests here https://github.com/BryanEngler/liferay-portal/pull/659

**Pull request closed without merging**
