### PR TITLE
[TS] LPS-161063 Missing WARN trace when there is a data inconsistency between Elasticsearch and Database entries

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
See https://issues.liferay.com/browse/LPS-161063

I am using exception.toString() instead of exception.getMessage() because the SF removes the ".getMessage()" and forces to display the entire exception stack trace in the log file.

My idea is to only display the entire exception stack trace if the customer enables the DEBUG traces and display the exception without the stack trace in the WARN case this will avoid flooding the customer log with stack traces.

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Rebased to latest master

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Rebased again, now using upstream/master

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
