### PR TITLE
LPD-2835 ElasticsearchStatusException "The number of terms exceeded the allowed maximum" (defined in index.max_terms_count) occurs on Elasticsearch 7 when there are more than 65536 inactive groups (users or sites) & LPD-23550 Create test to ensure that an ElasticsearchStatusException will not be thrown even if the number of terms exceeded the allowed maximum

### PR DESCRIPTION
**Pull request by AlmirFe**
### Previous PR: https://github.com/liferay-search/liferay-portal/pull/1332
- https://liferay.atlassian.net/browse/LPD-2835
- https://liferay.atlassian.net/browse/LPD-23550

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:help

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
test results look good! @BryanEngler can we forward it?

cc: @gustavolimav

**Comment by AlmirFe** [comment]
ci:forward:force

**Comment by AlmirFe** [comment]
The commits were forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/150262

**Pull request closed without merging**
