### PR TITLE
LPS-127030 Elasticsearch7 unit test NoClassDefFoundError and ExceptionInInitializerError failures

### PR DESCRIPTION
**Pull request by joshuacords**
Fixes regressions to Unit Tests caused by https://issues.liferay.com/browse/LPS-126920 

Author: @joshuacords 

cc: @brookedalton

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Added fix for ClusterExecutorImplTest.

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:reevaluate:1192004_7653

**Comment by joshuacords** [comment]
I'm sending to Matthew to review here: https://github.com/mtambara/liferay-portal/pull/1031

**Pull request closed without merging**
