### PR TITLE
LPS-178545 [BE] Create REST endpoint to return an sxp element with translated language keys

### PR DESCRIPTION
**Pull request by joshuacords**
**Subtask**: https://issues.liferay.com/browse/LPS-178545
**Story**: https://issues.liferay.com/browse/LPS-178417

Continued from https://github.com/liferay-search/liferay-portal/pull/925

**Author**: @joshuacords 
**Reviewers**: @gustavolimav, @peerkar 

I'm removed the use of the Service as per @peerkar [request](https://github.com/liferay-search/liferay-portal/pull/925#issuecomment-1557302010), and I've implemented the test as per @gustavolimav [request](https://github.com/liferay-search/liferay-portal/pull/925#issuecomment-1557053569).

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
LGTM

**Comment by joshuacords** [comment]
ci:forward-force

**Comment by joshchong** [comment]
ci:forward:force

**Pull request closed without merging**
