### PR TITLE
LPS-151266: Add version and key fields to SXPElement and SXPBlueprint entities

### PR DESCRIPTION
**Pull request by peerkar**
@gustavolimav please take a look and test the changes I did. See https://issues.liferay.com/browse/LPS-151266 for details.

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:stable

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:forward

**Pull request closed without merging**
