### PR TITLE
LPS-168236 Search results are not shown in Extranet Site

### PR DESCRIPTION
**Pull request by jkappler**
[Link to ticket](https://issues.liferay.com/browse/LPS-168236)

Dear Team, when checking the issue, I noticed that we don't take into account the widgets of a page that has a master page on first load, so I changed the code to take it into account.

Let us know what you think.

Thanks!

**Test Scenario**

Follow the steps in the ticket

@lfbesada

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:search

**Comment by joshuacords** [comment]
LGTM! :rocket:

**Pull request closed without merging**
