### PR TITLE
LPS-185632 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-185632

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search-remote

**Comment by brookedalton** [comment]
ci:test:search-remote-minimum

**Comment by brookedalton** [comment]
ci:test:search-as

**Comment by lipusz** [comment]
This probably also needs to be updated https://github.com/liferay-search/liferay-portal/blob/master/build-test-elasticsearch7.xml#L653 (https://github.com/o19s/elasticsearch-learning-to-rank/releases/tag/v1.5.8-es7.17.10)

**Comment by brookedalton** [comment]
ci:test:search-db-partition

**Comment by brookedalton** [comment]
ci:test:search-as

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
