### PR TITLE
LPS-173591 portal-search-web: Improve tests and apply specific context discribed in the Ticket

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-173591

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
Resent [here](https://github.com/liferay-search/liferay-portal/pull/823)

**Comment by joshuacords** [comment]
ci:stop

**Comment by joshuacords** [comment]
(you need to run "ci:stop" for each test)

**Comment by joshuacords** [comment]
ci:stop

**Pull request closed without merging**
