### PR TITLE
LPS-180395 AC suggestion contributor doesn't honor minimum searches configuration

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-180395

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
LGTM! :rocket:

**Comment by felipelorenz** [comment]
ci:reevaluate:1267401_9003

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
