### PR TITLE
LPS-205291 Activating another result ranking with same search query + scope is possible

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-205291 - Activating another result ranking with same search query + scope is possible

Changes:
- Add a check for when inactive result rankings are getting edited (it was returning earlier than expected)
- Throw duplicate exception during process when rankings get activated (original logic would throw duplicate exception at beginning without considering scope)
- Backend test fix in `RankingPortletDisplayBuilderTest`

Demo of behavior. Basically it activates each ranking one by one and stops if it hits the duplicate exception error. If there's no duplicate error, a not-applicable ranking warning would show at the end (if applies): 
https://github.com/liferay-search/liferay-portal/assets/14063502/41f021ed-c90b-4e0b-8f9c-4eabfc3770a1

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
https://github.com/liferay-search/liferay-portal/assets/2111174/7d0211f4-8e9d-4167-aa04-429c52f4c55b

@lipusz im testing this pr and im curious about this behavior... its not really consistent in the way that it activates duplicate inactive rankings, so...
seems that we should either 1) not activate the "alpha" ranking that does become active OR 2) also activate one of the "bravo" rankings and one of the "charlie" rankings...

i would probably lean toward option 2 (or just leave the current behavior, since the reported bug, which i guess is the important part of these changes, is resolved)

**Comment by BryanEngler** [comment]
i created a branch that processes all rankings (option 2 above), and includes some potential WIP (might need a little help @oliv-yu) for displaying more detailed errors on the UI
https://github.com/BryanEngler/liferay-portal/commits/2024_01_12_pr1217_liferay_search_LPS_205291_activate_duplicate_rankings_bug/

**Comment by oliv-yu** [comment]
@BryanEngler It looks like we can specify more detailed errors by passing info into SessionErrors, maybe this past example would help? https://github.com/liferay/liferay-portal/blob/d0fde45a6664d8b78a8644c9e1e8f4fa995746e0/modules/apps/commerce/commerce-order-content-web/src/main/resources/META-INF/resources/pending_commerce_orders/edit_commerce_order.jsp#L113-L127

**Comment by BryanEngler** [comment]
running tests here https://github.com/liferay-search/liferay-portal/pull/1221

**Comment by BryanEngler** [comment]
demo of behavior implemented in https://github.com/liferay-search/liferay-portal/pull/1221
https://github.com/liferay-search/liferay-portal/assets/2111174/5f3a60e7-6fbb-420f-9048-5c99fad0ce89

**Comment by oliv-yu** [comment]
Thanks @BryanEngler for updating that, the behavior is much better now! Closing this PR for https://github.com/liferay-search/liferay-portal/pull/1221

**Pull request closed without merging**
