### PR TITLE
LPD-23492 LPD-23487 Test Fixes

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-23492
https://liferay.atlassian.net/browse/LPD-23487

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search-opensearch2

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:report:63231223

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Review by oliv-yu — COMMENTED** [review]
Thanks for adding these changes, @joshuacords! 

It looks like `OpensearchSearch.testcase` repeats a lot of the `Search.testcase` except for the step in `AddSearchWidgetsOn__` to add an Elasticsearch Monitoring portlet (is that the only difference?). 

This seems like a lot of code to maintain? What are your thoughts on instead removing Elasticsearch Monitoring portlet from the original tests that were failing, so that `Search.testcase` could include the two search engines? We could maybe have a separate test to check Elasticsearch Monitoring portlet on content/widget pages (if needed), which runs only on elasticsearch7 with `property portal.suite.search.engine = "elasticsearch7"` individually set inside.

Let me know your thoughts, otherwise I don't have other suggestions for changes 👍

**Comment by joshuacords** [comment]
Yeah, that definitely seems better.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Hi @joshuacords! I'm not too sure about needing a new testcase for specifically ElasticsearchMonitoring? It also would work to just put the two new tests into `Search.testcase` and override inside the test with `property portal.suite.search.engine = "elasticsearch7"` like [this](https://github.com/liferay-search/liferay-portal/blob/93f6564f93e48166eb3ed8fd5b361f92ba652272/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/Search.testcase#L99).

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Hi @oliv-yu,

Made those changes - if the tests look good to you, could you ci:forward this?

**Comment by oliv-yu** [comment]
LGTM! I'll try forwarding

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
