### PR TITLE
LPS-163711 LPS-166197 

### PR DESCRIPTION
**Pull request by thektan**
Sending with both subtasks since their changes affect the same page.
- https://issues.liferay.com/browse/LPS-165821
- https://issues.liferay.com/browse/LPS-166197

## Summary of changes
- Updates the UI of the Semantic Search system settings page
- Adds an autocomplete input for selecting "Model" for hugging face sentence transform provider
- Adds a "Test Connection" button

### Semantic Search System Settings Page
Screenshot 2022-10-28 at 4 21 47 PM
Screenshot 2022-10-28 at 4 22 19 PM

### Model Autocomplete
Kapture 2022-10-28 at 18 37 56

### Test Connection
Kapture 2022-10-28 at 18 38 57

### CODE REVIEW

**Comment by thektan** [comment]
@oliv-yu Thanks for making those requested changes! I squashed all your changes into your first commit [6681af1](https://github.com/liferay-search/liferay-portal/pull/629/commits/6681af188e47fbbb204271eec77812ccb7680899) since they all seemed like code refactors for the original commit.

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
Failures don't seem related.

**Comment by thektan** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/125573

**Pull request closed without merging**
