### PR TITLE
LPS-199195 portal-search-solr8-impl: Bump apache zookeeper

### PR DESCRIPTION
**Pull request by gustavolimav**
Ticket: https://liferay.atlassian.net/browse/LPS-199195

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @gustavolimav, could you tell me about the changes to the bnd.bnd file? Were you cleaning up un-needed imports?

**Comment by gustavolimav** [comment]
Hello @joshuacords,

Absolutely, I can provide some insights. My approach involved understanding the role of ZooKeeper in our codebase. I discovered its usage in [CloudSolrClientFactory.java](https://github.com/liferay-search/liferay-portal/blob/master/modules/apps/portal-search-solr8/portal-search-solr8-impl/src/main/java/com/liferay/portal/search/solr8/internal/connection/CloudSolrClientFactory.java). To gain a deeper understanding, I referred to this [documentation](https://learn.liferay.com/w/dxp/using-search/installing-and-upgrading-a-search-engine/solr/installing-solr?p_l_back_url=%2Fsearch%3Fq%3Dsolr%2Bcloud&highlight=solr%20cloud#high-availability-with-solrcloud) on integrating ZooKeeper with Liferay.

Subsequently, I updated the dependency and attempted deployment. However, I encountered a recurring issue with a missing dependency every time I tried to deploy. To resolve this, I systematically removed each requested dependency until the deployment was successful. The only dependency I needed to add after some tests was zookeeper-jute.

**Comment by joshuacords** [comment]
Looks good! I'll forward it.

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
