### PR TITLE
[TS] LPS-158850 Content pages in search results dont link to the page of classPK for Layouts

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-158850

Notes from @javalosjr96:

> Ticket: [LPS-158850](https://issues.liferay.com/browse/LPS-158850)
> 
> Issue: Pages in search results do not link to the page.
> 
> Solution: Check if assetEntry's type is "layout", if so then use classPK instead of entryId

/cc @javalosjr96, @lr-cyun

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi @mbowerman,

As far as you can tell, has this always been a problem or is this a regression? Is there other asset types that need to be treated similarly?

Lastly, we like to have tests added for the bug behavior. Is this something you could add to this PR?

**Comment by mbowerman** [comment]
@javalosjr96 @lr-cyun Could one of you please address Joshua's questions above?

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lr-cyun** [comment]
Hi @joshuacords, Layouts was a special case because the Layout table uses plid rather than classPK from the AssetEntry table.

**Comment by joshuacords** [comment]
Hello @lr-cyun,
As far as you can tell, has this always been a problem or is this a regression? Is there another place in the code where AssetEntries and Layout are linked and special logic needed to be added?
Lastly, we like to have tests added for the bug behavior. Is this something you could add to this PR?

**Comment by lr-cyun** [comment]
Looks like the issue has always been a problem. It seems like testing never took into account the Display Selected Result in Context option. The issue also only affects Layouts in the search which we tested manually. We will write an integration test.

**Comment by lr-cyun** [comment]
Hi @joshchong,
For the integration test would we have to create test cases for each asset type or just layouts? Layouts seem to be the only type that uses plid as its primary key.

**Comment by joshuacords** [comment]
I'm just looking for testing the layout special case.

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Closed so it's in the overdue PR list unnecessarily

**Pull request closed without merging**
