### PR TITLE
LPS-199540 Refactoring of DefaultSearchResultPermissionFilter

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-199540

Previous PR: https://github.com/liferay-search/liferay-portal/pull/1199

Facet correction was removed as it did not work when a facet was selected as documents aren't returned in that case. Language key was also updated. But no other changes of significance to what Bryan said here: https://github.com/liferay-search/liferay-portal/pull/1199#issuecomment-1866795497 

**Authors**: @BryanEngler @joshuacords 
**Reviewers**: @joshuacords

Original PR here: https://github.com/liferay-search/liferay-portal/pull/1155

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
i think this looks good. i just fixed the semver failure and added a small SF commit, will forward from here - https://github.com/liferay-search/liferay-portal/pull/1207

**Pull request closed without merging**
