### PR TITLE
[TS] LPS-177249 Considering context path in search experiences

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

Can you review this pull request, please?

You can get more information in [LPS-177249](https://issues.liferay.com/browse/LPS-177249).

Thanks.

Regards.

### CODE REVIEW

**Comment by lipusz** [comment]
Hi @antonio-ortega 

Can you please,
* link the LPS in your message
* add the [TS] designation to the subject 
to follow our guidelines? 

https://liferay.atlassian.net/wiki/spaces/ENGSEARCH/pages/1507985561/How+to+send+pull+requests+to+the+Search+Team+liferay-search

Thanks!

**Comment by lipusz** [comment]
Soon we'll add this in an automatic message to PRs: https://issues.liferay.com/browse/LPS-176886

**Comment by lipusz** [comment]
Looks like there are SF errors.

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
Continued on https://github.com/liferay-search/liferay-portal/pull/820

**Pull request closed without merging**
