### PR TITLE
LPD-37742 Update Blueprints using Limit Search to These Sites Element to use ERCs

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-37742

Continued from: https://github.com/liferay-search/liferay-portal/pull/1518

**Author:** @felipelorenz 
**Reviewer:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:report:42294892

**Comment by felipelorenz** [comment]
ci:report:42318775

**Comment by felipelorenz** [comment]
ci:report:42383173

**Comment by felipelorenz** [comment]
ci:test:search

**Pull request closed without merging**
