### PR TITLE
LPS-183922 Remove 7.1 methods in PortletSharedSearchSettings

### PR DESCRIPTION
**Pull request by julschong**
@lipusz @peerkar 
Hi Petteri, Tibor, 
Per our discussion,
These methods were added back in 7.2 https://issues.liferay.com/browse/LPS-101007 to have two versions of the same methods for forward compatibility. Now in 7.4, there should be no need to do so anymore. We are removing these 71 methods here.

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@julschong I can see this in some place in the code base: `searchResponse.getDocuments71()`. What will happen to these after the removal?

**Comment by julschong** [comment]
@lipusz `searchResponse.getDocuments71()` and `getDocuments()` will remain the same in `portal-search` and `portal-search-api`. We are only getting rid of the redundant 71 methods in `portal-search-web` in this pull here since they are using Optional here that I'm trying to remove.

But looking at the implementation in SearchResponseImpl, `getDocuments71()` and `getDocuments()` actually have different behaviors. So, more review of the logic will need to take place when search team decides to remove them in the future.

**Comment by julschong** [comment]
@lipusz Hi Tobor,
Could you please help me move this forward if everything looks okay?
My next PR following this pull is the last one to conclude our team's big high priority task here: https://github.com/julschong/liferay-portal/pull/860
Thanks!

**Comment by lipusz** [comment]
Hi @julschong ,

This ticket is in our next sprint candidates list. If it  can't wait until next week when we start a new iteration, can you please ping our EPM, Bruno Falcao and ask him if someone from engineering could review it today or tomorrow?

Thanks!

**Comment by lipusz** [comment]
Looks like there are merge conflicts in the breaking changes md.

**Comment by julschong** [comment]
resolved conflict

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:search

**Comment by julschong** [comment]
@lipusz @joshuacords @brookedalton I'm forwarding this since tests all passed

**Comment by julschong** [comment]
ci:foward

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
