### PR TITLE
LPD-6008 Implement tests to "everything" scope

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-6008

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:report:2573481545

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by AlmirFe** [comment]
ci:forward

**Pull request closed without merging**
