### PR TITLE
LPS-181689 search-experiences-service: Fix bug with db partition

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-185342
https://issues.liferay.com/browse/LPS-185343

Bchan spotted a bug in the db partition: https://github.com/brianchandotcom/liferay-portal/pull/135686#issuecomment-1571370289

When DB Partition is enabled, every company has its own database schema. That's why we need to use `_companyLocalService.forEachCompanyId`

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search-db-partition

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Hi @gustavolimav, the SF error is the SXPBlueprintLocalServiceImpl ln 160 line return. I'm guessing the call should all fit on 1 line.

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search-db-partition

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search-db-partition

**Comment by gustavolimav** [comment]
ci:test:search-db-partition

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Ah, looks good :+1:

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search-db-partition

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
Pull Request forwarded: undefined

**Comment by gustavolimav** [comment]
Pull Request forwarded: https://github.com/brianchandotcom/liferay-portal/pull/136046

**Pull request closed without merging**
