### PR TITLE
LPS-165348 LPS-165349 [FE] Apply JS Local/Session Storage Management API in Search experiences components

### PR DESCRIPTION
**Pull request by thektan**
Task: https://issues.liferay.com/browse/LPS-165348
Subtask: https://issues.liferay.com/browse/LPS-165349

**Dev Notes:**
- `sessionStorage`'s `getItem` and `setItem` takes in an extra parameter for `CONTENT_TYPES`. See the new util method here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/storage.js
- The success toast is marked as `NECESSARY` since it provides a success message when a blueprint or element is saved or created.
- The Add Element sidebar open state is marked as `FUNCTIONAL` since it's a preference for the sidebar state should be remembered as opened or closed. If this cookie is disabled, the sidebar will always start as closed when switching between tabs in the Edit Blueprint page.

### CODE REVIEW

**Comment by thektan** [comment]
ci:stop

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:forward:force - test failures are unrelated.

**Pull request closed without merging**
