### PR TITLE
LPS-116907 - Search bar with federated search key returns no results

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-116907

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Looking into the ci:test:search `LocalFile.Elasticsearch7#SearchWithNonLiferayIndex` failure. 

I was able to locally reproduce at first, but after rebuilding portal and starting a clean database, this didn't seem to be an issue anymore. Running the test by itself at https://github.com/thektan/liferay-portal/pull/194 to make sure it's not something flaky or unrelated to these changes.

**Comment by thektan** [comment]
Added additional changes (8aaa55b) since I noticed the Custom Filter Widget was not being displayed if it had a federated search key. This isn't related to the test failure, but this should be added to follow the same changes that were made in the Search Results Widget.

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Waiting for test fixes before forwarding to master.

> This will require test fixes for LocalFile.Elasticsearch7#SearchWithNonLiferayIndex. Looks like the setup for the test is missing a configuration for the search bar's federated search key to "s1". [(Jira comment)](https://issues.liferay.com/browse/LPS-116907?focusedCommentId=2206234&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2206234)

**Comment by joshchong** [comment]
Added functional test fix and forwarding here: https://github.com/liferay-search/liferay-portal/pull/7

**Pull request closed without merging**
