### PR TITLE
LPS-148412 Modify ModelVisibilityContributor to add isVisible default method

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-148412

Hi Team,

This pull request modify ModelVisibilityContributor to add a default method in order to avoid the duplicated code in all its implementations.

Please see: https://github.com/brianchandotcom/liferay-portal/pull/114022#issuecomment-1055989150

Could you please review it?

Thanks!

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:relevant

**Comment by wcao20170619** [comment]
ci:forward

The errors (from ci:test:search) are not related to this PR(also verified that failed tests worked well in my local system).

cc @lfbesada

**Pull request closed without merging**
