### PR TITLE
[Deprecate unused method from Document]Lps 188914 7 10

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-188914

### CODE REVIEW

**Comment by dantewang** [comment]
cc @tinatian

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:search

**Comment by slnn** [comment]
Forced push to solve the conflict about markdown file, no logic changes

**Comment by BryanEngler** [comment]
@slnn This looks good to me, can we forward it or do you want it to also be reviewed by another team first?

**Comment by slnn** [comment]
> @slnn This looks good to me, can we forward it or do you want it to also be reviewed by another team first?

Thank @BryanEngler!

/cc @dantewang

**Comment by dantewang** [comment]
@BryanEngler It looks good to us either. I think we can just forward.

**Comment by BryanEngler** [comment]
forwarding from here https://github.com/BryanEngler/liferay-portal/pull/734

**Pull request closed without merging**
