### PR TITLE
LPD-28164 Break terms query when "The number of terms exceeded the allowed maximum"

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-28164

Sending again a solution for this Error because it was not tested the right way before, now it was tested manually and new tests were added to make sure it works fine.

Basically we had other place where Terms could generate the error.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:14056672

**Comment by gustavolimav** [comment]
ci:report:19466086

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:stop

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:20593975

**Comment by gustavolimav** [comment]
ci:report:20660240

**Comment by gustavolimav** [comment]
ci:report:20599466

**Comment by gustavolimav** [comment]
ci:report:20593975

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:report:22722690

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:report:23531714

**Comment by gustavolimav** [comment]
ci:report:23587436

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
