### PR TITLE
LPD-15374 - Reuse Site Item Selector in Blueprints

### PR DESCRIPTION
**Pull request by oliv-yu**
Continued from https://github.com/liferay-search/liferay-portal/pull/1244

https://liferay.atlassian.net/browse/LPD-6707 - "Limit Search to These Sites" OOTB SXP Element features a Site Selector so the user can browse and select the sites to limit the search without the need look-up and copy-paste the group IDs (Site IDs)
https://liferay.atlassian.net/browse/LPD-15374 - Reuse Site Item Selector in Blueprints

Motivation
-----
Avoid duplicated logic when we are selecting sites.

Proposed Solution
-----

Replace custom selector modal with openSelectorModal and item selector url for sites. Like we did for Results Rankings.

The multiple selection should be working if you select site one by one:

https://github.com/liferay-search/liferay-portal/assets/14063502/e83673e0-a878-41ab-b886-0319d4a432f4

@lipusz Moved the LPD subtask to the correct story and renamed the commits, also cleaned up some of the frontend. Thank you for working on this, @ealonso!

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:report:2530385185

**Comment by BryanEngler** [comment]
ci:report:2530385185

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:stop

**Comment by BryanEngler** [comment]
ci:forward:force

**Pull request closed without merging**
