### PR TITLE
LPS-179845: Headless portal search endpoint 

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-179845

Tests will follow in https://issues.liferay.com/browse/LPS-181827

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
Hey @peerkar, the test results look good except for one semantic versioning issue within `portal-search/portal-search-api`:
```[Baseline Warning] Bundle Version Change Recommended: 11.4.0```

Once that is resolved, you can push up your changes with `ci:forward:force` if you're ready. No need to rerun any other tests.

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:forward:force

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
Resending in https://github.com/brianchandotcom/liferay-portal/pull/133652

**Comment by brookedalton** [comment]
ci:stop

**Pull request closed without merging**
