### PR TITLE
LPS-196804 Category Facet - Cannot select vocabularies from Asset Libraries

### PR DESCRIPTION
**Pull request by thektan**
https://liferay.atlassian.net/browse/LPS-196804

In the category facet configuration:
- Allows vocabularies from asset libraries to display
- Filters out the global vocabularies for the other sites (so only the global vocabularies will be displayed under the "Global" site)

## Screenshot with fix
Screenshot 2023-09-20 at 6 39 43 PM

cc @joshuacords

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Nice!

**Comment by oliv-yu** [comment]
@thektan Looks good to me! Since this was added for the Category Facet configurations, not sure if we'd also want to add it here as well for the category selector in blueprints? https://github.com/liferay-search/liferay-portal/blob/ab84df048550a82e8b3762e30566b4f14ba0fda5/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_admin/js/shared/sxp_element/category_selector_input/index.js#L362-L389

I think for that one it'd just be slightly different since the id was added to the list of items as a number `Number(Liferay.ThemeDisplay.getCompanyGroupId())`

**Comment by thektan** [comment]
Makes sense, I'll update it for blueprints as well.

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
@thektan, @oliv-yu, Is this ready to be forwarded?

**Comment by thektan** [comment]
@joshuacords Oh, yes it is!

**Review by oliv-yu — APPROVED** [review]

**Comment by oliv-yu** [comment]
@joshuacords yup, thanks for asking!

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
