### PR TITLE
LPS-120846 Additional updates to the bundle localizations for the renamed LES apps

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-120846

Hi Brian, please backport these changes to 7.3.x. Thanks!

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:forward

**Comment by joshchong** [comment]
Manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/95707

**Pull request closed without merging**
