### PR TITLE
Fixes more than just search....

### PR DESCRIPTION
**Pull request by rbohl**
As reported by @oliv-yu, our search in-product links were broken. I fixed all the links in the learn-resources JSON files.
https://liferay.atlassian.net/browse/LPD-27012

I think when we send it we need to ask Brian to publish the learn resources as well

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hey Russ,

Thanks for catching and fixing it: :clap: 

One question: I saw this comment on the Slack thread:

> Hi, 
Olaf Kock
Thanks for repporting. At the moment, 
Jamie Sammons
 is working on these Learn's broken links and redirects. He is on PTO today and yesterday was holiday in the US, but I'm leaving him a message so he can take a look when he arrives.
cc: 
Caio Machado

Doesn't this change require some coordination with Jamie?

**Comment by lipusz** [comment]
@sammonsjl

**Comment by rbohl** [comment]
> ...Learn's broken links and redirects...

So, if they restore the redirects in Learn, these would be fixed. But I figured we could just fix these to go to the correct articles, avoiding the need for redirects. It doesn't fix learn's problem, but it's a solution for our in-product links. Is there some risk I might be missing?

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:report:2573380597

**Comment by oliv-yu** [comment]
Not sure why relevant seems to be stuck in pending, I'll try forwarding since it would run relevant anyway if it doesn't consider it green.

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
