### PR TITLE
LPS-153450 unit tests for BasicSuggestionsContributor

### PR DESCRIPTION
**Pull request by wcao20170619**
https://issues.liferay.com/browse/LPS-153450

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@wcao20170619 im thinking the tests would be more comprehensive if we ran asserts against an actual SuggestionsContributorResults object instead of a mocked one... there doesnt seem to be a whole lot of coverage on the actual logic with the current set of tests. i pinged @lipusz to see if he has any input on this

**Comment by wcao20170619** [comment]
@BryanEngler I think that both unit tests have around 90%  code coverage and our QA team will run the coverage tool to verify this. I am not sure that 'asserts' will be more comprehensive than 'verify'. In some cases of these tests, we would have the same SuggestionsContributorResults(such as SuggestionsContributorResults=null) with different inputs. In that case, the 'verify' is the only option we should use to make sure the test goes the test routine.

**Comment by BryanEngler** [comment]
i dont think it would be too much more effort and then we would have very solid tests, so lets change it to return a real SuggestionsContributorResults, assert getDisplayGroupName, and getSuggestions -> getAttribute/getScore/getText

let me know if you have any questions, thanks!

**Pull request closed without merging**
