### PR TITLE
LPS-191998 Result Rankings error when trying to add two existent queries

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-191998 - Result Rankings error when trying to add two existent queries

Two updates, after reading Petteri's comment:
- Include `DuplicateQueryStringException` in the check for exceptions, in order to forward to the edit page.
- I wasn't sure exactly why an example like "apple,pen" doesn't get split into "apple" and "pen" only in this particular case, but this change just takes the alias array and appends each value individually, to avoid that from happening. This is only in the validate step.

Demo:
https://github.com/liferay-search/liferay-portal/assets/14063502/39d2a246-1a9c-4667-8b4a-6ac627fa5ff8

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:relevant

**Review by thektan — APPROVED** [review]
LGTM!

**Comment by CaiocSiqueira** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
