### PR TITLE
LPS-202739: Align headless search API result summaries with the search widgets

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-202739

**Notes:**
This aligns the creation of search result item summaries in headless search API with the search widgets. Summary creation in search widgets relies on Indexer.getSummary() (see an example [here](https://github.com/liferay/liferay-portal/blob/fbe589eb729529318c9cc3232010549611fa1564/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/result/display/context/builder/SearchResultSummaryDisplayContextBuilder.java#L460-L461)) where the API requires PortletRequest and PortletResponse. To overcome this ModelSummaryContributors are called here directly.

Another issue was that the Locale resolution in `ModelSummaryContributor.getSummary() `  relies on `LocaleThreadLocal.getThemeDisplayLocale()`. It had to be set manually here.

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:test:search

**Pull request closed without merging**
