### PR TITLE
LPS-162054 Custom facet ordering

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-162054

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
LGTM

**Comment by joshuacords** [comment]
Hi @felipelorenz, I would still like the tests to be simplified - currently each test is testing 2 scenarios, but the first scenario is unnecessary as it's already covered by the second scenario. Please reduce the tests down to 1 scenario each and remove any unnecessary variables when you do. Thanks

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:relevant

**Pull request closed without merging**
