### PR TITLE
LPS-163949 search-experiences-web: Sort parameters inside util function validateRequired

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-163949 - Change validateRequired so this can be sorted

Sorted parameters + updated all places where `validateRequired` was called. Also added two frontend tests since it looks like there's no coverage for varied `nullable` and `required` parameters. Let me know if I should add anything else! Thanks

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Thanks! Looks good 👍

**Comment by joshchong** [comment]
I was investigating the test failures but I haven't been able to reproduce the issue manually. I reran the test on CI with this branch and it passed so the failure might have just been a fluke. I'll forward this PR for now and we'll continue monitoring the test.

**Comment by joshchong** [comment]
ci:forward

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/123851

**Pull request closed without merging**
