### PR TITLE
[TS] LPS-124886 Cannot exclude Asset Types from search results

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:forward

**Comment by brandizzi** [comment]
ci:forward

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by joshuacords** [comment]
ci:forward

**Comment by istvansajtos** [comment]
ci:reevaluate:1142004_7746

**Comment by istvansajtos** [comment]
It seems the change in TypeFacetPortletPreferencesImpl causes JSP compilation problem.

```
     [exec] > Task :apps:portal-search:portal-search-web:compileJSP FAILED
     [exec] 
     [exec] > Task :apps:portal-security:portal-security-api:compileJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search/portal-search-web/build/jspc/org/apache/jsp/type/facet/configuration_jsp.java:229: error: constructor TypeFacetPortletPreferencesImpl in class TypeFacetPortletPreferencesImpl cannot be applied to given types;
     [exec] TypeFacetPortletPreferences typeFacetPortletPreferences = new com.liferay.portal.search.web.internal.type.facet.portlet.TypeFacetPortletPreferencesImpl(java.util.Optional.of(portletPreferences));
     [exec]                                                           ^
     [exec]   required: Optional<PortletPreferences>,SearchableAssetClassNamesProvider
     [exec]   found: Optional<PortletPreferences>
     [exec]   reason: actual and formal argument lists differ in length
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-search/portal-search-web/build/jspc/org/apache/jsp/view_jsp.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
```

**Comment by joshuacords** [comment]
I'm looking into these failures

**Comment by joshuacords** [comment]
Continued at #89 with jsp fix.

**Pull request closed without merging**
