### PR TITLE
LPS-196807 Older versions of Web Content are indexed with the newest version's values

### PR DESCRIPTION
**Pull request by lfbesada**
Hello Team :wave: 

This PR has been reviewed by the Echo Team [here](https://github.com/liferay-echo/liferay-portal/pull/13943), but [this commit](https://github.com/liferay-search/liferay-portal/commit/136ebe6cecb633951a2d04e672f412d40ad99e16) is on your components, could you please review it?

Thanks in advance!

This PR fixes two bugs:
https://liferay.atlassian.net/browse/LPS-196807
https://liferay.atlassian.net/browse/LPS-198486
On already existing content, a reindex is needed to fix these issues.

**Motivation**

When content that has asset entries is reindexed, the different AssetEntry contributors add fields to the content based on information related to its assetEntry.
Journal articles have versions and not all of them have asset entries. 
Currently, the no-latest article published versions are processed assuming that their assetEntry was the latest published one, and that is not correct.
This PR adds a new method in AssetRendererFactory to get the AssetEntry from the base model and delegates the calculation of the entryClassPK field to that method. It is taking into account that the base model could have no asset entry, so its entryClassPK is going to be 0. So, from now on, for those articles that do not have any asset entry, its entryClassPK is going to be 0.
Consequently, the AssetEntryDocumentContributor does not add fields for versions that do not have an entry, which fixes the original bug.
The same logic manages to fix LPS-198486 because AssetTagDocumentContributor and AssetCategoryDocumentContributor receive 0 as entryClassPK so they do not use the categories and tags published for the other versions.

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
ci:test:depot

**Comment by lfbesada** [comment]
ci:test:knowledge-base

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:search

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
Hi @lfbesada, the LGTM code, but since it touches on some core search classes, I'd like @BryanEngler to take a look at it before moving forward.

He'll be able to take a look at it next week.

**Comment by joshuacords** [comment]
Hello @lfbesada,

Sorry for the delay in reviewing. In general the code is looking pretty good, I like that the latest searchable version of the JournalArticle will maintain the same entryClassId.

I found a bug though:

1. Create a Web Content "WC 1.0" and publish it
2. Edit it the WC to by "WC 1.1" and publish it
3. Check what's indexed using Kibana, WC 1.1 is indexed with an entryClassId and all the titles reflect "WC 1.1". WC 1.0 is indexed with 0 as the entryClassId and all titles reflect "WC 1.0"
4. Delete WC 1.1
5. Check what's indexed using Kibana

**Expected:** WC 1.1 is indexed with an entryClassId and all the titles reflect "WC 1.1". WC 1.0 is indexed with 0 as the entryClassId (?) and all titles reflect "WC 1.0"

**Actual:** WC 1.1 is indexed with an entryClassId and all the titles reflect "WC 1.1". WC 1.0 is **indexed with a non 0 entryClassId** and all titles except title_en_US reflect "WC 1.1"

**Comment by joshuacords** [comment]
I also wanted to note that extra fields are being index for older versions of the article. Here's an example:

1. Create Web Content Article "WC 4.0"
2. Check out what's indexed in Kibana [WC 4.0 after a new version was published.txt](https://github.com/liferay-search/liferay-portal/files/13127680/WC.4.0.after.a.new.version.was.published.txt)
3. Edit the Web Content Article and save
4. Check out what's indexed in Kibana for WC 4.0, the old article [WC 4.0 after initial creation.txt](https://github.com/liferay-search/liferay-portal/files/13127681/WC.4.0.after.initial.creation.txt)
**Actual Result:** 22 more fields are indexed when the article isn't the latest version.

**Expected Result:** Fields such as title_es_ES and urlTitle_es_ES should be present in both cases.

**Pull request closed without merging**
