### PR TITLE
[TS] LPS-119230 Ghost facets - permissions error

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-119230 

**Author**: @joshuacords

I need feedback on the direction of this fix. This prototype is working for DLFileEntries and DLFolders, but the final fix will be Bookmarks and their folders, JournalArticles and their folders, and MessageBoards and MessageCategories. I haven't figured out tests yet, you can look at the LPS for reproduction steps. I wanted to make sure I was on the right path before investing any more in this direction. Part of this fix is a permissions issue which I am talking to a core engineer about, the other part is indexing which I need feedback on. I'll list the particular commits which need review.

**Issue:** When a foldered object is indexed into a search engine, we index all permissions of that object. However, this is problematic because it ignores the Dynamic Inheritance Permissions of parent objects and folders. If a object's parent's permissions restricts the roles able to view the object, the search query used will not filter out those objects and they will be returned. In most cases this is okay, because we have post filtering which removes the objects returned for which the user doesn't have permissions. This step also decrements the counts of the facets. BUT, in the case where we select a facet, the other selectable options in that same facet are calculated by the search engine, and because the objects are never returned it is impossible to do post filtering to decrement counts. This results in facet counts revealing the number and type of content the current user doesn't have permission to see.

**Solution:** We need to index the objects with their Dynamic Inheritance Permissions (and keep them up to date) so that we can trust the facet counts. I'm working with a core engineer to get the getDynamicInheritanceRoles method needed. 

Commits to review:
**Addresses indexing dynamic inheritance:**
https://github.com/liferay/liferay-portal/commit/69b2c1e7c5ec5aed8621ff96d29ec6dddf9378a9 LPS-119230 portal-search: use dynamicInheritanceRoles when indexing
https://github.com/liferay/liferay-portal/commit/88cf7708aced953209a761793c7949f2c1ca6139 LPS-119230 portal-search: add groupId to document for use by SearchPe
https://github.com/liferay/liferay-portal/commit/4add93d2262e246396bee48a02df40d5ccd96b6a LPS-119230 document-library-service: cascade reindex child DLFolders (When indexing a DLFolder, checks to see if permissions were modified in comparison with what is indexed. If so, will recursively reindex the permissions of all child folders and their objects. Note, it didn't seem worth it to check each DLFolder for permissions changes during the recursion, but perhaps more checks could be worthwhile as many clients have large numbers of documents.)

**Addresses Partial Reindexing bug:**
https://github.com/liferay/liferay-portal/commit/b0d8e71ff7df58bf806702a46bdb91a17e192afd LPS-119230 portal-search-elasticsearch7-impl: Update expectations of … (Partial reindexing used in the above commit has a bug. When the document in ES has a field with a value, and the new value is empty, our addField Logic doesn't add the field to the request. This results in the original value persisting in the search engine.)
https://github.com/liferay/liferay-portal/commit/a8029d8302458dbe93131db570574f0d19590139 LPS-119230 portal-search-elasticsearch7-impl: allow for empty values (The changes to the addField Logic to index "" instead of having no field, insuring that the old value is overwritten. Note: there is ES API to r[emove fields during a partial reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) however I looked into how to implement this and it seems far too complicated.)
https://github.com/liferay/liferay-portal/commit/a919b9d83c3b3896878f73d699752b75ae5b3283 LPS-119230 portal-search: allow for empty values in portal.search.Fields

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
ci:test:search:norebase

**Comment by lipusz** [comment]
I'll do a review on this from both search and security pov next week. @lipusz TODO

**Comment by lipusz** [comment]
**Started reviewing...** :mag::nerd_face:

**Comment by lipusz** [comment]
@joshuacords One of my immediate questions (still reviewing though): how would it work during a full reindex?

**Comment by joshuacords** [comment]
Hi @lipusz,

My power was out Monday and then I had a migraine yesterday, sorry for the late response. You're absolutely right - a full reindex is much worse now as each document would need to be checked :(. If there was a way to know if a full reindex was happening we could remove the check during that time. The other problem is the change of indexing "" when a field is blank breaks Result Rankings. I'm planning to talk to Andre about these things.

**Comment by joshuacords** [comment]
@lipusz, 

After talking to Andre and considering your feedback about reindexing, I'm going to rework the approach of this fix. My 2 improvements would be to look into triggering the cascade reindexing from the LSI so that we avoid cascading during full reindexing. It would also be better to not call other indexing within a contributor.
I also need a better solution for remove fields from documents during a partial reindex. (My attempt at a fix is what caused the Result Rankings failures.)
If you already had some input let me know - otherwise I'll just be moving forward on this.

**Comment by lipusz** [comment]
We can schedule a call to discuss this issue together with André.

**Pull request closed without merging**
