### PR TITLE
LPS-117494 - Escaped HTML tags appearing in search results corresponding to WC summary

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-117494

TS ticket forwarded from https://github.com/thektan/liferay-portal/pull/198

cc @jonmak08

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
Assigned LPS to Search QA to make a test fix for `Search#SearchXSSAsset`. https://issues.liferay.com/browse/LPS-117494?focusedCommentId=2210123&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2210123

**Comment by joshchong** [comment]
These changes introduce an XSS vulnerability. See [explanation here](https://issues.liferay.com/browse/LPS-117494?focusedCommentId=2210274&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2210274).

**Pull request closed without merging**
