### PR TITLE
LPS-166098 Semantic Search can be enabled as a Beta Feature - Part 1.

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-166098

Hi Brian,

I'm sending the initial changes so we can leverage the new FF UI and Semantic Search can be enabled as a Beta feature according to the decision we made with @marco-leo earlier.

Note: currently if I add `feature.flag.LPS-163688.status=beta` under the FF section, SF wipes it out, so I moved it under the FF UI category as per Drew's suggestion. :thinking: 

image

Russell is working on resuming and finalizing the first version of the docs by the end of next week. :writing_hand: 

/cc @drewbrokke @rbohl

### CODE REVIEW

**Comment by lipusz** [comment]
@joshchong fyi, I'm testing these changes, nothing should be broken I believe

**Comment by lipusz** [comment]
@ling-alan-huang fyi, Just wanted to let you know that `PropertiesFeatureFlagsCheck` may need to be adjusted to account these new feature.flag suffixes in `portal.properties` as per https://github.com/brianchandotcom/liferay-portal/pull/127704/files

Currently, when I add `feature.flag.LPS-163688.status=beta`, SF wipes it out. thinking.

**Comment by ling-alan-huang** [comment]
@lipusz I will have a lookt at it later.

**Comment by ling-alan-huang** [comment]
Hi @lipusz 
I can see `feature.flag.LPS-122920.status=beta` was removed.
My question is what is the pattern for `feature.flag.LPS-122920.status=beta` in the code?

**Comment by lipusz** [comment]
@ling-alan-huang I think you should ping @drewbrokke for details

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
@lipusz the tests results look good to me :+1:

**Comment by lipusz** [comment]
Waiting for https://issues.liferay.com/browse/LPS-172161 to be merged as currently I can't enable Semantic Search through the UI.

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
Hi @joshchong 

If `relevant` will fail again, can you please look into it and maybe forward manually to BChan (with preserving the message from the beginning)? 

Thanks!

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:forward:force - tests look good to me.

**Comment by joshchong** [comment]
ci:forward:force

**Pull request closed without merging**
