### PR TITLE
LPS-171159 search-experiences: buildService

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-171159

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
Hey @joshuacords, can you review it one more time?
Bchan asked for some [changes](https://github.com/brianchandotcom/liferay-portal/pull/130814#issuecomment-1445038323), I wasn't aware of the pattern before, but now that I know, I'll be sure to keep it in mind for future reference. Also, just wanted to confirm that I've made the requested changes as per bchan's request. Let me know if there's anything else I can do. thx!

**Comment by gustavolimav** [comment]
If the tests are ok and @joshuacords reviews that I will solve the conflicts by run buildLang again and sent it directly to bchan

**Comment by joshuacords** [comment]
Good to go.

**Pull request closed without merging**
