### PR TITLE
LPD-37356 delete text embedding contributor

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-37356

From here https://github.com/liferay-search/liferay-portal/pull/1493

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:27404298

**Comment by joshuacords** [comment]
Asked CI about Relevant not running: https://liferay.slack.com/archives/C19PWQ74J/p1727903604507029

Regardless, since this passed ci:test:search this can be forwarded.

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
