### PR TITLE
LPS-146638 Make Blueprint Options instanceable

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-146638

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi @gustavolimav,

Notice the ci:test:sf failed. Be sure to run gw formatSource on modules after you make changes to insure the source formatting is correct.

**Comment by gustavolimav** [comment]
> @gustavolimav Did you discuss https://issues.liferay.com/browse/LPS-146638?focusedCommentId=2612046&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2612046 too with @arboliveira ?

@lipusz Andre just confirm what we expected: https://issues.liferay.com/browse/LPS-146638?focusedCommentId=2612078&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2612078

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by lipusz** [comment]
Let me ask it this way: if you have a page with the Blueprints Options widget, added BEFORE the fix, it still wont

**Comment by joshuacords** [comment]
I can confirm, only after manually re-adding the portlet does the fix work since the instance id is missing. I'm not sure how we would approach an upgrade step, it seems we would need to run through all Content Pages and update any Search Blueprints Options we found to be instantiable. Yuck. Any better way comes to mind?

**Comment by lipusz** [comment]
Considering that it probably hasn't been adopted much, I think we could just note it as a fix notes on the ticket without addressing it programmatically.

**Comment by lipusz** [comment]
If it comes back later we can look into it.

**Comment by joshuacords** [comment]
Please! :pray:

**Comment by joshuacords** [comment]
@gustavolimav if you can fix the rebase error (just cherry-pick what you're doing onto the latest master) and force push, I think we can forward this after tests.

**Comment by lipusz** [comment]
Just wanted us to consider additional aspects. Now that it's released, we don't have the luxury anymore to focus on new installations only.

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@gustavolimav I've never seen the `SXPBlueprintSearchResultTest.testBoostFreshness` test failure before so it may or may not be caused by this PR. Can you look into it?

**Comment by joshuacords** [comment]
@joshchong I ran the test on my local machine without failures. Maybe a flaky test??

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:forward

**Pull request closed without merging**
