### PR TITLE
[TS] PTR-2181 Solution guidance of LPS-123694 - Backend code and new BaseNestedFieldsFacetTestCase test

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/PTR-2181
https://issues.liferay.com/browse/LPS-123694

This pull request contains the backend code and the new BaseNestedFieldsFacetTestCase requested in https://issues.liferay.com/browse/PTR-2181?focusedCommentId=2357848&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2357848

The new BaseNestedFieldsFacetTestCase test extends the existing BaseSimpleFacetTestCase 

Let me know if you have any question

/cc @lipusz

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
The CI tests were run correctly in this PR https://github.com/jorgediaz-lr/liferay-portal/pull/329, I am executing them again.

**Comment by lipusz** [comment]
Hey @BryanEngler 

This is the changes we'd you to take a look at and discuss with André.

**Comment by jorgediaz-lr** [comment]
**Additional note**

This PR doesn't include any user interface change.

I have implemented two alternatives, see the explanation in the https://issues.liferay.com/browse/PTR-2181

- Option 1: Calculate the nested field query parameters from the DDM field, see: https://github.com/jorgediaz-lr/liferay-portal/compare/LPS-123694_nested_facet_backend...LPS-123694_ddm_auto
- Option 2: Let the final user to fill in the nested field query parameters from the UI, they will have to to find out them from the DDM field: https://github.com/jorgediaz-lr/liferay-portal/compare/LPS-123694_nested_facet_backend...LPS-123694_new_parameters

**Pull request closed without merging**
