### PR TITLE
LPS-149053 intermittent assertion errors for sxp element resource test 

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-149053

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Testing in https://github.com/liferay-search/liferay-portal/pull/347

**Pull request closed without merging**
