### PR TITLE
LPS-145631

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-145631

Currently running tests.

**Author**: @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
Besides the minor test failure this is looking good. I haven't considered https://github.com/liferay/liferay-portal/pull/4581#discussion_r798372416 yet. (using the elasticsearch.yml file for settings instead of hardcoding).

**Comment by joshuacords** [comment]
CI Tests can be run once @BryanEngler is able to upload legacy-geo to nexus.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
do we need the 7.16 Distribution classes for something?

**Comment by joshuacords** [comment]
Do we need any alternative Distributions at all? Any objection to removing all the ones we're not using?
@BryanEngler

**Comment by BryanEngler** [comment]
We probably dont... but the pattern does exist so there could be a reason for it. Cant really say off the top of my head whether it would be safe to remove versions that are already out there

**Comment by lipusz** [comment]
What's the point of having alternative distributions when it can only be changed programmatically? 🤔

**Comment by lipusz** [comment]
If the Sidecar version would be configurable I could see it justified, but now...

**Comment by BryanEngler** [comment]
ya i know the sidecar path is configurable, but thats only for sidecar dirs that already exist... the sidecar.version file probably could be changed manually by a user, but that and sidecar in general is not a "supported" env, so we can probably do what we want with it... in the past i did create a generic Dist class when we removed checksums, but deleted it once we put checksums back. could probably reimplement it... https://github.com/liferay/liferay-portal/commit/2b9491dbd74381c77283de293381bc2b5862b305#diff-23709f68835f88ac48ddd311dba1fe4d0041acf82d2a8e2dee8653207cae6152

**Comment by BryanEngler** [comment]
not sure if its really worth the extra effort to remove past versions, but probably wouldnt take more than a few min so i guess its not a big deal

**Comment by BryanEngler** [comment]
it wouldnt have an affect on our different CI suites right? i think those use remote when testing different/"minimum" versions

**Comment by lipusz** [comment]
It'd surprising having test suites which runs with different Sidecar versions

**Comment by lipusz** [comment]
Yeah, the min/max are for remote mode afaik

**Comment by lipusz** [comment]
We'll see if it's not 🙈

**Comment by lipusz** [comment]
What I meant by not being configurable was that it's not configurable through portal-ext or .config. Customizing the sidecar.version file in a release bundle is beyond what I would consider as configurable.

**Comment by lipusz** [comment]
And it's not even documented so should not be problem

**Comment by joshuacords** [comment]
I'll make a general distribution, remove the rest, still using checksums.

**Comment by joshuacords** [comment]
ci:test:search

**Pull request closed without merging**
