### PR TITLE
LPS-172161 Semantic Search Instance Settings always displays System Settings values

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-172161](https://issues.liferay.com/browse/LPS-172161).

I manually tested the bug as described in the ticket, and it seems to work well. 

However, since I also changed a number of other implementation classes, I think this needs to be tested more thoroughly to ensure I did not break anything else.

Please let me know if you have any questions or concerns. Thank you!

cc @peerkar @lipusz @felipelorenz @thektan

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1327401_8543

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
Looks ok to me. 

Tested the following manually:

- Setting semantic search configuration works and updated values are shown immediately
- Changing the configuration works and updated values are shown immediately
- Embeddings are created for web contents when enabled 
- Embeddings are are created when re-indexing
- Embeddings are created for keywords in Blueprint preview
- 'Rescore by text embedding' element works
- Embeddings are created for keywords on a search page using a Blueprint

@joshchong , @xbrianlee anything else should be tested?

**Review by peerkar — APPROVED** [review]
Looks ok to me, but let's see if search QA wants to do additional testing.

**Comment by joshchong** [comment]
The tests in this PR look good to me. I also performed some manual tests which also looked good. 

@peerkar can you take a look at the merge conflict in this branch?

**Comment by peerkar** [comment]
Rebasing and re-sending here https://github.com/liferay-search/liferay-portal/pull/842

**Pull request closed without merging**
