### PR TITLE
LPD-30647 portal-search-opensearch2-impl: add upsert on opensearch to…

### PR DESCRIPTION
**Pull request by joshuacords**
…o - see LPD-26725

https://liferay.atlassian.net/browse/LPD-30647

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search-opensearch2

**Comment by joshuacords** [comment]
ci:report:43845048

**Review by gustavolimav — APPROVED** [review]
Hey @joshuacords, code LGTM! Good job finding the fix for it.

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
