### PR TITLE
LPS-151895 search-experiences-web: Include language ids for i18n

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-151895 - Add i18n language codes "sxp-query-element.schema.json" (title, description)

Subtask of https://issues.liferay.com/browse/LPS-148749

Pretty straightforward, just adding language ids into the `sxp-query-element.schema.json` for title_i18n and description_i18n :)

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:forward

**Comment by lipusz** [comment]
Hi @oliv-yu 

One thing that came to mind is, if these language IDs are aligned with what we have as available locales in 
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2590

**Comment by oliv-yu** [comment]
@lipusz Ah, interesting, thanks for the reference! I was just going off the list from `Liferay.Language.available`, but I can resend with that list if that works better?

**Comment by lipusz** [comment]
If I'm not mistaken, that API you mentioned depends on the Available config of the given Virtual Instance, which might be shorter than what the product actually can support in terms of locales. But since this is a static list in the schema, it can't reflect if the instance setting changes, so I guess, it's better to list all locales in the schema now.

**Comment by oliv-yu** [comment]
ci:stop

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
