### PR TITLE
LPD-33329 "Portlet is temporarily unavailable" error appears if you try to filter by a non-existent categoryId via the URL

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-33329

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Review by lipusz — CHANGES_REQUESTED** [review]
Sent comments on the ticket.

**Comment by lipusz** [comment]
ci:stop

**Pull request closed without merging**
