### PR TITLE
LPS-175508: Move AC suggestion contributors to portal-search

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-175508

### CODE REVIEW

**Review by lipusz — APPROVED** [review]
:+1: LGTM.

@peerkar 2 notes:
* Before forwarding it, you may want to remove the the `:` from the commit message of the first commit.
* The author of AsahUtil should be you I guess, not Eduardo.

Later, there could be some optimization made, for example to `AsahUtil.isAnalyticsEnabled(long)` not to do these look-ups on each request.

**Comment by peerkar** [comment]
@lipusz 
"The author of AsahUtil should be you I guess, not Eduardo."
- It is Eduardo's code...

"Later, there could be some optimization made, for example to AsahUtil.isAnalyticsEnabled(long) not to do these look-ups on each request."
- Can you please elaborate? I'm not sure how to follow portal settings real-time without doing that on each lookup. If it's not real time, can you please suggest how should it be? Regardless, speaking of  reducing backend calls, I noticed that our search bar suggestions is not doing any client side caching. Identical keywords will send new search requests over and over again during the same page load. I'd suggest caching like at least some AC components do.  cc: @thektan

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
c:forward

**Comment by peerkar** [comment]
ci:forward

**Pull request closed without merging**
