### PR TITLE
[TS] LPS-118431 Restore old populateHttpHeaders code if _ddmIndexer.isLegacyDDMIndexFieldsEnabled() is true

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-118431

Regression caused by [LPS-103224](https://issues.liferay.com/browse/LPS-103224): integration test DLFileEntryIndexerIndexedFieldsTest.testIndexedFields only works with Elasticsearch after LPS-103224 changes. 

To avoid that, I am restoring old populateHttpHeaders code and using it in case _ddmIndexer.isLegacyDDMIndexFieldsEnabled() is true

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @liferay-search @arboliveira @BryanEngler 

Can you review this regression and send it to Brian?

@lipusz wants to include _Elasticsearch "Limit of total fields has been exceeded" error_ [LPS-103224](https://issues.liferay.com/browse/LPS-103224) in 7.2 SP3 fixpack but I cannot backport it until this regression is solved in master.

Thank you,
Jorge

**Comment by BryanEngler** [comment]
ill take a look at this today

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
@jorgediaz-lr it looks like DLFileEntryIndexerIndexedFieldsTest.testIndexedFields still failed ci:test:search-solr?

**Comment by jorgediaz-lr** [comment]
Hi @BryanEngler 

I am sorry I focused in restoring the old ddm test logic and I didn't noticed that solr test was also failing due to score field.

This problem is caused by `indexedFieldsFixture.postProcessDocument` there are two versions of this method:

- **com.liferay.portal.kernel.search.Document param:** receives and modifies a Document object from kernel package
- **com.liferay.portal.search.document.Document param:** receives and creates a copy of a Document object from search package

[LPS-103224](https://issues.liferay.com/browse/LPS-103224) changed the Document type from `com.liferay.portal.kernel.search.Document` to `com.liferay.portal.search.document.Document` but we weren't using the object returned by postProcessDocument.

I have added a new commit see https://github.com/liferay-search/liferay-portal/commit/487516bb34dc6ca10b7632c2c0d25e44a132cdf3 fixing it. I have also fixed same problem in UserIndexerIndexedFieldsByAssociationTest.java

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by jorgediaz-lr** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
looks good, thanks @jorgediaz-lr

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
