### PR TITLE
LPD-15140 Result Rankings Scoping can be enabled as Beta so users can opt-in not only the feature, but the new behavior (Search Bar scope honored)

### PR DESCRIPTION
**Pull request by AlmirFe**
- https://liferay.atlassian.net/browse/LPD-15140
	- https://liferay.atlassian.net/browse/LPD-15157
	- https://liferay.atlassian.net/browse/LPD-15158

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
FE looks good to me, and tested out some of the behavior. Scoped rankings were hidden behind FF, as well as the related UI to configure scoping 💯

**Comment by oliv-yu** [comment]
Oh one thing I forgot, the language keys were updated to mention scope. Should those get updated too? 😅 @lipusz 

Screenshot 2024-01-25 at 2 33 41 PM
Screenshot 2024-01-25 at 2 29 25 PM

**Comment by lipusz** [comment]
Hi @oliv-yu 
I'm not sure which language keys you are referring to or what it means by "updated to mention scope". :thinking: 

The messages on the screenshot looks OK to me. :eyes:

**Comment by BryanEngler** [comment]
adding this to https://github.com/liferay-search/liferay-portal/pull/1248 since there are merge conflicts with it

**Pull request closed without merging**
