### PR TITLE
LPD-40394 portal-web: correct expected order

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-40394

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
LGTM! Maybe I'd try rerunning `ci:test:search` to see it pass? Otherwise, looks good ⭐

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
