### PR TITLE
LPS-204036 Remove unused @References

### PR DESCRIPTION
**Pull request by joshuacords**
**Task: https://liferay.atlassian.net/browse/LPS-204036**
**Sub-Tasks:**
https://liferay.atlassian.net/browse/LPS-204287
https://liferay.atlassian.net/browse/LPS-204288
https://liferay.atlassian.net/browse/LPS-204289
https://liferay.atlassian.net/browse/LPS-205543

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Tests look good.

**Review by gustavolimav — APPROVED** [review]
Code and Tests looks good

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
Just running ci:relevant so we can forward it

**Comment by joshuacords** [comment]
ci:report:2502827999

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:forward:force

**Pull request closed without merging**
