### PR TITLE
[TS] LPS-193867 portal-search: no results should be used

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-193867

**Author:** @joshuacords

### CODE REVIEW

**Comment by felipelorenz** [comment]
LGTM!

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/140422

**Pull request closed without merging**
