### PR TITLE
LPS-195210: Add test for stored fields

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPS-195210

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
Sending directly here: https://github.com/brianchandotcom/liferay-portal/pull/140836

**Pull request closed without merging**
