### PR TITLE
LPS-161935 portal-search-web: Add back-end logic to be possible order the folder facet

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-161935

### CODE REVIEW

**Comment by BryanEngler** [comment]
@gustavolimav looks pretty good but one change... we dont want to use the the _ASC_FREQUENCY_COMPARATOR, we want elastic to actually return results in freq asc order... this can be done by passing the order here
https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/facet/folder/FolderFacetSearchContributorImpl.java#L118

and then translating here https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/facet/DefaultFacetProcessor.java#L48

ie termsAggregationBuilder.order(BucketOrder.count(true));

**Comment by gustavolimav** [comment]
@BryanEngler Changes made. Tested again and the results are the same.

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:help

**Comment by gustavolimav** [comment]
@BryanEngler Added some test coverage but not opened other ticket because I dont know if I should do that

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
added a few tests, will forward from https://github.com/BryanEngler/liferay-portal/pull/668
thanks @gustavolimav @thektan

**Pull request closed without merging**
