### PR TITLE
LPS-198941 search-experiences-service: Translate SXPElements when loc…

### PR DESCRIPTION
**Pull request by gustavolimav**
…ale is changed

https://liferay.atlassian.net/browse/LPS-198941

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Review by thektan — COMMENTED** [review]
Interesting, so changing `en_US` to the default language before start up fixes this issue?

I'm curious if the `title` and `description` in the response is blank here? And if so, if it'd have something to do with this part of the code https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/dto/v1_0/converter/SXPElementDTOConverter.java#L78-L80?

Screenshot 2023-10-17 at 11 39 44 AM

**Comment by gustavolimav** [comment]
> I'm curious if the title and description in the response is blank here?

Yep in master it return blank.

> And if so, if it'd have something to do with this part of the code

Yeah that looks a nice place to change, I will test it here and see if changing SXPElementDTOConverter would fix the bug

**Comment by joshuacords** [comment]
Hello @gustavolimav,

I've spent some time looking at this. From what I'm seeing in related tickets, we should expect to be able to retrieve the title/description language keys no matter what language we requesting from. Now the reason this appears to be possible is that the _language.get() method called by the [SXPElementDTOConverter](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/dto/v1_0/converter/SXPElementDTOConverter.java#L78-L80) will try to find the matching language key, and if it can't, it will default to the default language. This is were this bug comes in, because the language being looked for and the default language (pt) aren't en_US (the only available language) and so no title is returned.

2 things I don't like about this fix is we can no longer assume newly created Elements will be how the json defines them. This may or may not come up, but if it does it would be a sneaky bug. The bigger concern is that this doesn't fix customers that have already upgraded and have bad Elements.

Perhaps what we could do is in the [SXPElementDTOConverter](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/search-experiences/search-experiences-rest-impl/src/main/java/com/liferay/search/experiences/rest/internal/dto/v1_0/converter/SXPElementDTOConverter.java#L78-L80) we could pass as the default value the en_US title if sxpElement is read only (the flag for system created elements?). 

Could you look into this option Gustavo and take into the account situations where portals already contain the en_US Elements?

**Comment by gustavolimav** [comment]
@joshuacords sorry for dont update you about it but I talked with @thektan and I am doing the fixing in the DTOs now. You can ignore this PR now. Tomorrow I will push my code with the new way to fix it.

**Pull request closed without merging**
