### PR TITLE
[TS] LPS-166095 Feature requested by a DXP 7.4 customer: add a configuration to enable the 'DFS Query Then Fetch' search type to get consistent scoring between nodes

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-166095

This is a feature requested by a DXP 7.4 customer, they are complaining that they are getting inconsistent scoring between Elasticsearch nodes.

To solve this, you can enable the 'DFS Query Then Fetch' search type, for more information see https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch , https://www.elastic.co/guide/en/elasticsearch/reference/7.17/consistent-scoring.html and https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-search.html#search-type

See also https://issues.liferay.com/browse/LPS-166095 description.

I am sending this PR because this feature is very easy to implement, just create a new ElasticsearchConfiguration setting that enables this 'search type' and adds a call to `searchRequest.searchType(SearchType.DFS_QUERY_THEN_FETCH)` before executing the search.

The implementation is similar to existing **trackTotalHits** setting, that is also configured in ElasticsearchConfiguration and it is set to every search query.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Hi Jorge,

Thanks for proposing this change. We'd like to explore the topic first before accepting any code, so I'm closing this one until further evaluation. We can reopen or resend depending on the outcome of the discussion.

**Comment by lipusz** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
I have added a missing Semver commit, for future reference, see https://github.com/jorgediaz-lr/liferay-portal/tree/LPS-166095 branch

**Pull request closed without merging**
