### PR TITLE
LPD-29816 portal-search-web: Extra 'panel-body' class causing misalignment

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-29816 - Alignment on category facet is different from other search facets

After some refactoring of the `view.jsp`s in category/custom facets, there was an extra class name for "panel" that still remained. Taking that it out fixes the alignment of the category facet, custom facet, and custom filter widgets.

Screenshot 2024-06-27 at 4 18 11 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:report:27838977

**Review by thektan — APPROVED** [review]
Looks good! 👍

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
