### PR TITLE
LPS-197760 Inaccurate helptext on Searchbar configuration for "Invisible"

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-197760 - Inaccurate helptext on Searchbar configuration for "Invisible"

Small update to the helptext "invisible" in searchbar configuration, since it was overlapping with the "invisible" helptext for custom filter widget:
Screenshot 2023-10-02 at 4 03 32 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Review by thektan — APPROVED** [review]

**Comment by joshchong** [comment]
ci:forward:force

**Pull request closed without merging**
