### PR TITLE
[TS] LPS-189931 Unable to index com.liferay.object.model.ObjectDefinition

### PR DESCRIPTION
**Pull request by linolaoj**
https://liferay.atlassian.net/browse/LPS-189931

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
LGTM 🚀

**Review by gustavolimav — APPROVED** [review]
LGTM 🚀

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
