### PR TITLE
[TS] LPS-195649 All searches do not work when using expando date field with name "date"

### PR DESCRIPTION
**Pull request by AlmirFe**
### **LPP link:** [LPP-50714](https://liferay.atlassian.net/browse/LPP-50714)

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
i feel like our dynamic templates are starting to get too complex...

just be aware, in elastic the templates are matched IN ORDER. a field might actually match more than one template, but the first one matched is the one that is used. 

it seems that we might be arbitrarily moving this template "upward" and just placing it in alphabetical order? (which is not how the dynamic templates should be sorted)

to me it feels like its potentially moving way too far, which increases the chances of causing a regression.

one alternate could be to move _date down with the other "type" templates (template_double, template_float, template_integer, etc)

and i think really what the root problem is, is expando is super old and the mappings were never really done properly to start with. but i think the level of effort to fix that would be pretty big

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
forwarded and merged

**Pull request closed without merging**
