### PR TITLE
[TS] LPS-161173 Search Bar Destination

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-161173

**Authors:** @bakayattila @joshuacords 
**Reviewers:** @joshuacords briandotchan

This originally was approved all the way to Brian Chan [here](https://github.com/brianchandotcom/liferay-portal/pull/124722), but he wanted to unify naming:

`			_searchBarPortletInstanceConfiguration.destination();`
"We had several names for destination.. can we sync on one? Thx."

I've unified naming to "destination", "destinationURL", and "destinationOptional". The last thing I considered was renaming the attribute "searchURL" set [here](https://github.com/liferay/liferay-portal/blob/4744faabfa955fd068ea478cfdc8fb671afeb09b/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/search/bar/view.jsp#L108) but seemingly used across many components.

`.put("searchURL", searchBarPortletDisplayContext.getDestinationURL())`

In review we should consider whether we should change this as well.

### CODE REVIEW

**Comment by lipusz** [comment]
@joshuacords This was reverted due to a regression. Has that been addressed in the new PR?

**Comment by joshuacords** [comment]
> @joshuacords Previously, this fix was reverted due to regressions. Has that been addressed in the new PR?
> 
> * https://issues.liferay.com/browse/LPS-165424
> * https://issues.liferay.com/browse/COMMERCE-10143

Both of these regressions are addressed. Thanks for checking.

**Comment by lipusz** [comment]
:+1:

**Comment by lipusz** [comment]
Make sure the Search Bar Suggestions (through `/suggestions`) also covered and continue honoring the current destination search page setting when they are on/from a Master Page. I remember noticing problems with that when we were building the Gartner demo env,

**Comment by joshuacords** [comment]
> Make sure the Search Bar Suggestions (through `/suggestions`) also covered and continue honoring the current destination search page setting when they are on/from a Master Page. I remember noticing problems with that when we were building the Gartner demo env,

I believe this ticket demonstrates what you're talking about Tibor: https://issues.liferay.com/browse/LPS-170513
I'll see if it resolves this issue.

**Comment by lipusz** [comment]
@joshuacords Ah, yes, most likely. Let's see :crossed_fingers:

**Comment by joshuacords** [comment]
I've tested, this also resolves https://issues.liferay.com/browse/LPS-170513

**Comment by lipusz** [comment]
Great, thanks for the update Josh! 👏

**Comment by peerkar** [comment]
@joshuacords unifying / clarifying the 'destination' is a great initiative. There might still be some things to check & streamline there. Summarizing some bits of my findings here and also invoking @thektan to take a look, too:

- The search bar destination page configuration value is a friendly URL. At least help text says so. But still we want the configuration property be 'destination'?
- Taking a look at  SearchBarPortletDisplayContextFactory, there are three destination values in the game. It's still a bit confusing to me:
  - **destination**: the original configuration value, which IS a friendly URL (or empty)?
  - **destinationURL**: which actually also becomes a friendly URL. Should this one actually be 'destinationFriendlyURL'
  - **destinationFriendlyURL**:  which we set there to be the value of 'destination'. Should this be named 'destination' accordingly?
- The SearchBarPortletDisplayContextFactory still has 'destinationString' variable. Maybe -> 'destination' 
```
	private String _getDestinationURL(
		String destinationString, ThemeDisplay themeDisplay) {

```
- the /search/bar/view.jsp declares 'searchURL', carrying now the value of 'destinationFriendlyURL', which then carries 'destination' ... but I'm not sure if 'searchURL' is even used in the search bar anywhere (@thektan ?) Could we remove it?

Also to note, SuggestionResourceImpl uses 'destinationFriendlyURL':
```
		searchContext.setAttribute(
			"search.suggestions.destination.friendly.url",
			destinationFriendlyURL);
```

Summarized:
- are the URL values in question ever anything else than friendlyURLs? If not should the variables and parameters be suffixed with 'FriendlyURL'?
- the destinationFriendlyURL in SearchBarPortletDisplayContextFactory carrying value of 'destination' is confusing?
- instances of 'destinationString' could be renamed?
- is the 'searchURL' in /search/bar/view.jsp in use?

**Comment by peerkar** [comment]
Otherwise the code looks ok to me and seems to fix the issue.

**Comment by joshuacords** [comment]
Hi @peerkar,
I was able to simplify `destination` to `destinationFriendlyURL` and remove `destinationString`, we still need the full `destinationURL`. I talked to Kevin and Olivia about searchURL, it is in use in the SearchBar react componenet, and I ran into problems where "Show More" and the Search Bar search stopped working when trying to remove the searchURL parameter and using the destinationFriendlyURL instead.

I'm assuming that leaving the `destination` name in configuration is okay.

Could you do a final review? Thanks

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant:no-rebase

**Comment by joshuacords** [comment]
ci:test:relevant:norebase

**Comment by joshuacords** [comment]
ci:test:search:norebase

**Comment by joshuacords** [comment]
ci:test:sf:norebase

**Comment by joshuacords** [comment]
@peerkar

I found a bug, this isn't ready for review.

**Pull request closed without merging**
