### PR TITLE
LPS-171139: Future proof semantic search API 

### PR DESCRIPTION
**Pull request by peerkar**
Covers:

https://issues.liferay.com/browse/LPS-171139
https://issues.liferay.com/browse/LPS-171140

**Unblocks:**

https://issues.liferay.com/browse/LPS-166568

**Purpose in a nutshell:**

- Add a portal-search-web accessible API for showing statuses of embedding providers on the index actions page (LPS-166568)
- Get rid of provider specific configuration properties and namings because more providers will come
- Refactor APIs to be prepared to support multiple active embedding providers
- Modularize the retriever API to support retrievers of other kinds of embeddings (images)

### CODE REVIEW

**Comment by peerkar** [comment]
ci:reevaluate:1357401_3310

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@peerkar @thektan 

I still need to make some functional test fixes for this PR, but in the meantime I noticed a few things:

1. Semantic versioning is failing on `apps/portal-search/portal-search-api` with
```java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 11.1.0 ```
[Jenkins failure](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/317841/testReport/junit/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_portal_search_portal_search_api_/)

2.  Odd behavior when saving the Semantic Search System Settings where after saving, the "Text Embedding Provider Configurations" field replaces the entire form until a page refresh is made. This does not happen with Instance Settings. See below:

https://user-images.githubusercontent.com/14988026/213049462-a807ac3b-e7c5-44c0-9e41-c17aded21217.mp4

**Comment by thektan** [comment]
@joshchong For #2, I created a bug ticket to track this issue so this could be moved forward. https://issues.liferay.com/browse/LPS-172802 It'd most likely end up being assigned to someone on the US&M team.

**Comment by peerkar** [comment]
@joshchong baseline done for 1.

**Comment by joshchong** [comment]
Resent with test fixes here: https://github.com/liferay-search/liferay-portal/pull/740

**Pull request closed without merging**
