### PR TITLE
LPS-187293 Warn user if Elasticsearch is low on disk space before executing a Concurrent (Blue/Green) reindex and prevent execution if no disk space left in the Index Actions

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPS-187293

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
alright @felipelorenz i think we are getting close! i made a few more changes, can you take a look and do a little testing with it to make sure we are good? thanks! https://github.com/liferay-search/liferay-portal/pull/1079

**Pull request closed without merging**
