### PR TITLE
LPS-206184 portal-search: Honor "_commitImmediately" value even if commit() method is explicitly called

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPS-206184

Also see https://liferay.slack.com/archives/CKY6GP7BL/p1693807518701669?thread_ts=1693392616.400069&cid=CKY6GP7BL

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2487999419

**Comment by dantewang** [comment]
ci:report:2488000134

**Comment by dantewang** [comment]
@BryanEngler The reports show no unique failure in ci-test-relevant and ci-test-search. Only a tiny part of tests did not run.

**Comment by peerkar** [comment]
ci:forward

**Comment by peerkar** [comment]
ci:reevaluate:1397401_9246

**Comment by peerkar** [comment]
ci:forward:force

**Pull request closed without merging**
