### PR TITLE
LPS-199540 Refactoring of DefaultSearchResultPermissionFilter

### PR DESCRIPTION
**Pull request by BryanEngler**
https://liferay.atlassian.net/browse/LPS-199540

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by joshuacords** [comment]
Hey Bryan, when trying to find the last document and 19 are already found the logs can show this:

> 2023-11-22 01:25:41.272 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 20, amplification factor: 1, query size: 20
2023-11-22 01:25:41.468 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 2, query size: 2
2023-11-22 01:25:41.621 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 4, query size: 4
2023-11-22 01:25:41.752 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 8, query size: 8
2023-11-22 01:25:41.864 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 16, query size: 16
2023-11-22 01:25:41.993 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 32, query size: 32
2023-11-22 01:25:42.115 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 64, query size: 64
2023-11-22 01:25:42.271 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 128, query size: 128
2023-11-22 01:25:42.495 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 256, query size: 256
2023-11-22 01:25:42.832 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 512, query size: 512
2023-11-22 01:25:43.423 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 1024, query size: 1000 (limited by search query result window limit)
2023-11-22 01:25:44.510 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 2048, query size: 1000 (limited by search query result window limit)
2023-11-22 01:25:45.556 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:413] Results needed: 1, amplification factor: 4096, query size: 1000 (limited by search query result window limit)
2023-11-22 01:25:46.465 DEBUG [http-nio-8080-exec-7][DefaultSearchResultPermissionFilter:496] 13 sliding window searches took 5192 ms (4318 ms spent searching, 874 ms spent filtering results)

I think it makes sense not to dip down to such low query sizes. What about limiting the minimum query size to something like 20?

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf:norebase

**Comment by BryanEngler** [comment]
> I think it makes sense not to dip down to such low query sizes. What about limiting the minimum query size to something like 20?

@joshuacords Ya i wouldnt be against that, but im wondering if it would actually make a difference? even if the 2, 4, 8, 16 were changed to 20, 20, 20, 20, theres still nothing being found (at least in this case)... im assuming the 13 searches would still occur

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
> > I think it makes sense not to dip down to such low query sizes. What about limiting the minimum query size to something like 20?
> 
> @joshuacords Ya i wouldnt be against that, but im wondering if it would actually make a difference? even if the 2, 4, 8, 16 were changed to 20, 20, 20, 20, theres still nothing being found (at least in this case)... im assuming the 13 searches would still occur

I'm saying don't start at any thing less than 20 and multiply it from there. So the searches would be 20, 40, 80, 160 ..... 

I guess that only skips 4 searches. 

The thing is the searching round trip is what takes so long, in the case of just 4k documents, it took 5s! I can tell you the customer would not be satisfied with this level of improvement. And there's lots of customers that run into these performance issues because they use the folder permissions that necessiate the post filtering.

We need to be way more aggressive with the starting size and/or how quickly we scale.

**Comment by joshuacords** [comment]
What are we actually losing if we just start at 500 on the second search and then double it to a 1000?

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:search-solr

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by joshuacords** [comment]
I'm testing, I find when the timeout is hit this is displayed for 19 entries: 
image

**Pull request closed without merging**
