### PR TITLE
LPS-150870 Toggle between the new and old configuration screen in the Sort Widget: Enable the new UI by default and remove Feature Flag added in LPS-134052

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-150870

Developer notes:
- I'm purposely re-rendering all the inputs (which means re-initializing Liferay.AutoFields) when switching between views because the AutoFields don't have a unique key when deleting/undoing so switching back and forth would cause a lot of strange issues. Like for instance fields would start slowly getting deleted every time you switch between views.
- I'm also manually grabbing values of the input elements when switching from the classic to new view since it made the data more reliable than attempting to maintain a state when rows were deleted/added with the Liferay.AutoFields https://github.com/liferay-search/liferay-portal/blob/34b4fe1faf10673850d1c3623df4b41b5bdc9250/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/js/components/SortConfigurationOptions.js#L248-L268

I've also requested some feedback here https://liferay.slack.com/archives/G982WB4TH/p1654274539142769 on wording but the main logic of the code is good to review!

@oliv-yu Let me know if you have any questions and I can explain over slack/in-person!

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Review by oliv-yu — APPROVED** [review]
Thanks for fixing the bug! And adding very detailed notes about the event listener submission. And the fix for uncontrolled/controlled components. Looks 🔥 

I'll ask QA about the test update!

**Comment by brookedalton** [comment]
Continued in #456

**Pull request closed without merging**
