### PR TITLE
LPS-199540 Refactoring of DefaultSearchResultPermissionFilter

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-199540

Added improvements and corrections for when search is cut short, allowing for accurate document and search counts for all documents returned in these cases.

**Authors**: @BryanEngler @joshuacords 
**Reviewers**: @joshuacords

Original PR here: https://github.com/liferay-search/liferay-portal/pull/1155

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search

**Comment by joshuacords** [comment]
From what I can tell the tests look good.

@gustavolimav - I think Bryan's reviewing this already.

**Comment by BryanEngler** [comment]
@joshuacords other than the facet rebuilding, the only thing i might change is the ordering of the sentences in the lang key

permission-filtered-search-result-accurate-count-threshold-help=Set the minimum number of search results that will be processed by permission filtering. This allows results that are beyond the current page to also be removed by the permission filter, creating a more accurate total count. Searches that return a total number of results above this threshold may not have an accurate total count. This setting takes precedence over Permission Filtering Time Limit.

**Pull request closed without merging**
