### PR TITLE
LPS-133224 Allow filtering object entries by object field values

### PR DESCRIPTION
**Pull request by javierdearcos**
Hello team,

I was working on a bug related to filter object fields in the Object Entry APIs [LPS-133224](https://issues.liferay.com/browse/LPS-133224).

Following the same approach that @BryanEngler to allow sorting by ObjectEntry fields, I've modified the FilterTranslatorImpls to take into account the nestedFieldArray case. As this is an important portal future, it makes sense to me to be considered in the core of the portal and this way, the implementation of the rest of the modules is very clean.

I've considered the filter types that I think are more important, but please tell me if you think I need to add some more.

Please, can you take a look at this PR and tell me if you find some trouble with it?

Thank you very much

### CODE REVIEW

**Comment by BryanEngler** [comment]
hey @javierdearcos,
this obviously breaks ObjectEntryLocalServiceTest.testSearchObjectEntries, so i dont think its quite right... but i have no context on where you have a need to "filter object entries", so i dont have any suggestions yet... are there any tests written yet for filtering object entries? or tickets with more information?

**Comment by javierdearcos** [comment]
The filter should be applied from the REST and GraphQL APIs. It is provided as a String in a URL parameter or GraphQL query parameter and should be converted into a valid Filter.

I will check the search failing tests, add some specific tests filtering Objects and try to provide more context about the feature and scope

**Comment by javierdearcos** [comment]
I've fixed the ObjectEntryLocalServiceTest.testSearchObjectEntries and add some tests of basic filters with "eq", "ne" and "contains" of object fields through the GraphQL API.

I'm afraid that the context is very limited but the related ticket is [LPS-131288](https://issues.liferay.com/browse/LPS-131288)

The requirements is to be able to sort, filter and search the object entires by object fields as we are doing in any other Headless API of the portal: [https://help.liferay.com/hc/en-us/articles/360039026252-Filter-Sort-and-Search](https://help.liferay.com/hc/en-us/articles/360039026252-Filter-Sort-and-Search).

In order to do so, I've used the same syntax that we are using in sorting with the object fields (that is nestedFieldArray.[name of the nested field array property]#[name of the object field], trying to follow the same approach you did with sorting in the commit [https://github.com/liferay/liferay-portal/commit/6acbd3cd758d6dda568a0d9e04329eac4df531f3](https://github.com/liferay/liferay-portal/commit/6acbd3cd758d6dda568a0d9e04329eac4df531f3)

Sorry to not give you this information from the beginning. I hope with this update you are more in context to know what we are trying to achieve with this PR.

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:search

**Comment by javierdearcos** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
see https://github.com/BryanEngler/liferay-portal/pull/588

**Pull request closed without merging**
