### PR TITLE
[7.3-must] LPS-119890 Update supported version to 7.9 in Elasticsearch 7 connector app description

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-119890

Background:
* In 7.3 we are using the Java REST Client of Elasticsearch 7 (LPS-85208)
* The connector dependencies have been upgraded to 7.9.0 (LPS-115774) 
* The REST Client is compatible with greater minor versions so we are adding "7.9.+". See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.3/java-rest-high-compatibility.html
  > The High Level Client is guaranteed to be able to communicate with any Elasticsearch node running on the same major version and greater or equal minor version. It doesn’t need to be in the same minor version as the Elasticsearch nodes it communicates with, as it is forward compatible meaning that it supports communicating with later versions of Elasticsearch than the one it was developed for.
* The minimum required minor version for 7.3 CE GA6 and DXP 7.3 GA1 will be 7.9
* We change from singular ("to the ES 7.9+ search engine") to plural ("to ES 7.9+ search engines") since 7.3 supports multiple ES connections

/cc @dejuknow

/cc @jpince fyi too because I've seen your update in product-dev regarding the lang keys

### CODE REVIEW

**Comment by lipusz** [comment]
ci:forward

**Comment by jpince** [comment]
@lipusz thanks. This is not a big deal, because these translations are only for the app name, which I think only shows up if you're looking for the app in portal/dxp within Marketplace, or maybe in settings in the Control Panel. So not very visible to the customer.

Strangely, it looks like the app.bnd-localization files were never translated to begin with (should have been translated previously since these files have been in upstream for longer than 2 weeks). Probably something the search team should follow up on in [t-crowdin-translations](https://liferay.slack.com/archives/CN3HAAXEU)

**Comment by lipusz** [comment]
Wow, thanks for catching this, @jpince! We'll contact the translation teams.

I was wondering though if this was a generic problem affecting all app localizations... :thinking:

**Comment by lipusz** [comment]
@jpince Looks like these files are not visible to the translation team, see for example:
* https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/saml/app.bnd-localization/bundle_da.properties
* https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-search-elasticsearch-monitoring/app.bnd-localization/bundle_de.properties
* https://github.com/liferay/liferay-portal-ee/blob/7.2.x/modules/apps/portal-search-elasticsearch7/app.bnd-localization/bundle_de.properties

**Comment by jpince** [comment]
For reference (from Slack DM with Tibi), see https://issues.liferay.com/browse/LRIS-36432

**Pull request closed without merging**
