### PR TITLE
LPS-163126 portal-search-web: Fix bug that search bar was not loaded in the home page

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-163126

### CODE REVIEW

**Review by oliv-yu — APPROVED** [review]
Looks good! This addresses the bug regarding the faulty destination url. I think there might need to be a discussion later about the use case for invisible search bars, though that's a different task.

Thanks for working on this!

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Ah, we can check tests again after https://liferay.slack.com/archives/C19PWQ74J/p1691370995470499

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
Sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/138961

**Pull request closed without merging**
