### PR TITLE
LPS-180649 Add highlighting integration tests - rebased

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-180649

Original: https://github.com/liferay-search/liferay-portal/pull/932

Rebased to try removing the SF error.

**Author**: @joshuacords
**Reviewer**: @gustavolimav

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
SF error above is unrelated to this PR. It will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/135472.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:forward:force

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/135616

**Pull request closed without merging**
