### PR TITLE
LPS-158782

### PR DESCRIPTION
**Pull request by wcao20170619**
https://issues.liferay.com/browse/LPS-158782

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@wcao20170619 see 400a57fa54bcd543ede94ce8e56af1641d91e8d1

**Comment by wcao20170619** [comment]
> @wcao20170619 see 400a57fa54bcd543ede94ce8e56af1641d91e8d1

@brianchandotcom even better!

**Comment by joshchong** [comment]
Closing PR since BChan merged it: https://github.com/brianchandotcom/liferay-portal/compare/30cd807b%5E...400a57fa

**Pull request closed without merging**
