### PR TITLE
LPS-148862 search-experiences-web: Remove browser errors in blueprint query settings

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-148862 - Browser console errors when navigating to Blueprints Query Settings

Small change! This was the error I saw, I just did what it suggested.

```
Warning: Received `true` for a non-boolean attribute `borderless`.

If you want to write it to the DOM, pass a string instead: borderless="true" or borderless={value.toString()}
```

### CODE REVIEW

**Review by thektan — CHANGES_REQUESTED** [review]
Might need to just remove these properties. Double check with sticker api. https://clayui.com/docs/components/sticker/api.html

**Comment by oliv-yu** [comment]
ci:reevaluate:1277401_2336

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Forward to Bchan: https://github.com/brianchandotcom/liferay-portal/pull/114888

**Pull request closed without merging**
