### PR TITLE
[TS] LPS-118240 Not possible to set a "_score" sort in asc

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @joshuacords
Reviewer: @arboliveira 

LPS-118240 Not possible to set a "_score" sort in asc
https://issues.liferay.com/browse/LPS-118240

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:test:search

**Comment by arboliveira** [comment]
ci:test:search-solr

**Comment by arboliveira** [comment]
ci:test:stable

**Comment by arboliveira** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Manually forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/92551

**Pull request closed without merging**
