### PR TITLE
LPS-173591 portal-search-elasticsearch7-impl: Fix test

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-173591

### CODE REVIEW

**Comment by gustavolimav** [comment]
@felipelorenz see https://github.com/liferay-search/liferay-portal/pull/781/commits/0f3d0d3061ce3c82785c7f27b853576bc36376b0 and https://github.com/liferay-search/liferay-portal/pull/781/commits/55faea2dcf714006cf8df12eb48e42c2010179c2

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
This looks good enough for me

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
