### PR TITLE
[TS] LPS-157425

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-157425

Hi Team,

**Context**
This PR was created with guidance from [PTR-3915](https://issues.liferay.com/browse/PTR-3915) and the plan is for the Search Team and Headless Team to review.

This is a follow-up PR to: https://github.com/liferay-search/liferay-portal/pull/961

Additional Changes (since https://github.com/liferay-search/liferay-portal/pull/961):
- To fix the failing IndexedFieldsTest tests: I modified the **liferay-type-mappings.json** to no longer store the value.
  - No longer setting **"store": true** for the new mappings
  - Reference: https://github.com/liferay-search/liferay-portal/pull/961#issuecomment-1594840283
- As suggested by Bryan, I removed the extra entry in **schema.xml**
  - No longer adding the mapping for: ***_String_sortable.keyword_lowercase**
  - Reference: https://github.com/liferay-search/liferay-portal/pull/961#discussion_r1232372769

**Summary of Changes**
- Search
  - Update mapping to introduce multi-field keyword fields to replace the previous **\*_\<languageId>*_sortable** fields
    - As discussed, we will proceed with adding the sub-field: **\*_\<languageId>*_sortable.keyword_lowercase**
  - Also added mappings for Solr
- Headless API
  - For fields that are utilizing **\*_\<languageId>*_sortable** fields for filtering String fields
    - Use the associated sub-field: **\*_\<languageId>*_sortable.keyword_lowercase**
  - Added tests by updating the template: **base_resource_test_case.ftl** in portal-tools-rest-builder
    - Regenerated relevant tests by running gw buildRest

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:reevaluate:1407401_3395

**Comment by BryanEngler** [comment]
@ericyanLr i think the ElasticsearchIndexInformationTest needs to be updated because of the new mappings

**Comment by ericyanLr** [comment]
Thanks @BryanEngler , I'll take a look

**Comment by ericyanLr** [comment]
Resent PR with changes: https://github.com/liferay-search/liferay-portal/pull/968

**Pull request closed without merging**
