### PR TITLE
LPD-24715 Add a testSelection() method to CategoryFacetTest

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-24715

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Review by gustavolimav — CHANGES_REQUESTED** [review]
Hey @felipelorenz, the test it self looks good, but can you apply the changes? try to be critical and see if the changes really makes sense, I did a quick review so we can have a second round.

**Pull request closed without merging**
