### PR TITLE
LPD-6885 Update Elasticsearch 7 to 7.17.18 (Client & Sidecar)

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-6885

image

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:2539867174

**Review by gustavolimav — APPROVED** [review]
Tests looks good and I tested locally it is good to go

**Pull request closed without merging**
