### PR TITLE
LPS-162659 Blueprint Selector modal does not honor the user's display locale when there is a translation available in the Blueprints Options widget

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-162659

### CODE REVIEW

**Comment by thektan** [comment]
It doesn't seem like any of the failures are related, so I'm going to run `ci:test:relevant` to see if the same errors would block this PR from forwarding

**Comment by thektan** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
Oh, looks like there's actually another place to add this updated line, which is inside `search-experience-web` for blueprints options. This one is for the table inside the searchbar configuration's advanced blueprint options 🤣  

Link for reference: https://github.com/liferay-search/liferay-portal/blob/de1f94753f627f03c15b14b2478dae91d613778b/modules/dxp/apps/search-experiences/search-experiences-web/src/main/resources/META-INF/resources/sxp_blueprint_options/js/configuration/SelectSXPBlueprintModal.js#L67

**Comment by thektan** [comment]
Ah whoops good catch! Adding it in. Thanks @oliv-yu!

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:search

**Review by oliv-yu — APPROVED** [review]
Looks good to me! ⭐

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
