### PR TITLE
LPS-174758 LPS-203474 portal-search: Fix tests

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-203474

The tests were broken because of this change https://github.com/brianchandotcom/liferay-portal/pull/144897

To fix it I removed the unnecessary code and add the mock to `assetURLProviderImpl`

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:SF

**Comment by gustavolimav** [comment]
ci:test:sf

**Review by AlmirFe — APPROVED** [review]
LGTM! :100:

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
