### PR TITLE
LPD-34102 portal-search-opensearch2-impl: update test expectations in…

### PR DESCRIPTION
**Pull request by joshuacords**
… opensearch as they were in elasticsearch. See [LPD-26725](https://liferay.atlassian.net/browse/LPD-26725) 19d55114f10845a23e81cc958c99ac24e8edacd5

https://liferay.atlassian.net/browse/LPD-34102

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
