### PR TITLE
LPS-147066  In-product links to the documentation in the Query Builder

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-147066 - As a Blueprints user, I can see in-product links to the documentation in the Query Builder

Extra improvements / fixes to this ticket! Includes:
- Links will open a new tab instead of redirecting the page
- Period removed from `Learn how` in blueprint option's `Learn how to setup blueprint options`
- Removal of tooltips on clause contributors / indexer clauses

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Review by thektan — APPROVED** [review]
LGTM! Thanks @oliv-yu!

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
Forwarded in: https://github.com/brianchandotcom/liferay-portal/pull/114747

**Pull request closed without merging**
