### PR TITLE
LPD-15752 Upgrade process is not being executed

### PR DESCRIPTION
**Pull request by AlmirFe**
- https://liferay.atlassian.net/browse/LPD-15752

### CODE REVIEW

**Review by gustavolimav — APPROVED** [review]
Thx for add the changes I requested  cab6b5598e25dfb6ac8ff33861da9ca7ce75191b. The code looks good to me, lets run CI and see if it is good to go

**Comment by gustavolimav** [comment]
ci:test:upgrade

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:report:2534822107

**Comment by AlmirFe** [comment]
ci:test:upgrade

**Comment by gustavolimav** [comment]
ci:report:2534947915

**Comment by gustavolimav** [comment]
@AlmirFe it is still falling but this time I could not found the error message

**Comment by gustavolimav** [comment]
@xbrianlee, what would you do in this case, I tried to search in the console log for the error but I could not found the message to understand what is wrong.

**Comment by xbrianlee** [comment]
@gustavolimav Which test failure are you referring to?

**Comment by gustavolimav** [comment]
> @gustavolimav Which test failure are you referring to?

From upgrade suit

**Comment by xbrianlee** [comment]
@gustavolimav I'm still unsure which test you're referring to. 63 tests failed in the upgrade test suite run. Are you referring to the `PortalSmokeAutoUpgrade` failures?

**Comment by gustavolimav** [comment]
> @gustavolimav I'm still unsure which test you're referring to. 63 tests failed in the upgrade test suite run. Are you referring to the `PortalSmokeAutoUpgrade` failures?

Yeah in the report it says 3 tests unique failures but I could not found the error message in console log

**Comment by gustavolimav** [comment]
> ci:report:2534947915

@xbrianlee

**Comment by xbrianlee** [comment]
You'll have to copy the error message from testray-results.csv
```
java.lang.Exception:  ## ## 2 Liferay Exceptions were thrown ##  LIFERAY_ERROR: Failed upgrade process for module com.liferay.portal.search.tuning.rankings.web LIFERAY_ERROR: Pending Upgrade System Checker check result: Required upgrades in modules are pending. Run the upgrade process or type upgrade:checkAll in the Gogo shell to get more information. Optional upgrades in modules are pending. Run the upgrade process or type upgrade:checkAll in the Gogo shell to get more information.
```
Then search for them one-by-one in the [Jenkins console](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3580/functional-upgrade-tomcat90-db2111-jdk8/0/12/jenkins-console.txt.gz?authuser=0)
```
[beanshell] 2024-02-05 18:08:05.267 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.portal.search.tuning.rankings.web.internal.upgrade.v2_0_0.RenameRankingUpgradeProcess
[beanshell] 2024-02-05 18:08:05.269 INFO  [main][UpgradeProcess:137] Failed upgrade process com.liferay.portal.search.tuning.rankings.web.internal.upgrade.v2_0_0.RenameRankingUpgradeProcess in 2 ms
[beanshell] 2024-02-05 18:08:05.272 ERROR [main][UpgradeExecutor:333] Failed upgrade process for module com.liferay.portal.search.tuning.rankings.web
[beanshell] com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.reflect.UndeclaredThrowableException
...
```

**Comment by gustavolimav** [comment]
@xbrianlee thx for the steps, just curious because I was doing that and the console log was not the same, I wasen't able to see those errors, anyways I probably missed some step. Thanks again Brian ❤️

**Pull request closed without merging**
