### PR TITLE
[TS] LPS-124310 Enable nested queries in Custom Filter portlet

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-124310

In LPS-103224 we implemented nested fields for DDM. This breaks the custom filter widget which can only support a single top level field to aggregate on.

I have added support to nested queries in QueryTypeEntriesHolder and ComplexQueryBuilderImpl classes.

That allows adding a parent "nested" custom filter portlet with several child filter portlets.

For example if in previous Liferay versions you was filtering:
    - **Filter Query Type:** Match
    - **Filter Field:** ddm__keyword__40635__Field14510226_en_US (_name of the ddm structure field in elasticsearch_)
    - **Filter Value:** value_to_filter

...now you will be able to do the same using the nested fields:

1. **First custom filter portlet:** nested parent query
    - **Filter Query Type:** Nested (_new query type added in this LPS_)
    - **Filter Field:** ddmFieldArray  => _it will be used as the path of the nested query_
    - **Query Name:** nested_query
    - **Parent Query Name:** _(empty)_
2. **Second custom filter portlet:** first match child filter
    - **Filter Query Type:** Match
    - **Filter Field:** ddmFieldArray.ddmFieldName
    - **Filter Value:** ddm__keyword__40635__Field14510226_en_US   (_name of the ddm structure field in elasticsearch_)
    - **Query Name:** _(empty)_
    - **Parent Query Name:** nested_query
3. **Third custom filter portlet:** second match child filter
    - **Filter Query Type:** Match
    - **Filter Field:** ddmFieldArray.ddmFieldValueKeyword_en_US
    - **Filter Value:** value_to_filter
    - **Query Name:** _(empty)_
    - **Parent Query Name:** nested_query

This functionality should be also documented in the official Custom Filter portlet documentation

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
@jorgediaz-lr Would you be able to add test for this?

**Comment by jorgediaz-lr** [comment]
Hi @lipusz 

I have just added this commit https://github.com/liferay-search/liferay-portal/commit/4c70927d8484dcf209fda1c768335ba4be99cf05 with a NestedQuery test in ComplexQueryBuilderImplTest.

I am going to execute again the ci tests

Let me know if you consider it is necessary to add more tests.

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
looks good to me, will forward from https://github.com/liferay-search/liferay-portal/pull/63 once tests pass

@rbohl im sure you can track this pr down through jira but just a reminder that this pairs with LRDOCS-8659 and has a good description from jorge

**Comment by rbohl** [comment]
Thanks @BryanEngler ! Linked here from the LRDOCS.

**Pull request closed without merging**
