### PR TITLE
[7.3-must] LPS-113467

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-113467

`ci:test:sf` :heavy_check_mark: https://github.com/lipusz/liferay-portal/pull/320#issuecomment-680124086
`ci:test:relevant` :heavy_check_mark: https://github.com/lipusz/liferay-portal/pull/320#issuecomment-680163810
`ci:test:search` :white_check_mark: No unique failures in https://github.com/lipusz/liferay-portal/pull/320#issuecomment-680186177 based on https://docs.google.com/spreadsheets/d/1cDzu4itg1XPtK4EyuwWB3MBwK3m7MpT3LqLcXltx9QA/edit?pli=1#gid=873807728

Also tested with `logExceptionsOnly=false` just in case on https://github.com/lipusz/liferay-portal/pull/321, no failures.

### CODE REVIEW

**Comment by lipusz** [comment]
@BryanEngler I plan to forward this to BChan unless you have any objections. Thanks!

**Comment by BryanEngler** [comment]
looks good to me :shipit:

**Comment by lipusz** [comment]
Thank you, Bryan! @BryanEngler

**Comment by lipusz** [comment]
ci:forward

**Pull request closed without merging**
