### PR TITLE
LPS-166989 LPS-167392 txtai sentence transformer configuration supports connection using Basic Auth

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-167392

### Notes
I did notice that in https://github.com/liferay/liferay-portal/commit/cd0a4f27d2b346b2f3d412c719b3c7faa244f7d0 `txtaiUserName` was renamed to `txtaiUsername`, but in `search-experiences-web`, there is an SF error forcing the CamelCased `*Name` format. To keep the variable name consistent, I renamed all places back to the CamelCased `txtaiUserName`. This is the formatter rule enforced: "Variable names ending with name should be CamelCase" https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/camel_case_name_check.markdown 

### Screenshots
Screenshot 2022-11-10 at 5 44 07 PM

cc @peerkar

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:sf

**Comment by lipusz** [comment]
@thektan In the lights of the Test Configuration Story: the Basic Auth fields are not mandatory

**Comment by thektan** [comment]
@lipusz Got it. Thanks for the heads up!

**Comment by lipusz** [comment]
@thektan Do you see any gotchas we should consider in the Test Configuration behavior?__

**Comment by thektan** [comment]
@lipusz Not currently, maybe if anything better formatting for the errors that might be returned from the test configuration, but it seems like the data returned could be anything.

**Review by oliv-yu — APPROVED** [review]
looks good to me! 💯

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
According to the unique failure, it seems like updating to camel case `txtaiUserName` is requiring a bundle version change to 16.0.0. Looping in @peerkar, would it be okay to apply that?

**Comment by thektan** [comment]
I left a note for BChan in my first message so we'll see what he says when it goes into his PR queue.

**Comment by thektan** [comment]
Added an extra commit 741fd2f to run `gradle baseline`

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
