### PR TITLE
LPS-153377 Search Bar Suggestions Frontend

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-153377 - Configuration page
https://issues.liferay.com/browse/LPS-153379 - Search bar with suggestions

Demo of search bar
https://user-images.githubusercontent.com/4496722/170736127-3ddadb2d-2c9a-4d6a-b086-fb8c3660ab8f.mp4

Demo of search bar with scope selector
https://user-images.githubusercontent.com/4496722/170736123-507e0291-7ab5-45a1-9328-b48d6b48c4ae.mp4

Added an extra commit for showing the blueprints contributor only on DXP builds.

### CODE REVIEW

**Review by oliv-yu — APPROVED** [review]
Looks great! Thanks for adding in the check for DXP. 🙇‍♀️ 

Notes:
- support for blueprints search would likely be fixed with https://issues.liferay.com/browse/LPS-153331
- in order to have the assetURL render, the destination page should be included in configuration options

**Comment by lipusz** [comment]
The Search Bar already has a destination page Portlet preference. Would it be possible to use it? It would look odd to have another configuration option for it under the suggestions section in the widget configuration screen. 🤔

**Comment by thektan** [comment]
@lipusz We mean the Destination Page must be defined. If left blank, the suggestions won't be able to be clicked on.

**Comment by lipusz** [comment]
Can't we have the same fallback mechanism? Empty means /search iirc for the search bar widget.

**Comment by lipusz** [comment]
But I may be wrong

**Comment by thektan** [comment]
@lipusz Empty destination page uses the current page a user is on.

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Results in the latest run look good. No test failures caused by the changes in this PR.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
