### PR TITLE
LPS-172811 ModelSearchDefinitions for Object Definitions leak to other Virtual Instances

### PR DESCRIPTION
**Pull request by gustavolimav**
Issue: https://issues.liferay.com/browse/LPS-172811

That issue was caused by: https://issues.liferay.com/browse/LPS-157577

Revert the LPS-157577 is not interesting because it will cause regression bugs, so I adapted the logic to consider the new use case with DB Partition

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:object

**Comment by joshuacords** [comment]
@gustavolimav, I'm fine with these changes be we should send them to the Objects team for review.

**Comment by marcelabc** [comment]
Hi, 
I reviewed the code from Objects and LGTM :tada: 
I'm running again the Objects' suite because there were a lot of error in the last report. Thanks!

**Comment by marcelabc** [comment]
ci:test:object

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
I believe there is an Objects bug caused by these changes. [ObjectWorkflow#CanPreviewEntryInformationOnMyWorkflowTasks](https://testray.liferay.com/home/-/testray/cases/1610151734/view?p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc&statuses=3&errors=h3) has failed consistently for this PR while not failing on other PRs.

Test Steps:
1. Create a new Object called "Custom Object"
2. Under the fields tab, add a new text field to Custom Object
3. Under the layouts tab, add a new layout to Custom Object
4. Under the details tab, change Panel Category Key to "Control Panel > Object"
5. Publish Custom Object
6. Navigate to Workflow
7. Configure "Single Approver Workflow" for Custom Object
8. Add a new entry for Custom Object
9. Navigate to Personal Menu > My Workflow Tasks > Assigned to My Roles
10. Click the workflow task entry

Expected:
Preview, author, and comment sections are present.
Screenshot 2023-01-18 at 8 37 59 AM

Actual:
None of the sections above are present.
after2

@gustavolimav Could you take another look at this?

**Comment by gustavolimav** [comment]
Resend the changes with one more commit that fix the collateral effects caused by my previous change.

\cc @xbrianlee @joshuacords

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:object

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
@gustavolimav, failure [LocalFile.Search#SearchCompanyScopedObject](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/386209//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchCompanyScopedObject_) looks related but has been showing up before so I guess it's fine. If Objects or @marcelabc are good with the latest commit you can forward this.

**Comment by xbrianlee** [comment]
I can confirm that the `Search#SearchCompanyScopedObject` failure is happening upstream as well. Also `ObjectWorkflow#CanPreviewEntryInformationOnMyWorkflowTasks` is passing now with Gustavo's fix.

I found no new test failures in the runs above.

**Review by carolmariaabb — APPROVED** [review]
Changes related to Objects: LGTM!

**Pull request closed without merging**
