### PR TITLE
LPS-120168 Use Sites and Libraries as default title like other places.

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @brianikim
> https://issues.liferay.com/browse/LPS-120168
> 
> The issue is a straightforward issue of the wrong language key being used.
> 
> The title should, by default, be Sites and Libraries like other places such as the following:
> 
> https://github.com/liferay/liferay-portal/blob/b91a0ad886e23c94e043899ebe6af9ca6415872d/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalArticleItemSelectorViewDisplayContext.java#L597
> 
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by lipusz** [comment]
@SamZiemer Please also follow https://grow.liferay.com/share/How+to+send+Pull+Request+to+the+Search+Team+liferay-search#trigger-ci--review-results

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:search

**Comment by lipusz** [comment]
Hey @SamZiemer 

Is this related to a Technical Support issue? I don't see an LPP linked to the LPS ticket.

Thank you for the clarification!

**Comment by SamZiemer** [comment]
Hi @lipusz,

As far as I am aware this is not related to a TS issue. I believe Brian was working on some LPS issues and this was one of them.

**Comment by lipusz** [comment]
Got it, thx!

**Comment by lipusz** [comment]
Hey Dennis, @dejuknow 

This might require a PM check if we want to apply this naming convention to the site facet. :point_up: 

@SamZiemer Are the `sites-and-libraries` lang key and its translations available globally for all modules or it is specific to journal modules? In latter case, you need to add it to the lang keys of portal-search-web and run buildLang.

**Comment by dejuknow** [comment]
@lipusz The rename is fine since it'll be consistent w/ the rest of portal.

**Comment by lipusz** [comment]
@SamZiemer Can you please check my previous comment above? Thanks!

**Comment by SamZiemer** [comment]
@brianikim, please look into what @lipusz mentioned here: https://github.com/liferay-search/liferay-portal/pull/34#issuecomment-689648158

**Pull request closed without merging**
