### PR TITLE
LPS-185302 Logging & Troubleshooting: Execution Mode

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPS-185302

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:reevaluate:1397401_6423

**Comment by BryanEngler** [comment]
looking now...

**Comment by BryanEngler** [comment]
thanks guys, i added some more logging here - https://github.com/liferay-search/liferay-portal/pull/1016

**Pull request closed without merging**
