### PR TITLE
LPS-146797 search-experiences-web: Change conditions for 'Select All'

### PR DESCRIPTION
**Pull request by oliv-yu**
https://issues.liferay.com/browse/LPS-146797 - The "Select All" button should not appear within the Select Asset Types modal when all checkboxes are already checked

Small changes! Let me know if the styling/functionality is ok.
- Make 'Select All' only appear when not all are selected
- Turn 'Select All' link to button

### CODE REVIEW

**Review by thektan — CHANGES_REQUESTED** [review]
Can you take a look at the button link styling here? Mainly the hovering should look like a link with the text underlined. https://clayui.com/docs/components/management-toolbar/markup.html

You can start with `<ClayButton displayType="link"`

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:sf

**Review by thektan — APPROVED** [review]

**Comment by joshchong** [comment]
Continued here:
https://github.com/liferay-search/liferay-portal/pull/325

**Pull request closed without merging**
