### PR TITLE
[TS] LPS-167763 Everywhere scoped suggestions

### PR DESCRIPTION
**Pull request by joshuacords**
from: https://github.com/liferay-search/liferay-portal/pull/703
https://issues.liferay.com/browse/LPS-167763

**Author:** @georgel-pop-lr 
**Reviewer:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by kungfumanda** [comment]
Resent [here](https://github.com/liferay-search/liferay-portal/pull/721).

**Pull request closed without merging**
