### PR TITLE
LPS-201116 Enable/disable Date Facet according to toggle in Instance Settings > Feature Flags

### PR DESCRIPTION
**Pull request by BryanEngler**
Story: https://liferay.atlassian.net/browse/LPS-198410
* Sub-task: https://liferay.atlassian.net/browse/LPS-201116

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@lfbesada FYI, making some changes here to layout-impl if you have any thoughts on it

**Comment by BryanEngler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Hi @BryanEngler, would you be so kind as to mention us before sending it to Brian next time? So we have time to take a look and review.

Thanks a lot!

**Comment by BryanEngler** [comment]
@jkappler, ya not a problem, I did mention lfbesada just so someone would be aware, but should it have been someone else? (i did ping my project and product managers to see who the best person to mention would be, but never heard back from them) 
I figured it was safe to forward without a formal review since the changes were pretty trivial, and easy to revert if there was an issue... (i feel like it fell under the type of change that was discussed at product gathering that team leads were free to forward). If you want more time to look at it first you can close the pr with bchan since its still open

**Comment by lfbesada** [comment]
Hi @BryanEngler 

IMHO it would be tidier and easier to understand if we move all the conditions of this to a method, for example, something like this:

https://github.com/liferay/liferay-portal/pull/5752/commits/fad53ccb2a3d2e898f238ccfc908cfcc36bc32e3

What do you think?

If this feature flag is temporary and will later be removed IMHO is enough with this.
If this feature flag became in release feature flag or there was an intention to do this behavior for new portlets, I would further consolidate this mechanism, for example, with the rest of the changes that are in this PR: 

https://github.com/liferay/liferay-portal/pull/5752

I hope this helps

Regards

**Comment by jkappler** [comment]
Hi @BryanEngler, yes, it's what we talked. Just give us a bit of time next time to take a look 😅. Mentioning @lfbesada was great. Thanks for that!

**Comment by BryanEngler** [comment]
@lfbesada thanks for the thoughts, the SF commit looks good to me if thats what you prefer. 
for the other notes, one reason i went with more "minimal" changes was because we might not even keep the date facet but just incorporate the logic into our already existing custom facet (https://liferay.atlassian.net/browse/LPS-198415), so i would kind of see https://github.com/lfbesada/liferay-portal/pull/229 as overkill at this point (but ill make a note on that spike to maybe visit your pr again depending on the outcome of the spike). its almost 1am here so im going to sign off, if you want to close the pr with brian feel free to, and either resend what you want to include, or just let me know and ill check in the morning. thanks!
one other option is to see if bchan merges and then send a follow up pr, because there is kind of an open question on the PR already in regards to using an annotation on the unit test...

**Comment by lfbesada** [comment]
Hi @BryanEngler  

Don't worry, we're just getting started the work day, so I am going to take care of this. If that's okay with you, I'll keep an eye on the PR on Brian and if he merges, I'll push that SF commit mentioning you to be aware.

Thank you! Regards

**Comment by lfbesada** [comment]
I have sent the SF commit here: https://github.com/liferay-echo/liferay-portal/pull/14326

Regards

**Pull request closed without merging**
