### PR TITLE
LPD-37742 Update Blueprints using Limit Search to These Sites Element to use ERCs 

### PR DESCRIPTION
**Pull request by felipelorenz**
https://liferay.atlassian.net/browse/LPD-37742

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Made changes and testing here https://github.com/liferay-search/liferay-portal/pull/1519

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:search

**Pull request closed without merging**
