### PR TITLE
LPD-26932: Move semantic search to portal-search. Add embedding support for DLFileEntry

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-26932 

rebased code from this PR: https://github.com/liferay-search/liferay-portal/pull/1390

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:report:29708084

**Comment by gustavolimav** [comment]
ci:report:29658018

**Comment by gustavolimav** [comment]
Hey @peerkar, can you review https://testray.liferay.com/#/project/34754/routines/34756/build/29658018/case-result/29670901/history and https://testray.liferay.com/#/project/34754/routines/34756/build/29658018/case-result/29675255/history? both failed with different errors from the usual history, other than that the Results looks good.

**Comment by peerkar** [comment]
ci:reevaluate:1377401_17303

**Comment by peerkar** [comment]
Rebasing and continuing [here](https://github.com/liferay-search/liferay-portal/pull/1437)

**Pull request closed without merging**
