### PR TITLE
LPD-19971 End and start parameters are using default values in searchContext for federated search requests

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-19971

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:2548203530

**Review by felipelorenz — APPROVED** [review]
LGTM!

**Comment by felipelorenz** [comment]
ci:forward:force

**Pull request closed without merging**
