### PR TITLE
LPS-175322: Fix check logic

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-175322

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Hi @peerkar the results looks good but there is a merge conflict, can you please resolve? Thanks!

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:forward

**Pull request closed without merging**
