### PR TITLE
LPS-130753 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-130753

cc: @thektan @oliv-yu

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:forward

**Comment by xbrianlee** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107515

**Pull request closed without merging**
