### PR TITLE
[TS] LPS-124605 Not all available locales are returned by BaseIndexer

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-124605](https://issues.liferay.com/browse/LPS-124605)
Dear Team,

Please review my change.

The issue is that we return only fields belonging to supported (i.e. non-beta) locales instead of available (i.e. enabled) locales.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
running more tests here https://github.com/BryanEngler/liferay-portal/pull/549

**Pull request closed without merging**
