### PR TITLE
[TS] LPS-131302 Add showExtraInfo parameter for searched documents

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
ci:reevaluate:1037401_9646

**Comment by BryanEngler** [comment]
@lipusz im on PTO all next week but assuming all testing passes you guys can go ahead and forward this, thanks

**Comment by lipusz** [comment]
Sure, enjoy your PTO! 👍

**Comment by lipusz** [comment]
https://github.com/liferay-search/liferay-portal/pull/128

**Pull request closed without merging**
