### PR TITLE
[TS] LPS-123103 The Sort Widget's Top Option Isn't Applied on Page Load | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Reference:
https://issues.liferay.com/browse/LPS-123103

**General description of expected behavior**: When I search for a term in the page top search bar, I am redirected to the search page and my results are shown. Importantly, **I expect that if I have added a Sort Widget to the page, the top sort option is applied on page load.**
 
**General description of observed behavior:** To apply a Sort other than the default (relevance) I must select it from the Sort Widget.

**Steps to Reproduce:**
1. Add a Sort widget to the search page and configure it so the Created option (field: createDate- is the first choice.
2. Add three pieces of content, a minute apart. For example, blog posts like this:
        Title: First/Second/Third Blog Post
        Content: A blog post for sort testing
3. Search for second blog.

**Expected**: Results are returned in order of create date, with newest first (third blog, second blog, first blog) and the sort is represented in the URL.
**Actual**: Results are returned in order of relevance (second blog post is first in the list) and no sort parameter is present in the URL.

This may have simply been the way it was designed, for users to change the sort order after seeing the relevance-sorted results. But, it's still a perceived bug, because you'll see the Created option appearing in the Sort widget, while results are actually being returned by relevance. 

**Solution proposed:**
The flow of how search's order is applied has not been changed. Instead, this criterion (relevance) appears now as an option in the Sort Widget. 
This way,
- User knows what criterion was applied.
- That option is disabled so user can only choose between Sort Widget configuration criteria.
- The URL will be updated when user chooses another sort option.

This solution has been chosen since it is considered the simplest one.

Best.
Sergio.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by samanzanedo** [comment]
ci:test:search

**Comment by thektan** [comment]
Added additional changes here: https://github.com/liferay-search/liferay-portal/pull/58

**Pull request closed without merging**
