### PR TITLE
LPD-30648 opensearch: give permission for tests to create and delete …

### PR DESCRIPTION
**Pull request by joshuacords**
…snapshots

https://liferay.atlassian.net/browse/LPD-30648

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:search-opensearch2

**Review by AlmirFe — APPROVED** [review]
LGTM! :rocket:

**Comment by joshuacords** [comment]
ci:forward

**Comment by joshuacords** [comment]
ci:forward-force

**Pull request closed without merging**
