### PR TITLE
[TS] LPS-133177

### PR DESCRIPTION
**Pull request by crodriguezy**
https://issues.liferay.com/browse/LPS-133177

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by arboliveira** [comment]
@crodriguezy Please see my notes :) 

https://issues.liferay.com/browse/LPS-133177?focusedCommentId=2458044&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2458044

**Comment by joshuacords** [comment]
I'm finishing review. I looked to see if there's a way to see if portal is starting up as opposed to using the MergeLayoutPrototypesThreadLocal. I found [StartupHelperUtil.isStartupFinished()](https://github.com/liferay/liferay-portal/blob/9446399a0b2392c710de8466f25971118078b5bf/portal-impl/src/com/liferay/portal/events/StartupHelperUtil.java#L69-L71) however this registers `true` before all modules have finished upgrading. As far as I saw, there's not another way.

The changes themselves look good, and I'm happy to forward this. The search tests look clean, but I'm going to keep my eye on LocalFile.DatabasePartitioning#AddNewCompany test when ci:forward runs Relevant as there's a small chance it's related.

**Comment by joshuacords** [comment]
ci:forward

**Comment by crodriguezy** [comment]
Hi @arboliveira , @joshuacords ,

Please see my comment [here](https://issues.liferay.com/browse/LPS-133177?focusedCommentId=2458702&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2458702).  

Do you still think we should think of a different solution for this?

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
