### PR TITLE
LPS-178528: Custom facet support for Objects

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-178528

Functional tests: https://issues.liferay.com/browse/LPS-179295

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
@peerkar thoughts on adding a test to BaseNestedFieldsFacetTestCase?

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Passed manual testing following the steps in [LPS-178528](https://issues.liferay.com/browse/LPS-178528). Testing with the bundle generated from https://github.com/liferay-search/liferay-portal/pull/852#issuecomment-1481238740.

**Comment by xbrianlee** [comment]
Test results look good 👍 

@peerkar I can't tell if `search` suite needs to be re-run since changes were pushed after the last successful run. I'll leave it up to your judgment.

**Comment by peerkar** [comment]
ci:forward

**Pull request closed without merging**
