### PR TITLE
[TS] LPS-125636 Recognize index.on.startup.delay

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-125636

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by brandizzi** [comment]
ci:test:search

**Comment by brandizzi** [comment]
ci:test:relevant

**Comment by brandizzi** [comment]
ci:forward

**Comment by brandizzi** [comment]
Passed tests and seems quite good. Forward. Thank you, @holatuwol!

**Comment by brandizzi** [comment]
ci:reevaluate:1152004_3816

**Comment by lipusz** [comment]
https://github.com/liferay-search/liferay-portal/pull/83

**Pull request closed without merging**
