### PR TITLE
(WIP) LPD-26989 Add GET /search Headless API

### PR DESCRIPTION
**Pull request by marco-leo**
https://liferay.atlassian.net/browse/LPD-26989

### CODE REVIEW

**Comment by peerkar** [comment]
@marco-leo , @lipusz do you want me to proceed with this endpoint definition as is, even though it's not supporting facets or attributes, like when needed by custom Blueprint parameters?

**Comment by lipusz** [comment]
From product side,I think it would be great to keep facets and attributes also supported if it's technically feasible without too much performance drawbacks just like as we discussed it on the planning meeting originally.

I'm not sure what the use-case Marco created the WIP for required exactly. What do you think, Marco? @marco-leo

**Comment by marco-leo** [comment]
@lipusz @peerkar  In the use case We are using get like in data set and autocomplete we don't need the facets, that does't means it is bad to have it.  

Would be nice if we merge the PR under feature flag and keep working on the feature parity if you see values on it.

Thanks

**Comment by peerkar** [comment]
Updated integration tests and continuing [here](https://github.com/liferay-search/liferay-portal/pull/1375)

**Pull request closed without merging**
