### PR TITLE
FIXES: LPS-128571 portal-search: Searcher with specific models should return only requested types instead of all types + LPS-126704 Unnecessary match_all distorts scores when inner bool query has only filter clauses

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-128571
https://issues.liferay.com/browse/LPS-126704

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
ci:forward

**Comment by lipusz** [comment]
Hey @arboliveira @peerkar 

I wanted to ask if you are tracking somewhere which related tickets will be needed to be also backported to 7.3.x for Blueprints, besides the actual Blueprints modules.

Just asking because I came across this pull and saw that the tickets are marking Master only.

**Comment by arboliveira** [comment]
@lipusz

> which related tickets will be needed to be also backported to 7.3.x for Blueprints?

https://issues.liferay.com/browse/LPS-112855

**Comment by arboliveira** [comment]
ci:forward

**Comment by arboliveira** [comment]
Manually forwarded as https://github.com/brianchandotcom/liferay-portal/pull/100680.

**Pull request closed without merging**
