### PR TITLE
LPS-138643 Make CCR, Monitoring and LTR LES apps core and bundled

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-138643

### CODE REVIEW

**Comment by lipusz** [comment]
ci:help

**Comment by lipusz** [comment]
ci:test:search-remote

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:license

**Comment by xbrianlee** [comment]
Continuing testing in https://github.com/xbrianlee/liferay-portal/pull/636 since we can't download CI bundles from this repo (saved bundles not enabled)

**Comment by lipusz** [comment]
ci:test:license

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
https://issues.liferay.com/browse/LPS-140103 was merged.

**Pull request closed without merging**
