### PR TITLE
[Multi-Tenant] LPS-117703 + LPS-117704: Update Synonyms & Result Rankings

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-117703
https://issues.liferay.com/browse/LPS-117704

Also performed upgrade scenario described on the Epic (https://issues.liferay.com/browse/LPS-117702).

:information_source: **Notes**: I was thinking about to consolidate the index name creation logic completely to the respective builder impls so we could eliminate the need (and remove some code) to inject `IndexNameBuilder` to multiple DS services in the code: instead, the `*IndexNameBuilderImpl`-s would receive just a `companyId` and the rest would be constructed within the builders.
However, to do this, we'd need to use `CompanyThreadLocal` in `SynonymSetIndexCreationIndexContributor` because there we don't have the `companyId` available in the context. (And there may be other locations in the SS code with the same need.)

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Search failures are unrelated, also occurred on https://github.com/joshuacords/liferay-portal/pull/93#issuecomment-666876905 yesterday.

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
:white_check_mark: Failures are not related.

**Comment by arboliveira** [comment]
Continued: https://github.com/liferay-search/liferay-portal/pull/14

**Pull request closed without merging**
