### PR TITLE
[TS] LPS-138720 Escape custom facet attribute

### PR DESCRIPTION
**Pull request by markgulacsy**
Hi Search Team,

Could you review my PR regarding this [LPS](https://issues.liferay.com/browse/LPS-138720)?

Thanks!

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by markgulacsy** [comment]
Hello @lipusz,
I do not think the test failures are relevant. What do you think about it?
Thanks in advance!

**Comment by thektan** [comment]
ci:test:relevant

**Comment by thektan** [comment]
@markgulacsy The test failures don't seem related to this PR. Changes look good, thanks! Forwarding this.

**Comment by thektan** [comment]
ci:forward

**Comment by markgulacsy** [comment]
@thektan Thank you!

**Pull request closed without merging**
