### PR TITLE
LPS-142315 portal-search-elasticsearch7-impl: Run unit tests faster by starting search engine only once per class and Increase timout to 10

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-142315

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:reevaluate:1347401_2451

**Comment by joshchong** [comment]
ci:forward

**Pull request closed without merging**
