### PR TITLE
LPS-195967 Create one company to the test class and delete after all tests run

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPS-195967

sending again: https://github.com/brianchandotcom/liferay-portal/pull/143247#issuecomment-1793234026

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@gustavolimav i just pulled the branch and rebased already so dont worry about that conflicts

**Comment by BryanEngler** [comment]
@gustavolimav please resend after looking at a few things:
1 - separate the commits into the different modules that are changed, like we usually do
2 - in some places you replaced addCompanyAdminUser with addUser, maybe this needs to be double checked? 
3 - fix SF / line breaks. also try to make it pattern after other classes that are doing this (ie use _originalName etc). some example classes:
OpenAPIResourceTest
GCSStoreStoreAreaProcessorTest
WorkflowTaskManagerImplTest
CompanyLogServletTest
PortalImplGroupFriendlyURLTest
SynonymSearchTest
WorkflowMetricsSLADefinitionVersionLocalServiceTest

thanks!

**Comment by BryanEngler** [comment]
just sent you a pr with the rebased branch here https://github.com/gustavolimav/liferay-portal/pull/73

**Pull request closed without merging**
