### PR TITLE
LPD-25846 Add Test to ensure RR are applied to searches originating from Basic and Blueprints Suggestions Contributors (/suggestions)

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-25846

### CODE REVIEW

**Comment by joshuacords** [comment]
Hi @gustavolimav,

Could you add the http link of the ticket to the bottom of each commit?

Otherwise this looks good to me.

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search-opensearch2

**Comment by gustavolimav** [comment]
ci:test:search-solr

**Comment by gustavolimav** [comment]
ci:report:2570685315

**Comment by gustavolimav** [comment]
ci:report:2570686980

**Comment by gustavolimav** [comment]
ci:report:2570676942

**Comment by gustavolimav** [comment]
ci:report:2570695802

**Comment by gustavolimav** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
