### PR TITLE
LPS-143416 search-experiences: New custom view blueprints and elements page

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-143416

These browser errors are thrown by frontend-data-set components.

To fix, this removes the use of the `frontend-data-set:headless-display` taglib and related `FDS` java classes and replaces it with new view components in `search-experiences-web`. Since newer fixes/features of FDS aren't in 7.3, this will allow easier backporting.

### CODE REVIEW

**Comment by thektan** [comment]
ci:test:relevant

**Review by oliv-yu — APPROVED** [review]
LGTM, thanks for doing all this! 💯

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
continued in https://github.com/joshchong/liferay-portal/pull/525

**Pull request closed without merging**
