### PR TITLE
LPS-179362 LPS-180827 portal-search-web: Apply Clay taglibs and replace custom styles for search widgets

### PR DESCRIPTION
**Pull request by oliv-yu**
Story: https://issues.liferay.com/browse/LPS-179362
Subtask: https://issues.liferay.com/browse/LPS-180827

The goal was to update search widgets to be more "as is", in order for its appearance to have consistency with other parts of the product (page builder, web content, documents & media).
- Use Clay taglibs whenever possible. Only if possible, because some taglibs didn't seem ideal to use (for example, Clay Checkbox does not allow passing in some markup as its label). 
- Leveraging Clay classnames instead of relying on extra stylesheets. However, this should avoid using classnames that use `!important` since it cannot be overridden. For example, using tags `<strong></strong>` instead of `text-weight-semi-bold` to avoid the `!important`.
- Importing Clay's `atlas-variables` and using `var()` when assigning colors.
- Using `c-` prefix on current uses of spacing in order to avoid conflicts with other frameworks.

Besides the details table on search results, there were not many visual changes. That table was updated in order to follow existing Clay styles.

Before:
Screenshot 2023-04-05 at 2 32 56 PM

After:
Screenshot 2023-04-10 at 4 27 30 PM

Hopefully these changes were reasonable! Let me know if there is anything else to add, thanks for taking a look!

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
Pushed up some test fixes inside `SuggestionsPortletDisplayContextBuilderTest.java`, and the rest of the unique failures look like they have already been logged!

**Review by thektan — APPROVED** [review]
Awesome stuff! Cleans up so much which means less CSS we'll need to maintain in the future! Thanks for these very thorough changes!

**Comment by thektan** [comment]
ci:test:search

**Comment by thektan** [comment]
Running tests again just in case since it's been a few days.

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:forward:force

**Pull request closed without merging**
