### PR TITLE
LPS-194732 XSS Vulnerability in Result Rankings search query

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPS-194732 - XSS with result ranking's search query
https://liferay.atlassian.net/browse/LPS-183706 - Result Rankings alert container shows even when there is no alert

Two bug fixes:
- Escape the message that appears inside the toast for having a duplicate search query 
- Do not show the alert container when there is no alert

Demo of first 🐛 : https://github.com/liferay-search/liferay-portal/assets/14063502/bd760c65-1fd8-4b88-a6b7-0e7548c02e6c

Screenshot of second 🐛: 
Screenshot 2023-09-05 at 4 50 12 PM

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:search

**Review by thektan — APPROVED** [review]
Looks good!

In the future, could you also include a screenshot or better, a recording of how the fix looks like? I was wondering how the alert message would appear so it could help with a faster review process. I wanted to make sure it wasn't displaying encoded values like `%3C`.

**Comment by thektan** [comment]
Failing test doesn't seem related, so I'm going to attempt forwarding. I couldn't examine the screenshots/steps since the links lead to a 404, but from the test name it doesn't seem like it should be related.

**Comment by thektan** [comment]
ci:forward

**Comment by oliv-yu** [comment]
> Looks good!
> 
> In the future, could you also include a screenshot or better, a recording of how the fix looks like? I was wondering how the alert message would appear so it could help with a faster review process. I wanted to make sure it wasn't displaying encoded values like `%3C`.

Oh my bad, will do in the next one!

**Comment by CaiocSiqueira** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward:force

**Pull request closed without merging**
