### PR TITLE
[Remove Classes]LPS-178135 Remove unused interfaces SearchResultImageContributor and SearchResultImage

### PR DESCRIPTION
**Pull request by W2jx**
https://issues.liferay.com/browse/LPS-178135

Hi @lipusz, @tinatian, @dantewang, I have removed SearchResultImageContributor and SearchResultImage.

Detail: https://liferay.slack.com/archives/CKY6GP7BL/p1678239012660689

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by dantewang** [comment]
ci:test:relevant

**Review by peerkar — APPROVED** [review]
Tested and looks good to me. I'll still ask search QA to check the CI errors.

**Comment by joshchong** [comment]
ci:forward:force - tests look good to me

**Pull request closed without merging**
