### PR TITLE
LPD-32466 portal-search-opensearch2-impl: fix mappings test

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPD-32466

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:opensearch2

**Comment by joshuacords** [comment]
ci:test:search-opensearch2

**Comment by joshuacords** [comment]
ci:report:47681239

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
