### PR TITLE
LPS-158850

### PR DESCRIPTION
**Pull request by AlmirFe**
https://issues.liferay.com/browse/LPS-158850
follow up: #509

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
I like this fix

**Comment by joshuacords** [comment]
Hi @AlmirFe, Broken tests need to be resolved, if you just add commit(s) to fix it you can continue to use this PR.

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
