### PR TITLE
LPS-183245 Add description to the /search API that appears on the API UI page to indicate that this is not stable, in development and requires a Dev FF

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-183245

Hi Brian,

As this is behind a FF, I thought it's better to indicate this as the API itself is already discoverable. Wordsmithed by @rbohl.

image

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
@peerkar fyi

**Comment by lipusz** [comment]
ci:forward

**Comment by lipusz** [comment]
ci:forward:force

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:forward

**Comment by brookedalton** [comment]
ci:forward

**Pull request closed without merging**
