### PR TITLE
LPS-166190 search-experiences-rest-impl: Fix mismatch in 'enabled' property

### PR DESCRIPTION
**Pull request by peerkar**
A follow up to:

- https://issues.liferay.com/browse/LPS-166190
- https://issues.liferay.com/browse/LPS-166197

### CODE REVIEW

**Comment by lipusz** [comment]
There is another PR under LPS-161172 at BChan's queue: https://github.com/brianchandotcom/liferay-portal/pull/125639

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:reevaluate:1327401_6637

**Comment by joshchong** [comment]
Sent to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/125674

**Pull request closed without merging**
