### PR TITLE
LPS-150101 portal-search-similar-results-web: Fall back to default link behaviour when view in context URL is blank

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-150101

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:stable

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
Manually tested here: https://issues.liferay.com/browse/LPS-149306?focusedCommentId=2645911&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2645911

**Comment by xbrianlee** [comment]
Test results here look good. All test failures are unrelated.

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:forward

**Comment by BryanEngler** [comment]
ci:forward

**Pull request closed without merging**
