### PR TITLE
LPS-186376 Fix SearchResultEntity filter fields after LPS-157425

### PR DESCRIPTION
**Pull request by AlmirFe**
### **LPS link:** [LPS-186376](https://liferay.atlassian.net/browse/LPS-186376)

# Context 
A new constructor was added in the [StringEntityField](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-odata/portal-odata-api/src/main/java/com/liferay/portal/odata/entity/StringEntityField.java) class by [LPS-157425](https://liferay.atlassian.net/browse/LPS-157425). This PR aims to change the title field in the [SearchResultEntityModel](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-rest-impl/src/main/java/com/liferay/portal/search/rest/internal/odata/entity/v1_0/SearchResultEntityModel.java) to use the new [StringEntityField](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-odata/portal-odata-api/src/main/java/com/liferay/portal/odata/entity/StringEntityField.java) constructor. 

The Description field has been removed following the conversation in this [PR](https://github.com/AlmirFe/liferay-portal/pull/8).

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
@AlmirFe the code looks good to me! Did you validate the functionality with Brian Lee's example from here: https://liferay.atlassian.net/browse/LPS-157425?

**Comment by AlmirFe** [comment]
Hi @peerkar, I followed Brian Lee's example steps and it worked.

**Comment by peerkar** [comment]
@AlmirFe good to go then 👍

**Comment by AlmirFe** [comment]
ci:test:search

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward:force

**Pull request closed without merging**
