### PR TITLE
LPS-156876 portal-search-elasticsearch7-impl: Fix MultiMatchQueryTest

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-156876

Testing Here: https://github.com/gustavolimav/liferay-portal/pull/25

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by joshuacords** [comment]
Hi @gustavolimav, 

Note that [com.liferay.portal.search.elasticsearch7.internal.query.MultiMatchQueryTest.testMultiMatchQueryBoolPrefix](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137086//testReport/com.liferay.portal.search.elasticsearch7.internal.query/MultiMatchQueryTest/testMultiMatchQueryBoolPrefix) failed. It looks like `_indexUserDocuments("omega", "delta", "userName5");` should also have been indexed.

The refactoring looks good in general, but could you keep an extra document indexed that shouldn't be found in each refactored test. This insures the filter is actually filtering correctly.

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:stable

**Comment by gustavolimav** [comment]
> Hi @gustavolimav,
> 
> Note that [com.liferay.portal.search.elasticsearch7.internal.query.MultiMatchQueryTest.testMultiMatchQueryBoolPrefix](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/137086//testReport/com.liferay.portal.search.elasticsearch7.internal.query/MultiMatchQueryTest/testMultiMatchQueryBoolPrefix) failed. It looks like `_indexUserDocuments("omega", "delta", "userName5");` should also have been indexed.
> 
> The refactoring looks good in general, but could you keep an extra document indexed that shouldn't be found in each refactored test. This insures the filter is actually filtering correctly.

Done, and testing here: https://github.com/gustavolimav/liferay-portal/pull/25

**Comment by joshuacords** [comment]
Perfect, forwarding.

**Comment by joshuacords** [comment]
ci:forward

**Pull request closed without merging**
