### PR TITLE
[TS] LPS-167763 Search Bar Scope Everything doesn't return Site members documents results for Guest role if View Document scope isn't also All Sites And Asset Library

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Comes from https://github.com/liferay-search/liferay-portal/pull/660

https://issues.liferay.com/browse/LPS-167763

https://issues.liferay.com/browse/PTR-3482

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
ci:reevaluate:1387401_5014

**Comment by joshuacords** [comment]
Hello @georgel-pop-lr,

This fix looks good - I uncovered another bug when testing it, [LPS-169883](https://issues.liferay.com/browse/LPS-169883), but I think it's fine to address that separately. However, it's important to get some tests to future protect this. Would you be able to make tests for both the SearchBarPortletSharedSearchContributor and the SuggestionResourceImpl that insure all groupIds are added to the searchContext when the search scope is "everything"? Unit tests would be fine.

Thanks for your work on this.

**Comment by georgel-pop-lr** [comment]
> SuggestionResourceImpl

Hi @joshuacords,

I had a look on how to do the tests, but I realized that I have no access to searchContext inside SearchBarPortletSharedSearchContributor or SuggestionResourceImpl

For example, for SearchBarPortletSharedSearchContributor it's using a searchRequestBuilder.withSearchContext, and it's impossible to retrieve it from it in order to see the groupsIds.

What should I do in this situation?

Regards.

**Pull request closed without merging**
