### PR TITLE
LPS-155555

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-155555

Made the changes you were asking for @BryanEngler. I wasn't sure who you were asking to review it, it seems weird to me to ask @arboliveira, but I guess it does involve him.

@arboliveira would you mind signing off on this? Thanks

**Author:** @joshuacords

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:stop

**Comment by joshuacords** [comment]
ci:stop

**Comment by BryanEngler** [comment]
1 - hmm, im confused haha. when did i ask for this?
2 - if someone does want these changes, maybe its better to just add my name instead of swapping it out?
3 - i dont have permission to see the LPS

**Comment by BryanEngler** [comment]
merged. thank you

**Pull request closed without merging**
