### PR TITLE
LPD-20241 search-experiences-service: Use getSummary instead of getSearchSummary

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-20241

portletRequest and portletReponse are necessary to translate the summary

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:report:2549166405

**Review by felipelorenz — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
ci:forward:force

**Comment by gustavolimav** [comment]
ci:forward:force

**Pull request closed without merging**
