### PR TITLE
LPD-27986 poshi: Use a different search result for test assertions

### PR DESCRIPTION
**Pull request by oliv-yu**
https://liferay.atlassian.net/browse/LPD-27986 - Search#CanViewTermsOfUseWhenEnterpriseSearchIsEnabled
https://liferay.atlassian.net/browse/LPD-27129 - Search#ViewSearchResultDetails
https://liferay.atlassian.net/browse/LPD-28374 - Blueprints#AddBlueprintInNonRootContext
https://liferay.atlassian.net/browse/LPD-27989 - OpenSearch2#SSLSmokeTest

These are all related to some issues not being able to see "Test Test" user when performing a search.

Something they all have in common are the properties `property test.liferay.virtual.instance = "false"`, `property test.run.type = "single"` so it runs one test without a virtual instance, perhaps that increases likeliness for a failed run? Anyway, the test change is to just assert a different result, going with searching for "tree" > asserting "tree.png" .

Sample screenshot from Testray:
image

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:sf

**Comment by oliv-yu** [comment]
ci:test:search

**Comment by oliv-yu** [comment]
Hi @xbrianlee would you mind taking a look at these changes and let me know if it's okay to forward? Thanks!

**Comment by xbrianlee** [comment]
@oliv-yu These changes look good! I'd monitor them upstream to see if our hypothesis is correct (the OOTB documents are a more consistent assertion than the test user).

**Comment by oliv-yu** [comment]
@xbrianlee Awesome, thanks! In that case, I'll forward this and keep an eye out on the results afterward 🤞

**Comment by oliv-yu** [comment]
ci:forward

**Pull request closed without merging**
