### PR TITLE
LPD-32568 RankingJSONStorageEntryUpgradeProcessTest [Integration] (search-solr)

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-32568

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:search-solr

**Comment by AlmirFe** [comment]
ci:test:search-solr

**Comment by AlmirFe** [comment]
ci:report:56653746

**Review by gustavolimav — APPROVED** [review]
LGTM 🚀

**Comment by gustavolimav** [comment]
ci:forward

**Pull request closed without merging**
