### PR TITLE
LPS-166342: Add keywords parameter name to suggestions query parameters

### PR DESCRIPTION
**Pull request by peerkar**
https://issues.liferay.com/browse/LPS-166342

### CODE REVIEW

**Comment by peerkar** [comment]
ci:test:relevant

**Review by thektan — APPROVED** [review]
Thanks, Petteri! Looks good for what was needed for the frontend.

**Comment by thektan** [comment]
Failures from `ci:test:search` seem unrelated so I'll go ahead and forward this.

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
