### PR TITLE
LPS-157748 Unable to change search bar display template when suggestions are enabled

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-157748

- This puts the react component inside of the `liferay-ddm:template-renderer` tags so it can be replaced with a different display template when suggestions are enabled.
- I had to add both `event.preventDefault()` and `event.stopPropagation()` or else the hidden inputs `${namespace}_formDate` and `start` would have been added to the URL (meaning the default browser form submission was taking place instead of the JS navigation). 
- Added a div id `<portlet:namespace />reactSearchBar` to not initialize the AUI `Liferay.Search.SearchBar` component when the react component is being used

### CODE REVIEW

**Comment by oliv-yu** [comment]
ci:test:relevant

**Comment by oliv-yu** [comment]
ci:test:stable

**Review by oliv-yu — APPROVED** [review]
Thank you for finding and fixing this! Looks great to me 👍  I'll try forwarding

**Comment by oliv-yu** [comment]
ci:forward

**Comment by oliv-yu** [comment]
ci:forward

**Comment by thektan** [comment]
ci:forward

**Pull request closed without merging**
