### PR TITLE
LPS-162052 LPS-164629 Add widget configuration to show/hide frequencies

### PR DESCRIPTION
**Pull request by felipelorenz**
https://issues.liferay.com/browse/LPS-164629

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:test:sf

**Comment by felipelorenz** [comment]
ci:test:relevant

**Comment by felipelorenz** [comment]
ci:reevaluate:1267401_7079

**Comment by felipelorenz** [comment]
ci:test:search

**Comment by gustavolimav** [comment]
LGTM!

**Comment by gustavolimav** [comment]
You can forward it manually @felipelorenz

**Pull request closed without merging**
