### PR TITLE
LPD-19989 Allow to search by vocabularyIds that are indexed

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPD-19989)

Dear Team, as part of https://liferay.atlassian.net/browse/LPD-18421 we now index vocabulary IDs, so we also wanted to allow filtering by them.
I added new methods to the search context, to set and retrive vocabularyIds, also a new QueryPrefilterContributor.

Instead of changing the search context, I could also set an attribute.

A test is also provided.

We wanted to run this trough you, so please let us know what you think. Thanks a lot in advance!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
@jkappler looks good to me, did you want us to forward it?

**Comment by jkappler** [comment]
Hi @BryanEngler, thanks for the review! Just wanted to pass it to you, I can forward it :)

**Pull request closed without merging**
