### PR TITLE
LPS-206318 Validate companyAdmin in EditMVCActionCommand for reindexed companies & Add and Apply Dev System FF

### PR DESCRIPTION
**Pull request by gustavolimav**
Sending again together https://github.com/liferay-search/liferay-portal/pull/1224 and https://github.com/liferay-search/liferay-portal/pull/1223

https://liferay.atlassian.net/browse/LPS-206367
https://liferay.atlassian.net/browse/LPS-206318

### CODE REVIEW

**Comment by lipusz** [comment]
@gustavolimav I don't see the points mentioned here addressed in this new PR.

Is this intentional?

https://github.com/liferay-search/liferay-portal/pull/1224#issuecomment-1895374887

**Comment by gustavolimav** [comment]
@lipusz 

About this security layer:

FF enabled + User is Company Admin + ReindexConfiguration allows the given company + the User is the Company Admin of the given Company

FF enabled and the ReindexCondiguration allows the given company are covered by SearchAdminControlPanelEntry, otherwise the user will not be able to access the portlet to make the request.

 About "User is Omin Admin or company Admin of the given Company (the company that he is trying to reindex)", now I the code is validating every copany from the companyIds array that is sent in the request, if the user is not companyAdmin of any of the companies the reindex will fail with a must have permission exception.
 
 
 Does it looks good to you?

**Comment by gustavolimav** [comment]
> @gustavolimav I don't see the points mentioned here addressed in this new PR.
> 
> Is this intentional?
> 
> [#1224 (comment)](https://github.com/liferay-search/liferay-portal/pull/1224#issuecomment-1895374887)

I was writing it

**Comment by gustavolimav** [comment]
@lipusz we can have a call to discuss the behavior if you want to

**Comment by lipusz** [comment]
I see your comment, however it's working like that: the control panel entry check won't prevent the execution if you arbitrary invoke the URL.

Refer to my reproduction steps: i was testing that with my changes in place. 

Even though the request fails at the control panel entry, the action command is still invoked.

**Comment by gustavolimav** [comment]
> I see your comment, however it's working like that: the control panel entry check won't prevent the execution if you arbitrary invoke the URL.
> 
> Refer to my reproduction steps: i was testing that with my changes in place.
> 
> Even though the request fails at the control panel entry, the action command is still invoked.

I will test it and add the change to this PR, in my tests yesterday it didn't happen, anyway I will let you know the results.

**Review by lipusz — APPROVED** [review]
Fetched, built, tested again. 

When FF disabled or enabled, but access not granted, there is a WARN in the log :heavy_check_mark: 

```
2024-01-17 15:51:17.796 WARN  [http-nio-8080-exec-7][SecurityPortletContainerWrapper:395] User 33135 is not allowed to access URL http://tibusz.com:8080/group/control_panel/manage and portlet com_liferay_portal_search_admin_web_portlet_SearchAdminPortlet: User does not have permission to access Control Panel portlet com_liferay_portal_search_admin_web_portlet_SearchAdminPortlet
```

When FF enabled + access granted, but submitting the action request with another `companyId` the user is not the admin of: Getting HTTP 200 + error response in the HTML :heavy_check_mark: 

```
	Error:You do not have the required permissions.

```

Attached screenshot to the Story ticket.

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
ci:test:search

**Comment by BryanEngler** [comment]
rebased and forwarding from here https://github.com/liferay-search/liferay-portal/pull/1232

**Pull request closed without merging**
